### ISSUE TITLE
authentication times out when idle on page

### ISSUE THREAD

**Issue by creoden** [theotherp/nzbhydra2#100]
I've noticed that if I keep the search page for NZBHyrda2 open for a few hours when I go to do a search, nothing is found, and upon refreshing the page, I am brought to the login page. Under Authorization, I have cookies set to expire after 30 days, but it still times out after less than. NZBHyrda v1 did not have this issue.

The specific part of the logs show this;
`2018-01-29 18:12:02.164  INFO --- [0.0-8006-exec-5] org.nzbhydra.searching.SearchWeb         : [Search: 122843, IP: <IP>] New search request: SearchRequest{source=INTERNAL,<.....>`

`2018-01-29 18:12:02.398 ERROR --- [0.0-8006-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [Search: 361021, IP: <IP>] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception`

`org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.`

**Comment by theotherp** [comment]
Generally, please post the debug infos ZIP. ALWAYS. Don't just paste an extract from the log. The issue template even says so.

Anway, I'll try to reproduce and fix this.
