### ISSUE TITLE
Version number doesn´t show and API-call to github gives 403

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#101]
On my Ubuntu 16 test-installation i have a very strange problem: the call to the Github API for updates and version information doesn´t work anymore and returns a 403.
Everything else works fine (searching, sending nzbs to nzbget etc). I tried to ping `github.com` and it works. On an identical "production" installation everything works fine. I tried a manually update, same problem.
[nzbhydra-debuginfos-2018-01-30-11-13.zip](https://github.com/theotherp/nzbhydra2/files/1677216/nzbhydra-debuginfos-2018-01-30-11-13.zip)

**Comment by Hobbabobba** [comment]
noticed #89 and will try another useragent setting.

**Comment by Hobbabobba** [comment]
looks like a general problem with my os-installation. Not hydra-related.

**Comment by theotherp** [comment]
Well that was a roller coaster :-D

**Comment by theotherp** [comment]
Aha! Well, do you restart your container / process every 30 seconds or something? Hydra should cache the update infos and only refresh them every 15 minutes. It doesn't seem to be a problem for any other users. I'm not gonna put my API key in the code for the update infos - unfortunately GitHub still doesn't provide read-only tokens.

**Comment by claym** [comment]
No, however I’ve got a full suite of apps that check GitHub status regularly. 

I think I’ve seen one or who apps that allow you to enter your own API token in.

**Comment by Hobbabobba** [comment]
no idea what you changed, but since 1.3 it works flawless.

**Comment by theotherp** [comment]
Huh...

**Comment by theotherp** [comment]
I didn't change anything in that area. Well, as long as it works...
