### ISSUE TITLE
Error 404 on initial startup

### ISSUE THREAD

**Issue by spacecakes** [theotherp/nzbhydra2#105]
Starting the **NBZ Hydra2** from the `linuxserver-hydra2` Docker container returned the following error. There's not much else to report since I haven't used the software at all. The container is configured as per LinuxServer's instructions and is using `-p 5076:5076`. There's no getting past this.

```An error occured :
404: HTTP/1.1 404
{
  "timestamp" : 1517515309952,
  "status" : 404,
  "error" : "Not Found",
  "message" : "No message available",
  "path" : "/static/html/states/header.html"
}```

**Comment by theotherp** [comment]
Could you try an older tag?

Does the browser console (press F12) say anything?

Am 01.02.2018 21:20 schrieb "Gabriel Lundmark" <notifications@github.com>:

**Comment by spacecakes** [comment]
Um... it started up now. I did nothing but restart the container. But that's good!

**Comment by theotherp** [comment]
Ok, I'll take it 😉

Am 01.02.2018 21:35 schrieb "Gabriel Lundmark" <notifications@github.com>:

**Comment by theotherp** [comment]
I can't really explain why that might've happened. If it happens again please reopen.

**Comment by Eltargrim** [comment]
Just to add to this in case anyone else has the same problem. I ran into this exact issue with the latest version of linuxserver's container (119 at the time of writing). I simply had to clear my browser cache to get it to work.

**Comment by nevillution** [comment]
Just wanted to say I switched from v1 to v2 in same Docker container and got the same error. Restarted container and cleared cookies from my browser did NOT solve the issue.

A <shift><F5> browser refresh of the page in Chrome did the trick!

**Comment by jofimendes** [comment]
@theotherp i run nzbhydra2 in my qnap nas (not the container one) and got the same " HTTP Status 404-not found" after  restore a backup. When the nzbhydra2 is running fine i got the same issue just by rebooting my nas too.

I try to clean the cache in the browser like @aaroncoville said and had tried shift f5 and nothing. 

Other thing, i can restore my backup manually but i've set nzbhydra2 with a password and now when i try to login the password dosen't work. While restoring through the nzbhydra i got the issue above.

I changed the "auth type" to "NONE" in the  file nzbhydra.yml and restart the app but i got the login screen again. 

The only way to have the nzbhydra working again is by doing a clean install but i while restoring i can't pass through login, i pull the correct pass but i can't login and manually the auth set "none" dosen't work.

I'am running the last version 2.90.
