### ISSUE TITLE
Search doesn't work with Drunken Slug or NZBCat (javax.persistence.EntityExistsException)

### ISSUE THREAD

**Issue by benbar21** [theotherp/nzbhydra2#109]
Hi!

I have many indexers set up with Hydra (6box, altHUB, DogNZB, Drunken Slug, nzb.ag, nzb.su, NZBCat, NZBGeek, nzbplanet, oznzb, and Tabula-Rasa). All worked with NZBHydra1, but now NZBCat and Drunken Slug won't work with NZBHydra 2.

I have tried removing them and setting them up again, to no avail. I can check caps, but am unable to complete any search with them. 

I get the same error with both. 

Here is the current error for Drunken Slug: 

A different object with the same identifier value was already associated with the session : [org.nzbhydra.searching.SearchResultEntity#-1620806341965025013]; nested exception is javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.nzbhydra.searching.SearchResultEntity#-1620806341965025013]
--

Here is the current error for NZBCat: 

A different object with the same identifier value was already associated with the session : [org.nzbhydra.searching.SearchResultEntity#7139667612807239853]; nested exception is javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.nzbhydra.searching.SearchResultEntity#7139667612807239853]
--

Here is the zip created by the bugreport page:

[nzbhydra-debuginfos-2018-02-03-16-07.zip](https://github.com/theotherp/nzbhydra2/files/1692232/nzbhydra-debuginfos-2018-02-03-16-07.zip)

Let me know if you need any further information!

Ben

**Comment by theotherp** [comment]
The good thing is that I can reproduce it and it's basically not my fault but the indexers'. I've

But I'll make it more robust to better handle this problem.
