### ISSUE TITLE
Update resets/deletes nzbhydra.yml

### ISSUE THREAD

**Issue by michaelarlt** [theotherp/nzbhydra2#110]
If i trigger the Update, nzbhydra is deleting or even overwriting the nzbhydra.yml config file in the subfolder data for whatever reason. If i take a backup in front of the procedure and copy back once im getting initial errors after the update procedura it does start of course. So atleast the wrapper in linux is working for me.
Attached both the log files. If you need further informations, please let me know.
Timestamp of the copied .yml is 2018-02-04 8:56 if you want to crosscheck against the logfiles.

[wrapper.log](https://github.com/theotherp/nzbhydra2/files/1692590/wrapper.log)
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/1692591/nzbhydra2.log)

**Comment by theotherp** [comment]
#108 is about the same issue, although there I thought it was caused by windows rights which can't be the case here.

Unfortunately I can't reproduce the problem.

**Comment by theotherp** [comment]
Please post the debug infos ZIP which should contain more log output.

**Comment by theotherp** [comment]
I've added code to the new version which should prevent the sympton (if not the root cause). Obviously it will only work when you update from that version (hopefully).

**Comment by michaelarlt** [comment]
Thanks a lot. I'll increase the loglevel for the further upgrades to upload them once you'll request them. Apart from that, i'll keep you updatet.

**Comment by michaelarlt** [comment]
Just ran the update to version 1.3.2 and the issue is gone. Thanks a lot for your effort and the awesome work ;)

**Comment by theotherp** [comment]
Yay.
