### ISSUE TITLE
Clean indexer statuses / Add option to truncate history & stats

### ISSUE THREAD

**Issue by Obscurax** [theotherp/nzbhydra2#112]
First of all thanks for NZBHydra2 because wow V2 is A LOT faster. Java certainly is the way to go.

Indexer statuses:
When I check the indexer statuses page at first glance I think all indexers are disabled. Optical (I think) it would be better to remove the 'reason' when the indexer is enabled. This is because they all fail once in a while and they all have a reason why they've been disabled in the past. (I think) it would be better when you hover over or click on the time of the last failure to show the fail reason. I hope this makes sense.

History/stats:
I would like a button to delete all history and/or stats, every once in a while I want to start over.

Thanks for your time and dedication.

**Comment by theotherp** [comment]
I agree with the first point. I look at that page so rarely but when I do it looks very cluttered. I'll think about it.

See #29 for the second point. You can't really delete only the stats but delete everything older than a certain age which effectively be the same.

**Comment by theotherp** [comment]
For truncating the history see #29.

**Comment by Obscurax** [comment]
About the indexer statuses. It seems like the indexers are not automatically reenabled. Time and date is now 13:19 12/02/2018.

![2018-02-12 13_15_13-nzbhydra](https://user-images.githubusercontent.com/6681453/36096587-54fd6494-0ff7-11e8-8182-51c7a3bc1e4c.jpg)

**Comment by theotherp** [comment]
Oops

**Comment by theotherp** [comment]
This got a bit more complicated than I had anticipated...
