### ISSUE TITLE
[Visual Bug] Stats

### ISSUE THREAD

**Issue by danjames92** [theotherp/nzbhydra2#116]
![chrome_2018-02-06_20-16-28](https://user-images.githubusercontent.com/16107603/35882022-a99460c4-0b7a-11e8-8ab8-b068733502c7.png)

![chrome_2018-02-06_20-17-08](https://user-images.githubusercontent.com/16107603/35882041-bb419d64-0b7a-11e8-88fb-3ef3541efa0c.png)

[Cut off text / out of circle text]

**Comment by theotherp** [comment]
The first one I can't fix, already spent multiple hours on it. The second is somewhat easy to fix I think.
