### ISSUE TITLE
NZBGet Unable to Fetch URL/Unable to add NZB

### ISSUE THREAD

**Issue by whispy** [theotherp/nzbhydra2#12]
**Environment**
- NZBGet 19.1 (docker container)
- Hydra 2, 1.0.2  (docker container)
-- Internal/external port changed to `5075`

---

**Steps:**
1. Delete all downloaders in Hydra
2. Add NZBGet as a downloader with `NZB Adding Type` `Send Link`. Checking in NZBGet shows `NZBHydra 2 connected to test connection` was successful.
3. Run a search, find a result, and send it to be downloaded
4. Result shows in NZBGet as `Fetching` `URL`

**Results:**
- NZBGet errors with `Connection to 127.0.0.1 failed: ErrNo 111, Connection refused` and fails to get the nzb file (see screenshot: https://vgy.me/rGEBBb.png)

**Alternate Steps:**
1. 1 and 2 from above.
2. Select `NZB Adding Type` `Upload NZB`
3. Run a search, find a result, and send it to be downloaded.

**Results:**
- Hydra shows the error: `Unable to add NZB. Make sure the downloader is running and properly configured.`

_Note:_ I had no issues with these settings in Hydra 1.

**debuginfos:**
https://dl.dropboxusercontent.com/s/tkob0k5gk38eueb/nzbhydra-debuginfos-2018-01-06-19-03.zip

Please let me know if I can provide more info or troubleshooting. Hopefully I'm not overlooking something basic like I did in my last issue... :P

**Comment by whispy** [comment]
I'm having a similar issue in Sonarr too:
````
Error
	ReleaseModule	Downloading nzb failed: Downloading nzb failed	7:16pm
	Nzbget	Downloading nzb for episode '<SHOW NAME>' failed (http://127.0.0.1:5075/getnzb/api/4709310699468001055?apikey=(removed): Error: ConnectFailure (Connection refused): 'http://127.0.0.1:5075/getnzb/api/4709310699468001055?apikey=<API KEY>'
````

It looks like both NZBGet and Sonarr are trying to connect to `127.0.0.1`. Since I'm running Hydra in a Docker container, I think it should be trying to connect to a different IP. For example, I connect to Hydra's web UI via `192.168.0.XXX:5075`, not `127.0.0.1:5075`

**Comment by whispy** [comment]
I also note that, in Hydra's logs, it lists the IP as `172.17.0.1`, which I believe is the internal Docker IP?

`2018-01-06 19:15:33.639  INFO --- [0.0-5075-exec-2] org.nzbhydra.api.ExternalApi             : [Search: 428223, IP: 172.17.0.1] Search took 8590ms. Returning 25 results`

**Comment by theotherp** [comment]
Enter http://192.168.0.whatever:5075 as your external URL in the hydra config.

**Comment by whispy** [comment]
That worked, but I also had to toggle `Use local address in API results` to `Off`. It was `On` by default.

**Comment by theotherp** [comment]
Makes sense. Thanks, will add some notes to the docker instructions.
