### ISSUE TITLE
FR: Filtering Results by Typing in Search Box like NZBH1

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra2#120]
I love NZBHydra2, it's genuinely an improvement all around.  The only functionality I'm missing is the ability to filter the results in the search box by adding additional words, which was quick and easy.

## How to request a new feature
* What do you want to happen?

I'd like to have the ability to type into the search box and have the results filtered like the original NZBHydra had.  

* If not clear, why do you want it?

It was a quick and clean way to quickly whittle down results.  For example, if you searched for `Titanic 1997 Bluray` and it returned 100+ results you could very easily add some qualifiers like a group tag, resolution, or audio format without having to actually run the entire search again.

* Do you think it's something only you need or something that might be popular?

Considering it was in the original NZBHydra I imagine people might miss it.  Certainly power users like myself found it indispensable. 

Thanks!

**Comment by fryfrog** [comment]
I use this all the time in the original and had to go prove to myself it isn't in this one because I swear it is. But you're right, it doesn't do it. I'm +1 for this, using it virtually every time I do a manual search.

**Comment by theotherp** [comment]
Click the filter buttons in the the results table header (the funnel).

Am 08.02.2018 23:16 schrieb "Donald Webster" <notifications@github.com>:

**Comment by albino1** [comment]
Ahh... interesting.  A lot of good stuff in those funnels.  Thanks so much!

**Comment by albino1** [comment]
Reopening for a small suggestion: would it be possible to have the results update live like before as opposed to having to hit enter?  Not a big deal, but I thought it was a little quicker and it really showed you what was happening as you modified stuff.  Even if it's just for the Title search and not for the other ones, that would be an improvement.  

If not, this is plenty good, but thought I'd throw it out there.  Thanks!

**Comment by theotherp** [comment]
I'll see what I can do. If it's quickly done, yes.

**Comment by fryfrog** [comment]
That funnel is really well hidden.

If making it part of the original search box isn't possible, it would be much more obvious and usable if *another* text box appeared underneath the Search box, with a title of Filter and a big text box next to it just like search.

**Comment by theotherp** [comment]
No, I'll keep it that way. That symbol is widely used for filtering. I will not anything that relates to the search results to the search area.

**Comment by fryfrog** [comment]
Two people had no idea this feature existed until you pointed it out. The icon is well known, you're right. But it is tiny and placed in a way that makes it look more like a sort direction button. If you don't want to improve the usability by making an always showing filter text box, at least consider something else to raise discoverability.

A bigger icon that is part of the search bar itself (like the type selector, search history and go button) would improve discoverability and be a very logical association.

**Comment by albino1** [comment]
As an alternative suggestion, maybe put an always there search box in title box, like this:

![nzbh-filter-results-bar](https://user-images.githubusercontent.com/12164957/36054927-e66600f4-0dad-11e8-8e74-c3f8bc0a7c9b.jpg)

**Comment by theotherp** [comment]
I went with that.

**Comment by albino1** [comment]
Looks great and works great, thanks!

**Comment by fryfrog** [comment]
I concur, perfect and super discoverable. Thanks! :)

**Comment by theotherp** [comment]
I experimented with adding a guided tour to explain all the functions but that was too much work. I'm pretty sure there are a lot of things in Hydra that are barely known or used... :-)

**Comment by albino1** [comment]
I'm consistently amazed how powerful this tool is.  When people recommend it as "a way to combine your indexers" or "an easier way to search" they're really selling it short :)
