### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by danjames92** [theotherp/nzbhydra2#121]
* What do you expect to happen? **No java error? Not sure.**

* Can the problem be reproduced? How? trigger mass search i.e. 1000+ show search

[java.txt](https://github.com/theotherp/nzbhydra2/files/1714315/java.txt)

Using 200MB.

**Comment by theotherp** [comment]
Well, try a higher XMX value...

Also you didn't post the debug infos... Just restart Hydra, go to the system tab and generate the ZIP like the instructions that you ignored told you.

**Comment by danjames92** [comment]
I have now set it to 500MB. 

[nzbhydra-debuginfos-2018-02-11-12-43.zip](https://github.com/theotherp/nzbhydra2/files/1714357/nzbhydra-debuginfos-2018-02-11-12-43.zip)

**Comment by theotherp** [comment]
How big is your database file?

**Comment by danjames92** [comment]
nzbhydra.mv.db is 97.2MB.

**Comment by theotherp** [comment]
Sorry for the delay. Do you still have this problem?

**Comment by danjames92** [comment]
Not since I raised it to 500MB but it should probably work with a lower amount of RAM used than that?

**Comment by theotherp** [comment]
Yes it should. I guess you have one of the newer versions running? Please post a current debug infos ZIP.

**Comment by danjames92** [comment]
Was on 1.4.6, just upgraded to 1.4.7 and post logs later.

Noticed the reload animation (on upgrade waiting for nzbhydra to return message) doesn't stay long enough for the app to reboot properly so I get a service unavailable message and have to refresh the page manually after about 15 - 20 seconds.

**Comment by danjames92** [comment]
Here's some logs now... hopefully they help.

[nzbhydra-debuginfos-2018-03-14-07-31.zip](https://github.com/theotherp/nzbhydra2/files/1810012/nzbhydra-debuginfos-2018-03-14-07-31.zip)

**Comment by theotherp** [comment]
Yeah, the restart doesn't work properly. I ping the server to find out when it's back and unfortunately it returns the ping long before that page can actually be loaded. It's hard to test and debug so I've avoided trying to fix it yet... ;-)

**Comment by theotherp** [comment]
You need to manually update the wrapper by shutting down Hydra and overwriting the executable from https://github.com/theotherp/nzbhydra2/releases/download/v1.4.7/nzbhydra2-1.4.7-linux.zip

My update function isn't yet able to update the wrapper itself. The new version will cause Java to write log files for the memory consumption. Wait a day or so and post the new debug infos.

Sorry about that.

**Comment by danjames92** [comment]
That's ok, would be wise to always mention that in the changelog if the release requires it. 👍

**Comment by theotherp** [comment]
A heap dump would also help. Wait for the java process to be at least a couple of hours old, then find out its PID and run `jmap -dump:format=b,file=hydra.bin <pid>`.

Zip that file and post it here. If it's too big I recommend using [http://ufile.io/](http://ufile.io/).

**Comment by theotherp** [comment]
You're right, I added it for v1.2.2 but not for the one where I changed the wrapper again. The only changes were related to the memory logging and I didn't consider it important enough for most users. But I'll make sure to note any changes to the wrapper in the changelog.

**Comment by danjames92** [comment]
Out of interest I'm switching to a docker based system soon, does the docker require manual intervention or will it auto update (inc wrapper) on docker stop / start?

**Comment by theotherp** [comment]
I'm not much of a docker expert but I was told docker containers should never update internally (meaning using the embedded update mechanism). When you pull the latest container version it will update. This may be done on startup but I don't know for sure. That's more of a general question which I'm afraid I'm not qualified to answer.

**Comment by danjames92** [comment]
@hotio maybe you can comment here given it runs off your suitarr?

**Comment by danjames92** [comment]
@theotherp 

link to heap dump https://ufile.io/8hlx1

**Comment by theotherp** [comment]
Please also post your newest debug infos ZIP which should hopefully contain more logs (because you updated the wrapper).

I currently can't explain why it takes so much memory.

**Comment by danjames92** [comment]
@theotherp here ya go, sorry I forgot.

[nzbhydra-debuginfos-2018-03-17-10-06.zip](https://github.com/theotherp/nzbhydra2/files/1821494/nzbhydra-debuginfos-2018-03-17-10-06.zip)

**Comment by theotherp** [comment]
Sooo... your currently running instance would probably run well with 200 XMX or even less without crashing. I made some changes a couple of weeks ago that hopefully fixed some memory leaks. You could try running Hydra with 200 XMX and see what happens. I just released 1.4.9 with another update to the wrapper. It will write the memory dump file automatically when an OutOfMemory exception occurs. That will allow me to see the content of the memory at the time of the crash.

So my advice is this: Update the wrapper, use XMX 200 and see what happens.

**Comment by danjames92** [comment]
Well like I said in the opening post I was using 200MB and it wasn't stable under load.

I've just updated to 1.4.9 (manually), set to 200MB.

**Comment by theotherp** [comment]
I understood that but the ticket is a month old and issue might already have been solved. At least that's what I hope.

**Comment by hotio** [comment]
Usually a docker image is static, the person that creates it, will test it and if all goes as planned, it'll get released to the world. Every user that creates a container based on that image will be running exactly as the maintainer of the image intended it.

However, with fast updated sofware like in this case nzbhydra2, jackett, radarr, etc. you'll have to wait for the maintainer to update the docker image... annoying when you wanna run the latest and greatest.

This is the "ideal" way to work with docker for stability reasons. Docker image is basically a self contained app that has everything bundled to run, and should be fairly OS independent.

Suitarr does it a bit different, everything required to run the supported apps is bundled, except the apps themselves, when suitarr starts up, the latest version is downloaded and installed. Just a restart of the container will have you running the latest version. You don't have to wait for me to update the image.

The downside, besides breaking the "docker way", when you've got no internet/github or appveyor down, the app can't get downloaded. Luckily I provide an option to feed a binary for installation.

**Comment by saitoh183** [comment]
[java_pid415.zip](https://github.com/theotherp/nzbhydra2/files/1840219/java_pid415.zip)
 
![image](https://user-images.githubusercontent.com/1534197/37812451-7514b7d4-2e36-11e8-9137-983410b6f775.png)

**Comment by theotherp** [comment]
@saitoh183 The actual thread dump is not very big. The memory usage of the process should be significantly less than 1024M or, to be more precise, work with a lot less memory.
