### ISSUE TITLE
Move the Cancel button during indexer search

### ISSUE THREAD

**Issue by digitaldelboy** [theotherp/nzbhydra2#124]
* What do you want to happen?
Move the cancel button when searching for results so I don't have to chase it to click on it.

* If not clear, why do you want it?
Pretty silly request and probably should be last on priority but I have a large collection of indexers and when I search and then quickly want to cancel, I have to scroll and quickly try and hit the cancel button lol.

* Do you think it's something only you need or something that might be popular?
LOL probably only me.

**Comment by theotherp** [comment]
I think I spent half a day on getting that to behave properly and gave up. I can add "Escape" as a hotkey (perhaps that already works, give it a try).

**Comment by digitaldelboy** [comment]
Thank you Escape already works.
