### ISSUE TITLE
Import database from Hydrav1 to Hydrav2 fails with a Java Exception on FreeBSD 11.1

### ISSUE THREAD

**Issue by Thefrank** [theotherp/nzbhydra2#125]
* What do you expect to happen? What does happen? 
Import to work. It throws an exception

* Can the problem be reproduced? How?
As using nzbhydra2-1.4.2-linux:
Either by copying files from 0.2.233 to a tmp path (for method 2) or using method 1. Both give the same result. Honestly, I didn't expect method 1 to work anyways as each version of Hydra are in different jails which are kinda like containers.

Some more details
Hydra v1 is in an old "warden" style jail running FreeBSD 11.0. Hydra v1 is launched via python2.7
Hydra v2 is in an "iocage" style jail running FreeBSD 11.1. Hydra v2 is launched via the wrapper using python2.7. I have included the output of "pkg info" for this jail in my debug info.

[nzbhydra-debuginfos-2018-02-21-18-55.zip](https://github.com/theotherp/nzbhydra2/files/1746410/nzbhydra-debuginfos-2018-02-21-18-55.zip)

**Comment by theotherp** [comment]
Will be fixed today or tomorrow; sorry about that.
