### ISSUE TITLE
Lib folder error "/Applications/nzbhydra2/lib not found"

### ISSUE THREAD

**Issue by meat-ball** [theotherp/nzbhydra2#128]
MACOS Sierra
I have the python file dropped in the main NZBH2 director (also have jDK8 installed) but I keep receiving this error when trying to launch the app from terminal (error message is the same in logs): "Error: Lib folder /Applications/nzbhydra2/lib"

I apologize, I had NZBH2 running fine before a recent OS reinstall and for whatever reason, Im running into this error and tried multiple ways of getting this launched to no avail. 
FYI really appreciate your work on this NZBHv2 is awesome. Thanks a lot.

**Comment by theotherp** [comment]
Well, does that folder exist? What does the folder `/Applications/nzbhydra` look like?

**Comment by meat-ball** [comment]
the lib(s) folder it's looking for isn't there like it is NZBHv1. I can't be sure but I thought this was resolved was I installed JRE. 

![screen sharing picture february 25 2018 at 1 54 36 am pst](https://user-images.githubusercontent.com/5460919/36640229-875e610e-19cf-11e8-8018-97134f4142da.png)

**Comment by theotherp** [comment]
You must extract the ZIP somewhere and put the wrapper.py file in the same folder, then run the python file.

**Comment by meat-ball** [comment]
thats what I did. you can see the wrapper file there. running it is what brings the lib folder error

**Comment by theotherp** [comment]
Make sure to run it in/from the same folder.

Your screenshot does not show the content of the nzbhydra folder.

**Comment by meat-ball** [comment]
sorry Just updated the screenshot

**Comment by meat-ball** [comment]
Not sure if this is gives any insight but this is the error I ran into (same as in logs)

![nzbh2 term](https://user-images.githubusercontent.com/5460919/36640332-23ae3a2e-19d1-11e8-94e4-40698053df80.png)

**Comment by theotherp** [comment]
Glad it's working now.
