### ISSUE TITLE
Basic instructions for macOS (High Sierra)

### ISSUE THREAD

**Issue by Alrescha-git** [theotherp/nzbhydra2#13]
To get nzbhydra2 running (commandline):

- Install Java(8).  If you want the standard gui install go to [java.com](https://java.com).
If you want my minimalist recommendation, go to [Oracle](http://www.oracle.com/technetwork/java/javase/downloads/index.html) and download the Java SE release 8 JRE tar.gz file.  That's the one with no installer.  Just double-click it to unpack and put the files where you want.

- Download the linux version of nzbhydra2 from https://github.com/theotherp/nzbhydra2/releases and unzip it somewhere.

- cd to the nzbhydra2 directory and run the following: 

`java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=ALWAYS -jar lib/core-1.0.0-exec.jar directstart`

or (if you used my minimalist install of Java)

`export JAVA_HOME=/SOMEPATH/jre1.8.0_152.jre/Contents/Home`
`$JAVA_HOME/bin/java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=ALWAYS -jar lib/core-1.0.0-exec.jar directstart`

Notes:

Those java options are extracted from the python obfuscation, and some may not be necessary.

You must get Java SE **8**.  Nzbhydra2 will not run with Java SE 9.

The formatting of the Config pages is a bit strange in that everything wraps badly.  Reducing the font size helps a lot, so use command and -

I just run this in a Terminal window.  It's possible to create a fancy launchdaemon entry to auto(re)start it as needed, but I'm too lazy to do that now.  Until then things like restart won't work, use shutdown and rerun hydra from the Terminal window.

**Comment by theotherp** [comment]
Thank you.

**Comment by deanishe** [comment]
> Those java options are extracted from the python obfuscation

The [wrapper script](https://github.com/theotherp/nzbhydra2/blob/master/other/wrapper/nzbhydra2wrapper.py) works on macOS (after you install PyYAML).

**Comment by Alrescha-git** [comment]
> The wrapper script works on macOS (after you install PyYAML).

Yes, I snapped at the need to install/maintain two languages and an add-on package in order to run nzbhydra and just shredded out the requirements.  I was in debug mode as it did not work at all with my first choice of JRE (SE 9).

:-)

**Comment by theotherp** [comment]
I'll remove the PyYAML dependency soon (it's just used to read one single entry).

In the long term I hope to replace the python based wrapper with a leaner custom written, but that will have to wait until the base program runs fine.

**Comment by deanishe** [comment]
> install/maintain two languages and an add-on package

Python is part of macOS, so requiring Python isn't really an issue.

> my first choice of JRE (SE 9)

Fortunately, I have a much older version installed from the last time a program I wanted to run was unfortunately written in Java 😜 

I'm not 100% sure about this, but I think if you install the JDK instead of the JRE, you get a `/usr/bin/java` command, which saves faffing around trying to figure out where your JRE is installed.

In any case, I have a `/usr/bin/java`. I can't remember exactly why, but I certainly didn't put it there myself.

**Comment by deanishe** [comment]
> leaner custom written

The Python wrapper runs in about 0.1s. Given that the app proper takes 200x longer to start up, I'd say there's little to be gained by optimising the wrapper.

**Comment by theotherp** [comment]
It's more about the file size and memory usage.

**Comment by theotherp** [comment]
PyYAML dependency is gone.

**Comment by Alrescha-git** [comment]
> Python is part of macOS, so requiring Python isn't really an issue.

Except that nzbhydra1 does not run with the shipping version of python (2.7.10).  Thank you for playing.

> if you install the JDK instead of the JRE, you get a /usr/bin/java command, which saves faffing around trying to figure out where your JRE is installed.

Yes, it does, which is why my first suggestion is to just get the GUI Java installer from Java.com.  But thanks again.

Personally, what I hate about using Java is the obnoxious binary installers which require root and dump in automatically spawning 'helpers' and other garbage.  If it weren't for the installer-less JRE, I simply would not consider having Java at all.

It will be a nice thing for macOS users if a simplified python wrapper was compatible with the shipping version of python, then they could just install Java and go.

A.

**Comment by Alrescha-git** [comment]
The new wrapper works (with the stock version of python) if I specify a value for xmx, but if I don't the parameter list looks like it has an embedded cr after 128 and before "M" and java complains.  I've stared at the code and don't see it.

Other than that everything looks good.

**Comment by deanishe** [comment]
> Except that nzbhydra1 does not run with the shipping version of python (2.7.10)

We're talking about NZBHydra **2**, and I'm running it right now with the system 2.7.10.

> Yes, it does, which is why my first suggestion

But your *recommendation* was the minimal JRE…

> Thank you for playing

If you're going to be rude, at least try to be correct as well…

**Comment by Alrescha-git** [comment]
> If you're going to be rude, at least try to be correct as well…

If you're going to be a backbiting asshole, just don't.  Fuck off.

**Comment by theotherp** [comment]
@Alrescha-git Thanks for the contribution :-)
