### ISSUE TITLE
Why the re-write in Java?

### ISSUE THREAD

**Issue by greencopper** [theotherp/nzbhydra2#131]
As the title says, why the re-write in Java?

**Comment by theotherp** [comment]
Some answers here: https://www.reddit.com/r/usenet/comments/7ojguw/first_public_release_of_nzbhydra2_better_faster/ and here: https://github.com/theotherp/nzbhydra2/blob/master/readme.md

Short: I know it better and can do the better program using it.

**Comment by greencopper** [comment]
Thanks!
