### ISSUE TITLE
Exclude results in filter box

### ISSUE THREAD

**Issue by sumofatguy** [theotherp/nzbhydra2#135]
NZBHydra2 is great, and I used it almost every day. The ability to manually filter results is awesome to have back in the recent versions, I would just like if the filter box could _exclude_ results.

How to request a new feature
What do you want to happen?
I'd like to have the ability to exclude results in the filter box, possibly by adding '-' before the keyword (like popular search engines)

If not clear, why do you want it?
It would add additional usability to the existing filter box

Do you think it's something only you need or something that might be popular?
I believe many people might make use of it. It's a 'simple' way to exclude results in many search engines, it would be nice if hydra had it as well. 

Thanks!
![untitled-1](https://user-images.githubusercontent.com/228393/37005264-c1c4f5fc-2090-11e8-8086-b1df81e3e494.png)

**Comment by albino1** [comment]
+1 

If it's easy I would definitely use this.

**Comment by theotherp** [comment]
Good idea, funny I never thought of that.

**Comment by theotherp** [comment]
I chose "!" instead of "-" because it's usually not present in titles and I split results by "-" when searching.
