### ISSUE TITLE
Hold shift to select check box range

### ISSUE THREAD

**Issue by digitaldelboy** [theotherp/nzbhydra2#136]
It would be good to add something similar to what sabnzbd has where you hold shift and click on a check box and then click on another check box and it would put a tick in all the other ones between those two.

Hope you understand :)

**Comment by theotherp** [comment]
That worked at some point...

**Comment by theotherp** [comment]
Hmm, what browser are you using? It seems to work with Chrome but not with Firefox. I usually use FF but Chrome for development.

**Comment by digitaldelboy** [comment]
I use Firefox, would you be able to get it working in FF.

**Comment by theotherp** [comment]
Already pushed the fix, available in next version.

**Comment by digitaldelboy** [comment]
Thank you :)
