### ISSUE TITLE
Show all results on one page

### ISSUE THREAD

**Issue by digitaldelboy** [theotherp/nzbhydra2#137]
More of a question but how do I show all the results on a single page, I'm only seeing eight results but with nine pages.

**Comment by theotherp** [comment]
https://i.imgur.com/6KE9wgq.png

**Comment by digitaldelboy** [comment]
Thanks but it must be broken, after clicking "Load All Results" I see the blue loading bar thing going across and when it gets half way it jumps to the end and nothing changes. It still has "Loaded 1166 of 1927" and there are still multiple pages.

Also how do I get the nzb to go to specific categories in Sabnzbd, So I'd like TV Shows to go to my TV shows category in Sab, Movies to go to the Movies Category etc.

**Comment by theotherp** [comment]
In the downloader config write "No category" as default category.

**Comment by digitaldelboy** [comment]
Sorry

[nzbhydra-debuginfos-2018-03-14-11-49.zip](https://github.com/theotherp/nzbhydra2/files/1810880/nzbhydra-debuginfos-2018-03-14-11-49.zip)

![1](https://user-images.githubusercontent.com/33402113/37400822-08ff0162-277e-11e8-8188-4ad8e322a717.PNG)
![2](https://user-images.githubusercontent.com/33402113/37400824-091e1232-277e-11e8-81b1-8963834be6f0.PNG)

**Comment by theotherp** [comment]
I'll have to do some tests. I *think* I added a circuit breaker that stops after five or ten calls to prevent hammering the indexers.

There's a also a problem with DogNZB's API results which they never managed to fix which requires me to make a dirty workaround and which makes the whole handling much more complicated and error prone than it needs to be.

**Comment by theotherp** [comment]
In this case I can't see it but usually you should see this line in the log:
`Aborting loading all results because more than x results were already loaded and we don't want to hammer the indexers too much`

**Comment by theotherp** [comment]
Already implemented, kinda...
