### ISSUE TITLE
Question about indexers

### ISSUE THREAD

**Issue by saitoh183** [theotherp/nzbhydra2#138]
I use Sonarr for English tv shows and Anime but i use Medusa (fork of sickrage) for my french TV shows. If i were to add my torznab french indexers that are in jackett to Hydra, could i make them only be used when the query comes from Medusa so there isnt a chance that Medusa gets the file in english, So english shows i carry the french version as well.

**Comment by theotherp** [comment]
No, that's not possible.

If Medusa searches only using the newznab category for "Foreign" (5020) then you could enable your french indexers only for that category. If Medusa searches "5000" or "5030,5040" or something like that there's no way to do what you want.

**Comment by saitoh183** [comment]
ok thanks  :)
