### ISSUE TITLE
Does not work with TPB (using Jackett)

### ISSUE THREAD

**Issue by manderss99** [theotherp/nzbhydra2#139]
Add The Pirate bay in Jackett
Verify by doing manual search in Jackett (works ok)
Add Pirate bay in hydra
Search for something: Hydra hangs on search dialogue

**Comment by manderss99** [comment]
If I select TPB and an additional indexer the search dialogue closes, 
indexer statuses say 0 for TPB, results are shown for TPB but shown as NZB

**Comment by theotherp** [comment]
Follow the bug report instructions.

manderss99 <notifications@github.com> schrieb am Sa., 17. März 2018, 06:14:
