### ISSUE TITLE
Looks for `lib` folder in datafolder path instead of WorkingDir

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra2#14]
I'm working on the AUR package for nzbhydra2 and the typical setup is `/usr/lib/nzbhydra2` for static content and `/var/lib/nzbhydra2` for db, etc. When I feed in --datafolder, it then looks for `lib` there too.

2018-01-06 12:17:03,088  CRITICAL - Error: Lib folder /var/lib/nzbhydra2/lib not found. An update might've failed or the installation folder is corrupt

**Comment by theotherp** [comment]
Try starting from the folder where the binary is located.

**Comment by fryfrog** [comment]
Actually, this looks like how the auto updater works. Working as intended?

**Comment by theotherp** [comment]
What do you mean?
