### ISSUE TITLE
Request- API key per user

### ISSUE THREAD

**Issue by kylerw** [theotherp/nzbhydra2#140]
Would like to be able to differentiate API calls by user.

**Comment by theotherp** [comment]
Not gonna happen.

**Comment by aconitumnapellus** [comment]
Can you quickly elaborate what has to be done to implement this feature myself? 
Its clear why you dont want that, but i really like that feature to control what application uses x api hits. 

So could you atleast lead me in a direction? 
I would be very grateful.

**Comment by theotherp** [comment]
@aconitumnapellus  Are you a java developer?

**Comment by aconitumnapellus** [comment]
@theotherp I think i have enough java knowledge to atleast try it, so yes.

**Comment by theotherp** [comment]
I'll try to write something up on sunday.

**Comment by aconitumnapellus** [comment]
@theotherp Did you already wrote something down? Can i help you with something?

**Comment by theotherp** [comment]
Sorry.

In `org.nzbhydra.api.ExternalApi#api` make sure to accept any of the API keys that you want to use. In `org.nzbhydra.api.ExternalApi#buildBaseSearchRequest` add the API key to the `SearchRequest` object. In `org.nzbhydra.searching.IndexerForSearchSelector` check if the indexer should be used for the search depending on the API key. I recommend just deciding this on a random value (see `org.nzbhydra.searching.IndexerForSearchSelector#checkLoadLimiting`) as everything else would require the API key and all that stuff in the database and that would require so much coding and it could break with any future update.
