### ISSUE TITLE
NZBHydra 2 may not work properly when run in E:\Program Files

### ISSUE THREAD

**Issue by Goram** [theotherp/nzbhydra2#142]
Hi,

I collect all programs, where I don´t want to loose the configs, under the path above. Can you allow that to start? I see no reason to just exit the program :)

**Comment by theotherp** [comment]
I could change it so that it only checks on C:.

**Comment by YipYup** [comment]
@Goram Are you saying that you run it from E:\ but it is only making a config file in C:\ ?

@theotherp Linking these just in case they come in handy at all. [Windows Environmental Variables](https://ss64.com/nt/syntax-variables.html)

**Comment by theotherp** [comment]
I'm aware of those environment variables but never thought to compare the `ProgramFiles` variable with the path of Hydra, thanks.

**Comment by Goram** [comment]
@YipYup 
Nope, I just meant that I collect all my progs where I don´t want to loose anything under e:\, so that I can wipe c:\ without probs anytime

**Comment by theotherp** [comment]
Fixed in next release.
