### ISSUE TITLE
Save NZB to black hole

### ISSUE THREAD

**Issue by Goram** [theotherp/nzbhydra2#143]
Hi²,

I love NZBHydra 2 so far, changed today from NZBMegasearch.

What I really miss is "Save to black hole". I use Alt.Binz for downloading and at the moment I choose a few releases, download as zip, click winrar message away, drag and drop the nzb into alt.binz window.

Better workflow:
- Choose releases
- Press "Save to black hole"
- done

Thx! :)

**Comment by theotherp** [comment]
I never thought people would use anything but nzbget or sabnzbd so I never so a reason to implement a black hole for NZBs. I'll add it to the list.

**Comment by Goram** [comment]
Thanks mate!

**Comment by biship** [comment]
Would love this, thank you!

**Comment by titocr** [comment]
Trying to understand if this issue covers what I'm seeing. Currently there's the option under Config->Downloading to set a black hole directory. And from the Search screen, the rightmost item under Link column says "Save torrent to black hole or send magnet link" on hover. Clicking that option doesn't seem to save the link to the directory from config. Will this issue fix that?

**Comment by biship** [comment]
no, what you're doing works for me. It'll save the .torrent file to whatever you configured for your torrent blackhole. We're asking for an additional option to save nzb's to a nzb blackhole.

**Comment by buntin7419** [comment]
+1 for the nzb blackhole folder please.

**Comment by theotherp** [comment]
I gave it a shot once and it turned out to be much more complicated than
anticipated. Will be a while until I'll have time to get it done.
