### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by Dulanic** [theotherp/nzbhydra2#144]
## How to do a bug report

So just starting in the past couple days, I've noticed my radarr/sonarr reporting that hydra wasn't working. So I went over to my hydra address and it keeps saying access denied. I looked deeper into the logs and kept saying authentication failed. I don't use any authentication for hydra as it is only locally accessible and is run in docker.

![image](https://user-images.githubusercontent.com/2948206/37911932-f0ba5af4-30d6-11e8-81d4-723c99816a67.png)

Docker Container:
https://github.com/linuxserver/docker-hydra2

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076system/bugreport). If other tools are involved post their logs as well.**

[nzbhydra-debuginfos-2018-03-26-09-09.zip](https://github.com/theotherp/nzbhydra2/files/1848159/nzbhydra-debuginfos-2018-03-26-09-09.zip)

* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
I don't have steps really, it just started happening recently and I can find nothing that has changed.
* What do you expect to happen? What does happen? 
NZBHydra allows me to edit config etc... via system tab.
* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
Not sure original cause, so not sure, but I can't correct this issue to attempt to recreate.
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

**Comment by Dulanic** [comment]
Figured it out, my proxy was down and that seemed to be causing this problem.

**Comment by Dulanic** [comment]
Reopening, I was wrong, same issue continues.

**Comment by theotherp** [comment]
Disable CSRF protection in the main config. If Hydra is run locally there's no downside.

**Comment by Dulanic** [comment]
Thanks, yeah I don't plan to allow outside traffic either way and can use vpn if I really needed to. Seems to be fine without CSRF.
