### ISSUE TITLE
Does not filter from search results

### ISSUE THREAD

**Issue by knarf1** [theotherp/nzbhydra2#146]
One of my favorite features of the original was the way it would dynamically filter the results based on additional information typed into the search box.  This allows a user to only run one broad search against their indexers (band name for example) and then drill down to find specific releases (album name for example) individually rather than running repeated api calls, the number of which allowed by each indexer being sometimes limited.

This doesn't appear to be a feature in 2 or, if it is, it's not one I'm able to get working.  Please advise.

**Comment by theotherp** [comment]
Use the input field and the filter buttons in the search result table
headers.

**Comment by albino1** [comment]
![nzbhfilter](https://user-images.githubusercontent.com/12164957/38077555-31618a96-32ee-11e8-8c0e-33c11dbcf685.jpg)

**Comment by knarf1** [comment]
Beautiful.
