### ISSUE TITLE
Add 'Downloading->Downloaders' settings per user account.

### ISSUE THREAD

**Issue by 88keyz** [theotherp/nzbhydra2#148]
It would be nice to be able to setup NZBGet or SABnzbd per user so that the 'Downloading->Downloaders' settings weren't universally shared between all user accounts.  This would make the application more multi-user friendly.

**Comment by theotherp** [comment]
No. There's a limit to which I support multiple users. If you're a family or flatmates sharing an instance (e.g. on a common HTPC) that's fine. If you have different downloaders you are free to each run extra hydra instances.
