### ISSUE TITLE
Empty results when using category

### ISSUE THREAD

**Issue by biship** [theotherp/nzbhydra2#150]
v1.4.8, Windows x64. NZBHydra2 is on 5099. apikey verified as correct.

When searching from Lidarr, it calls:
`http://htpc:5099/api?t=search&cat=3000,3010,3020,3030,3040&extended=1&apikey=(removed)&offset=0&limit=100&q=Linkin Park One More Light`
It returns zero results.

Manually running that URL does the same.

Also, no results from:
http://htpc:5099/api?t=search&cat=3000&extended=1&apikey=(removed)&offset=0&limit=100&q=Linkin Park One More Light
![image](https://user-images.githubusercontent.com/1854029/38417747-8ab75c9a-3967-11e8-8329-71c6d10f2450.png)

However, when I remove the category I get results from:
http://htpc:5099/api?t=search&extended=1&apikey=(removed)&offset=0&limit=100&q=Linkin Park One More Light
And those (30 results) results contain categories (only showing first result):

![image](https://user-images.githubusercontent.com/1854029/38417573-d5cc14ce-3966-11e8-9ffe-b4ffcb00cec8.png)

Running the search from NZBHydra2 returns 39 (9 more!).
Debug logs attached. I also included the json debug file.
I also included results.xml returned from removing the category.

[nzbhydra-debuginfos-2018-04-06-06-54.zip](https://github.com/theotherp/nzbhydra2/files/1883693/nzbhydra-debuginfos-2018-04-06-06-54.zip)

**Comment by biship** [comment]
Your the best! Ah, the old OR && AND screw-up - my bad - sorry.
Any chance you can let us use (||, &&) or (OR, AND)?

That's my config. I added all categories thinking if not explicitly specified, then they will be excluded.
Thanks for the help. I expect you'll fix the debug log issue? :)

**Comment by theotherp** [comment]
When you search using "TV" it will search for any TV release. When you search using "TV HD" it will search for any release in "5040". It's possible that 5040 actually includes "5045", you'd need to ask indexer staff about that.

When a result is found with category "5045" and you have your "TV HD" configured is above it will be handled as "TV HD" result. Hydra will try to find the most specific matching category.

**Comment by biship** [comment]
Sorry to bug you, but what do I do in this case?
api.drunkenslug.com had zero results with cat=3000, but when I remove the category from the URL it returns results, all in category 10.

If I set NZBHydra2 in Lidarr to 3000,10 then it seems correct, and finds them:

2018-04-06 12:43:52.619  WARN --- [0.0-5099-exec-4] org.nzbhydra.searching.CategoryProvider  : [Search: 955714, IP: 192.168.1.53] Search supplied a general category and a subcategory: 3000,10. Will use the subcategory Audio

{"@timestamp":"2018-04-06T12:43:52.637-04:00","@version":1,"message":"Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<apikey>&t=search&extended=1&q=Eminem%20Revival&password=0&cat=10,3000&limit=100&offset=0","logger_name":"org.nzbhydra.indexers.Newznab","thread_name":"pool-57-thread-8","level":"INFO","level_value":20000,"IPADDRESS":"192.168.1.53","SEARCH":"556126"}

{"@timestamp":"2018-04-06T12:43:53.071-04:00","@version":1,"message":"Drunken Slug: Successfully executed search call in 432ms with 4 results","logger_name":"org.nzbhydra.indexers.Newznab","thread_name":"pool-57-thread-8","level":"INFO","level_value":20000,"IPADDRESS":"192.168.1.53","SEARCH":"556126"}

As long as I have 3000 in there, NZBHydra2 will assume 'Audio'? 
and I also have to add all indexers special categories to Lidarr or NZBHydra2?
(this last question confuses me)

**Comment by theotherp** [comment]
You have a category "Audio" with the newznab category "3000". Any search using that category will be interpreted as an audio search and use the restrictions you configured.

Is the 10 an example? Never seen that category.

Hydra will try to match indexers' special categories but that will only work to a degree. If an indexer doesn't use the default categories (e.g. 9999 for audio) then it won't work and it wouldn't work without Hydra either.

Not sure if that answers your question...

**Comment by biship** [comment]
I understand that when a search comes to NZBH2 it'll apply the restrictions set in the category that match the cat= on the URL.

No, api.drunkenslug.com liteerally only returns results if I specify cat=10, or remove cat=. Which means at least that indexer has custom categories. Searches will never find those entries unless I add 3000,10 to Lidarr. Which will call NZBH2 with cat=3000,10 - which is good for drunkenslug, but likely not correct for other indexers. And I bet other indexers have their own private categories. 

I'd rather not add all of these categories to Lidar (ie 3000,10,10330,..), otherwise NZBH2 will search all indexers with those categories. Most of which will not be applicable to that indexer.

Do we need indexer specific mappings in NZH2?

**Comment by theotherp** [comment]
> Hydra will try to match indexers' special categories but that will only work to a degree. If an indexer doesn't use the default categories (e.g. 9999 for audio) then it won't work and it wouldn't work without Hydra either.

I will not add indexer specific mappings to solve the indexers' "wrong" categories. It would be very hard to implement  and even harder to work properly, configurable or debug.

Using http://newznab.readthedocs.io/en/latest/misc/api/#music-search should make Hydra do some category mapping but apparently Lidarr doesn't use that, probably because not all indexers support it.
