### ISSUE TITLE
Clarification: Should 'Result' be shown without user scripts? w/Sabnzbd only shows requested

### ISSUE THREAD

**Issue by sunnyd71** [theotherp/nzbhydra2#154]
There seems to be mixed messages if this feature is integrated directly without the need of scripts. The Help tip says it does but other posts say it does not. All of my downloads only ever show 'requested' as result. 

Current setup: Hydra version: 1.4.8 
Sabnzbd: 2.3.2
Full Sab API key provided to Hydra

**Comment by theotherp** [comment]
Yes.

You can enable level for the log file and select the logging marker "Download status updating" to get more information about what's going on.

User scripts are not needed anymore.

**Comment by theotherp** [comment]
Give it some time post the debug infos zip.
