### ISSUE TITLE
Possible to search by lanuage?

### ISSUE THREAD

**Issue by devbrian** [theotherp/nzbhydra2#155]
My indexers support language filtering.  However, I don't see anyway to use this in Hydra.

`Language * Used for movie query generation and autocomplete only.`

Doesn't seem to have any effect.

is this possible?

For example, all of my trackers make responses with:

`<newznab:attr name="language"   value="French" />`

or 

`<newznab:attr name="language"   value="N/A" />`

I want to filter to ONLY accept 
`<newznab:attr name="language"   value="N/A" />`

Is this possible?

**Comment by theotherp** [comment]
No. How does the language filtering work? What indexers?

**Comment by devbrian** [comment]
omgwtfnzbs. returns `<newznab:attr name="language" value="N/A" />`  N/A is english, if not english, it's specified.  Would great to have a filter like this.

**Comment by theotherp** [comment]
Hm, so you can't search by it but I could reject results with unwanted languages. Wouldn't be too hard to do. I'll do it when I have some time.

**Comment by devbrian** [comment]
@theotherp N/A = the default language you pick. I don’t know why they do this. 


N/A = English for me 

I just want to stop getting foreign copies of films that are clearly labeled as not-English by trackers (for items that don’t have audio language in nzb title)

**Comment by theotherp** [comment]
They seem to have changed this so that `language="English"` is used instead of N/A.
