### ISSUE TITLE
Enhancement Request: Only search usenet or torrents

### ISSUE THREAD

**Issue by mikeparkie** [theotherp/nzbhydra2#156]
Would it be possible to add an option for just searching usenet/torrents, I know there's some default options, and I know the searching can be inverted for indexers, but from a usability point of view it would be great to have a little button/checkbox to search usenet/torrents/both. I did look through the previous post and couldn't see anyone requesting this already, so apologies if I missed it. And kudos on developing such an awesome app.

**Comment by mikeparkie** [comment]
Nope! But I do now. Thanks for the education lol

**Comment by theotherp** [comment]
I assume that option is good enough. Thanks for helping out, @fryfrog
