### ISSUE TITLE
Error on searching a title already searched

### ISSUE THREAD

**Issue by intrel** [theotherp/nzbhydra2#158]
I was able to search and get results for a title without any issues. However I get the following error when search for the same title again:
"An error occurred:
500: Internal Server Error

Path: /internalapi/search

Message: result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements" 

Can you please help? cheers!
Attached: Bugreport / Debug infos

[nzbhydra-debuginfos-2018-04-22-11-18.zip](https://github.com/theotherp/nzbhydra2/files/1935906/nzbhydra-debuginfos-2018-04-22-11-18.zip)

(PS - Full disclaimer: I have a very basic understanding of how the whole system works, so please bear with me if I ask some stupid!)

**Comment by theotherp** [comment]
No, you didn't do anything wrong, this is likely a bug. You mean you
repeated the search from the small search history dropdown or you just made
the same search again?

**Comment by intrel** [comment]
I repeated the search but using the search history dropdown return the same error.
