### ISSUE TITLE
Sonarr/Radar - No results were returned from your indexer, please check your settings

### ISSUE THREAD

**Issue by samcro1967** [theotherp/nzbhydra2#160]
I have been unable to get either Sonarr or Radarr to successfully connect to nzbhydra.  I get "No results were returned from your indexer, please check your settings" when I test the connection.   I have looked at numerous posts on this and none of the solutions seem applicable to me.  Debug log is attached.

I am running version 0.2.231,  I am able to search via https://192.168.1.103:5075/nzbhydra/.  I have blanked out Config | Searching | Generate Queries.  I am only using the default indexers that are in nzbhydra.  I have enabled them for internal and API searches.

Hopefully I have tried everything and provided enough information.  Running out of ideas.

![image](https://user-images.githubusercontent.com/2319445/39267579-d7c62cca-4892-11e8-91dd-28f0ba26fb03.png)

[nzbhydra.log](https://github.com/theotherp/nzbhydra2/files/1948478/nzbhydra.log)

**Comment by theotherp** [comment]
Please attach the debug infos zip as described in the issue template.

**Comment by samcro1967** [comment]
Missed that there was a way to get a downloaded zip of the logs and settings.  I think this is what you are looking for.  Sorry about that.

[debuginfo.zip](https://github.com/theotherp/nzbhydra2/files/1948672/debuginfo.zip)

**Comment by theotherp** [comment]
You're running python based v1. This is for NZBHydra 2. Please use https://github.com/theotherp/nzbhydra/issues in the future or just switch to v2.

Anyway, you only have raw search engines configured, no "proper" indexers. Sonarr and radarr search by proving IMDB or TVDB IDs which isn't supported by your indexers.

1. Get a proper indexer. I'm not sure which indexers are open for registration, perhaps NZBGeek. You can search on https://www.reddit.com/r/usenet for information on that.
2. In the NZBHydra searching config enable "Generate queries" for API searches. This will solve your problem somewhat but don't expect proper results. Usenet, especially automation, without proper indexers will not get you what you want.
