### ISSUE TITLE
Feature Req: Removal of API key from logs

### ISSUE THREAD

**Issue by biship** [theotherp/nzbhydra2#162]
When creating debug logs:
In the nzbhydra-config.yaml, for indexers that fail and report a **lastError**, the apikey is visible.
The debug json file also has the apikey visible.
Any change you can parse these out?

**Comment by theotherp** [comment]
The json logfile is meant to contain the apikeys because it's not included in the debug infos and you can copy the URLs from it to test stuff. I'll remove the apikey from the lastError column.
