### ISSUE TITLE
Sonarr + Anime + Hydra2

### ISSUE THREAD

**Issue by saitoh183** [theotherp/nzbhydra2#165]
For the past few weeks i have had a issue that Anime was not being auto downloaded. When i would do a manual or Automatic search The anime would be found. After discussing with Sonarr dev markus101 i was able to correct the issue with a workaround. 

In Sonarr:
I had 2 indexers one for Newsnab in hydra and one for Tornznab in hydra. 
Torznnab was setup with categories 5030,5040 and under anime 5070
When RSS scan is executed it generates `|Debug|Torznab|Downloading Feed https://domain.com/nzbhydra/torznab/api?t=tvsearch&cat=5030,5040,5070&extended=1&apikey=(removed)&offset=0&limit=100`

The result in Hydra: 
![image](https://user-images.githubusercontent.com/1534197/39592963-7d11c056-4ed6-11e8-8eff-6d220246546c.png)
![image](https://user-images.githubusercontent.com/1534197/39593019-9fb00492-4ed6-11e8-883e-14fce68e985c.png)

As you can see no Anime indexers

In Sonarr, when i execute a **Automatic Search**(on episode/season/Show level), the query sent is like this
`|Debug|Torznab|Downloading Feed https://domain.com/nzbhydra/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Last%20Hope+05`

The result in Hydra:
![image](https://user-images.githubusercontent.com/1534197/39593253-4324467e-4ed7-11e8-93ae-73831ba1774b.png)
![image](https://user-images.githubusercontent.com/1534197/39593288-56b16988-4ed7-11e8-8347-10cd00020d0f.png)

The Workaround i had to do is create a 3rd indexer in Sonarr with only the anime category populated with 5070. Once this was done the RSS scan of Sonarr made Hydra pick up anime.

![image](https://user-images.githubusercontent.com/1534197/39593396-9ec778fc-4ed7-11e8-8e20-3e150a18f145.png)

From what markus101 says, it seems to be a problem with Hydra not parsing right.

> give me results for x, y and z and it returns results for x and y and drops z

Here are the logs (let me know if i should enable search options and regenerate log)
[nzbhydra-debuginfos-2018-05-03-13-42.zip](https://github.com/theotherp/nzbhydra2/files/1972034/nzbhydra-debuginfos-2018-05-03-13-42.zip)

So the question is who is at fault and is creating a 3rd indexer to target only anime the only solution?

**Comment by theotherp** [comment]
This is caused by how Hydra tries to find out which category matches the request. The search is done with 5030,5040,5070. 5040 matches TV HD, 5070 matches Anime. Because it can't know which one is the right it tries to find a more generic one which is TV (5000).

I can't think of a better workaround than the one you mention.
