### ISSUE TITLE
Some indexers are not reachable with multiple network interfaces on windows.

### ISSUE THREAD

**Issue by caleb90** [theotherp/nzbhydra2#166]
I am running nzbhydra2 on window server 2016. I have four network interfaces that are active. Two of them are connected to the internet, and the other two are lan only and have no internet access. When I search for something with all four network interfaces active, some of the indexers work, and others don't. If I disable the two lan only network interfaces it doesn't have any issues with the indexers.  Log file is attached 
[nzbhydra-debuginfos-2018-05-04-04-38.zip](https://github.com/theotherp/nzbhydra2/files/1973717/nzbhydra-debuginfos-2018-05-04-04-38.zip)

**Comment by theotherp** [comment]
Huh... I'll do some research but I won't be able to reproduce this. Let's see what I can find.

**Comment by YipYup** [comment]
@caleb90 Post the configs for each of your NICs: IP, Subnet Mask, Gateway, and which bonding/balancing methods are employed (if any).

ie, Are any using LACP, EtherChannel? Are you doing any type of NIC teaming?

**Comment by theotherp** [comment]
I only understand half of what @YipYup asked so I'll leave this to you guys for now ;-)

I googled a bit and didn't find anything about this being a general Java issue. Not sure what I can do.

**Comment by YipYup** [comment]
@caleb90 can you post the DNS configs for all the NICS?

Also, can you post a copy of your route table? I'm not sure if these instructions still apply to Windows 10 as I don't have a Win 10 box in front of me... but try them anyways :) https://unh.edu/it/kb/article/how-to-route-print-windows.html

**Comment by caleb90** [comment]
After finally having some time to mess with it this weekend, I changed the metric priority of one of the interfaces connected to the internet to be higher than those not connected, and it seemed to fix it it.

**Comment by theotherp** [comment]
Thanks for the feedback.
