### ISSUE TITLE
Improper HTTP response to a getnzb request

### ISSUE THREAD

**Issue by enilfodne** [theotherp/nzbhydra2#170]
I've noticed that when proxying `NZB` to `SABnzbd`, every request fails. After a bit of debugging, found the following:

In response to `/getnzb/api/<uid>`:

this is the header:
```http
HTTP/1.1 200
```

(just for reference) v1:
```http
HTTP/1.1 200 OK
```

and `SABnzbd` in turn, marks the result as a failure.

**Comment by theotherp** [comment]
"200" means "OK". I've tested sending links to NZBs to sabnzbd and it works fine. Whatever your problem is, this is not it.

**Comment by enilfodne** [comment]
Sorry, if i mixed-up the terminology. By proxying i meant the process, where `NZBHydra` returns the `NZB` to `SABnzbd`, instead of redirecting it to the indexer in question.

[This](https://github.com/sabnzbd/sabnzbd/blob/master/sabnzbd/urlgrabber.py#L364) is where `SABnzbd` fails.

There are no errors being thrown by `NZBHydra`. As far as its concerned, its all good. `tcpdump` confirms that the response is there and its a valid `nzb` file. These are the only lines in the log after searching:

```logtalk
INFO --- [0.1-5076-exec-3] org.nzbhydra.downloading.FileHandler     : [Search: 653353, IP: X.X.X.X] NZB download request for "<name>" from indexer <indexer>
INFO --- [0.1-5076-exec-3] org.nzbhydra.downloading.FileHandler     : [Search: 653353, IP: X.X.X.X] NZB download from indexer successfully completed in 2158ms
```

**Comment by theotherp** [comment]
I tested this an hour ago and it works fine for me. What does the sabnzbd log say? Enable debug logging and try again.

https://github.com/sabnzbd/sabnzbd/blob/master/sabnzbd/urlgrabber.py#L353 is only reached when the status code is != 200 or the input of that function is empty. No idea why sabnzbd behaves differently. Perhaps @sahifire has an idea.
