### ISSUE TITLE
Searching with age filters on Binsearch creates apparent loop

### ISSUE THREAD

**Issue by mattswest** [theotherp/nzbhydra2#174]
Pretty self-explanatory. The search(es) will go on forever until I restart NZBHydra; hitting cancel makes no difference.

https://imgur.com/a/QAM66Ok

It seems like the age filter isn't being added to the Binsearch request URL.

`https://www.binsearch.info/?adv_col=on&postdate=date&adv_sort=date&max=100&q=family%20guy`

...instead of:

`https://www.binsearch.info/?adv_col=on&postdate=date&adv_sort=date&max=100&q=family%20guy&adv_age=30`

Also, it doesn't seem to be going through all the pages, but instead gets stuck on the second page (`&min=100&max=100`).

Without any max age set, the search finishes in short order.

**Comment by mattswest** [comment]
Happening again under different circumstances; I don't think the endless looping is due to the age filters.

This time the search was through Sonarr instead of the web interface.

https://imgur.com/a/PdnTKD5

Seems to be stuck on the third page on this one.

**Comment by mattswest** [comment]
Also, here is the line in the log from Sonarr where the request timed out.

`NZBHydra server is currently unavailable. http://192.168.86.190:5076/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=100&limit=100&q=Supernatural&season=13&ep=23 The request timed out: 'http://192.168.86.190:5076/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=100&limit=100&q=Supernatural&season=13&ep=23'`

**Comment by theotherp** [comment]
I don't use the age filter parameter because it's hard or impossible to properly convert the user input (e.g. 75 days) to the format that binsearch requires.

I improved the code a bit but your scenario will still fail. That's a part of the code that's the most complicated and I think I'll never get it completely right... I won't be able to properly fix this for now.

**Comment by theotherp** [comment]
Seems to be fixed :-)
