### ISSUE TITLE
Cannot complete Capabilities Check for DogNzb - Cannot cast to CapsRoot

### ISSUE THREAD

**Issue by AnnieTheEagle** [theotherp/nzbhydra2#177]
## Logs File
[nzbhydra-debuginfos-2018-05-15-15-49.zip](https://github.com/theotherp/nzbhydra2/files/2005534/nzbhydra-debuginfos-2018-05-15-15-49.zip)

## Reproduction Steps
1. Create new indexer by selecting "DogNZB" from the list
2. Paste in your API key, and set priority (for me, I set this value to 100).
3. It will try to check caps (the results seem random? Sometimes it says it supports TVRAGE, sometimes it doesn't).
4. Caps check will fail and cannot be used.

**Comment by AnnieTheEagle** [comment]
Update, it may be caused by their API. It seems a couple people on their forums are complaining about issues.

**Comment by theotherp** [comment]
Does this still occur?

**Comment by alexdelifer** [comment]
@theotherp 
I just got a DogNZB account and I seem to be getting this...
```
An error occurred:
500: Internal Server Error

Path: /internalapi/indexer/checkCaps

Message: org.nzbhydra.mapping.newznab.xml.NewznabXmlRoot cannot be cast to org.nzbhydra.mapping.newznab.xml.caps.CapsXmlRoot
```
[nzbhydra-debuginfos-2019-01-03-11-21.zip](https://github.com/theotherp/nzbhydra2/files/2724511/nzbhydra-debuginfos-2019-01-03-11-21.zip)

**Comment by theotherp** [comment]
I'll improve the error message but it basically means that dog responded differently than expected.
