### ISSUE TITLE
Torrents Not Saving in Black Hole Folder

### ISSUE THREAD

**Issue by BzowK** [theotherp/nzbhydra2#178]
Hey Guys - 

This morning I migrated from running NZBHydra to NZBHydra2 plus am running it within a Docker container.  When setting everything up, I realized that I could not only search usenet indexers, but torrent ones as well via Jackett so I got to configuring and now have about a dozen indexers total - all of which seem to return search results well!

The issue is that the search result option to "save torrent to black hole" works for only 3 of the 10  torrent indexers which I added via Jackett.  I'm assuming that it's due to these sites only offering magnet links, but since I don't run my torrent client locally; I can't use the other options for download so am stuck.

Is there something that could be done in the app or on my side to get 100% of them to save to black hole or honestly any other way of easily adding a result to download directly from the results?  To note, I most commonly use the Chrome extension "[Remote Torrent Adder](https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci?hl=en)" when browsing indexers which works great, but it doesn't work with the NZBHydra2 results unfortauntely.  If the issue is due to the sites only offering magnets, is there a magnet -> torrent converter which could be integrated into the app perhaps?

Just wanted to post to see what options I had if any or if there were any plans for additional development of this feature.  Below are log entries that appear when it fails to add a result to black hole folder.  I also performed a log grab which [may be downloaded here](https://kelnetcloud.com/owncloud/index.php/s/yXni6OZttYEkDll).

Thanks!!

**Log Events When Adding to Black Hole Fails**
Below are log results when trying to add randomly searched for results to the black hole folder.  Eac his from a different Jackett indexer - all of which are communicating successfully

> Unable to add magnet link for The Blacklist - Season 5 (Complete) - Mp4 x264 AC3 720p: Could not open Uri scheme handler for magnet:?xt=urn:btih:0c2ddfc5523a0637826e46aa7d4d3a438a39c06e&dn=The+Blacklist+-+Season+5+%28Complete%29+-+Mp4+x264+AC3+720p&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.opentrackr.org:1337&tr=udp://tracker.pirateparty.gr:6969&tr=udp://eddie4.nl:6969

> Unable to add magnet link for Star Wars 043 (2018) (digital) (Minutemen-Midas).cbr: Could not open Uri scheme handler for magnet:?xt=urn:btih:d79bba77e659741b8c817b8e7e7565b78b1c775e&dn=Star%2BWars%2B043%2B%282018%29%2B%28digital%29%2B%28Minutemen-Midas%29.cbr.torrent

> Unable to add magnet link for Star.Wars.Rebels.S04E09.720p.WEB.x264-TBS: Could not open Uri scheme handler for magnet:?xt=urn:btih:3fe1b1731d66e17fe6c4126f593f955d222809f3&dn=Star.Wars.Rebels.S04E09.720p.WEB.x264-TBS&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969&tr=udp:%2F%2Fzer0day.ch:1337&tr=udp:%2F%2Fopen.demonii.com:1337&tr=udp:%2F%2Ftracker.coppersurfer.tk:6969&tr=udp:%2F%2Fexodus.desync.com:6969

Thanks again!

**Comment by theotherp** [comment]
Trackers with magnet links should show a button to add the link to the
registered app on the server. I'm not at home until Monday so I can't give
any details right now. To be honest I rarely use trackers with hydra so I
am not quite sure what works and what doesn't.

**Comment by theotherp** [comment]
Not without external tools or services which I don't want to rely on.

**Comment by fryfrog** [comment]
Sorry, I actually meant in general, not in nzbhydra2. I've never tried, but what happens if you just toss a magnet url into a `.torrent` file and then ingest that in a torrent client. Does it work?

**Comment by theotherp** [comment]
@wh0cares supplied a solution here: https://github.com/theotherp/nzbhydra2/pull/193

Magnet links can be saved as .magnet files. Works with my deluge.
