### ISSUE TITLE
Can't restart after upgrade to 1.05 - xmx error in YAML config

### ISSUE THREAD

**Issue by adx442** [theotherp/nzbhydra2#18]
Had it installed as a service in 1.00, upgrade to 1.05 failed.  Subsequent starts (I installed the fresh 1.05 copy manually, and added the data folder from the original install) fail with an error regarding xmx 256M value being incorrect.  If that xmx line is deleted from the YAML file, and NZBHydra2 is manually started from the command line as:  `nzbhydra2 --nobrowser --xmx 256M ` it runs correctly without issue.  I believe this may be a parsing issue from the original 1.00 file where I modified the xmx value from within the web GUI and saved it.   Running it through TMUX at the moment, as my service won't start it now.  

Ubuntu 16.04.3 x64 install.

**Comment by theotherp** [comment]
Fixed in 1.0.6
