### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by d0t1q** [theotherp/nzbhydra2#180]
https://github.com/theotherp/nzbhydra2/blame/2681f5e86219d40f5cc053dc5d7536b95a157f46/core/src/main/java/org/nzbhydra/config/MainConfig.java#L90

`result.getWarningMessages().add("You've maded changes that affect Hydra's URL and require a restart. Hydra will try to reload to the new URL when it's back.")`

Should be changed to 
`result.getWarningMessages().add("You've made changes that affect Hydra's URL and require a restart. Hydra will try to reload to the new URL when it's back.")`

**Comment by albino1** [comment]
Took me a second to spot it, but the proposed change it `maded` to `made`.

But the `to` after `reload` should probably be removed as well.  Here's a cleaner line:

`result.getWarningMessages().add("You've made changes that affect Hydra's URL that require a restart. Hydra will try and reload the new URL when it's back.")
