### ISSUE TITLE
Feature request: Make Add new indexer button clearer

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra2#187]
The "Add new indexer" button has two modes, click the main part and it opens up a blank template. But is it newznab or torznab? Does it matter?

Click the triangle and you get a nice big long list of pre-configured indexers, almost all usenet. It scrolls off screen in my browser because there are so many! :)

My suggestion here would be to add a blank newznab and a blank torznab, *if* that matters. If it *doesn't* matter, it would be nice to make that obvious in some way. I'm still thinking about how that might be possible. The blank entry might still even be the simplest, even if it doesn't matter.

I'd also suggest sub-grouping usenet and torrents, then making the sub menus have multiple columns so that a large number of indexers can be shown all at once on the screen in a grid.

![screen shot 2018-05-22 at 8 22 41 am](https://user-images.githubusercontent.com/87748/40372382-6809ab84-5d99-11e8-8265-0eda28819739.png)

**Comment by theotherp** [comment]
You don't see a difference but there is one.

The Jackett/Cardigann is the blank entry for torznab indexers, yes.

**Comment by fryfrog** [comment]
Actually, there kind of is an indicator. But I can't really tell if it is a warning, notification or indicator. Anyway, making it *explicit* that there is one would be great. I think the top of each should say if it is torznab, newznab or custom.

And a blank newznab and torznab entry in the triangle drop down would be great too.

![screen shot 2018-05-22 at 9 04 23 am](https://user-images.githubusercontent.com/87748/40374980-2e32f004-5d9f-11e8-8b72-003df1c63f10.png)

**Comment by fryfrog** [comment]
No rush, I'll probably keep piling on little usability requests as I help people get nzbhydra2 working and when I run into weird stuff. Low priority. :)

**Comment by theotherp** [comment]
Done.
