### ISSUE TITLE
Startup failure in nzbhydra2wrapper.py because readme.md missing in 1.4.15 linux zip

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra2#188]
The readme.md file was left out of the recent release.

The wrapper uses this file to determine if the base directory is correct.

:(

```
2018-05-22 09:36:07,616  CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /usr/lib/nzbhydra2
```

**Comment by theotherp** [comment]
https://github.com/theotherp/nzbhydra2/pull/186/files changed the name from readme.md to README.md and I didn't notice it :-/

**Comment by fryfrog** [comment]
Is the file going to change from readme.md to README.md? The wrapper probably needs to be updated too, if so.

**Comment by fryfrog** [comment]
Also, the changelog isn't UPPER... if you're going for consistency! ;)

**Comment by theotherp** [comment]
Not my day. I reverted the change. I didn't even see that the PR had changed the filename's case.

**Comment by danjames92** [comment]
Thanks for your quick work guys. Glad to know I wasn't losing it. 👍
