### ISSUE TITLE
Unable to handle API request - Both manually and via Sonarr

### ISSUE THREAD

**Issue by mrvaghani** [theotherp/nzbhydra2#197]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**
See attached zip file for logs for both Hydra and Sonarr

[nzbhydra-debuginfos-2018-06-09-17-27.zip]
[sonarr.trace-2018-06-09-17-27.txt](https://github.com/theotherp/nzbhydra2/files/2087357/sonarr.trace-2018-06-09-17-27.txt)

(https://github.com/theotherp/nzbhydra2/files/2087355/nzbhydra-debuginfos-2018-06-09-17-27.zip)
* What do you expect to happen? What does happen? 
  * I expect Hydra2 to respond to the REST call made by Sonarr. Instead, I get an error that it was unable to handle the request

* Can the problem be reproduced? How?
  * I made a backup and restored it to a different install on different VM and it still keeps happening. Not sure how others can reproduce it without the backups

NOTE: This is running on Ubuntu 16.04 host inside Docker container. Both Sonarr and Hydra2 are inside containers on the same host within same docker network. This was working at some point and one day it just stopped working. I am not really sure what it was that I changed that caused it.

Please let me know if there is anything else I can test or provide to make this troubleshooting easier.

Thanks!

**Comment by theotherp** [comment]
You configured a hit limit of "0" for your indexer "nzbplanet" which doesn't make sense. Please remove that from the config. I'll add a check that prevents this from happening.

**Comment by mrvaghani** [comment]
I see. When setting this up, I wasn't thinking and was just copying what the indexers had written on their page. So what happened was that I do not have premium for this specific indexer and thus my limits as regular users are:

* Daily DL : 0 of 5
* Daily API : 0 of 0

Without thinking what it actually means, I just wrote down 0 for the API limit. Now that I think about it, this means I cannot make API calls to this indexer rather go on there manually and download 5 times. Since I do not have the ability to make any API calls to this indexer, I just manualyl disabled it and it fixed the issue I was having.

Appreciate the prompt resolution! :+1:
