### ISSUE TITLE
"Add new downloader" button does not open

### ISSUE THREAD

**Issue by brickstool** [theotherp/nzbhydra2#198]
**What do you expect to happen? What does happen?** 

Trying to click on the "Add new downloader" button and expecting a window with options to add a downloader, however getting no response from the button once it is clicked with the only thing popping out beneath it being a small dark gray box.

** Have you searched for this problem? You don't have to answer, just make sure.**

Yes, no results from what I could see.

**Can the problem be reproduced? How?**

Yes, at least on my end. I have restarted the docker container several times, turned off adblock/scripts etc in my browser (firefox 60.0.2). It is the only thing currently happening when I click the add downloader button.

Attached is my debug information and a screenshot of the button after it has been activated. Thanks.

![screenshot from 2018-06-11 22-09-22](https://user-images.githubusercontent.com/4110173/41230707-2c3ece32-6dc4-11e8-9797-02a27a9dd01c.png)

[nzbhydra-debuginfos-2018-06-11-21-59.zip](https://github.com/theotherp/nzbhydra2/files/2089839/nzbhydra-debuginfos-2018-06-11-21-59.zip)

**Comment by theotherp** [comment]
I expected my last changes to break something but not expected it to be something this basic...
