### ISSUE TITLE
An Error Occurred: Undefined: Undefined | Message: Undefined

### ISSUE THREAD

**Issue by DrSeussFreak** [theotherp/nzbhydra2#200]
I am running Ubuntu 18.04 and every day NZBHydra2 stops working, and I get the error listed above. I cannot run the export from the bugreport section, as I get the same error message there, so I copied the logs, and ran the export after I restarted the app.

No action I can take makes this happen, it is simply a matter of time, and things stop working.  I usually find out by logging into Sonarr or Radarr, and I will see that the indexer is offline.

Any help determining how to stop this would be appreciated.

`NZBHydra2 version = Current version: 1.5.1 `

> root@indexer-01:/opt/nzbhydra2# java -version
> openjdk version "1.8.0_171"
> OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
> OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

[logs.zip](https://github.com/theotherp/nzbhydra2/files/2117788/logs.zip)
[nzbhydra-debuginfos-2018-06-19-22-53.zip](https://github.com/theotherp/nzbhydra2/files/2117795/nzbhydra-debuginfos-2018-06-19-22-53.zip)

**Comment by theotherp** [comment]
Increase the XMX value in the config and restart. Try 256 or 512.

**Comment by DrSeussFreak** [comment]
Change has been made, I will close this in a day or two, assuming the issue is resolved.  Thanks!

**Comment by DrSeussFreak** [comment]
Issue seems resolved since the memory change, thanks!
