### ISSUE TITLE
[Bug] Unable to update relative path in torrent "blackhole" directory.

### ISSUE THREAD

**Issue by tnebrs** [theotherp/nzbhydra2#201]
Only a front-end issue, so I'll simply paste the JSON response when trying to save.

Previously I was able to set the black hole directory to one relative to ~, however Hydra did not understand this correctly (parsing it literally as a relative directory) and subsequently prevented me from saving any configuration via the UI with a modal on hitting the "Save" button at the top-right of the config, including when trying to update this field. Attempting to bypass this by hitting carriage return on the field with a new value results in the following response. 

`{"data":"","status":406,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","headers":{"NzbHydra2-Handle-Errors-Generically":true,"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"ed8c5743-491c-489a-8534-3e20b864bd61"},"url":"internalapi/help/Downloading","cached":false},"statusText":"","xhrStatus":"complete"}
`
Let me know if you need any additional logs,

Thanks,
tnebrs

**Comment by tnebrs** [comment]
Some helpful logs with a stack trace.

'Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]: 2018-06-22 19:38:23.401 ERROR --- [0.0-5076-exec-4] o.a.c.c.C.[.[.[.[dispatcherServlet]      : [IP: 77.99.75.220] Servlet.service() for servlet [dispatcherServlet] in context with path [/nzbhydra2] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: resource /help/downloading.md relative to org.nzbhydra.web.HelpWeb not found.] with root cause
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]: java.lang.IllegalArgumentException: resource /help/downloading.md relative to org.nzbhydra.web.HelpWeb not found.
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at com.google.common.io.Resources.getResource(Resources.java:209)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.nzbhydra.web.HelpWeb.askForAdmin(HelpWeb.java:19)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.nzbhydra.web.HelpWeb$$FastClassBySpringCGLIB$$e6d2be01.invoke(<generated>)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.nzbhydra.web.HelpWeb$$EnhancerBySpringCGLIB$$ea695e3.askForAdmin(<generated>)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at java.lang.reflect.Method.invoke(Method.java:498)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]: 2018-06-22 19:38:23.676  WARN --- [0.0-5076-exec-4] org.nzbhydra.web.ErrorHandler            : [IP: 77.99.75.220] Unexpected error when client tried to access path /nzbhydra2/error. Error message: Could not find acceptable representation
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]: 2018-06-22 19:38:23.786  WARN --- [0.0-5076-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : [IP: 77.99.75.220] Failed to invoke @ExceptionHandler method: public org.springframework.http.ResponseEntity<java.lang.Object> org.nzbhydra.web.ErrorHandler.handleConflict(java.lang.Exception,javax.servlet.http.HttpServletRequest)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:259)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:203)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:113)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:384)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:59)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:136)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:74)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1222)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1034)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
Jun 22 19:38:23 [HOST REDCATED] nzbhydra2[23780]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
'
'

**Comment by theotherp** [comment]
While I understand that using a relative directory would be nice is there any reason why you can't just set an absolute one?
