### ISSUE TITLE
How to move directory? 

### ISSUE THREAD

**Issue by imadunatic** [theotherp/nzbhydra2#203]
So like an idiot I initially ran the .exe from my download folder and migrated... realizing my folly, I moved it to where I actually wanted the directory to live (G:Program Files) and now it won't run from that location. If I run it from my download folder all is well. I'm assuming there is a config file somewhere being written. Any ideas?

**Comment by theotherp** [comment]
Extract the zip anywhere (that's not in a folder called (program files,
that will be fixed at some point) and move the data folder which was
generated in the downloads folder to the folder where you extracted the zip
(so that on the same level as the exe you have the data folder).
