### ISSUE TITLE
Trouble Upgrading Docker Container

### ISSUE THREAD

**Issue by BzowK** [theotherp/nzbhydra2#204]
Hey Guys - 

I'm running 1.4.18 of the container and see that 1.5.1 is the latest available.  I cannot find out how to upgrade the container instead of just the app, itself; short of backing up my settings to a file, wiping the container, rebuilding it from scratch, and restoring the settings.

Forgive me as I'm fairly new to Docker, but any assistance would be fantastic!  I've already downloaded the latest image and use Portainer as well as the obvious SSH connection to my Docker host which is Project Atomic (Fedora 28) within an ESX 6.7 VM.

Thanks!

**Comment by theotherp** [comment]
Which container do you use? The official one?

I think I forgot to update the container. I'll try to push the latest
version tomorrow.

**Comment by theotherp** [comment]
The latest container here https://hub.docker.com/r/theotherp/nzbhydra2/tags/ is 1.5.1

I don't use docker myself, sorry. Anybody else that can help?

**Comment by whispy** [comment]
@BzowK, were you able to figure it out, or do you still need help?
