### ISSUE TITLE
404 when using a domain name

### ISSUE THREAD

**Issue by paulrumens** [theotherp/nzbhydra2#207]
Hydra works great now (thanks for you help so far!). Also, when you said its faster now... my god, its a massive gain over V1 !

Great job.

But I can only get to it via an IP address, when I try and access Hydra via a domain, I get this

```
An error occured :
404: 

{
  "timestamp" : 1530308913035,
  "status" : 404,
  "error" : "Not Found",
  "message" : "No message available",
  "path" : "/static/html/states/header.html"
}
```

**Comment by paulrumens** [comment]
Ignore this, its working now for some reason!

**Comment by theotherp** [comment]
Great.
