### ISSUE TITLE
Feature Request: Seed Time and Ratio Overrides for Torznab Indexers

### ISSUE THREAD

**Issue by jd4883** [theotherp/nzbhydra2#208]
Greetings,

In the most recent Sonarr/Lidarr releases there is now a feature to preset a seed time, and a ratio per indexer. While it is neat to be able to do this directly to the Torznab container within Sonarr/Lidarr, can the feature-set be expanded to allow GUI options for this and maybe other Torznab/Uzenab parameters? It would be really cool to be able to configure this on a per-indexer basis within Hydra for greater customization and the ability to override settings for a PVR client.

Thank you again for releasing such a great successor to Hydra, I hope this post inspires some new features for PVR clients to have additional options configured within Hydra.

Kind regards,

Jacob

**Comment by theotherp** [comment]
Hey,

I'm not sure I understand. Do you want to reject results from torznab indexers which have a seed time or number of seeders below a certain value?

**Comment by jd4883** [comment]
Greetings,

I'm sorry if that was unclear. Essentially I want to be able to use the Torznab parameters now available in the GUI in Sonarr but be able to make overwrites on a per indexer basis in Hydra. An example would be say one tracker I want to seed for 24 hours and another for 48, Sonarr only lets me configure one of these values so I'd like to be able to overwrite this in Hydra if at all possible. Having more GUI options for Usenab/Torznab parameters would also make more of the options available to users without having to do as much trial and error with testing XML parameters. Thought it would be cool to see the features in Sonarr mirror and be adjustable on a per indexer basis in Hydra.

Please let me know if further clarification would help or if anything is unclear.

**Comment by theotherp** [comment]
Uhm, I think you're confusing something. You add NZBHydra to Sonarr as an indexer. You can configure Sonarr to seed torrents until a certain seed time or seed ratio is reached. That is controlled completely by Sonarr - Hydra only returns a search result once and then perhaps a torrent and that's it. There's no way for Hydra to affect when a torrent reaches the minimum seed time or ratio.

**Comment by jd4883** [comment]
Thank you for educating me here, I was not aware that what was sent up to Sonarr did not include these flags. You can close out this thread due to my ignorance on how the Sonarr/Hydra interaction works. Appreciate having the better understanding. Keep up the good work, Hydra is a really cool project!
