### ISSUE TITLE
Add support for the removal multiple trailing values of a single post

### ISSUE THREAD

**Issue by jant90** [theotherp/nzbhydra2#215]
Could you add support for the removal multiple trailing values of a single post?

Currently NZBHydra 2 only removes the last trailing value if it matches a value from the "Remove trailing..." setting. However sometimes posts have multiple trailing values and then only the last one is removed.

To clarify, an (unrepresentative) example where "repost" and "English" are specified as "Remove trailing..." values (NZBHydra 2 default).

Found post name:
"Release.Name.2018.1080p.BluRay.x264-GRP English repost"
Would become:
"Release.Name.2018.1080p.BluRay.x264-GRP English"
Whereas the desired outcome would be:
"Release.Name.2018.1080p.BluRay.x264-GRP"

Thanks! :)

**Comment by theotherp** [comment]
Fixed in next version.
