### ISSUE TITLE
Unable to use authorization

### ISSUE THREAD

**Issue by Tiwas** [theotherp/nzbhydra2#218]
Not sure what info you need here. I set authentication, check the username and password, save, unable to login (wrong username/password). I've tried both "login form" at "basic auth".

Is this a known problem?

System is Windows 10 x64. Worked fine with v1.

**Comment by theotherp** [comment]
Please post the debug infos ZIP as described in the issue template.

**Comment by Tiwas** [comment]
These are the settings from v1 that's worked fine for me in the past
![v1](https://user-images.githubusercontent.com/17053402/42780243-f4858cc0-8942-11e8-9f6a-09a6d02f86cd.PNG)

These are the settings I'm trying to set in v2 with no luck
![v2](https://user-images.githubusercontent.com/17053402/42780248-f6f7b7d0-8942-11e8-9342-470ca7d88408.PNG)

I'm accessing it from an internal IP on my LAN. I've also tried from the same computer it's running from, but no luck.

**Comment by theotherp** [comment]
Please try to log in, shut down hydra, open the nzbhydra.yml file in the
data folder, set the setting Auth type to NONE, save, start hydra and
create the debug infos zip and post it. In the meantime I'll try if I can
reproduce the issue.

**Comment by Tiwas** [comment]
[nzbhydra-debuginfos-2018-07-17-08-55.zip](https://github.com/theotherp/nzbhydra2/files/2200505/nzbhydra-debuginfos-2018-07-17-08-55.zip)
Hope these will do. Set it to use login form, saved, double checked the password using the "show password" button, tried to log in from another computer, which failed, set it back to none and saved. Much easier than editing files, but please tell me if that doesn't work for the logs for some reason and I'll do it again.

**Comment by theotherp** [comment]
I don't see anything in the logs that indicates a failed auth attempt. Have you verified that the yml file contains the username and password you entered in the GUI? Do username or password contain any special characters? I'm kinda fishing here, to be honest.

**Comment by robertbaker** [comment]
Seems like this doesn't work with a password like BA3X#lj6p#my#&XMU9v3  (randomly generated)

@theotherp
