### ISSUE TITLE
Migration suggestions

### ISSUE THREAD

**Issue by CyberMew** [theotherp/nzbhydra2#222]
- When setting up the migration and manually entering the file paths, it should be populated by default, so user knows correctly, e.g. /enter/path/to/your/config.cfg and /enter/path/to/your/nzbdatabase.db
I initially pointed to the folder that both files were in and a popup told me about some db error when both files or rather path are incorrect.

- When migration is happening, the Start Migration button should be disabled (grey color).

- Also, when error is encountered, e.g. out of memory error, instead of clearing existing status and show a blank screen and with the text "java heap space" in the migration box AND a spinner right below that line, it should have just shown the full error _without_ the spinner, or at least some message saying "migration cancelled, no data was imported. please check logs.". That would be much more helpful. I thought it was just a display bug (was wondering to myself why is 'java heap space' showing up?) and the migration was still happening and I waited 20 hours before cancelling it (I kid). I also thought that the migration was half-done and I had to delete and reinstall the whole image.

- When migration was done, it prompted that changes will be done after a restart, which I clicked on (I'm on docker) and nothing happened, except that the window closed. Went to the main page and viola it appears. Nothing in the logs as well. I'm still not sure if I have to restart the container till this day. It should either say "pending restart or changes will not appear" across the whole website or maybe a restart might not have been required after all? Even if it was required, maybe it could tell us to manually restart the docker container instead?

Just my observations and how to make it better. Been using this for a couple years and I really appreciate it!

**Comment by theotherp** [comment]
1. Easy to do
2. Easy to do
3. Impossible as an "out of memory exception" means that the process went completely whack. There's no way to catch that error and display it.
4. Will verify this.
