### ISSUE TITLE
[REQ] Set proxy per indexer

### ISSUE THREAD

**Issue by h45rd** [theotherp/nzbhydra2#227]
Hi,

Any chance you could implement an option to set proxy usage on a per indexer basis?
I.e. a checkbox on each indexer configuration page _"use proxy"_ and a main configuration toggle _"use proxy selectively"_.
An alternative could be to allow switching between whitelisting (only use proxy for these domains) and blacklisting (do not use proxy for these domains) proxy usage on the main configuration page.

Background: one might need a proxy to reach a certain indexer (e.g. due to censorship), but one might not want to slow down all other requests by using a proxy globally.
Right now one could achieve similar results to the proposition above by blacklisting everything but the indexer one wants to be accessed via proxy, but this is a lot more cumbersome.

Thanks for a great app and keep up the good work!
h45rd

**Comment by theotherp** [comment]
No. Would be a pain to test and develop, make the configuration hard(er) to understand and seems to be a fringe case. Sorry.

**Comment by h45rd** [comment]
Understood. Thanks for the consideration and clear response.
