### ISSUE TITLE
Slowdown over time

### ISSUE THREAD

**Issue by nate1280** [theotherp/nzbhydra2#228]
I've had a NzbHydra2 instance running (in docker, the linuxserver one) since June 4th, and just recently, its been slowing down on searches and UI access.

I noticed the database file was 2.6gb (its a heavily used instance).  As a test, I stopped the container, renamed the database, restarted, and everything was fast again.

I opened the H2 database, and it seems all the relevant tables have data going back to June 4th, so the IndexerApiAccess table has 1.6m rows, IndexerSearch has 1.5m, SearchResults has 0.5m.  Are the cleanup tasks not behaving as desired, or am I just misreading the code behind them.

I'm not sure what other information I can provide, there's nothing that stands out in the log files, and I usually have just error related logs otherwise they grow quite large.

I primarily work with C#, but I'd gladly help in anyway if you'd like.

**Comment by lyfesaver** [comment]
I have experienced this as well

**Comment by theotherp** [comment]
The database will be compacted and defragged which should improve performance. The entries in the database are used for stats calculation. 500k searches is kind of a lot...

**Comment by samwiseg00** [comment]
My database is 4.2G... I too notice the slow down. I think its mostly when using the front end. The API does not to be affected as much

**Comment by lyfesaver** [comment]
How often does/will that compacting and defragging happen? What will be the triggers?

**Comment by nate1280** [comment]
Just an updated, since deleting the DB, 3.5 days ago.  Its currently sitting at 835MB with a combined row count of 1.27m

The largest table is SEARCHRESULT with 964,662, INDEXERAPIACCESS and INDEXERSEARCH are sitting at around 100k each.  SEARCH table has 6635 rows.

**Comment by theotherp** [comment]
Yeah, that's big... My database is 450 MB after two years....

**Comment by lyfesaver** [comment]
How often does/will that compacting and defragging happen? What will be the triggers?

**Comment by theotherp** [comment]
Not sure yet. The one approach is to use a different version of the
database but that will require a migration and may have some side effects.
The other works but requires a shut down of the database. I don't think an
automated restart is a viable solution.

**Comment by theotherp** [comment]
Still happening?

**Comment by nate1280** [comment]
Restarting the container (so restarting hydra) doesn't cause the DB to shrink any, and setting 1 week of stats retention didn't seem to have any effect.

So, unfortunately still have massive file growth (1gb+ after 2-3d), but that's likely down to how many indexers are in use (~20, not my choice).  I wound up creating a cron script to just auto nuke the DB when its > 1GB.  This for me atm is keeping it fast, its just to bad I have to lose the DB to do it.

The times I do check the DB before it gets nuked, the records are still in the millions.  Have a feeling H2 just doesn't play well with an excessive number of rows?

I did sort of manage to get the project open in IntelliJ (still not totally sure I'm doing that right), and I was able to get it work, I think.

On another note, would it be possible to add SickGear as a parsed UserAgent, since that shows up as Other.

**Comment by theotherp** [comment]
When you restart the container does hydra log that it's shutting down? Or does restarting the container just kill the process? Would be easiest if you just post the debug infos ZIP. Hydra needs to shut down to compact the database.

There's actually a bug in the "new" db format used by H2 which causes this behavior. The amount of rows is nowhere near the limit of which H2 can manage (theoretically).

You can just add SickBeard to the "Map user agents" setting in the searching config.

**Comment by nate1280** [comment]
I'd have to check, I have a feeling it may just kill it, I'm using the linuxserver.io container.

I'll see if I can get some debug logs (they grow out of control when I enable that level of logging).

Wow, no clue how I missed that setting for the user agents, my bad.

**Comment by John-Gee** [comment]
Hello,

Is there any update on this?
I have 2.5Gb of dbs and the same for logs at this point, which seems excessive.
Changing 'Store results for ...'  and 'Keep history for...' didn't have an effect after shutdown done from the UI so I guess clean. The log states that it was shutting down.

Thanks

**Comment by theotherp** [comment]
I'm waiting for a new version of the database library to be released. As I cannot reproduce this issue on my machine I have now of properly testing it. When I import a user's big database file into my instance and shut down Hydra it's compressed (e.g. from 750MB down to 175MB).

You can try this: 

1.  Shut down your Hydra instance and make a backup of your database file
2. Start Hydra and go to http://127.0.0.1:5076/system/bugreport (or whatever your host and IP is, obviously)
3. In the upper text area enter `shutdown defrag` and press "Execute"
4. Wait. Hydra will at some point throw an error that the database is already closed. Any search executed during this time may fail. When the error was displayed you need to restart Hydra again. Check the database file size.

**Comment by John-Gee** [comment]
I got this error right away:

An error occurred:
500: Internal Server Error

Path: /internalapi/debuginfos/executesqlupdate

Message: Unable to commit against JDBC Connection; nested exception is org.hibernate.TransactionException: Unable to commit against JDBC Connection



I'm using the Arch Linux AUR package if it matters.
I just reinstalled in case, but no difference.

**Comment by theotherp** [comment]
Please post your debug infos.

**Comment by John-Gee** [comment]
When I click on the "log and settings" button I get

An error occurred:
undefined: undefined

Message: undefined

So I just cleared my logs folder, restarted nzbhydra2, tried again, stopped it and grabbed the logs folder.
Here they are: https://mega.nz/#!ZhYjGIqT!nurgpr1TtYuciaoQmF4dyXPLKhOXM4qEl2ufcjJ8klg

I hope that gives you enough.

**Comment by theotherp** [comment]
The error message you posted above is the one I talked about. Try executing the command while no search is active.

The error with creating the debug infos is a new one, I'll check it out. Thanks for the logs.

**Comment by John-Gee** [comment]
Thank you for caring about privacy!
Though removing the links does not really do much since they are still in the history, unless only I can see them? I've invalidated them on mega either way.

I'm not running anything manual and I've taken down any service that might call nzbhydra2, but I don't see a difference so I guess I'm missing something. What do you mean by no search is active?

**Comment by theotherp** [comment]
The history is only visible to you and perhaps me. Users watching this thread will have gotten a notification with the old entry. But yes, invalidating the link is the right way to go.

I mean that Hydra was called by an external tool (I guess sonarr or such) while the command was executing. That might produce some problems. 

It's also possible that the command already was executed properly and just didn't help.

I'm currently at work. When I home I'll send you some short(ish) instructions how to execute that command against the database without NZBHydra being active. That way we can make sure the command is executed properly. If the database is still large afterwards there's noting I can do at the moment.

**Comment by theotherp** [comment]
Ohhh.......! That's just logging.

Just post the first and last 50 lines or so and then you can delete that file.

**Comment by John-Gee** [comment]
Ooooooooh.
So my issue may be different than the others here after all.
Sorry about that!

Though I didn't look at the files themselves before running the shutdown defrag command.

How do I make nzbhydra2 clean that up regularly?
(Same with the logs folder too, I never read the logs, so I definitely don't need logs from last summer...)

https://gist.github.com/John-Gee/4e6857dfad40d0555f5fb2f398950918

**Comment by theotherp** [comment]
The logs should be cleaned from every x days. I'll take a look at limiting the size of that file.

So, is your only problem the size of that file or do you think that Hydra has gotten slower? Perhaps the one is linked to the other. See if it is better with the file deleted.

**Comment by John-Gee** [comment]
Hydra is often one of the apps using the most RAM and CPU on my system from a quick look at htop. I think it used to feel a bit slow, but since then I've made Hydra auto restart itself every 2-3 days and it seems ok that way.

I stumbled on this bug because I've been looking at what is taking most space on my root partition and it was Hydra by far (about 5Gb total, about a third of the partition).

Thank you!

**Comment by theotherp** [comment]
Writing such a big trace file might explain why it's slow. Please just keep an eye on the file size and memory and process usage and report back in a couple of days.

For comparison, my hydra instance on a dedicated server with 700MB database uses about 200-300MB of memory.

You could also give this a try: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9 I was able to reduce memory usage by at least 30% using that.

**Comment by John-Gee** [comment]
So the database folder seems fine now.
After about a week the db file is about 27Mb and the trace one 31Mb, very reasonable.

The logs folder is still expanding more than expected, at 1.5Gb, most of it coming from the hprof files. Does that mean I should change the default 256Mb of allowed memory?

Thank you!

**Comment by John-Gee** [comment]
Well I switched to openj9 and so far no hprof so that looks good!
Maybe I'll try with more recent than jdk8 later and see if that's even better,
