### ISSUE TITLE
Feature request: Edit download path, Auto name truncation over 255 char in workflow

### ISSUE THREAD

**Issue by tastyratz** [theotherp/nzbhydra2#230]
Currently if an NZB is fed to nzbhydra2 it can be very long. Once extracted that can easily exceed 255 char. This will lock up the whole workflow with no way to resolve. You can't edit a pending download's path, you can't edit a name after it starts downloading, the only thing you can do is download it all over again and change the path.

It would be very helpful if existing downloads could have paths edited (such as when a drive is full) and if temp/extracted paths are detected to exceed 255 char then automatically truncate the created folder names. 
In the end, it really doesn't matter what things are called while being processed, only that the end result is named properly (or at least created with an error requiring you rename but saving the download).
The most frustrating part is losing the download in the workflow and starting over.

**Comment by CelagentT3** [comment]
I have seen the same issue.

**Comment by theotherp** [comment]
Sorry, I don't understand what you want.

**Comment by tastyratz** [comment]
As an example: I have Radarr/Sonarr feeding into nzbhydra2 an nzb.
nzbhydra2 is set to save to d:\downloads\complete and maybe has a temp dir of d:\downloads\incomplete\tmp.
Radarr sends an nzb to nzbhydra to download and process. Said download is 
reallylongname.nzb
nzbhydra creates a folder for the download d:\downloads\incomplete\reallylongname\reallylongname.rar
then once downloaded, it extracts to d:\downloads\incomplete\tmp\reallylongname\reallylongname\reallylongfilenameinsidetherar.mkv
Since the above path exceeds 255 char, it will fail. Since the path is static in the download and can't be moved or renamed, I can't fix it. The solution might be to make everything make a mess of the root path but that presents it's own issues. 
If NZBHydra2 could detect that it would likely exceed 255 char with the option enabled to truncate, it might in an attempt to avoid an error create it as
d:\downloads\incomplete\tmp\reallylo\reallylo\reallylongfilenameinsidetherar.mkv 
instead of
d:\downloads\incomplete\tmp\reallylongname\reallylongname\reallylongfilenameinsidetherar.mkv

in addition, if there is an issue with the destination/temp directory (such as path, or space) allowing the download in error to have the directories edited in flight and then re-processed may avoid a complete re-download or blacklisted download which doesn't have an actual error.

I hope I did a better job explaining my thoughts there.

**Comment by tastyratz** [comment]
Maybe it could be as simple as auto-truncate all created folders not within the download to x char as long as a duplicate does not exist?

it would need duplicate error handling in that respect though i.e. reallylo, then reallyl1, reallyl2, etc.

The challenge is entirely about the nzb's creating too much unnecessary folder depth through the workflow and failing without the capacity to automatically or manually intervene. The bonus of allowing them in addition to be manually edited and reprocessed would overcome space errors as well.
The challenge of not knowing what's in the download till you have it makes the x char default folder name limitations more viable.

To duplicate it, try making a 200char long nzb and importing it.
As silly as that sounds, you really do encounter unreasonably long nested naming (i.e. releasegroupmrfancyreleases.ripped.by.mr.ripper.fulllengthmoviename.1080p.mkv.aac.5.1.prerelease.webdl.subtitles.2018.nzb
)
The above example is 121 char long and would fail miserably in almost any path with current routine.

**Comment by theotherp** [comment]
You're talking to the wrong person. NZBHydra does not download anything. You mean https://github.com/nzbget

**Comment by tastyratz** [comment]
You are entirely right, clearly I wasn't paying enough attention this morning. Sorry to waste your time!
