### ISSUE TITLE
Category restriction is partially working

### ISSUE THREAD

**Issue by Seeveen** [theotherp/nzbhydra2#231]
If i apply restriction (in categories) for a release group is working but if i want to add more then 1, in Required words (that will be displayed in title) will end up with no results is more then 1 restriction is added, as peer Forbidden words is not working (is bypassing whatever words i add) , on Size preset still get result over the chosen size (i put a limit on a zise for Ex:900 MB and still get result for 1GB+), i am using Torrent index+Jackett+Sonarr+Radarr

**Comment by theotherp** [comment]
Post your debug infos zip

**Comment by theotherp** [comment]
As the description for the required words says "Only results with titles that contain *all* words will be used. Title is converted to lowercase before. Apply words with return key.". So it works as intended.

Regarding the size limits, if you mean API searches make sure to enable "Limit API results size" in the category settings.
