### ISSUE TITLE
Show std deviations in response time stats

### ISSUE THREAD

**Issue by toddcurry** [theotherp/nzbhydra2#234]
Enhancement request

When selecting timeout limits by indexer, it would be helpful to know not *just* the average response time, but what the distribution of response times looks like.  Enter the standard deviation...

If one is doing: 
    Select .... average(response) from log, group by indexer; 

Might I respectfully suggest you simply tag on:
    ... std_dev(response)

Because an indexer cannot respond in less than 0 seconds, the distributions are very likely to look lognormalish rather than normal.  That is OK.   For simplicity, just show the resulting sd in the table for now and don't bother trying to graph it...

...then if people (other than me) find the information useful, you may want to consider:
     - setting timeouts based on standard deviations
       e.g., timeout for indexer X = avg + 4 std deviations; for Y = avg + 3 std deviations.  That way a user  can set it at a likeliness-based threshold and when the results vary more, the limit goes up; when they vary less, the limit goes down.  
    - graphing distributions nicely

Thank you for considering this request!

**Comment by theotherp** [comment]
Interesting idea, but I don't think I will do this. I always tell people not to take these stats too seriously anyway. It would also be a lot of work for little payoff (in my opinion).

So, thanks for the request, but that's a no from me, sorry.
