### ISSUE TITLE
Unable to use AnimeTosho 

### ISSUE THREAD

**Issue by xinseo** [theotherp/nzbhydra2#235]
I'm unable to send NZBs to SABNZBD or NZBGET from NZBHydra2. When sending to NZBGET, this is what it shows in the NZBGET logs:

`Error parsing nzb-file *removed*.nzb: Reference to undefined entity 'raquo'.
`

**Comment by M0UL** [comment]
maybe it was fake release? that sometimes happens and they will get removed. i had one today on animetosho.

**Comment by xinseo** [comment]
I've tried like at least 20 so far. Files ranging from age: 1 hour ago to 1 year ago.

**Comment by xinseo** [comment]
Just tried adding it from Sonarr, and that seems to work fine. Only gives problems with NZBHydra2. This has started happening a few weeks ago. I haven't changed any settings.

**Comment by albino1** [comment]
Post your debug logs.

**Comment by xinseo** [comment]
Logs have been attached.
[nzbhydra-debuginfos-2018-09-05-10-39.zip](https://github.com/theotherp/nzbhydra2/files/2351398/nzbhydra-debuginfos-2018-09-05-10-39.zip)

**Comment by xinseo** [comment]
PS, this is what the logs in SAB show:
`2018-09-05 10:39:35,938::WARNING::[nzbstuff:795] Empty NZB file [Commie] Lupin the Third Part 5 - 22 [0901C9D4] [[Commie] Lupin the Third Part 5 - 22 [0901C9D4]]
`

**Comment by albino1** [comment]
Empty NZB file usually means 404 file not found, are you sure your API key is working?  Take the fetch line from your logs and try it in your browser.

**Comment by xinseo** [comment]
I don't have any API key entered. AnimeTosho doesn't require any. My settings on Sonarr for Animetosho match with Hydra. Sonarr is able to fetch and add the NZB files to both SAB and NZBGET perfectly fine.

**Comment by albino1** [comment]
I don't know then.  Guess you'll have to wait for @theotherp to go through your logs.

**Comment by theotherp** [comment]
I'll take a look later this today.

**Comment by theotherp** [comment]
It seems that animetosho changed their ourput format. Turns out I had a bug in the code that determined the URL from the feed. Should be fixed in next release.

**Comment by xinseo** [comment]
Sounds great! When is the next release expected?

**Comment by xinseo** [comment]
Just checked the latest update. Everything works fine now. Thanks again!
