### ISSUE TITLE
How do I add my own Certificate Authority to NZBHydra?

### ISSUE THREAD

**Issue by rfgamaral** [theotherp/nzbhydra2#236]
I use NZBHydra (along with Sonarr/Radarr and NZBGet) on my NAS, each one running in an individual Docker container. I also have my own CA and generated a self-signed certificate that I use for my local network (i.e: `domain.home` and `*.domain.home`). Then I have a bunch of reverse proxies configured so that I can access `https://nzbhydra.domain.home` to access NZBHydra (instead of using something like `http://domain.home:5076).

Everything is working just fine from my PC's point of view, I can access all these apps through HTTPS with my self-signed certificate with no need for ports, just specific hostnames for each individual app. The problem is configuring them to communicate with each other through that same hostname (https without port).

Let's go through some examples:

- Configure Sonarr/Radarr to access NZBHydra through `https://nzbhydra.domain.home` ✔
- Configure NZBHydra to access NZBGet through `https://nzbget.domain.home` ❌

Actually, Sonarr/Radarr prints the following error when accessing NZBHydra through `https://nzbhydra.domain.home` but it ignores the error and goes through with the request:

> 18-9-5 11:36:28.4|Debug|X509CertificateValidationPolicy|Certificate validation for https://nzbhydra.domain.home/api?t=tvsearch&cat=5010,5040&extended=1&apikey=(removed)&offset=0&limit=100 failed. RemoteCertificateChainErrors

While NZBHydra does not do that when accessing NZBGet in the same way...

So, how can I either:

1. Make NZBHydra ignore certificate errors when accessing NZBGet or...
2. Add my own CA to NZBHydra inside Docker so that it succssfully validates the certificate when accessing NZBGet or...
3. Is there any other solution for this?

**Comment by theotherp** [comment]
I'm currently not at home and can't test it but you can try this:

Make sure in the main config you have enabled to use the packaged cacerts file. In the data folder there should be a file called `cacerts`. Follow these [instructions](https://stackoverflow.com/a/11617655) to import your certificate. Restart Hydra and try again.

**Comment by rfgamaral** [comment]
Those instructions seem to import the certificate into the JRE store but then you're also suggesting that I enable the "use packaged CA certs" which skips the JRE store. I'm confused!

**Comment by rfgamaral** [comment]
Haven't yet tested that solution but I'm thinking that even if that works I'll have to do it every time I update the Docker container (when a new NZBHydra version is released). Isn't there a way to automate all this?

**Comment by theotherp** [comment]
Yeah sorry, I forgot how I had implemented that...

Disable that option and import your certificate into the JRE cacerts file. It's up to you to keep your JRE (and with that the cacerts file) updated.

In any case, I would strongly recommend using Let's encrypt to get a valid certificate for your server.

**Comment by rfgamaral** [comment]
>Disable that option and import your certificate into the JRE cacerts file. It's up to you to keep your JRE (and with that the cacerts file) updated.

Thank you, will look into that :)

> In any case, I would strongly recommend using Let's encrypt to get a valid certificate for your server.

I don't need a valid certificate because I'm the only one accessing my server through a VPN, the server is not accessible to the public and it will never be.

**Comment by theotherp** [comment]
In that case I wonder why you're using SSL at all...

**Comment by rfgamaral** [comment]
Because, why not? :)

**Comment by theotherp** [comment]
So adding to the cacerts file worked?

**Comment by rfgamaral** [comment]
Sorry, never tried it because I can't find a way to automate that and I don't want to be bothered to do that any time I need to update the Docker container. But I'm assuming it will work, I've done something similar in the past on a different context, but it makes sense that it works here too. Sorry again.

**Comment by rfgamaral** [comment]
Wouldn't be a beet option to ignore the certificate error (still print to log) and let it continue like Sonarr does? Perhaps a multi option where you can pick to ignore certificate errors on external requests, local requests, or both? Or just do it for local network requests, I don't know... Whatever you think it's best :)

**Comment by theotherp** [comment]
Well, there's the option "Verify SSL" which you can disable...
