### ISSUE TITLE
Docker Updates

### ISSUE THREAD

**Issue by BzowK** [theotherp/nzbhydra2#238]
Hey Guys - 

First of all, a big thanks to the developers for such a great tool!

I run NZBHydra2 in Docker so when a new version is released, it's obviously recomended to upgrade the container instead of the application layer within.  Unfortunately, I've found that although it seems to be created by the same owner, the official Docker container isn't updated at the same time as the application, but many days after.  As of writing, 2.0.5 is the latest version, but the container (last updated 9 days ago) is at 2.0.3.

**Overall Question**
I just wanted to post to ask if there was a supported procedure one could follow to manually upgrade the container while waiting on a release.

**Quick Container Update Script**
_The below isn't related to the question / issue above, but thought it may help out anyone who may be reading this, perhaps..._
As updates for it are somewhat frequent, I wrote a small script which can be executed to automatically upgrade the container if anyone reading is interested.  Overall, it stops the existing container, removes it, deletes its image by purging all unused images, then adds the container back - downloading the latest release, then finally runs the container to bring it back online again.
```
docker stop NZBHydra2
docker rm NZBHydra2
docker image prune -a --force
docker run --name=NZBHydra2 \
    -v ~/nzbhydra2/data:/data:z \
    -v ~/nzbhydra2/torrents:/torrents:z \
    -e PGID=0 -e PUID=0 \
    -e TZ=America/Chicago \
    -p 5076:5076 theotherp/nzbhydra2
```

**Notes**
- Edit lines lines as desired to match your environment including the container's name ("NZBHydra2" above), paths, ports, timezone, etc
- As config is stored in a path on the host if using a config similar to the one above, executing this will still retain your config - even though it deletes the container & image
- Since each version of the image changes it's ID, I have it deletes the old one by purging any/all images on the host which are not referenced therefore do not use if you wish to keep other images which may be in this state
- Once you create the .sh file, remember to run "sudo chmod +x filename.sh" against it to make it executable

Thanks!

**Comment by theotherp** [comment]
I recommend using the container by binhex or linuxserver.io as linked in
the Readme.

**Comment by theotherp** [comment]
Will try to do updates more regularly.
