### ISSUE TITLE
iframe organisr no longer working

### ISSUE THREAD

**Issue by phairplay** [theotherp/nzbhydra2#24]
hi,
i‘ve just switched over to your new version which looks great and is super fast. i‘ve got everything up and running after migrating yet now i cant get nzbhydra to show up in organisr

**Comment by theotherp** [comment]
I have no idea what do to with that information (or lack thereof). v1 and v2 are completely separate, one should not affect the other.

Do you mean that you had an entry for v1 before and it's gone now? Or that your entry for v1 is empty or missing now that v2 is running? The port is different for v2, so you need to adapt it.

When you create an issue it says right there that you should provide all the information that might help me. In this case more details, screenshots, etc are needed.

**Comment by creoden** [comment]
I know exactly what they are talking about, experiencing the same thing. NZBHyrda2 will not load in an iframe (embedded in a page), v1 was able to, this one will not, just loads white.

**Comment by theotherp** [comment]
Ah, that is the tiny bit more information that I needed.

**Comment by theotherp** [comment]
Note: Unlike with v1 when an issue is closed that doesn't mean the changes are already active. The next released version will contain the fix.
