### ISSUE TITLE
404 when using domain and url base with nginx reverse proxy

### ISSUE THREAD

**Issue by DcBexter** [theotherp/nzbhydra2#241]
The Same Problem as Issue #207 

![image](https://user-images.githubusercontent.com/2346602/45934396-025a2400-bf9e-11e8-84c2-b5732c9ffc56.png)
```
An error occured :
404: 

{
  "timestamp" : 1537747611259,
  "status" : 404,
  "error" : "Not Found",
  "message" : "No message available",
  "path" : "/nzbhydra/static/html/states/header.html"
}
```

It works fine using https://serverip/nzbhydra but using https://domain.name/nzbyhdra gives the error above. I am using the configuration for nginx from the wiki

```		
location /nzbhydra {
	proxy_pass http://127.0.0.1:5076/nzbhydra;
	proxy_set_header        X-Real-IP		$remote_addr;
	proxy_set_header        Host			$host;
	proxy_set_header        Scheme			$scheme;
	proxy_set_header        X-Forwarded-For		$proxy_add_x_forwarded_for;
	proxy_set_header        X-Forwarded-Proto	$scheme;
	proxy_set_header        X-Forwarded-Host	$host;
	proxy_redirect off;
}

**Comment by theotherp** [comment]
Please enable debug log file level and enable the logging marker for URL calculation in the main settings. Open the page again, go to the systems section (via IP), get the debu infos ZIP and post it.

**Comment by DcBexter** [comment]
Here is the debug output you requested

[nzbhydra-debuginfos-2018-09-24-18-58.zip](https://github.com/theotherp/nzbhydra2/files/2412012/nzbhydra-debuginfos-2018-09-24-18-58.zip)

While writing this and thinking about how to provide you with more information, I tried recording the activity in the network tab of chromes devtools. While doing that I activated the "disable cache" checkmark, and after that it worked.

So the problem lies not within nzbhydra2 but with my caching settings. sorry about the fuzz ;-)

So this is too much caching for nzbhydra2, **don't** use these settings:
```
	# Expires map
	map $sent_http_content_type $expires {
		default                    off;
		text/html                  epoch;
		text/html~				   epoch;
		~text/css                  max;
		~text/javascript	       max;
		application/javascript     max;
		application/json		   off;
		~application/	           max;
		~image/                    max;
		image/png                  max;
	}
	expires $expires;
```

**Comment by theotherp** [comment]
Thanks for solving this yourself and providing the solution.
