### ISSUE TITLE
How do I send to downloader?

### ISSUE THREAD

**Issue by bluelavalamp** [theotherp/nzbhydra2#242]
I think I've got the system setup correctly.  I've entered my indexers, I've setup the downloader (nzbget - which I'm currently using with Medusa and Radarr) and it's able to make the connection.  I do a search and I get my results.  But when I click on NZB in the far right column all it does it download the NZB to the web browser.  

How do I have it send the NZB directly to nzbget?

**Comment by theotherp** [comment]
Please follow the instructions and post your debug infos zip.

**Comment by henningBunk** [comment]
Hey!
I had the same problem that I was not sure how to add something to the downloader after configuring it.

Here is what I had to do:

1. Save the settings (upper right)
2. Somehow force refresh the website, I had to press the reload icon in firefox while holding the `Alt`-Key

Between the `Download NZB` icon an icon from your downloader will appear.  
Hope this willl help others when they stumble upon the same problem.

> 
> 
> I think I've got the system setup correctly. I've entered my indexers, I've setup the downloader (nzbget - which I'm currently using with Medusa and Radarr) and it's able to make the connection. I do a search and I get my results. But when I click on NZB in the far right column all it does it download the NZB to the web browser.
> 
> How do I have it send the NZB directly to nzbget?
