### ISSUE TITLE
Feature Request: Support for NNTmux/nZEDb WEB-DL categories 

### ISSUE THREAD

**Issue by DariusIII** [theotherp/nzbhydra2#243]
NNTmux and nZEDb have separate Web-DL categories for **TV (2010**) and **Movies (5080**) categories.
When searching indexers that use them, and admin has not disabled web-dl categorization, results within those categories are not returned. 
Adding custom categories also does not work, as hydra supports only newznab based categories.

While admins CAN disable categorization into those 2 categories, i believe hydra should support these.

**Comment by theotherp** [comment]
I'll check it out. You're free to configure those categories by yourself.

**Comment by DariusIII** [comment]
That is the problem. When i try to add that category, hydra complains that it is not a newznab category and refuses to add it.

**Comment by theotherp** [comment]
Works fine for me: https://i.imgur.com/0Oe32iy.png

**Comment by DariusIII** [comment]
Ahhhh, then it is fine. My bad. Thanks anyway.
