### ISSUE TITLE
API Missing Covers on NZB360

### ISSUE THREAD

**Issue by Adam1986** [theotherp/nzbhydra2#244]
Hello,

Just tried switching from Hyrda1 to Hyrda2 and on NZB360 on my phone none of the results have covers anymore, when I click on a result I am granted with a Hyrda login page, once this is entered I am then taken to the indexer.  

This behaviour seems to be a little bit different from Hydra1.  

Is it possible to get it so the results take me straight to the indexer as well as show the cover images?

Cheers

**Comment by theotherp** [comment]
Works fine for me. I get covers and tapping a result leads me directly to the indexer.

Open the API results in your browser by entering e.g. http://127.0.0.1:5076/api?apikey=<yourapikey>&search&cat=2000
Do you see covers? The images are part of the description in the results which I don't have any control over.

I'm not exactly sure what link NZB360 uses when you tap a result, I guess the one for comments. You could ask the developer.

**Comment by Adam1986** [comment]
Cheers for getting back to me, I switched back to Hydra1 again for now but will do some further testing tomorrow. I did test the API in the browser and I dont recall seeing the covers.  It was the first thing I checked as I used to run a small newznab installation.

I'll get back to you asap, would it make any difference that my Hydra setup is behind a reverse proxy?

**Comment by Adam1986** [comment]
Morning, so I've done some further testing between both versions and for me Hydra2 isn't giving any newznab:attr name="coverurl" result back in the API.

I've copied and pasted a comparison of the results for the same release between Hydra1 and Hydra2.

Hydra1:
`        <item>
                <title>Sicario.Day.of.the.Soldado.2018.720p.BluRay.x264-WiKi</title>
                <guid isPermaLink="false">055f95f208c6a1a7f1ad6a1a92ca7f29075d0427</guid>
                <link>https://xxx/getnzb?apikey=xxx&amp;searchresultid=055f95f208c6a1a7f1ad6a1a92ca7f29075d0427</link>
                <comments>https://drunkenslug.com/details/fbd59e668be101c639ce278f9ab152971c54e2c3</comments>
                <pubDate>Mon, 01 Oct 2018 09:36:50 +0100</pubDate>
                <category>Movies HD</category>
                <description>Sicario.Day.of.the.Soldado.2018.720p.BluRay.x264-WiKi - api.drunkenslug.com</description>
                <enclosure url="https://xxx/getnzb?apikey=xxx&amp;searchresultid=055f95f208c6a1a7f1ad6a1a92ca7f29075d0427" length="6464239152" type="application/x-nzb"/>

                
                    <newznab:attr name="hydraIndexerScore" value="10"/>
                    <newznab:attr name="category" value="2040"/>
                    <newznab:attr name="hydraIndexerHost" value="https://api.drunkenslug.com"/>
                    <newznab:attr name="hydraIndexerName" value="api.drunkenslug.com"/>
                    <newznab:attr name="poster" value="zKZGptjqka37sM@kSmixXl.Fe6"/>
                    <newznab:attr name="coverurl" value="https://drunkenslug.com/covers/movies/5052474-cover.jpg"/>
                    <newznab:attr name="comments" value="0"/>
                    <newznab:attr name="grabs" value="1"/>
                    <newznab:attr name="imdb" value="5052474"/>
                    <newznab:attr name="guid" value="055f95f208c6a1a7f1ad6a1a92ca7f29075d0427"/>
                    <newznab:attr name="group" value="alt.binaries.xylo"/>
                    <newznab:attr name="password" value="0"/>
                    <newznab:attr name="usenetdate" value="Mon, 01 Oct 2018 09:36:50 +0100"/>
                    <newznab:attr name="files" value="67"/>
                    <newznab:attr name="size" value="6464239152"/>
                    <newznab:attr name="category" value="2040"/>
                    <newznab:attr name="category" value="2050"/>
                    <newznab:attr name="category" value="2060"/>
            </item>`

Hydra2:
`        <item>
            <title>Sicario.Day.of.the.Soldado.2018.720p.BluRay.x264-WiKi</title>
            <link>http://xxx/getnzb/api/5843345798626694630?apikey=xxx</link>
            <enclosure url="http://xxx/getnzb/api/5843345798626694630?apikey=xxx" length="6464239152" type="application/x-nzb"/>
            <pubDate>Mon, 01 Oct 2018 08:43:16 +0000</pubDate>
            <guid isPermaLink="false">5843345798626694630</guid>
            <description>Sicario.Day.of.the.Soldado.2018.720p.BluRay.x264-WiKi</description>
            <comments>https://drunkenslug.com/details/fbd59e668be101c639ce278f9ab152971c54e2c3#comments</comments>
            <category>Movies HD</category>
            <newznab:attr name="category" value="2040"/>
            <newznab:attr name="comments" value="0"/>
            <newznab:attr name="files" value="67"/>
            <newznab:attr name="grabs" value="3"/>
            <newznab:attr name="group" value="alt.binaries.xylo"/>
            <newznab:attr name="guid" value="5843345798626694630"/>
            <newznab:attr name="imdb" value="5052474"/>
            <newznab:attr name="password" value="0"/>
            <newznab:attr name="poster" value="zKZGptjqka37sM@kSmixXl.Fe6"/>
            <newznab:attr name="size" value="6464239152"/>
            <newznab:attr name="usenetdate" value="Mon, 01 Oct 2018 09:36:50 +0100"/>
            <newznab:attr name="hydraIndexerScore" value="10"/>
            <newznab:attr name="hydraIndexerHost" value="api.drunkenslug.com"/>
            <newznab:attr name="hydraIndexerName" value="api.drunkenslug.com"/>
        </item>`

Cheers

**Comment by theotherp** [comment]
I just tested the query from DS manually using https://drunkenslug.com/api?apikey=<apikey>&t=search&cat=2000&extended=1&q=soldado and the results don't contain any coverurls. 

I forward all the newznab attributes from the indexer, without removing any.  You might want the DS admin(s) if they have any idea what's going on. I don' think this is an issue on my part.

**Comment by Adam1986** [comment]
I've just disabled DS on both Hydra setups and left nzbplanet enabled and its doing just the same :-s

This is Hydra1:

> <item>
> <title>Death.Race.Beyond.Anarchy.2018.BDRip.AC3.X264-CMRG</title>
> <guid isPermaLink="false">49aeeddad3405860c6b16d90303abf17bcc13d78</guid>
> <link>
> https://xxx/getnzb?apikey=xxx&searchresultid=49aeeddad3405860c6b16d90303abf17bcc13d78
> </link>
> <comments>
> https://api.nzbplanet.net/details/ac4cd4263924cbedd91f793cbf85cfd4
> </comments>
> <pubDate>Mon, 01 Oct 2018 12:06:58 +0100</pubDate>
> <category>Movies HD</category>
> <description>
> Death.Race.Beyond.Anarchy.2018.BDRip.AC3.X264-CMRG - api.nzbplanet.net
> </description>
> <enclosure url="https://xxx?apikey=xxx&searchresultid=49aeeddad3405860c6b16d90303abf17bcc13d78" length="1869997204" type="application/x-nzb"/>
> <newznab:attr name="imdbdirector" value="Don Michael Paul"/>
> <newznab:attr name="grabs" value="62"/>
> <newznab:attr name="imdb" value="3807900"/>
> <newznab:attr name="imdbtitle" value="Death Race 4: Beyond Anarchy"/>
> <newznab:attr name="usenetdate" value="Mon, 01 Oct 2018 12:06:58 +0100"/>
> <newznab:attr name="size" value="1869997204"/>
> <newznab:attr name="hydraIndexerScore" value="10"/>
> <newznab:attr name="guid" value="49aeeddad3405860c6b16d90303abf17bcc13d78"/>
> <newznab:attr name="hydraIndexerName" value="api.nzbplanet.net"/>
> <newznab:attr name="comments" value="0"/>
> <newznab:attr name="files" value="42"/>
> <newznab:attr name="category" value="2040"/>
> <newznab:attr name="backdropurl" value="https://api.nzbplanet.net/covers/movies/3807900-backdrop.jpg"/>
> <newznab:attr name="hydraIndexerHost" value="https://api.nzbplanet.net"/>
> <newznab:attr name="poster" value="pNApG1s2MnJ62IFOymxnK0VF@CsyvzQc1VWFX.Trp"/>
> <newznab:attr name="genre" value="Action"/>
> <newznab:attr name="group" value="alt.binaries.triballs"/>
> <newznab:attr name="password" value="0"/>
> <newznab:attr name="rageid" value="0"/>
> <newznab:attr name="imdbactors" value="Zach McGowan, Frederick Koehler, Christine Marzano, Yennis Cheung"/>
> <newznab:attr name="imdbyear" value="2018"/>
> <newznab:attr name="coverurl" value="https://api.nzbplanet.net/covers/movies/3807900-cover.jpg"/>
> <newznab:attr name="imdbscore" value="5.7"/>
> <newznab:attr name="imdbplot" value="Black Ops specialist Connor Gibson infiltrates a maximum security prison to take down legendary driver Frankenstein in a violent and brutal car race."/>
> <newznab:attr name="category" value="2040"/>
> <newznab:attr name="category" value="2050"/>
> <newznab:attr name="category" value="2060"/>
> </item>
> <item>

Hydra2:

> <item>
> <title>Death.Race.Beyond.Anarchy.2018.BDRip.AC3.X264-CMRG</title>
> <link>
> http://xxx:5076/getnzb/api/-6920241342698905989?apikey=xxx
> </link>
> <enclosure url="http://xxx/getnzb/api/-6920241342698905989?apikey=xxx" length="1869997204" type="application/x-nzb"/>
> <pubDate>Mon, 01 Oct 2018 11:07:18 +0000</pubDate>
> <guid isPermaLink="false">-6920241342698905989</guid>
> <description>Death.Race.Beyond.Anarchy.2018.BDRip.AC3.X264-CMRG</description>
> <comments>
> https://api.nzbplanet.net/details/ac4cd4263924cbedd91f793cbf85cfd4#comments
> </comments>
> <category>Movies HD</category>
> <newznab:attr name="category" value="2040"/>
> <newznab:attr name="comments" value="0"/>
> <newznab:attr name="files" value="42"/>
> <newznab:attr name="grabs" value="62"/>
> <newznab:attr name="group" value="alt.binaries.triballs"/>
> <newznab:attr name="guid" value="-6920241342698905989"/>
> <newznab:attr name="imdb" value="3807900"/>
> <newznab:attr name="password" value="0"/>
> <newznab:attr name="poster" value="pNApG1s2MnJ62IFOymxnK0VF@CsyvzQc1VWFX.Trp"/>
> <newznab:attr name="rageid" value="0"/>
> <newznab:attr name="size" value="1869997204"/>
> <newznab:attr name="usenetdate" value="Mon, 01 Oct 2018 12:06:58 +0100"/>
> <newznab:attr name="hydraIndexerScore" value="10"/>
> <newznab:attr name="hydraIndexerHost" value="api.nzbplanet.net"/>
> <newznab:attr name="hydraIndexerName" value="api.nzbplanet.net"/>
> </item>

I have just tried the soldado search straight onto the DS API though as you did and as you say it doesnt contain the URLS but Hydra1 is certainly giving them back as you can see - very unusual :-s

**Comment by theotherp** [comment]
Well, this is mysterious... I currently don't have the time to take a deeper look but hopefully will be able to do so on the weekend.

**Comment by Adam1986** [comment]
Morning, just wondered if you managed to take a further look at this over the weekend?

Cheers
Adam

**Comment by theotherp** [comment]
I can't explain it :-/

**Comment by Adam1986** [comment]
Ah :-/ this is the only thing holding me back from using Hydra2 :-(

**Comment by Adam1986** [comment]
I've emailed both DS and Planet and sent them this discussion link so hopefully they will look at this.

Failing that can anything be done Hydra side to perhaps change the way the queries are made per indexer basis?

**Comment by Adam1986** [comment]
Hello, I don't suppose you've had a chance to think about the above have you?

I never got any responses from either admin at both indexers unfortunately, so it doesn't appear that this will be rectified at the indexer end :-(

Thanks

**Comment by Adam1986** [comment]
> I'll think about it.

Hello again, just wondered if you had thought above the above?

Cheers
Adam

**Comment by theotherp** [comment]
I can't think of a proper, performant way to provide the covers if the indexer doesn't provide them, sorry. If the indexers won't fix it I'm afraid I can't help you. I'll leave this open until I find a way or have more time to analyze this further.

**Comment by theotherp** [comment]
Let me know if it works.
