### ISSUE TITLE
AltHUB Indexer Error - Unable to find valid certification path

### ISSUE THREAD

**Issue by thepawn713** [theotherp/nzbhydra2#246]
Log Line:

{"@timestamp":"2018-10-03T21:37:30.003+00:00","@version":"1","message":"Connection check with indexer AltHUB failed with message: Error while communicating with indexer AltHUB. Server returned: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target","logger_name":"org.nzbhydra.indexers.capscheck.NewznabChecker","thread_name":"http-nio-0.0.0.0-5076-exec-5","level":"WARN","level_value":30000,"IPADDRESS":"172.19.0.1"}

[nzbhydra-debuginfos-2018-10-03-16-46.zip](https://github.com/theotherp/nzbhydra2/files/2444019/nzbhydra-debuginfos-2018-10-03-16-46.zip)

**Comment by theotherp** [comment]
As a quick fix you can just disable SSL certificate verification in the main settings. 

I've looked into it and currently don't have an idea how to fix it properly as this is really in depth SSL stuff which I don't know enough about.

**Comment by juanchristian** [comment]
Have the same issue. Had to disable SSL check.

**Comment by Hobbabobba** [comment]
carefull: if you disable SSL check in general settings, you disable it for any indexer!
better change the URL-setting for AltHub from HTTPS to HTTP and you are fine

**Comment by theotherp** [comment]
I'll try to add an option to disable certificate checking per indexer as a quick fix and get a proper solution for the problem in the long run, but I don't have much time at the moment.

**Comment by thepawn713** [comment]
Still happens for me.  I added them to the disable by Host field and it worked again.

Thanks!

[nzbhydra-debuginfos-2018-10-23-13-30.zip](https://github.com/theotherp/nzbhydra2/files/2507484/nzbhydra-debuginfos-2018-10-23-13-30.zip)

**Comment by Hobbabobba** [comment]
updated to v2.0.11 but it still happens. thx.

**Comment by theotherp** [comment]
Which docker are you both running?

**Comment by thepawn713** [comment]
I've had this issue on my Macbook (idk what version) and on Unraid running docker 18.06.1-ce

**Comment by theotherp** [comment]
By which maintainer? My docker? linuxserver.io's? Binhex'?

**Comment by thepawn713** [comment]
Linuxserver's.  

Docker 1bd30973bd80 (if that number is useful)

**Comment by Hobbabobba** [comment]
Docker from linuxserver (latest)

**Comment by Hobbabobba** [comment]
tried with a "normal" installation of nubhydra2 on a Ubuntu 16 LTS server: same problem (didn´t use the docker container)

**Comment by theotherp** [comment]
The problem is, as far as I understand it, is something called SNI which allows that the same certificate is used for multiple domains (on the same server). While Java 8 and upwards *should* support that for some reason I can't get it to work with my code. The certificate is found but is supposedly for "althub.co.za" which doesn't match "api.althub.co.za". I had to import the certificate for the latter into the packaged cacerts file. It should work with the next version.

The solution isn't ideal as I would need to do this for any indexer with the same problem but it's a solution nonetheless.

**Comment by theotherp** [comment]
I just tested it and it works.

**Comment by thepawn713** [comment]
You're awesome, thanks!  Linuxserver hasn't pushed the update for me yet but I'll try it out soon.

**Comment by thepawn713** [comment]
Just updated, still not working for me. 
<img width="1449" alt="screen shot 2018-10-26 at 8 26 48 am" src="https://user-images.githubusercontent.com/26048694/47569419-34420b80-d8f9-11e8-9be8-1e75da0faa97.png">
<img width="725" alt="screen shot 2018-10-26 at 8 27 47 am" src="https://user-images.githubusercontent.com/26048694/47569426-36a46580-d8f9-11e8-87cc-6e19fbd6308b.png">



Unraid
LinuxServer.io/hydra2
version 2.0.12
[nzbhydra-debuginfos-2018-10-26-08-25.zip](https://github.com/theotherp/nzbhydra2/files/2519323/nzbhydra-debuginfos-2018-10-26-08-25.zip)

**Comment by theotherp** [comment]
Try changing "api.althub.co.za" to "althub.co.za".

**Comment by theotherp** [comment]
I don't understand, it worked when I tested it :-(

**Comment by thepawn713** [comment]
Genius!  I should have tried that myself... removing api worked!

**Comment by theotherp** [comment]
That's a workaround, I just found out why the update didn't work. Should hopefully actually work in next release even with "api."
