### ISSUE TITLE
Issues in Sonarr

### ISSUE THREAD

**Issue by BzowK** [theotherp/nzbhydra2#247]
Hey Guys - 

First off, thanks for a GREAT app!  Looking forward to future feature enhancements.

I use NZBHydra2 within Docker for internal searches as well as API with Sonarr, CouchPotato, etc.  Most of my indexers are from Jackett, but also have some NZB sites within it.  I recently noticed that in Sonarr where I have NZBHydra2 added as an indexer, I never get results from it.  Ilooked in logs and found the following error when it tries to search against it:
`Feed does not contain application/x-nzb, found application/x-bittorrent, did you intend to add a Torznab indexer?`

 Below is how I have the indexer configured:
- Newznab
- Enable RSS Sync: Yes
- Enable Search: Yes
- URL: http://192.168.0.21:5076/search/torznab
  (That's the address I visit for internal searches with "/torznab" added to the end as I have "/search" added as a base path.
- API Path: /api
- API Key: xxxxxx
- Categories: 5030,5040,5000
The remaining fields are empty

I enabled debug logging, but didn't see any additional information.  I'm using NZBHydra2 v2.0.9 and within Config tried changing "Generated Queries" from "All Searches", but got the same results.

Any suggestions?  Thanks!

**Comment by theotherp** [comment]
In the future please follow the instructions and always post the debug infos ZIP as requested.

You need to add Hydra once as torznab indexer and once as newznab indexer. You can get the URLs for that from the "API?" button in the Hydra config.

**Comment by BzowK** [comment]
OK - Apologies and thanks!

**Comment by theotherp** [comment]
You're welcome.
