### ISSUE TITLE
You are not allowed to visit that section

### ISSUE THREAD

**Issue by addaitrs** [theotherp/nzbhydra2#249]
By simply going to 'History & Stats' I get a "You are not allowed to visit that section" blue message pop up at the bottom.

This only appears to happen when visiting the site via an external URL, this doesn't happen when using an internal URL.

I have no auth setup in NZBHydra2 (I'm using Nginx to Auth)

**Comment by theotherp** [comment]
As mentioned above please post the debug infos. Also post your ngix.conf
