### ISSUE TITLE
An unknown error occurred while communicating with NZBHydra:

### ISSUE THREAD

**Issue by phairplay** [theotherp/nzbhydra2#25]
Hi,
When viewing nzbhydra2 on any device iPad (iOS) mobile (android) I get the below error message.

```
An unknown error occurred while communicating with NZBHydra:

{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"headers":{"NzbHydra2-Handle-Errors-Generically":true,"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"3e2f2f2b-0b2d-4d8c-a222-d1364bd88067"},"url":"internalapi/welcomeshown","cached":false},"statusText":""}
```
I don’t see this message on my pc (windows 10) and I’m accessing it via nginx proxy if that makes any difference.

**Comment by theotherp** [comment]
The newest version should provide a bit more infos in the log. If you get the error again please post the debug infos.

**Comment by phairplay** [comment]
[nzbhydra-debuginfos-2018-01-08-19-48.zip](https://github.com/theotherp/nzbhydra2/files/1612853/nzbhydra-debuginfos-2018-01-08-19-48.zip)
hi,
i upgraded and i‘m still seeing the same error. i‘ve attached the logs as requested

**Comment by theotherp** [comment]
Hm, I'm seeing some interesting errors that indicate other bugs that I have to fix but nothing that has anything to do with your's. Right now I have no idea. Perhaps I'll think of something. Sorry.

**Comment by sydlexius** [comment]
I'm receiving a very similar error, with my install being RP'd by Apache 2.4.29:

`An unknown error occurred while communicating with NZBHydra:

{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"headers":{"NzbHydra2-Handle-Errors-Generically":true,"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"f53c00a2-08b8-4173-8762-0fa46966e713"},"url":"internalapi/welcomeshown","cached":false},"statusText":""}`

I've attached my most recent log file as well.

[downloadlog.txt](https://github.com/theotherp/nzbhydra2/files/1641295/downloadlog.txt)

**Comment by theotherp** [comment]
Thanks, I have an idea.

**Comment by theotherp** [comment]
Still?

**Comment by phairplay** [comment]
still getting on both ipad and phone
[nzbhydra-debuginfos-2018-01-21-21-42.zip](https://github.com/theotherp/nzbhydra2/files/1650254/nzbhydra-debuginfos-2018-01-21-21-42.zip)

**Comment by theotherp** [comment]
Hmm... No idea. I don't have an ios device to test this.

**Comment by theotherp** [comment]
Is this still happening?

**Comment by sydlexius** [comment]
I no longer experience this issue.

**Comment by phairplay** [comment]
I'm no longer seeing the message thank you

**Comment by DrakeJones** [comment]
This is a rather frequent error condition - mostly with three character strings in the search term.
