### ISSUE TITLE
Is there a way to filter for just the file as the search result?

### ISSUE THREAD

**Issue by Tomservov2** [theotherp/nzbhydra2#250]
## How to create a bug report

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
* What do you expect to happen? What does happen? 
* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

## How to request a new feature
* What do you want to happen?
* If not clear, why do you want it?
* Do you think it's something only you need or something that might be popular?
* If need be explain the use case.

**Comment by Tomservov2** [comment]
I'm searching for immortal hulk 001 comic, it is being found but not understood by mylar.  Mainly because there is a bunch of date and other header stuff that comes with it in the result.  Can I apply a regex or something that returns just the filename associated with that post?

**Comment by theotherp** [comment]
Hydra has no way knowing the actual file name(s) contained in the results.

Tomservov2 <notifications@github.com> schrieb am Do., 18. Okt. 2018, 20:06:
