### ISSUE TITLE
Using output JSON in CAPS Newsnab API call results in XML

### ISSUE THREAD

**Issue by 11001010111111101011101010111110** [theotherp/nzbhydra2#251]
To test, hit ```http(s)://server_hostname:port/api?apikey=YOURAPIkey&t=caps&o=json```

Hydra2 version: 2.0.10

Expected: capability document in JSON / ```Content-type: application/json```
Result: capability document in XML / ```Content-type: application/xml;charset=UTF-8```

o=json is ignored and result is sent in XML instead.

This is similar to https://github.com/theotherp/nzbhydra2/issues/39 but for CAPS instead of Search

**Comment by theotherp** [comment]
Actually, the case doesn't matter... ;-)

**Comment by DariusIII** [comment]
Capabilities response does not return JSON on any existing indexerm, regardless of backend used. Only real JSON API response is sent by NNTmux based indexers API v2 output, but API v2 is not supported by any existing software on the market.

**Comment by theotherp** [comment]
I'll think about it.

**Comment by theotherp** [comment]
Took a while, sorry...

**Comment by edasque** [comment]
🙏🏼
