### ISSUE TITLE
Updated Windows Java build causes errors when searching with Newznab?

### ISSUE THREAD

**Issue by seriosbrad** [theotherp/nzbhydra2#252]
Windows 10, Java build 1.8.0_191-b12

Once I updated Java, I noticed I could no longer search with Radarr.  Then noticed I couldn't search with hydra either.  It's really the only thing that has changed with my system.  Debug log attached.

Edit: Not just trying to search Newznab. But also when trying to do a Force Update:

> 500: An error occurred while updating or getting update infos: Error while getting latest version: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>
>Path: /internalapi/updates/installUpdate
>
>Message: An error occurred while updating or getting update infos: Error while getting latest version: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

[nzbhydra-debuginfos-2018-10-22-17-04.zip](https://github.com/theotherp/nzbhydra2/files/2503706/nzbhydra-debuginfos-2018-10-22-17-04.zip)

**Comment by theotherp** [comment]
Does the file `%JAVA_HOME%/jre/lib/security/cacerts` exist? 

Try setting "Use packaged cacerts file" to false. If that doesn't work disable SSL verification in the main config for now. I'll take a look later.

**Comment by theotherp** [comment]
Can't reproduce this. Works fine on Windows 10 with re1.8.0_191

**Comment by DariusIII** [comment]
I am having the same issue:

> Error while communicating with indexer xxxxxx. Server returned: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
