### ISSUE TITLE
Add ability to search download history, etc

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [theotherp/nzbhydra2#253]
It would be nice if we had the ability to search through download history etc. My current use case is trying to determine how many files were grabbed with the release type of "web" not "web-dl".

**Comment by theotherp** [comment]
![filter](https://user-images.githubusercontent.com/14368889/47443548-da382d80-d7b4-11e8-8516-7f08adc74367.png)

**Comment by TheMeanCanEHdian** [comment]
Huh, my eyes completely glazed over those. Was looking for a box but this is definitely more powerful. Sorry about that.

**Comment by theotherp** [comment]
No problem. I always considered that a relatively well established icon for filtering, especially in tables, but apparently some users do not recognize it as such.

**Comment by TheMeanCanEHdian** [comment]
You are not wrong. I do recognize them but I completely glazed over them looking for the kind of filter box that exists for search.
