### ISSUE TITLE
Mixed Content https: Warning from http://static.tvmaze.com

### ISSUE THREAD

**Issue by akzkak** [theotherp/nzbhydra2#255]
When searching with Categories IDs.

Console log:
Mixed Content: The page at 'https://example.com/nzbhydra2/' was loaded over HTTPS, but requested an insecure image 'http://static.tvmaze.com/uploads/images/medium_portrait/6/16178.jpg'. This content should also be served over HTTPS.

**Comment by theotherp** [comment]
Please post the debug infos.
