### ISSUE TITLE
Headphones expects size attrs in XML payload

### ISSUE THREAD

**Issue by RagingRhinoz** [theotherp/nzbhydra2#256]
If I use the Jackett api I can see the size attribute in the API payload if I manually hit the Hydra API I'm not seeing a size attribute in the XML payload which explains why Headphones is complaining like.

An unknown error occurred trying to parse the feed: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/app/headphones/headphones/searcher.py", line 1337, in searchTorrent
size = int(item.find("torznab:attr", attrs={"name": "size"}).get('value'))
AttributeError: 'NoneType' object has no attribute 'get'

[nzbhydra-debuginfos-2018-11-21-07-58.zip](https://github.com/theotherp/nzbhydra2/files/2601546/nzbhydra-debuginfos-2018-11-21-07-58.zip)

Nice app btw.

**Comment by theotherp** [comment]
I just forward the attributes from the tracker. Do you have example XMLs, one from Jackett directly and one from Hydra?

**Comment by RagingRhinoz** [comment]
Thanks for getting back to me here are the returned XML files after I removed my keys.

[hydra.txt](https://github.com/theotherp/nzbhydra2/files/2603368/hydra.txt)
[jacket.txt](https://github.com/theotherp/nzbhydra2/files/2603369/jacket.txt)

**Comment by theotherp** [comment]
Fixed in 2.0.16

**Comment by RagingRhinoz** [comment]
Legend.
