### ISSUE TITLE
drop down search box

### ISSUE THREAD

**Issue by jbravo2uk** [theotherp/nzbhydra2#26]
When i click on drop down box on search and i press any of the options movies,TV  or and other category it always says all and not the category i have clicked on.I used to be able to click on movies and press search it would give me all the latest releases.?.Also there is not much cover art showing in nzb360 now.
[20180107_095616(1)(1).zip](https://github.com/theotherp/nzbhydra2/files/1609645/20180107_095616.1.1.zip)

**Comment by theotherp** [comment]
Please check the browser console (press F12) and see if there are any errors in there.

**Comment by theotherp** [comment]
Hmm I think I still don't understand what you mean, sorry.

**Comment by theotherp** [comment]
Ahh now I see it, thanks.

**Comment by theotherp** [comment]
Haha, sorry, I have the same problem. What the hell...

**Comment by theotherp** [comment]
Argh, what a stupid mistake. Ignore that, only the name is not updated. The rest should work as intended.

**Comment by jbravo2uk** [comment]
Also on the old version lets say i clicked the movie tab then just pressed search without putting in the search box it would give me a list of the latest releases.You are doing a great job.

**Comment by jbravo2uk** [comment]
Also here is a screen shot from nzb360 
![screenshot_2018-01-07-10-37-50](https://user-images.githubusercontent.com/35189655/34648721-40394ab8-f397-11e7-9937-57bc2812ccd4.png)

**Comment by theotherp** [comment]
I'll contact the NZB360 dev, I don't know what I have to do for that to work.

**Comment by theotherp** [comment]
See #28
