### ISSUE TITLE
Add magnet link to result listing display.

### ISSUE THREAD

**Issue by ruifung** [theotherp/nzbhydra2#263]
In the cases where results only have a magnet link, with proxying enabled, clicking the "download" button seems to try to download a null.torrent file.

I suggest not showing the download button for those entries, and showing a seperate magnet link button when a magnet link is available.

Hydra2 v2.0.17

Edit: Fixed typo.

**Comment by theotherp** [comment]
Works fine for me.

Please enable debug log level in Hydra, reproduce the problem and post your debug infos.

**Comment by ruifung** [comment]
```
Unsuccessful NZB download from URL http://server3.rfhome.lan:9117/jackett/dl/ettv/?jackett_apikey=<apikey>&path=Q2ZESjhManVuMkVPMXpwTXZTa3BZRGRfWl9ZdG1fOHdBcS1YNDNEWjZvYzJFbXhiQVdKV3o5LUNVd0xxRGE1WXFBbHZOMDdocGpwbDEzNXdPcERqTHVWRVpxSm1tcTljSU5yVk1WQ0tZSDcya3QyeVBNaGpTTFdhZ2dDRGlCel9ycThKX1dCaXhjWUVMbUdiTFpvVTNYWlVUQUdPQVpxdGhiRHRuYktaSmhWQWFNd1dUd2lxc1lRQ05WWkgtTUpVOVZNVHdn&file=They+Are+Billions+v0.6.0.55+torrent. Code: 302. Message: Found
```
Just saw the above... does this not handle redirects properly?

[nzbhydra-debuginfos-2018-12-05-18-54.zip](https://github.com/theotherp/nzbhydra2/files/2648473/nzbhydra-debuginfos-2018-12-05-18-54.zip)
