### ISSUE TITLE
Details link is not shown when unauthenticated

### ISSUE THREAD

**Issue by ruifung** [theotherp/nzbhydra2#264]
Despite that the option to "restrict details, comments and downloads" is disabled, the details link is still not shown when using as an authenticated user.

Hydra2 v2.0.17

Additional Details Below:
![image](https://user-images.githubusercontent.com/1073945/49379827-17e08c80-f74b-11e8-81b2-e344c4120f76.png)
![image](https://user-images.githubusercontent.com/1073945/49380273-40b55180-f74c-11e8-9d96-23def2697e14.png)
[nzbhydra-debuginfos-2018-12-03-22-39.zip](https://github.com/theotherp/nzbhydra2/files/2639843/nzbhydra-debuginfos-2018-12-03-22-39.zip)

**Comment by theotherp** [comment]
This could have multiple reasons. Please post your debug infos and a screenshot with an example. Make sure the log in the debug infos contains the search for which you made the screenshot.

**Comment by ruifung** [comment]
I've updated the issue with the requested details.

**Comment by theotherp** [comment]
In your screenshot you only have results from trackers. Not every tracker provides such links. Do you have the same problem with indexers?

**Comment by ruifung** [comment]
I would like to add, that these results, do show the details link, when logged in.

![image](https://user-images.githubusercontent.com/1073945/49421551-67669d00-f7cb-11e8-8f48-85600f0b09c5.png)

**Comment by theotherp** [comment]
Ohh, I see. I kinda skipped over the issue title, sorry.
