### ISSUE TITLE
Book-Search fails on nzedb

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#27]
Tried to search for an ebook on my nzedb-indexer (with hydra1 it works 100%) and got the error message
`Indexer returned error code 202 and description 'No such function (book)' when URL http://www.mydomain.com:7780/api?apikey=xxxyyyzzz&t=book&extended=1&q=Darcy&cat=7010&limit=100&offset=0 was called`
settings are exactly as in the hydra1 installation.

[nzbhydra-debuginfos-2018-01-07-11-21.zip](https://github.com/theotherp/nzbhydra2/files/1609673/nzbhydra-debuginfos-2018-01-07-11-21.zip)

**Comment by theotherp** [comment]
Huh, I didn't know I supported that in v1... Haven't implemented it, might take a bit. Sorry about that.

**Comment by theotherp** [comment]
Weird, the indexer is reporting to support the search type "book" but when called it says it's unsupported. 

Please do another caps check for http://www.mewes-chen.de:7780 in your config. It should remove the search type "book". Save and search again.

**Comment by Hobbabobba** [comment]
Perfect! Works - and I have no idea, why i didn´t try it before ;)

**Comment by theotherp** [comment]
All right. No idea why it didn't work in the first place.
