### ISSUE TITLE
NNTmux api url gives 404, manually testing url without "/api" works. How to change?

### ISSUE THREAD

**Issue by Rawh** [theotherp/nzbhydra2#270]
Hi,

Are there any plans on supporting NNTmux for use with Hydra2? When I add a tmux host it parses "/api?apikey=****&t=search" behind the hostname I entered.

This results in a 404 when Hydra2 is checking out the api. But when I remove the "/api" part from the url and try it manually, it seems to work.

Cheers

**Comment by theotherp** [comment]
I don't understand. What would be the correct URL to use? Can you give an example of an indexer that doesn't work?

**Comment by Rawh** [comment]
Ok I'm currently using https://nntmux.6box.me/

When I enter the credentials on Hydra2:
![image](https://user-images.githubusercontent.com/10486655/50341547-68affd80-051f-11e9-8a5a-e563454bdea9.png)

I get the following error:
![image](https://user-images.githubusercontent.com/10486655/50341604-a6148b00-051f-11e9-9d74-27ca8e2427d0.png)

As shown above, there's an URL there. If I open this one in a tab I indeed get a 404 errorcode.
![image](https://user-images.githubusercontent.com/10486655/50341663-fbe93300-051f-11e9-8113-ab3b383d55da.png)

When I remove "/api" from the url, the page seems to load ok:
![image](https://user-images.githubusercontent.com/10486655/50341721-33f07600-0520-11e9-982b-5e6a34c17c3a.png)

**Comment by Rawh** [comment]
Might be these pages could help out a bit:
API: https://nntmux.6box.me/apihelp
API v2: https://nntmux.6box.me/apiv2help

**Comment by theotherp** [comment]
Thanks. `https://nntmux.6box.me/rss?t=0&dl=1&i=36&r=APIKEY` works so I think `https://nntmux.6box.me/api?apikey=APIKEY&t=search` should work as well. I don't think the error is on my end. It doesn't work with Sonarr either.

**Comment by Rawh** [comment]
Hmm, worth forwarding / mentioning this issue then on the nntmux github page?

**Comment by theotherp** [comment]
I'll see what I can find out. Off for the holidays now.

**Comment by richmobile** [comment]
Close issue... I had something not set correctly for nntmux api. Everything should be good now.

**Comment by Rawh** [comment]
Seems the baseurl of the site needed something like "api/v1/" appended to it.
