### ISSUE TITLE
Disable SNI being ignored?

### ISSUE THREAD

**Issue by Rombus** [theotherp/nzbhydra2#272]
I'm having issues getting NZBGeek to add on a fresh install. Every time I try to add it, I get the unrecognized_name error. Here is what I've tried to fix the problem:
Tired both OpenJDK v11 and Oracle Java V11 (Debug info provided below is running on Oracle Java V11).
Removed and readded nzbgeek.info to the Disable SNI list
Tried to add NZBGeek with Verify SSL certificates turned off
Tried to add with both nzbgeek.info and api.nzbgeek.info in "Disable SNI for" list
Other trackers have added just fine. NZBGeek is the only one giving me trouble for some reason.

Any thoughts or other things I should try? Short of a fresh install? 
[nzbhydra-debuginfos-2018-12-27-14-13.zip](https://github.com/theotherp/nzbhydra2/files/2713185/nzbhydra-debuginfos-2018-12-27-14-13.zip)

**Comment by theotherp** [comment]
Try using Java 8, 9 or 10 as 11 isn't supported. Not sure that will make a difference, but who knows. That whole SNI thing is a bit weird and I've never really understood it properly, to be honest...

**Comment by Rombus** [comment]
I dropped down to OpenJDK 8 (easiest to install) and I can confirm I that Disable SNI is working correctly now and I added NZBGeek successfully. Thanks for the suggestion!

**Comment by theotherp** [comment]
Good to hear. To be fair. the readme says:

> You need Java Runtime Environment or OpenJDK (both >=8u101 or 9 or 10).

I don't support Java 11 for now. I'll take a closer look when I do work on the support.
