### ISSUE TITLE
Add new indexer - WtFnZb - Custom!

### ISSUE THREAD

**Issue by wtfnzb** [theotherp/nzbhydra2#275]
RSS/API is accessed via apache auth, so there would be needed some workaround for it.

**AUTHENTICATED** Accessing RSS via browser:
`https://USER:PASS@wtfnzb.pw/user/rss.php?code=PRIVATECODE&user=USER&cat=MP3`

NZBHydra2 returned **401: Unauthorized**

RSS Sample output:
```
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>WtF[nZb]</title>
<link>https://wtfnzb.pw/</link>
<description>WtF[nZb]</description>
<language>en-us</language>
<copyright>NoCopyLeft</copyright>
<atom:link href="http://wtfnzb.pw/" rel="self" type="application/rss+xml" />
<item>
<title>Duke_Demont_-_Club_FG-SAT-12-29-2018-TALiON_[aae5e0591]</title>
<link>https://wtfnzb.pw/user/dl.php?nzb=Duke_Demont_-_Club_FG-SAT-12-29-2018-TALiON_[aae5e0591]&amp;date=/2018/12/29/&amp;code=PRIVATECODE&amp;user=USER</link>
<pubDate>December 29 2018, 11:26:35</pubDate>
</item>
</channel>
</rss>
```

**Comment by theotherp** [comment]
Does it support searches or just RSS feeds?

**Comment by Kurisutian** [comment]
AFAIK it does support RSS with Search. Should look like this: https://wtfnzb.pw/user/rss.php?code=PRIVATECODE&user=USER&search=SOMETHING

**Comment by savahu** [comment]
It also seems to have an API at https://wtfnzb.pw/user/api.php?code=[PRIVATECODE]&user=[USERNAME]

**Comment by anonvoy** [comment]
SABnzbd says the search RSS feeds from this site are not XML and won't accept them.

**Comment by albino1** [comment]
Even with RSS every NZB I tried failed as password protected.

**Comment by wtfnzb** [comment]
Its apache auth for BETA aka wtfnzb.pw :)

https://0ccec98d8962a17294688363537bfe2e.wtfnzb.pw/ - is GAMMA and does not have apache auth, RSS/API works 100%

**Comment by robson90** [comment]
any update on this?

**Comment by theotherp** [comment]
I don't have an account and it's invite only. I have no way of testing it.

**Comment by theotherp** [comment]
Their API is shit. The URL format doesn't follow the standard. I tried implementing it but got a 403 when trying to download the NZB via hydra (while the same download URL works in my browser).

According to their admin posts in the forum they don't care and, I quote, "dont support *arr tools, and probably never will." so I don't really see why I should invest any time in supporting an indexer which goes out of their way to be as complicated to use as possible.

**Comment by robson90** [comment]
I saw the same post on the forum. I see your point. 

Thank you very much for the clarification 🥲

**Comment by theotherp** [comment]
FWIW I got it mostly working. Then it stopped working later and I'm still trying to find out way. I think they're explicitly blocking requests from hydra using the user agent. Using the user agent of a browser seems to work. I'll test some more and may release it as a "use on your own risk" type of feature. 

They also do not support paging, NFOs, extended attributes or mapping of shows / movies and therefore no searches by ID.

**Comment by ne0ark** [comment]
It seems like I can't add it radarr or sonarr. Is search only supported?

**Comment by theotherp** [comment]
You need to enable query generation.

As mentioned in the release notes the indexer does not support ID based searches so hydra will need to generate regular searches. The indexer is just shit :-)

**Comment by WebBuddha** [comment]
I'm not able to add the indexer the right way. How to solve this? Any ideas?
`The config of this indexer is incomplete. Please click the button at the bottom to check its capabilities and complete its configuration.`

**Comment by theotherp** [comment]
> I'm not able to add the indexer the right way. How to solve this? Any ideas? Query generation is already enabled. `The config of this indexer is incomplete. Please click the button at the bottom to check its capabilities and complete its configuration.`

Please create a new issue and post debug infos there.
