### ISSUE TITLE
Using "Forbidden Words" make some indexer return 0 results

### ISSUE THREAD

**Issue by Romfrosk** [theotherp/nzbhydra2#276]
For a while now i've seen 0 results on many of my indexers.
Went troubleshooting today, and it seems that added "Forbidden Words" under the Searching config makes them return 0 results no matter what you search for .

This behavior is the same both when adding it in config, and using the --prefix when searching

No "Forbidden words" searching for "Big Bang Theory"
<img width="364" alt="no illegal words" src="https://user-images.githubusercontent.com/3740193/50546721-ca155200-0c2c-11e9-9577-164b23f14fda.PNG">

Using --2ch when searching for "Big Bang Theory"
<img width="391" alt="2ch illegal words" src="https://user-images.githubusercontent.com/3740193/50546723-da2d3180-0c2c-11e9-98b3-6e139cf5deb8.PNG">

**Comment by theotherp** [comment]
Please post your debug infos zip.

**Comment by theotherp** [comment]
Some indexers use "!forbidden", some "--forbidden". I try to decide which to use by the backend of the indexer. It looks like this recognition doesn't work properly. I'll take a look.

**Comment by theotherp** [comment]
Works fine for me. Of the affected indexers in your screenshot I only have access to DS. I readded it and the backend was correctly recognized as NZEDB. Excluded words were correctly added to the generated query.

Without seeing the log from when you added the indexers I can't tell what might've gone wrong. I suggest you shutdown Hydra, open the `data\nzbhydra.yml` file and for the affected indexers change the `backend` value to `NZEDB`. Start Hydra again and see if it works.

**Comment by Romfrosk** [comment]
Did as you asked, and it now works as intended.
I guess readding them will also work.

They all had "Backend: NEWZNAB"
Also those who did work had NEWZNAB, but i haven't changed them to NZEDB
