### ISSUE TITLE
Have categories match multiple newznab categories

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#278]
See #268 

E.g. "10020,7000" only matches items that have both 7000 and 10020 as newznab category.

~But what about items that only have 7000? They wouldn't match that category. And if you add "7000" to that category it would again match the wrong items.~

**Comment by theotherp** [comment]
Jesus, that was tough.

**Comment by theotherp** [comment]
@alexdelifer Perhaps I could give you a beta to test this.

**Comment by alexdelifer** [comment]
Absolutely, I have so much time to kill right now.

Thank you so much for looking at this!

**Comment by alexdelifer** [comment]
@theotherp 
If you already have a build that would be great... I've been using the Docker container by binhex, but if you have a jar I can make it work.

**Comment by theotherp** [comment]
You can use 2.1.8-beta from here: https://hub.docker.com/r/theotherp/nzbhydra2/tags Hope it works, my docker experience is limited and I've never done a prerelease.

**Comment by alexdelifer** [comment]
Great container, and thank you so much for doing all this!
I was very easily able to move my config.

[nzbhydra-debuginfos-2019-01-01-05-02.zip](https://github.com/theotherp/nzbhydra2/files/2719246/nzbhydra-debuginfos-2019-01-01-05-02.zip)
yikes 2019, happy new years!

```
  - name: "E-Learning"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "8040"
    - "7000&100003"
```
```
Indexer returned error code 201 and description 'cgpeers does not support the requested query. 
Please check the capabilities (t=caps) and make sure the search mode and categories are supported.' when URL http://10.10.10.4:9117/api/v2.0/indexers/cgpeers/results/torznab/api?apikey=supersecretdontlook&
t=search&extended=1&q=something%20popular&password=0&cat=8040 was called
```

When I grep my log I don't see it searching for 7000 or 100003. 
Maybe it's not being passed to the indexer?

**Comment by theotherp** [comment]
You're right. I'll have a new build soonish.

**Comment by theotherp** [comment]
I understand that the query should also contain the categories 7000 and 100003. But why does the indexer not support the query? I would expect the correct URL to look like this:

http://10.10.10.4:9117/api/v2.0/indexers/cgpeers/results/torznab/api?apikey=supersecretdontlook&t=search&extended=1&q=something%20popular&password=0&cat=8040,7000,100003

**Comment by theotherp** [comment]
New container with tag: 2.1.8-BETA2

**Comment by alexdelifer** [comment]
Just tested the same query and it seems to work now!
I don't know how you did it, but you did...
I'm gonna spend the day trying to break it now...

Thank you so much. I was starting to convince myself it wasn't possible...

[nzbhydra-debuginfos-2019-01-01-13-50.zip](https://github.com/theotherp/nzbhydra2/files/2719551/nzbhydra-debuginfos-2019-01-01-13-50.zip)

**Comment by theotherp** [comment]
As I haven't had any feedback after that (or from anybody else) I guess it' working ;-)
