### ISSUE TITLE
Use dereferer for details links

### ISSUE THREAD

**Issue by jallakim** [theotherp/nzbhydra2#279]
Hi,

The details links (`http://foo.bar/nzbhydra/details/-1234`) should use the dereferer configured within nzbhydra. Currently it sends the browser to the destination by changing the `Location` header.

This is especially relevant when external programs use nzbhydra (for example CouchPotato), where the details link is presented. Clicking it will send the client directly.

**Comment by theotherp** [comment]
Hm? You mean the "i" icon in the search results? Works for me.

**Comment by jallakim** [comment]
Thanks for the fix!
