### ISSUE TITLE
Default search category other than All?

### ISSUE THREAD

**Issue by jsodeman** [theotherp/nzbhydra2#281]
Is there a way to set the Search category dropdown on the search page to default to something other than All? For example almost all my searches are Movies HD and it would be nice to not have to pick that every search.

**Comment by jbravo2uk** [comment]
I would like this option back as well

**Comment by theotherp** [comment]
Back? Why back?

**Comment by jbravo2uk** [comment]
![20190206_205314](https://user-images.githubusercontent.com/35189655/52373036-9dd1ca00-2a51-11e9-98de-7538399235c6.jpg)
Sorry i meant i have no drop down box showing movies etc

**Comment by theotherp** [comment]
You don't want a dropdown box at all? That's odd. No, not doing that. I'll
add a switch to the categories config to set one category to be preselected
initially.

**Comment by theotherp** [comment]
Funny, I seem to have forgotten about it and apparently changed my mind. Already implemented ;-)
