### ISSUE TITLE
RarBG as Jackett Indexer

### ISSUE THREAD

**Issue by g4m3r7ag** [theotherp/nzbhydra2#284]
When adding RarBG as a Jackett indexer it outputs a lot of errors during the capabilities check, gives a warning about it may not be used and when I try to run a search with only that indexer selected, Hydra advises there are no indexers selected. I have tried running the capabilities check multiple times at different times of day spread out across multiple days in case it was an issue on their end. When I run a test from Jackett for that indexer it passes and if I manually add the Jackett indexer into Sonarr/Radarr it will search it and return results. Only when using Hydra does it not ever return results. 

Attached the relevant section of the log
[hydra-rarbg-log.txt](https://github.com/theotherp/nzbhydra2/files/2757472/hydra-rarbg-log.txt)
 
I replaced my domain with "mydomain" as I'm resolving DNS internally for the machine running the services and Jackett is running on port 38087. My other Jackett indexers all work correctly it's just RarBG that has the issue. I saw a user mention the same trouble in this Reddit thread but it was never brought up again. 

[Reddit Thread](https://www.reddit.com/r/nzbhydra/comments/a4j79f/adding_tpb_to_hydra_2_possible/)
 
* What do you expect to happen? What does happen? 

Capabilities check to run and determine how to search RarBG and utilize those capabilities to complete searches. Check fails and indexer is not searched/or searched accurately. 

* Have you searched for this problem? You don't have to answer, just make sure. 

Found mention of issue in Reddit issue posted above.

* Can the problem be reproduced? How?

Running check to RarBG reproduces issue.

**Comment by theotherp** [comment]
Sorry, only now had time to look at this. The caps check will take longer now but should complete successfully.
