### ISSUE TITLE
Why is the site being shown as not secure

### ISSUE THREAD

**Issue by soupy14** [theotherp/nzbhydra2#285]
## How to create a bug report

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
* What do you expect to happen? What does happen? When hydra is up and running showing as not secure.

* Have you searched for this problem? You don't have to answer, just make sure. I can't seem to find an answer to this

* Can the problem be reproduced? How? Pretty straight forward it shows the web address as not secure.

Overall is hydra always going to show not secure?

**Comment by theotherp** [comment]
Uhm, I don't have much to work with here. I guess you're running Hydra without SSL and that makes your browser show that message. As long as you don't expose Hydra to the internet (as in making it accessible from outside your network) you can ignore it.
