### ISSUE TITLE
nzbindex.com changed address / doesn't work anymore

### ISSUE THREAD

**Issue by count00zero** [theotherp/nzbhydra2#286]
Hi there,

would you be able to update the predefinded nzbnidex.com to the new address: https://beta.nzbindex.com/
I don't think I've to upload a logfile for that :)

Thank you and best regards,
count

**Comment by theotherp** [comment]
Urgh, this doesn't just require changing the address but also requires changes in the parsing of the results which is a PITA. I'll probably do it at some point but it's not a quick fix.

**Comment by count00zero** [comment]
I understand that, thanks for considering it and the plan to do it some day, cause I usually like the results of nzbindex.nl/.com a lot :)

**Comment by theotherp** [comment]
Yes, because it doesn't work anymore...
