### ISSUE TITLE
oznzb stoped working because of caps

### ISSUE THREAD

**Issue by M0UL** [theotherp/nzbhydra2#287]
oznb was working fine for while then it stopped working because checking capabilities fails.   oznzb works fine in sonarr and radarr. any way to fix this?
[nzbhydra-debuginfos-2019-01-23-09-21.zip](https://github.com/theotherp/nzbhydra2/files/2786277/nzbhydra-debuginfos-2019-01-23-09-21.zip)

**Comment by theotherp** [comment]
Please follow the instructions for reporting a but / requesting help.

**Comment by theotherp** [comment]
Works for me on two machines. Try updating your java version. You can also try adding the host to the "Disable SSL for..." list in the main settings.
