### ISSUE TITLE
Delete database entries older than X

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#29]
nzbhydra has a lovely button to delete the log and database. 
will be nice to have it back in nzbhydra2, too.

(or there is no problem about an ever growing log and database regarding the RAM for java?)

**Comment by theotherp** [comment]
I didn't really think people would use that...

The size of the log doesn't matter. I'll add a function to truncate the database to get rid of entries older than X. That should do the same,

**Comment by theotherp** [comment]
Present in next release.
