### ISSUE TITLE
Error while communicating with indexer Drunken Slug. Server returned: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by Elenedeath** [theotherp/nzbhydra2#294]
hello @theotherp i have this error on a fresh installation of nzbhydra2 and openjdk11 on  debian 9.7
i prefer to use openjdk 11 because openjdk8 are outdated now, end of life in january2019

openjdk are installed via apt-get

> openjdk-11-jdk/stretch-backports,now 11.0.1+13-2~bpo9+1 amd64  [installé]
>   OpenJDK Development Kit (JDK)

java -version
> openjdk version "11.0.1" 2018-10-16
> OpenJDK Runtime Environment (build 11.0.1+13-Debian-2bpo91)
> OpenJDK 64-Bit Server VM (build 11.0.1+13-Debian-2bpo91, mixed mode, sharing)

[nzbhydra-debuginfos-2019-01-29-00-56.zip](https://github.com/theotherp/nzbhydra2/files/2805424/nzbhydra-debuginfos-2019-01-29-00-56.zip)

I found a workaround need to  change the key store from pkcs12 to jks, regenerate the cacert and error are resolved (method 1) or if you don't want to change, you need to add the password for cacert to the application (method2).

**_method 1_**
`cat /etc/java-11-openjdk/security/java.security`
change keystore.type=pkcs12 to keystore.type=jks

` rm /etc/ssl/certs/java/cacerts`

`update-ca-certificates --fresh`

check with if you change the key file type are changed to jks
`keytool -list -cacerts`

if you need to enter a password on jks keystore simply press enter but on pkcs12 the password is changeit

**_method 2_**
the second method is to add a parameter in your startup script 'nzbhydra2'
this is the original one
java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/nzbhydra2/data/logs -Xlog:gc*:file=data/logs/gclog-2019-01-29_19-34-07.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /opt/nzbhydra2/lib/core-2.3.3-exec.jar --datafolder /opt/nzbhydra2/data in folder /opt/nzbhydra2

and this is my test script
java -Djavax.net.ssl.trustStorePassword=changeit -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/nzbhydra2/data/logs -Xlog:gc*:file=data/logs/gclog-2019-01-29_19-34-07.log::filecount=10,filesize=5000 -Dspring.output.ansi.enabled=ALWAYS -jar /opt/nzbhydra2/lib/core-2.3.3-exec.jar --datafolder /opt/nzbhydra2/data in folder /opt/nzbhydra2

i simply add the password of the keystore file and he use it for all request but for the moment gclog dont rotate like on original script

**Comment by theotherp** [comment]
Wow, a bug report with two proposed solutions. Thanks for the detailed information. 

I'll see what I can do.

**Comment by theotherp** [comment]
What happens when disable the setting "Use packaged cacerts" and you start the program without any special commands?

**Comment by Elenedeath** [comment]
i launch without anything special than add the line i did on method 2.

i try to off "use packaged cacerts" and have the error like before.

i try the python wrapper and add the line and work like normally without anything special, simply "./nzbhydra2wrapper.py"

line 387 to 394
    java_arguments = ["-Xmx" + xmx + "M",
                      **"-Djavax.net.ssl.trustStorePassword=changeit",**
                      "-DfromWrapper",
                      "-XX:TieredStopAtLevel=1",
                      "-noverify",
                      "-XX:+HeapDumpOnOutOfMemoryError",
                      "-XX:HeapDumpPath=" + os.path.join(args.datafolder, "logs")
                      ]

**Comment by theotherp** [comment]
I tried it with this https://jdk.java.net/11/ on my local ubuntu VM and it runs fine.

**Comment by Elenedeath** [comment]
strange i use OpenJDK with J9 maybe debian 9 not including patch on ca-certificates

**Comment by theotherp** [comment]
That password is the default password for the java keystore which is used by Java by deafult.. I don't understand why explicitly setting that would help.

**Comment by Elenedeath** [comment]
yes it's the default one but the argument arent pass by default on debian and the error occur.

try simply to launch without password
`keytool -list -cacerts`

if like me you got 0 key

try the same command but with the changeit password and you got 151 key.

**Comment by Elenedeath** [comment]
i think i install a vm for try on another debian on confirm that this is a debian bug

**Comment by Elenedeath** [comment]
i try on a debian vm and my test work without touch something but when i check the keystore,i have jks by default.
on my nas debian 9 i have pkcs12 by default, strange but dont touch your code. i apply method 1 to my nas.
thanks for the try and your time, i close the issue

**Comment by theotherp** [comment]
Right, thanks for the info.
