### ISSUE TITLE
Feature request: create FreeNAS plugin

### ISSUE THREAD

**Issue by 2fst4u** [theotherp/nzbhydra2#296]
* What do you want to happen?

It would be awesome if a FreeNAS 11.2 plugin could be created.

* If not clear, why do you want it?

There is a massive userbase of FreeNAS user, many of which prefer to use plugins for ease of installation and maintenance.

* Do you think it's something only you need or something that might be popular?

I believe this will be popular as many of the current plugins are already related to sabnzbd, sonarr, radarr, CouchPotato etc. These same users would love to use hydra.

* If need be explain the use case.

Now that FreeNAS 11.2 plugins are much easier to create and maintain, it would be really awesome if someone were able to do this.

**Comment by insanepoet** [comment]
Saw the help wanted tag, started looking into how to build a plugin for FreeNAS, downloaded an ova to fire it up in ESXi, went to make a repo for it and oh look it already exists:

https://github.com/stefanschramek/iocage-plugin-nzbhydra2

If you are unsure how to install an unofficial plugin it is described near the bottom of the documentation here: https://www.ixsystems.com/community/resources/create-an-unofficial-iocage-plugin.99/

The json file you will need to install is located at:
https://raw.githubusercontent.com/stefanschramek/iocage-plugins/master/nzbhydra2.json

Essentially it looks like ssh in and run: (untested, replace the ip address with your own)
`sudo iocage fetch -P -n https://raw.githubusercontent.com/stefanschramek/iocage-plugins/master/nzbhydra2.json ip4_addr="em0|192.168.0.220/24"`

It seems as though it is working its way into the official plugins list as described in the development issues listed here: https://redmine.ixsystems.com/issues/32442

All in all it seems this issue can be closed.

**Comment by theotherp** [comment]
@insanepoet Thanks for the assistance!

@2fst4u Could you please verify this is working?

**Comment by 2fst4u** [comment]
Ah it'll take me a while as I'm not that proficient with these things so
you may as well close this and if it doesn't work I'll come back with why.

**Comment by famewolf** [comment]
If you are using the legacy nzbhydra version 1 plugin/jail and wish to upgrade it to nzbhydra version 2 a fellow did an excellent step by step walkthrough here and it worked great a couple of days ago:  https://www.reddit.com/r/freenas/comments/9fj19p/install_nzbhydra2_on_freenas/ecl0d9b/
