### ISSUE TITLE
Allow user to be set from X-Forwarded-User

### ISSUE THREAD

**Issue by Alives** [theotherp/nzbhydra2#297]
Using basic-auth if X-Forwarded-User is set, use that as the user and don't prompt for auth, assuming a proxy has set this and already authed the user.

**Comment by theotherp** [comment]
Did you read the wiki entry for reverse proxies? It works for me.

**Comment by Alives** [comment]
Yeah I get the user passed through, but auth fails.  I'm saying, if X-Forwarded-User is passed, should hydra still try to auth or should it just accept that user as authed already?

**Comment by theotherp** [comment]
I think I confused that header with something else. I'm not sure if that should work as most of that stuff is handled by the underlying framework. I'll see if I can find some time on the weekend.

**Comment by theotherp** [comment]
I barely find any documentation on that header. Are you sure that's the right one?

**Comment by Alives** [comment]
Yeah I think I should be able to add a username that matches the one from the proxy in hydra and it should work... nagios3 does it this way at least... https://github.com/bitly/oauth2_proxy/blame/master/README.md#L216

**Comment by theotherp** [comment]
As I said that works for me. That has nothing to do with X-Forwarded-User as far as I can tell.

Your mention of the header confused me.

Please describe your setup in more detail.

**Comment by theotherp** [comment]
I just checked to be sure. I enabled basic auth in NZBHydra and in nginx. I configured nginx as described in the wiki. I only authenticate once to nginx and Hydra uses the provided authentication header.

If you mean that I should just read the x-forwarded-user header when no authorization header is provided, I don't think that's how it works.

**Comment by Alives** [comment]
Yeah I got it working.  https://github.com/bitly/oauth2_proxy wasn't setting the password in the auth digest, just the user.  I had to use a flag instead of the setting in the conf file to get it to work (-basic-auth-password).

**Comment by theotherp** [comment]
Great. Thanks for letting me know.
