### ISSUE TITLE
after update to .11 i can´t access nzbhydra2 anymore

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#30]
restarted hydra and my system, still the same problem. how can i downgrade to .10?
error message in my browser:
`Unexpected error when client tried to access path /. Error message: Zugriff verweigert`

**Comment by theotherp** [comment]
Just download the release from https://github.com/theotherp/nzbhydra2/releases/tag/v1.0.10

But weird, that bug "should have" appeared in .10

**Comment by theotherp** [comment]
Do you have basic auth enabled?

**Comment by theotherp** [comment]
Works fine for me, I installed v10, updated to v11, everything works fine.

**Comment by Hobbabobba** [comment]
Downgrade to .9 fixed it.
I am using the FORM auth.

**Comment by theotherp** [comment]
Hmmm

**Comment by theotherp** [comment]
Everything still works fine for me in 1.0.11. Cannot reproduce that issue even with form auth.

**Comment by Hobbabobba** [comment]
update from ,9 to .11 worked! now everything is ok.
