### ISSUE TITLE
Disable SNI non-functional with Java 11

### ISSUE THREAD

**Issue by Alamei** [theotherp/nzbhydra2#302]
This issue is effectively an extension of #272. I'm not entirely sure if it's more appropriate etiquette to start a new thread on the same issue or to necro a closed thread in these instances.

Since Java 11 support was tentatively announced with 2.3.0 a short while back, but the Disable SNI feature still requires Java<=10 (my tests are showing success with 10.0.2+13 and failure with 11.0.2+9), I think it might be good to put a note in the readme or changelog letting people that rely on that particular feature know to keep Hydra pointed at an older JDK/JRE for the time being.

I'm assuming that it's just a compatibility issue with Java 11 causing the errors based on your responses in #272, but if the issue was theoretically resolved and is only failing on my configuration, let me know and I can provide more info to help troubleshoot.

**Comment by theotherp** [comment]
Thanks for reporting this. I'll take a look when I have time. This isn't something I can test automatically. I'll have hopefully have a better general solution soon.

**Comment by theotherp** [comment]
Alright, I had a fix but that caused some other problems.

**Comment by Alamei** [comment]
Patch verified working with AOJDK 11.0.2+9 on my configuration. Thank you for the resolution!

**Comment by theotherp** [comment]
Great!
