### ISSUE TITLE
NZBIndex requires set cookie 'disclaimer'

### ISSUE THREAD

**Issue by samkatakouzinos** [theotherp/nzbhydra2#303]
NZBIndex fails ongoingly.

When searching in browser you are asked to accept a Disclaimer. 
Agreeing sets a cookie 'disclaimer' in my browser. 
Searches through browser then work correctly.

I don't believe this request is handled correctly.
I also don't know if this is known to the developer.

<details>
  <summary>Image of Cookies set after clicking 'I Agree'</summary>

![](https://i.imgur.com/nJ3piTg.png)

</details>

**Comment by theotherp** [comment]
It doesn't work one way or the other. See #286
