### ISSUE TITLE
HistoryCleanup task causes SQL exception

### ISSUE THREAD

**Issue by TChilderhose** [theotherp/nzbhydra2#305]
When the HistoryCleanup/"Delete old history entries" task runs (automatically or manually) it throws a SQL Exception

```
org.h2.jdbc.JdbcSQLException: Column "ID" must be in the GROUP BY list; SQL statement:
select max(t.id) from SEARCH t where t.time < ? order by id desc [90016-197]
```

Version: 2.3.5
Docker Container: theotherp/nzbhydra2
Platform: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-45-generic x86_64)
Debug info ZIP: [nzbhydra-debuginfos-2019-02-06-11-25.zip](https://github.com/theotherp/nzbhydra2/files/2837240/nzbhydra-debuginfos-2019-02-06-11-25.zip)

Let me know if you need more info!

**Comment by theotherp** [comment]
Oops, that wasn't supposed to be part of the release.
