### ISSUE TITLE
Sonarr/Radarr blacklisting doesn't work

### ISSUE THREAD

**Issue by hacktek** [theotherp/nzbhydra2#306]
It seems like Hydra changes the NZB ID (or something similar) which breaks Sonarr/Radarr blacklisting and causes it to keep re-downloading the same, broken, releases.

Is there a workaround for this? I'd really like to avoid having to add the indexers manually as Hydra seems to do a much better job at caching and overall responsiveness than directly querying the indexers within Sonarr/Radarr.

This is on the LSIO docker.

Thanks

**Comment by theotherp** [comment]
It does not change the ID. As you didn't provide the debug infos as
requested and no further data or examples I can only guess what's happening.

Duplicates are recognized usually. Are you sure it's actually the very same
release that's being downloaded?
