### ISSUE TITLE
Upload/Import CSV or Txt file?

### ISSUE THREAD

**Issue by ellis1884** [theotherp/nzbhydra2#307]
Feature Request: 

Would it be possible to upload/import a string of titles whether it is consumed via CSV or Txt file?

For example if I have a list of various titles I would like to search, is there any way to do a mass search of them all instead of manual one-by-one.

cheers

**Comment by theotherp** [comment]
You could parse it with python (or anything else) and open the browser to
the appropriate URL.

No function to import such a list or will be implemented.

**Comment by ellis1884** [comment]
Ok I will investigate that option, thank you for the reply and thanks for the great application!
