### ISSUE TITLE
Checking for caps isn't counted towards api hit limit

### ISSUE THREAD

**Issue by markheloking** [theotherp/nzbhydra2#308]
What I expect to happen:
When checking caps for an indexer I expect the api hits to be counted towards the api hit count limit.

What happens:
The checking caps hits to the api of the indexer are not counted, leading to too many request errors from that indexer later in the day, disabling this indexer indefinitely (until manual activation by the user again).

Running version 2.1.4 on Windows 10 x64 build 1809

**Comment by theotherp** [comment]
Please post the debug infos zip as requested in the issue template you
chose to ignore.

**Comment by markheloking** [comment]
I didn't choose to ignore it (entirely), it's just impossible to properly reproduce today, so I have to wait for tomorrow to re-enable the relevant indexers and have it go wrong again. I'm suspecting that maybe hydra doesn't properly count the api hit count as it seems all of my free indexers (25 accesses and the like) trip with "too many requests". I'll investigate a bit further and provide debug logs in the coming days.

**Comment by theotherp** [comment]
The indexer is not disabled indefinitely, just for a certain time. After that it's reenabled automatically. While I understand that the handling of the API hits could be improved at the second day everything should be working as expected. If it does not then the configuration may not be correct. 

Indexers handle their API hit limits differently and usually don't say how. Some reset them at a certain time of the day. some have a rolling window. You might want to contact TR's admins how they've implemented API hits.

I see no indication that API hits are not registered or handled apart from the special case with caps checks.

**Comment by markheloking** [comment]
So then the caps check is still uncounted. Not a major issue, but rather annoying. What's the time period the indexers are disabled for? There is no indication of this (or the "currently used counter" per indexer) in the user interface. Would be a nice addition the stats->indexers page imo.

Thanks for the great software! It's rather magical how good it's working.

**Comment by theotherp** [comment]
The log says how long the indexer is disabled. The time increases with every error until the indexer is connected successfully.

**Comment by theotherp** [comment]
The indexer statuses page should actually show the error and until when the indexer is disabled:

![screenshot](https://i.imgur.com/gVFFGyv.png)

**Comment by markheloking** [comment]
Thanks for the fix!
