### ISSUE TITLE
Nzbget Connection Check failed

### ISSUE THREAD

**Issue by rjulie95** [theotherp/nzbhydra2#309]
## How to create a bug report

[nzbhydra-debuginfos-2019-02-09-11-40.zip](https://github.com/theotherp/nzbhydra2/files/2847713/nzbhydra-debuginfos-2019-02-09-11-40.zip)

When i try to update the Nzbget connection, i have this error

![image](https://user-images.githubusercontent.com/8410772/52519693-b4e60700-2c5f-11e9-8a35-c31ca51eff49.png)

I update my post with this information

hydra and nzbget running in docker, with Linuxserver.io
Nzbget is in version 20.0
Hydra is in version 2.3.7
Thank

**Comment by theotherp** [comment]
Hopefully fixed in 2.3.8 which should be built by LSIO soon.

**Comment by rjulie95** [comment]
Thank you

**Comment by rjulie95** [comment]
The version 2.3.9 Fix this issue

Thank
