### ISSUE TITLE
Nzbhdra2 no longer starts/loop after update from 2.3.6 ->2.3.x

### ISSUE THREAD

**Issue by silkw0rm** [theotherp/nzbhydra2#310]
After updating from 2.3.6 to 2.3.7 I'm getting this error message and nzbydra won't start up or load the GUI.

```
Feb 09 12:49:57 sr-imx6 python[3166]: 2019-02-09 12:49:57.785  WARN --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.be
ans.factory.BeanCreationException: Error creating bean with name 'securityConfig': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-linux-arm_32 in java.library.path
Feb 09 12:49:57 sr-imx6 python[3166]: 2019-02-09 12:49:57.806  INFO --- [           main] org.nzbhydra.NzbHydra                    : Shutting down
Feb 09 12:49:57 sr-imx6 python[3166]: 2019-02-09 12:49:57.837  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...

```

I'm running Debian 9 and have installed Java through APT.

Java version is:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK Client VM (build 25.181-b13, mixed mode)
```

I've also tried to manually upgrade to v 2.3.8 by copying the new binaries manually but getting same error anyway. Am I lacking some library in my Java installation or what could be the issue here? 

Thanks in advance.

**Comment by theotherp** [comment]
I'm having bad luck lately. Whatever I do to improve on things I break others or make it worse for some...

**Comment by theotherp** [comment]
See if 2.3.9 works.

**Comment by jalmansor** [comment]
> I'm having bad luck lately. Whatever I do to improve on things I break others or make it worse for some...

This is why I like containers, then you don't have these issues.
