### ISSUE TITLE
NZBGeek handshake alert:  unrecognized_name since 2.3.9

### ISSUE THREAD

**Issue by Inervo** [theotherp/nzbhydra2#312]
Hello,

NZBHydra2 auto-updated to v2.3.9. Since then, NZBGeek doesn't work anymore, with an error handshake alert:  unrecognized_name
Even though i have nzbgeek.info in the Disable SNI.

I've tried to disable the Verify SSL certificate. It still doesn't work.

I don't know what happened, or how to fix it. Can you please help me?

Here's the debug log:
[nzbhydra-debuginfos-2019-02-09-21-18.zip](https://github.com/theotherp/nzbhydra2/files/2848236/nzbhydra-debuginfos-2019-02-09-21-18.zip)

**Comment by theotherp** [comment]
My fault, sorry.
