### ISSUE TITLE
NZBStars (spotweb) fails to get caps with error handshake_failure

### ISSUE THREAD

**Issue by markheloking** [theotherp/nzbhydra2#313]
When I try to check caps for NZBStars, it errors out saying:

```
Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer NZBStars Spotweb. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

Maybe this is related to #312?

I tried adding `nzbstars.com` and `www.nzbstars.com` to `Disable SNI`, but it didn't help/matter.

Running version 2.3.10 on Docker for Windows using the [linuxserver/hydra2](https://hub.docker.com/r/linuxserver/hydra2) image.

It used to work (I know for a fact it worked in version 2.1.7 on Windows 10 native at least).

Log: [nzbhydra-debuginfos-2019-02-10-00-17.zip](https://github.com/theotherp/nzbhydra2/files/2848366/nzbhydra-debuginfos-2019-02-10-00-17.zip)

**Comment by theotherp** [comment]
Please try with 2.3.11. Works for me.

**Comment by markheloking** [comment]
No, this is still a problem for me. Can I help you replicate this?

**Comment by murac** [comment]
Ok so i'm seeing a similar error when trying to upload to sabnzbd. its a fresh install in a Ubuntu 16.04 LXC container

```
An error occurred:
500: Internal Server Error

Path: /internalapi/downloader/SABnzbd/categories

Message: I/O error on GET request for "https://sabnzbd.domain/api": Received fatal alert: handshake_failure; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

i'm on the latest version.
note i have also seen the error mentioned above but after a couple retried, the caps check is successful

**Comment by murac** [comment]
sorry to hijack, but i switched to the wrapper and set the enableECC to true and defined the protcols. now i can upload to sab...im on openjdk 8 btw

```
 "-Dcom.sun.net.ssl.enableECC=true",
                       "-Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2"
```

**Comment by theotherp** [comment]
Thanks for the info.

**Comment by theotherp** [comment]
@markheloking Please try with the latest container (2.3.13).

**Comment by markheloking** [comment]
Still broken in build 2.3.15.

**Comment by theotherp** [comment]
Yeah, why not...

**Comment by markheloking** [comment]
[nzbhydra-debuginfos-2019-03-03-12-48.zip](https://github.com/theotherp/nzbhydra2/files/2923059/nzbhydra-debuginfos-2019-03-03-12-48.zip)

This is on version 2.3.15. Sorry it took so long.

**Comment by rg9400** [comment]
I am having this issue as well on version 2.5.5 on Windows 10 native. 

It is only happening with a few indexers (Miatrix, NZB-Tortuga), and the websites for all these indexers work. They used to work before, and I can't figure out if anything changed on their end to make my config not work. The exact error is below (same as OP). I have also attached my debug logs. 

[nzbhydra-debuginfos-2019-04-22-11-15.zip](https://github.com/theotherp/nzbhydra2/files/3104038/nzbhydra-debuginfos-2019-04-22-11-15.zip)


```
Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer miatrix. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

**Comment by erenfro** [comment]
So, the problem is definitely with how nzbhydra2's binary is working. It's specifically disabling TLS EC certificates, which is unreasonable and kinda bad. 

When I switched to the nzbhydra2wrapper.py it doesn't do that specifically, and OpenJDK 11 enabled and supports ECC TLS.

**Comment by theotherp** [comment]
The binary is just the compiled python script, I don't see how that would
make a difference. Are you sure you're using the latest binary?

**Comment by theotherp** [comment]
Might also be that the binary in the the repo is outdated. Will check next
week.

**Comment by theotherp** [comment]
I've just released a version with better debugging of SSL issues.

Please do the following:
1. Update to 2.11.1
2. In the main config enable the logging marker "HTTPS"
3. Restart Hydra
4. Execute the caps check for nzbgeek
5. Create the debug infos zip and post them here again
6. Disable the logging marker again and restart Hydra (otherwise it will write a huuuge file in the logs folder).

Thank you.
