### ISSUE TITLE
Version 2.3.11 generates Java protocol_version errors when connecting to webserver that does not support the deprecated TLSv1.0 protocol.

### ISSUE THREAD

**Issue by alron** [theotherp/nzbhydra2#314]
If the webserver that Hydra connects to does not have TLS 1.0 enabled, hydra generates java protocol_version errors.

Enabling TLS 1.0 on said webserver causes these errors to go away.

Running in docker on Ubuntu 18.04.1 LTS.

Webserver is nginx 1.14.0-0ubuntu1

This works:
 ssl_protocols TLSv1.2 TLSv1.1 TLSv1; 

This generates protocol errors:
 ssl_protocols TLSv1.2 TLSv1.1;

The only change on my side between a working and broken hydra2 was hydra2 update. You may wish to add more than just TLSv1.0 into the allowed protocol list.

**Comment by alron** [comment]
Just as a side note. This appears to break the automatic update functionality of hydra2.

Screenshots attached. When hitting update page it does not list current or latest versions. Generates protocol_version error in console log.

<img width="1409" alt="screenshot 2019-02-10 12 45 25" src="https://user-images.githubusercontent.com/566136/52539331-cef01a00-2d31-11e9-8ce3-880f901bc345.png">
<img width="2001" alt="screenshot 2019-02-10 12 45 42" src="https://user-images.githubusercontent.com/566136/52539333-d4e5fb00-2d31-11e9-9d19-beb96e3e6b4c.png">

**Comment by theotherp** [comment]
Jesus fucking christ, I hate SSL.

**Comment by theotherp** [comment]
Yeah, having broken the update function for every instance out there is pretty bad.

**Comment by alron** [comment]
SSL and TLS are a total kick in the junk at times, especially when using Java (I'm not bashing on it, I've seen this kind of crap happen at work).

**Comment by theotherp** [comment]
Yeah, no idea how others manage to get it working properly. The times when I had everything working on my three machines some users reporting it not working at all on their machines. I'm about to give up. SNI is the only thing that I can't get to work and it only affects one or two indexers. My previous workaround mostly worked for most users, that has to be good enough.

**Comment by alron** [comment]
This is the first major problem I've had with SSL related to Hydra. I'm by far not the best representative of the common user, but... worked for me, and I've got 17 indexers configured.

**Comment by theotherp** [comment]
That's good to hear. It worked for me and for most people but unfortunately not for all. And every time I tried to improve it I actually made it worse, so as I said I should just keep it as it is (was).

**Comment by theotherp** [comment]
Well, at least now I have a reason to use the news mechanism to show news for certain versions which I implemented two years ago for cases just like this :-D
