### ISSUE TITLE
Another "suddenly stopped working" post, lol

### ISSUE THREAD

**Issue by STaRDoGG** [theotherp/nzbhydra2#317]
was running fine a day or 2 ago, then I tried to do a search today and started getting (your favorite, lol) SSL errors.

I wasn't even able to see the currently installed version or latest version on the Updates page.

I pretty much knew my Java installation was fine, but just for shits n grins, uninstalled and reinstalled it, still the same problem. While doing a search I'd get this error for all indexes:

`Server returned: javax.net.ssl.SSLException: Received fatal alert: protocol_version`

Came here to grab the latest (Windows) version to try a re-install (couldn't tell if I already had this latest version 2.3.12) but installed it anyway. That solved the issue of not being able to see the version on the Updates page, but still having errors trying to search. Now the error for all of them is:

`Error while communicating with indexer (index name). Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

Hope ya have a few strands of hair left to rip out. ;p

P.S. Would it be possible to add a button/link on the Indexes page to Enable All / Disable All? Hydra's automatically disabling them all after each failed search, and I have to go back and manually enable a ton of them each time, even just when testing.

**Comment by albino1** [comment]
You should post the debug logs.

**Comment by theotherp** [comment]
You may choose to enable the option "Ignore temporary errors" in the Searching config.

Please update to 2.3.13 and update the EXE files. See if that helps.

**Comment by STaRDoGG** [comment]
Working again in 2.3.13, thanks!

**Comment by theotherp** [comment]
Great!
