### ISSUE TITLE
NZB Tortuga (free/signup indexer) javax.net.ssl.SSLHandshakeException (2.3.12, works on 2.3.6)

### ISSUE THREAD

**Issue by james-d-elliott** [theotherp/nzbhydra2#318]
Using linuxserver/hydra2. Today I updated from 2.3.6 to 2.3.12 and www.nzb-tortuga.com now fails with the following error: 

Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer NZB Tortuga. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Reverting to the image that contains the 2.3.6 install works fine without changing any configuration settings.

I think the cause is IPv6 related (maybe, would have thought overriding the hosts file, or a complete zone overwrite should have fixed it if so) since nzb-tortuga.com is the only one I'm having issues with, and it's the only one that  resolves any IPv6 address (nslookup). This may be related to the issues others are having. I'm also running mine over a OpenVPN tunnel which blocks IPv6 traffic. It may also be the linuxserverio image which I note uses a different openjdk (you have an open issue). 

I've done a few tests to see if I can figure out the cause of the issue such as:

* curl-ing their api with a t=caps (works fine from the container on 3.6.12)
* static /etc/hosts entries for the IPv4 addresses (no difference)
* revert to previous image (works, but old version)
* restarting everything

Debug Log Excerpt: https://hastebin.com/luruzitike.log

**Comment by james-d-elliott** [comment]
https://github.com/theotherp/nzbhydra2/issues/313 this indexer also has IPv6 records in DNS.

**Comment by theotherp** [comment]
Please wait for 2.3.13 to be built and try with that.

**Comment by james-d-elliott** [comment]
Yes that works for me on Tortuga. I'm closing but if you need help testing I'm more than willing.
