### ISSUE TITLE
can't search in hydra

### ISSUE THREAD

**Issue by adamcirillo** [theotherp/nzbhydra2#320]
After a while hydra can't search the indexers pops with this error

An error occurred:
500: Internal Server Error

Path: /internalapi/history/searches/forsearching

Message: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection

and then this error comes up afterwards

An error occurred:
500: Internal Server Error

Path: /internalapi/search

Message: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection

Java version is 8 update 201 64 bit running on windows server 2019
also the indexer fails to respond to api calls from sonar as well when this happens

here are the logs files

https://mega.nz/#!zkIwwa5b!GNtzMZkGAtH8pm7F0LVY7kQt3wBDvt9JLEWS04beAjc

**Comment by theotherp** [comment]
For some reason I cannot determine Hydra loses its database connection and cannot reestablish it. Is it possible that two instances are running or Hydra for some reason cannot access the database file?

Also one of your automation tools (I guess something comic related?) is executing invalid queries. Do you have anything like that running?

**Comment by nicolahinssen** [comment]
I also have this error, even when just opening the NZBHydra front page, it immediately pops up. It started happening after updating from 2.3.11 to 2.3.13.

**Comment by theotherp** [comment]
@nicolahinssen Your problem seems to be different. Apparently the database is corrupted. I recommend you shutdown hydra, restore the database file from your latest backup and start Hydra again.

**Comment by nicolahinssen** [comment]
Ah okay, just coincidence then because the error is exactly the same. But will try and report back. Thx.

**Comment by nicolahinssen** [comment]
@theotherp Deleting the database and restoring an earlier backup solved my problem, thanks!

**Comment by adamcirillo** [comment]
I have mylar running for comics

**Comment by adamcirillo** [comment]
I just tried stopping mylar for a while the same issue still happened anyway

**Comment by theotherp** [comment]
Yeah, that was just a side observation.
