### ISSUE TITLE
Can't connect to Radarr/Sonarr on Docker in Synology NAS

### ISSUE THREAD

**Issue by raulkeats** [theotherp/nzbhydra2#321]
*What do you expect to happen? What does happen?*
Connect Hydra to radarr/sonarr; Return an error like below (Same error for radarr/sonarr):

![capture d ecran 2019-02-15 a 20 25 44](https://user-images.githubusercontent.com/16153586/52879721-2f32f180-3160-11e9-8d8c-67a5c3e438c5.png)

* Have you searched for this problem? You don't have to answer, just make sure.
Yes i have in the issue list.

* Can the problem be reproduced? How?
absolutely, on a Synology, with docker, set sonarr/radarr/hydra2 and try to connect them

* If you use a docker container please tell me which one.
I use Docker on Synology NAS

The more information you provide up front the higher the chance that I can help you.
In addition: 
- I use host network in the docker;
- After investigate the log in sonarr/radarr&Hydra2, it seems that Hydra receive the request but as it's a empty request, hydra search a result and ofc return nothing. I think this is the root issue.

[nzbhydra-debuginfos-2019-02-15-20-25.zip](https://github.com/theotherp/nzbhydra2/files/2870547/nzbhydra-debuginfos-2019-02-15-20-25.zip)

**Comment by theotherp** [comment]
Sonarr and Radarr usually don't search for specific releases but just do update queries for the latest releases and see if there's anything interesting. You have only two indexers which both don't support "empty" queries so neither indexer is selected for the search. You'll need to get at least one "proper" indexer like Tabula Rasa, Drunken Slug or whatever. [Here's a good list](https://old.reddit.com/r/Usenet/wiki/indexers) to start.

**Comment by h45rd** [comment]
I cannot verify as it is currently down, but afaik the anizb (the only indexer you have configured for API searches in Hydra) API does only support direct queries, no newznab style general category browsing.
If you want to use Sonarr and Radarr for "release watching", you need to add an indexer which supports this style of browsing.

**Comment by raulkeats** [comment]
Oh Ok ! Thanks to answer me and sorry to disturb you.
Good luck for the next.

**Comment by theotherp** [comment]
All good, no worries.

**Comment by raulkeats** [comment]
I confirm, it work perfectly with another Indexer. Thanks for your reactivity.
