### ISSUE TITLE
NZBHydra.yml Corrupts Repeatedly

### ISSUE THREAD

**Issue by rutskiuk** [theotherp/nzbhydra2#322]
I'm not sure whether this counts as a fault or a feature request.

While experiencing electrical problems I have had multiple power outages and I have found that the only app that is guaranteed to fail to open after the reboot is NZBHydra2. This means that multiple times a day I have to restore a copy of the nzbhydra.yml from the backups folder back into the data folder.

Is there anything I can do to avoid having to restore this file on every reboot (aside from the electrical supply being fixed) or is it possible that once NZBHydra2 finds that the yml file is unreadable it just automatically retrieves the most recent backup?

Windows 10
Version 2.3.14

**Comment by theotherp** [comment]
That's a problem that was actually reported before but I've never been able to reproduce it.

Please do the following:

- Enable debug log level for the log file
- Enable the logging marker "Config file handling"
- The next time your config is corrupted send me a) the corrupted log file and b) your debug infos ZIP

**Comment by rutskiuk** [comment]
Thanks, I've updated the config (I did pause in case the latest update fixed the problem but it didn't)

**Comment by rutskiuk** [comment]
OK, so I have had the issue again today after a number of power cuts.
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/2922189/nzbhydra2.log)
Is this the file you are looking for?

**Comment by theotherp** [comment]
Please check the logs folder. Send me any log file it may contain.

**Comment by rutskiuk** [comment]
The log files come to 569MB which is more than I can attach here. nzbhydra2.2019-03-01.log alone comes to 20MB. I also have files such as gclog-2019-03-01_18-06-49.log.0.current and wrapper.log
I haze tried zipping the folder but that still comes to 110MB.

**Comment by theotherp** [comment]
Upload the zip to https://uploadfiles.io/ and send me the link. Ignore the wrapper.log and the .current file

**Comment by rutskiuk** [comment]
Ahh superb, here we go: https://ufile.io/2qoyu

**Comment by theotherp** [comment]
Unfortunately you didn't configure the logging as described above (no debug level, etc).

Not sure if that would've helped, though. I don't see at what point Hydra crashed. 

Anyway, with debug level your log files would be ginormous because you're constantly hammering Hydra with TV searches. Do you download every TV show that was ever released? I mean, it doesn't matter, Hydra should not (and normally does not) corrupt just because it's used a lot.

So, I still don't know what's going on. Please configure Hydra as described above and also set the max log history to 3 days or so.

**Comment by h45rd** [comment]
What filesystem and underlying storage topology is Hydra writing to in your case? What mount options are you using?
Could make quite a difference, especially when it comes to reproducing the issue.

**Comment by rutskiuk** [comment]
You're pretty much right about the amount of TV shows and as I enabled Hydra for backlog searches SickChill will search not just for the episodes you want but for every show that doesn't meet the quality requirements so yes it gets hit pretty hard.
The file system is NTFS and the Hydra files are stored in My Documents/Usenet/NZB Hydra2
I did make the changes but I suspect that after a couple of settings corruptions it must have taken them back off again. I've reactivated them now and reduced the log history.

**Comment by theotherp** [comment]
With the changes made in one of my last updates searches should not cause a writing of the config file. My previous theory was that Hydra crashed while writing the config file but that is a very, very short duration and the chances of the system crashing right then are pretty slim. I don't have another theory.

The next time Hydra can't start check the data folder for the files nzbhydra.yml and nzbhydra.yml.bak. Check their content. Upload the logs. Do that *before* restoring Hydra and running it again.

Sorry for the inconvenience.

**Comment by h45rd** [comment]
Don't mean to be _that guy_, but if you value your data and server hardware: fix your PSU and get a UPS.
Doesn't cost the earth, but it can make a world of difference in avoiding data corruption :)

Have you run `chkdsk /v /f /r /b` on the affected drive after one of those hard resets?
The reason I believe this might not be a Hydra-specific problem: Many years ago I had a similar issue (only fb2k's config file being corrupted after a hard reset; didn't even have to be running/writing to it's config at the time of the crash for it to happen) that turned out to be hardware related (dying HDD with bad sectors was causing FS issues/silent corruption that in turn caused the fb2k issues..). 
Took me a while to figure that one out.. :)

**Comment by rutskiuk** [comment]
Thank you for your suggestion. I am fully on board with the UPS suggestion. I have two of them. The problem I have is electrical in the property, not power supply in the machine. I am in the process of moving out so the building can be rewired. I get where you're coming from with the chkdsk and I'll try that when I get the electric back however I have different machines running Hydra, one for film, one for TV, one for music, graphic novels and books and they all have the same problem with the yml file corrupting when I have an outage so I doubt it is a drive failure.

**Comment by h45rd** [comment]
Ah, got it.
You're right. Drive failure / dirty FS sounds unlikely when the same issue occurs on various instances over different physical machines.

Tried reproducing your issue by having a small script hammer a cloned Hydra instance and having it hard-reset at random intervals. Was not able to cause any corruption this way.
Can you actually provoke the issue by just force killing your Hydra instance, e.g. with `taskkill /f`?

**Comment by rutskiuk** [comment]
Here we go, another cut today and another corruption:
https://ufile.io/qwk3t

**Comment by theotherp** [comment]
So, I'm guessing you lost power at 2019-03-06 10:12:55.773?

And you have restored Hydra from the backup and now it's working again? The new log file should contain an error message about why specifically the config cannot be loaded.

I also asked to see the nzbhydra.yml and nzbhydra.yml.bak files which are corrupted but now it's too late.

Anyway, Hydra does not seem to write the yml file before / during the crash so there's really no reason why it would be corrupted. What error message do you get when you try to start Hydra?

**Comment by rutskiuk** [comment]
Fortunately I can retrieve the lost yml file

https://ufile.io/5i7ep

When I got back from work I had the error message across three separate screens, all machines had the same problem. The message is along the lines of the nzbhydra.yml cannot be read and to restore it from a backup. I'll get a screenshot of it next time.

**Comment by rutskiuk** [comment]
Here's a screenshot from the error today
![hydra](https://user-images.githubusercontent.com/25068977/54079024-bbea4e80-42cb-11e9-8e94-39895d62155a.png)

**Comment by rutskiuk** [comment]
I've had the same problems a few times so far this week. I just took a look through the log after restoring the yml file and reloading but it doesn't show anything about the instances when loading failed. I looked at the log before doing that and the log just stops, it doesn't show any errors with the subsequent attempts to start so I think the logging doesn't begin until the initialisation has already been validated. Is there anything else you would like me to try?

**Comment by theotherp** [comment]
Nah. I have no idea why it's happening. I'll install Hydra on a VM and have that shut down, perhaps I can reproduce it.

**Comment by theotherp** [comment]
Any improvements?

**Comment by rutskiuk** [comment]
Thank you for your help on this one, I've had my first power cut this week and it is still happening

**Comment by theotherp** [comment]
Have you taken a look at the corrupted file before restoring it? Can you send it and its backup?

I can't think of anything else to do...

**Comment by rutskiuk** [comment]
Here you go

https://ufile.io/hszxz

Maybe it's an odd observation but I've noticed I can never restore from the .yml.bak file, shouldn't I be able to restore from that?

**Comment by theotherp** [comment]
Hydra writes the backup file, reads it and verifies that it can be successfully read. If that is the case, it copies the backup to the actual data file. If on startup the actual file cannot be read it tries to retrieve the backup file.

If both are corrupt that means that Hydra successfully writes the backup file and then the actual file but both files still end up being corrupted. I have no idea how that could happen. The corrupted files are not empty but about as big as they should be, just filled with null characters.

[This comment](https://notepad-plus-plus.org/community/topic/13302/fix-corrupted-txt-file-null/62) describes the same issue with a different program. It also describes disabling the disk write cache. Can you try that out and wait for the next powerout?

Apart from being hard to to reproduce this is a problem hard to google for...

**Comment by rutskiuk** [comment]
Thank you, I have disabled that now, lets see how it goes 🤞

**Comment by theotherp** [comment]
See if that helps.
