### ISSUE TITLE
Cannot add NZBGeek - Handshake Alert

### ISSUE THREAD

**Issue by aybesea** [theotherp/nzbhydra2#325]
I'm trying to add NZBGeek and I'm getting the following error:

javax.net.ssl.SSLProtocolException: handshake alert: unrecognized_name

My log is attached. I see that you provided an "exception" for someone else (don't know what that is, but I guess I need one too?)

[nzbhydra-debuginfos-2019-02-17-17-06.zip](https://github.com/theotherp/nzbhydra2/files/2873468/nzbhydra-debuginfos-2019-02-17-17-06.zip)

**Comment by aybesea** [comment]
I just updated Hydra to the latest and all is good!

**Comment by theotherp** [comment]
Great.
