### ISSUE TITLE
Binsearch ERROR: Text '17-Feb-2019' could not be parsed at index 3

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [theotherp/nzbhydra2#327]
Release Version: v2.3.15, Using Wrapper [nzbhydra2wrapper.py] with Linux ver
OS: macOS 10.14.3

Logs: 
[nzbhydra-debuginfos-2019-02-20-04-01.zip](https://github.com/theotherp/nzbhydra2/files/2881089/nzbhydra-debuginfos-2019-02-20-04-01.zip)

Simply using the built in search with the bin search indexer throws me the error: ```Text '14-Feb-2019' could not be parsed at index 3```
Log Snippet: https://gist.github.com/XxUnkn0wnxX/31fb5fcba8392b4b1222fd7e7b8d63d8

**Comment by theotherp** [comment]
Works fine for me. Does this still happen for you?

Sorry for the super late response.
