### ISSUE TITLE
Turn off movie covers?

### ISSUE THREAD

**Issue by danjames92** [theotherp/nzbhydra2#328]
Is there a way to turn off movie covers permanently without having to untick the box every time?

I have no use for them.

PS sorry for posting this here, I'm not really where else I can ask, you should make a forum! 👍

**Comment by theotherp** [comment]
This is the right place to ask.

The display options are stored in the local storage of your browser. You likely have some kind of extension running that blocks that.

**Comment by danjames92** [comment]
> 
> 
> This is the right place to ask.
> 
> The display options are stored in the local storage of your browser. You likely have some kind of extension running that blocks that.

Thanks for the reply but I'm asking if it's possible to turn the covers off so they aren't displayed ever?

**Comment by theotherp** [comment]
That's what I was trying to say. You normally don't have to disable that option more than once. It works for me and most other users that you disable it once and it's stored in your browser. If it doesn't work for you it means that Hydra is unable to store the options in your browser for some reason. My guess is that you're running some adblocker, NoScript or running your browser in private mode.

**Comment by danjames92** [comment]
Yeah I do use incognito and I would rather not change that.

Couldn't an option be built into the UI to turn them off in all searches?
________________________________

**Comment by theotherp** [comment]
No. There's a downside with using incognito mode and you'll have to live with it. If you wish you can use an adblocker or something like that to block the movie covers from being displayed.
