### ISSUE TITLE
Looking for ways to improve performance

### ISSUE THREAD

**Issue by piejanssens** [theotherp/nzbhydra2#331]
Running docker on DSM with JVM memory of 1024MB. 
No throttling on DSM because of other processes. 
4 indexers active
 Current version: 2.3.15 

When I load up the home page it can take ~30s up to 1min sometimes to have the blue line reach the right side of the screen. I guess this indicates it is doing some sort of loading, what is it doing?
Most of the time when executing a search query before this blue loading loading is complete the search popup will show but it will never show any results from one of the indexers.

**Comment by theotherp** [comment]
Please enable debug log level, the logging marker for performance, use the
program a bit and then post the debug infos zip.

**Comment by piejanssens** [comment]
[nzbhydra-debuginfos-2019-03-10-09-54.zip](https://github.com/theotherp/nzbhydra2/files/2949241/nzbhydra-debuginfos-2019-03-10-09-54.zip)

**Comment by theotherp** [comment]
Your database is very large with more than one million searches. When the start page is opened Hydra tries to show the last 10 queries in the little history box next to the search field. That query just takes very long.  You can do your searches while the blue line is loading, there's no reason to wait for it.

**Comment by piejanssens** [comment]
You are saying that the SQL query to select the last 10 queries takes that long? 
That seems very odd, maybe a bug in the query or a missing index?

**Comment by theotherp** [comment]
Let me know if that helps.

**Comment by piejanssens** [comment]
Just tested, it's blazing fast (not kidding). Less than 1s.
Indexing is important 😉 

Thanks!

**Comment by theotherp** [comment]
I never expected this table to get so big that an index would be needed.
But there's no reason not to use one, so yes.
