### ISSUE TITLE
401 Authorization Required when using reverse proxy

### ISSUE THREAD

**Issue by TRaSH-** [theotherp/nzbhydra2#332]
Got nzbhydra running in a container with a reverse proxy (letsencrypt).
Have a ngnix with user/pass authorization.

Added nzbhydra to radarr and the test works
![image](https://user-images.githubusercontent.com/6155095/54090846-bb5bc180-4378-11e9-86ab-35e364d7fc21.png)

doing a manual search in radarr and it get's results.
when i want to send the nzb to nzbget i get a red cloud.

and the following errors i get from the radarr logs.
![image](https://user-images.githubusercontent.com/6155095/54090975-a1bb7980-437a-11e9-9ce7-8170ed848e91.png)

tried to add https://user:pass@domain.duckdns.org/hydra,
but that doesn't work in radarr.
even the test fails.

i checked the logs in nzbhydra but there's nothing in it because it's beeing blocked by ngnix before it can be reached i think.

This is my reverse proxy settings of the lets encrypt container,
```
# first go into nzbhydra settings, set the URL Base to /nzbhydra and restart the nzbhydra container

location ^~ /nzbhydra {
    # enable the next two lines for http auth
    auth_basic "Restricted";
    auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_nzbhydra hydra2;
    proxy_pass http://$upstream_nzbhydra:5076;
}

location ^~ /nzbhydra/api {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_nzbhydra hydra2;
    proxy_pass http://$upstream_nzbhydra:5076;
}
```

Accessing nzbhydra local works without any issues.

**Comment by TRaSH-** [comment]
solved it by removing the ngix authentication,
and use the auth from nzbhydra

**Comment by theotherp** [comment]
When nginx is configured as described in the wiki you can add basic auth to nginx and to Hydra. As long as both use the same username and password the authentication will be handled by nginx and the credentials will be forwarded to Hydra so that it can log it and you're not required to auth again.
