### ISSUE TITLE
DogNZB - unable to send any NZBs to SABnzbd ("NZBs for the following titles could not be downloaded")

### ISSUE THREAD

**Issue by agrudsky** [theotherp/nzbhydra2#333]
I am having a problem where NZBHydra is unable to send any NZBs from DogNZB to SABnzbd. When I click the Send to SABnzbd button in Hydra, I receive an error saying "NZBs for the following titles could not be downloaded: (NZB name)"

The log file then gives a fatal handshake failure:
`Error while downloading NZB from URL https://dognzb.cr/fetch/c2f0c95aabf7612225dc1206db313c28/<APIKEY>: Received fatal alert: handshake_failure`

This same error happens for every NZB from DogNZB. I am able to download NZBs fine, but sending them to SAB doesn't work for some reason. All other indexers I have are able to send to SABnzbd fine.

I have tried readding Dog as an indexer, along with restarting Hydra, neither of which have fixed the problem.

Thanks for any help in advance.

**Comment by theotherp** [comment]
Please follow the issue instructions and post your debug infos ZIP.

That error message indicates an SSL problem which is weird because Hydra can clearly access DogNZB to search.

You could try changing the "NZB adding type" for sabnzb in Hydra to "Send link" which will leave the downloading to sabnzbd.

**Comment by agrudsky** [comment]
Sorry about that, here's the ZIP. The error happens at line 2163.
[nzbhydra-debuginfos-2019-03-17-11-35.zip](https://github.com/theotherp/nzbhydra2/files/2975450/nzbhydra-debuginfos-2019-03-17-11-35.zip)


I tried changing the NZB adding type and it was able to grab and download the NZB fine in Sab.

**Comment by theotherp** [comment]
I'll see what I can see out. The debug infos not only provide more infos but they also hide sensitive data. Your original post contained your dog API key which you would not want to be public.

**Comment by agrudsky** [comment]
Appreciate the help; I will change the key as a precaution.

**Comment by theotherp** [comment]
I don't have an explanation. Have you tried setting the nzb adding type to "Send link"? You can also disable SSL verification for `dognzb.cr` in the main settings.

**Comment by agrudsky** [comment]
Yes, setting the adding type to Send link works. Guess I'll just stick with that in the meantime. I tried disabling SSL verification and the error persisted.

**Comment by mauirixxx** [comment]
Have you made any headway on this @theotherp ? I'm having the same issue as @agrudsky only I'm using nzbget (which looks like that doesn't matter). I'm running under CentOS 7 though - maybe that's part of the issue?

@agrudsky are you running under Linux or Windows?

**Comment by agrudsky** [comment]
@mauirixxx I'm running on Ubuntu 18.04.1.

**Comment by mauirixxx** [comment]
well now we just need someone who runs hydra under windows AND has an account with dog to see if they got the same issue :/

**Comment by D0MF** [comment]
I believe the SSL issue with dog is that some clients are trying to connect on less-secure protocols, and we only accept connections on tls1.2

**Comment by mauirixxx** [comment]
> I believe the SSL issue with dog is that some clients are trying to connect on less-secure protocols, and we only accept connections on tls1.2

would this be something on the operating system level, or is it an old java library being used?

I'm currently using OpenJDK v1.8.0_212-b04 which looks to be Java Runtime Environment 8, but I see there's a v11 available ... guess I'll try that soon.

**Comment by D0MF** [comment]
Should be on the application level, afaik? I'm doing lots of testing on it because people have reported problems with the main site (which I don't have access to) and not with the API (which I have full access to the front end of)

**Comment by mauirixxx** [comment]
it appears the Windows version of nzbhydra works just fine with dog.

I downloaded it to my desktop and ran it, and copied the config from my CentOS install. Did a search on both instances for a recently uploaded show, and sure enough manually clicking on the "Download NZB" link on the Windows instance nets me a valid .nzb file, where as clicking the same release on Linux nets me the dreaded null.nzb file @ 0 bytes.

I guess the next step is for me to try a different jdk. @agrudsky what java setup did you use in Ubuntu?

**Comment by agrudsky** [comment]
Well, I had a huge brainfart and mixed up Organizr (which I run on Linux) and Hydra (which I actually run on Windows). So please ignore my earlier comment, I am *actually* running Hydra on Windows 10 1809. Java 8 update 201.

**Comment by agrudsky** [comment]
Updated Java to update 211 and the error persists. @mauirixxx any luck with a different JDK?

**Comment by mauirixxx** [comment]
@agrudsky When I ran it on Windows - which worked for me - I'm on [Windows 10 1803](https://i.imgur.com/iRw40KW.png) and my Java control panel says I'm on version [10.0.2](https://i.imgur.com/aaSqpr7.png). Apparently my Java is out of date just like my Windows 👎 

I'm going to spin up a new CentOS virtual machine later today and take a stab at different JDK and report back.

**Comment by theotherp** [comment]
I'll consider this closes. Most if not all SSL related issues were resolved some time ago.

**Comment by agrudsky** [comment]
Yes, I believe this was fixed with the same resolution as #504. Thanks.
