### ISSUE TITLE
Hydra will not start, SQL issue - unRAID

### ISSUE THREAD

**Issue by hermy65** [theotherp/nzbhydra2#335]
This morning i noticed my hyrda was running but nothing was able to connect to it. I pulled up the log and saw this in it

> Unable to obtain connection from database: File corrupted while reading record: "type: 1". Possible solution: use the recovery tool; SQL statement:
> ALTER TABLE PUBLIC.SEARCHRESULT ADD CONSTRAINT PUBLIC.FKR5G21PDW3HHS1SEFVJY30TGMI FOREIGN KEY(INDEXER_ID) REFERENCES PUBLIC.INDEXER(ID) ON DELETE CASCADE NOCHECK [90030-199]
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> SQL State : 90030
> Error Code : 90030
> 
> Message : File corrupted while reading record: "type: 1". Possible solution: use the recovery tool; SQL statement:
> ALTER TABLE PUBLIC.SEARCHRESULT ADD CONSTRAINT PUBLIC.FKR5G21PDW3HHS1SEFVJY30TGMI FOREIGN KEY(INDEXER_ID) REFERENCES PUBLIC.INDEXER(ID) ON DELETE CASCADE NOCHECK [90030-199]

Tried rebooting it and that always happens. Restored from last weeks backup and that didnt help so i went back another week and got the same thing. Also, i have attached my full log
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/2979083/nzbhydra2.log)

**Comment by theotherp** [comment]
Please upload your database file and the one from the last backup to https://ufile.io/ and send me the link.

**Comment by hermy65** [comment]
Here you go - https://ufile.io/la04d

**Comment by theotherp** [comment]
Sorry, that took longer than expected. Please update manually to 2.3.19 and it should work again.

**Comment by theotherp** [comment]
Turns out, your old file was already corrupted but only the new database version failed to read it. Here's a fixed file: https://ufile.io/pt525
