### ISSUE TITLE
Weird error, please see logs attached on pastebin

### ISSUE THREAD

**Issue by antonispgs** [theotherp/nzbhydra2#337]
So i am running cloudbox and have nzbhydra2 in a docker container, yesterday i migrated the config to a new server and i started noticing a weird command in htop which led me to these logs, within app/logs
https://pastebin.com/KcFRWpwu
Can someone shed any light? The error that appears in htop is also attached
<img width="1898" alt="Screenshot 2019-03-21 at 10 18 10" src="https://user-images.githubusercontent.com/17891028/54745543-6dde2080-4bd2-11e9-9799-91e9336c1bc0.png">
I tried raising the JVM threshold to 1024 but then the error would just show xmx1024 instead of xmx512
Edit; I can't seem to find how to enable debug log level. Everything seems to be working normally otherwise.

**Comment by theotherp** [comment]
You can very likely ignore those errors. The "error" doesn't appear in htop but is just part of the command line of the process which spawns a lot of threads.
