### ISSUE TITLE
You are not allowed to visit that section.

### ISSUE THREAD

**Issue by alxlaxv** [theotherp/nzbhydra2#338]
Hello,

The blue popup seems to pop everywhere I'm going.
I am able to add indexers and do some searches but not to change the theme color for example.
I have full permissions on the config folder and running the docker container from linuxserver with the lastest.

Here are the logs: https://send.firefox.com/download/abfbd45902/#QFUc3_FRerRYDcD04sH6nw

Thanks for your help

**Comment by theotherp** [comment]
Disable CRSF protection in the main Hydra settings.

**Comment by alxlaxv** [comment]
Thanks!
