### ISSUE TITLE
Adding sabnzbd fails

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#339]
When adding SABnzbd it ends in an error:
```
The connection to the downloader failed: I/O error on GET request for "https://homeserver.com:12101/api": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Do you want to add it anyway?
```
I know it will work with http, but I want https. When I add it anyway, it won't work. I use exact the same login for NZBgeek, there it works.

How can I fix this?

I am running NZBhydra 2 2.3.19 on CentOS 6.

**Comment by theotherp** [comment]
You didn't post your debug infos ZIP as requested.

Try adding the domain to the list of "Disable SSL for..." in the main config. Or use an sabnzbd instance without SSL. If you use a reverse proxy that should be easy. If not I recommend doing so. There's no reason to use SSL if sabnzbd and Hydra are on the same machine.

**Comment by pven** [comment]
They are running on different machines on different locations, so I really want to use SSL for SABnzbd. When adding the host to the DISable-section, I can save that without errors. But after that SABnzbd is telling me the apikey is wrong. But I am very sure it is ok.

Where can I send the debug-info? (I don't want my history only.)

**Comment by pven** [comment]
Ah ... I used the wrong api-key from SABnzbd. I used the NZB key iso the API key, with the last one it works as expected.  :)

**Comment by theotherp** [comment]
That's a really weird error for that problem, but alright, as long as it
works now...

**Comment by pven** [comment]
Do you want me to check anything, or can this issue be closed?

**Comment by theotherp** [comment]
No, sorry, that's alright.
