### ISSUE TITLE
XXX results don't appear

### ISSUE THREAD

**Issue by garnwofi** [theotherp/nzbhydra2#341]
I'm using NZBHydra 2. Specifically, v2.3.19.

XXX is not shown as a category on the Search page. Also, if I search for "All" content which would return some XXX-category results, those XXX results are filtered out. In the nzbhydra.log file, for each indexer, there is a message like this. For example, for 6box:
`Rejected 61 search results from 6box for the following reason: In forbidden category`

NZBHydra 1 works fine.

[nzbhydra-debuginfos-2019-03-26-01-37.zip](https://github.com/theotherp/nzbhydra2/files/3006698/nzbhydra-debuginfos-2019-03-26-01-37.zip)

**Comment by theotherp** [comment]
In the category config change "Ignore results" from "Both" to "Never" or "None" or something like that.

**Comment by garnwofi** [comment]
You might want to document that adult content is filtered by default somewhere. It's not mentioned in documentation/readme.

**Comment by theotherp** [comment]
I can't possibly document everything there is to know without the documentation getting so long that nobody reads it. Most users don't seem to read the online help anyway.
