### ISSUE TITLE
Add the time-unit to the help

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#342]
When looking at the stats I saw values like 'Response time 1000', when checking the question mark I read 'Avg. response times: Response time is the time an API request takes, from start to completion of the web call'. I am quite sure the mentioned value is in milliseconds. But can you please add the time-unit to the text behind the question mark?

Yes, I know: very very low prio ;-)

**Comment by theotherp** [comment]
Sure :-)
