### ISSUE TITLE
Indexers disabled, okhttp error

### ISSUE THREAD

**Issue by deurk** [theotherp/nzbhydra2#344]
Getting the error `Could not initialize class okhttp3.internal.platform.Platform` with all my indexers no matter what I try.

Running latest 2.3.19 on docker.

Any quick fix available?

Thanks.

**Comment by theotherp** [comment]
Please follow the instructions and post the debug infos zip.

**Comment by deurk** [comment]
[nzbhydra-debuginfos-2019-03-31-10-56.zip](https://github.com/theotherp/nzbhydra2/files/3026364/nzbhydra-debuginfos-2019-03-31-10-56.zip)

**Comment by deurk** [comment]
Just to detail a bit what happened:

I noticed a couple days ago that nzbhydra2 was not returning any results anymore. After checking, the mentioned error was displayed in the logs. Re-enabling the indexer works but they get disabled as soon as a search is made.

I've been using the same setup for over a year, just updating application when I realize there is a new version. Reverting to older version did not solve the issue, reimporting an old configuration backup did not either.

Let me know if you need more information on my end and thank you for the time you can spend on this.

**Comment by theotherp** [comment]
What docker container is that? Pretty sure there's something wrong with its Java or OpenSSL installation.

**Comment by deurk** [comment]
```
root@a1e61cd72d5e:/$ java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (IcedTea 3.11.0) (Alpine 8.201.08-r0)
OpenJDK 64-Bit Server VM (build 25.201-b08, mixed mode)
```
What information can I give you? It's a custom container based of linuxserver.io one.

**Comment by theotherp** [comment]
See https://github.com/docker-library/openjdk/issues/289
