### ISSUE TITLE
/api/stats/indexers can be seen with authorization

### ISSUE THREAD

**Issue by RaymondSchnyder** [theotherp/nzbhydra2#345]
## How to create a bug report

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**
No Debug logs, there is no log i could give you except:
The only line that occurs is (I tailed over all files, this is the only thing happening on DEBUG):
![grafik](https://user-images.githubusercontent.com/12892508/55282659-1a45a280-5349-11e9-879b-2ac057f2ff7a.png)

* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
* What do you expect to happen? What does happen? 
No matter if i turn "Allow stats access" off or on, /api/stats/indexers can be seen external without authorization.
Also it shows apikeys (in failed requests to indexers) in that call. Very unfortunate

* Have you searched for this problem? You don't have to answer, just make sure.
I did, noone reported or i didnt searched enough

* Can the problem be reproduced? How?
1. try the call in curl on a remote host
2. see it for yourself
3. Disabling "Allow stats access" has no effect, switched between Login Form and Basic Auth, doesnt do anything. _(Weirdly tho, after i enabled basic auth on nginx, it worked. This must be weird caching on my end then)_

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
There is no error, this is a security problem.
* If you use a docker container please tell me which one.
https://github.com/hotio/docker-nzbhydra2
Currently using version 2.13.15

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

Workaround/FIX:

**Put your NZBHydra2 Instance behind a Basic Auth, as recommended by the wiki.
I thought the internal basic auth was enough, turns out its not.**

**Comment by theotherp** [comment]
Oop, sorry about that.
