### ISSUE TITLE
nzbindex - SSLHandshakeException

### ISSUE THREAD

**Issue by count00zero** [theotherp/nzbhydra2#346]
Hi,

before doing the whole debug-log thingy; I just want to know if I'm doing anything wrong or if there is a solution for this problem.
If not I will asap include debug-log!

`Error while communicating with indexer NZBIndex. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

Thanks in advance and BR,
count

**Comment by theotherp** [comment]
The easiest workaround is disabling SSL verification for that host in the main settings. But it's not the most secure. This kind of problem has been around for some time and it only affects some users and some domains. There's no other straight forward solution, unfortunately.

**Comment by count00zero** [comment]
I already did that ... i excluded nzbindex.nl, nzbindex.com, beta.nzbindex.nl, beta.nzbindex.com but I still reveive the same error ...

**Comment by theotherp** [comment]
Please post your debug infos. If you use a docker container, please tell me which one.

**Comment by count00zero** [comment]
[nzbhydra-debuginfos-2019-04-03-21-44.zip](https://github.com/theotherp/nzbhydra2/files/3040471/nzbhydra-debuginfos-2019-04-03-21-44.zip)
Hi, debug file is attached! Thanks a lot in advance and for your great work!!!

**Comment by theotherp** [comment]
Something is weird because SSL connections to a lot of sites are failing, not just NZBIndex. You can try installing OpenJDK11 and running Hydra with that. It should work with a regular OpenJDK version so I can't really explain that behavior.

Other than that I can only recommend running a docker container to prevent issues like this.

**Comment by theotherp** [comment]
Please also do the following:

- Download https://confluence.atlassian.com/kb/files/779355358/779355357/1/1441897666313/SSLPoke.class
- Go to its folder and run `java -Djavax.net.debug=all SSLPoke tvmaze.com 443` and write the output to a file (e.g. `java -Djavax.net.debug=all SSLPoke tvmaze.com 443 > sslpoke.txt`
- Post that file.

**Comment by count00zero** [comment]
Thanks again; the sslpoke log is attached (jdk11)...
[sslpoke.log](https://github.com/theotherp/nzbhydra2/files/3040713/sslpoke.log)

When I run hydra2 within jdk11 I get the following Error:
`Error while communicating with indexer NZBIndex. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

**Comment by theotherp** [comment]
That's weird. The connection to TVMaze works using that class but fails when using Hydra...

Ok, next try:

- Shutdown hydra.
- Go to its main folder and run this command `java -Djavax.net.debug=all -jar lib/core-2.3.21-exec.jar directstart > ssllog.log`
- Do another search, shutdown Hydra (you may have to kill the process) and send me the log file

Sorry for the inconvenience, this isn't easy to debug (as you can see)...

**Comment by count00zero** [comment]
Hey again and thank you for your time!!!
Curiously; when I started hydra2 that way => no error message when connecting to nzbindex!
[ssllog.log](https://github.com/theotherp/nzbhydra2/files/3044138/ssllog.log)

**Comment by theotherp** [comment]
Well, that doesn't make any sense at all. The log unfortunately doesn't provide any more info because the HTTPS connection succeeded.

Try replacing the binary file in the main folder with this one: https://ufile.io/p4gnw

**Comment by count00zero** [comment]
HI again!
Very interesting .... using this new binary and started from the cli, nzbindex works as well as when nzbhydra2 is started via `/usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /opt/nzbhydra2/lib/core-2.3.21-exec.jar directstart --nobrowser`

So I think my problem seems to be fixed; but what was the cause? :-o

**Comment by theotherp** [comment]
I tried out some SSL related parameter a couple of months ago and then reverted it but forgot to update the binary wrapper. As I had forgotten about the parameter I didn't include it in the command I posted. I looked at your previous debug infos and checked what parameters were used when you start Hydra. I'll release an update soon.

**Comment by count00zero** [comment]
Thank you very, very much!
You are my hero ;-)

BR, count

**Comment by count00zero** [comment]
Thank you very, very much!
You are my hero ;-)

BR, count
