### ISSUE TITLE
Binsearch results only inlcude collections and no single file posts.

### ISSUE THREAD

**Issue by mjmag** [theotherp/nzbhydra2#347]
Current Behavior: 
When searching Binsearch.info, the advanced "only show collections (hide individual files)" search option (`adv_col=on`) is used in the search URL NZBHydra generates:

`Binsearch: Calling https://www.binsearch.info/?adv_col=on&postdate=date&adv_sort=date&min=0&max=100&q=queryhere`

With this option enabled search results that are made up of a single .rar file will be excluded from search results.  For small files such as Ebooks, many/most of the posts only consist of a single rar file and no PAR files so they are not considered "collections" and thus don't get returned when NZBHydra searches Binsearch.

I am not sure if enabling this option is important for other categories, but for Ebooks it is makes binsearch almost useless and it is often the best/only indexer for these files.  

Desired Behavior in order of best to worst case:
    Create a checkbox in the Categories config tab that enables/disables the Collections (exclude individual files) option for binsearch results on category by category basis.
or 
  Create a checkbox in the Binsearch config popup that enables/disables the Collections (exclude individual files) option.
or
  Remove the "adv_col=on" substring from the binsearch.info search URL by default.

I noticed this when I got results from the basic Binsearch.info web search, but not from NZBHydra.  Removing the "adv_col=on" option from the search string returned the desired results.  For many books Binsearch will have results when other indexes (free or paid) come up empty.

**Comment by theotherp** [comment]
Yeah, that was a deliberate decision when I wrote the code because the option improved the quality of results for what I tested it with. But I never find anything I want on the raw indexers anyway, so what do I know...

I'll add an option to the binsearch config. Putting this in the category config would be kinda nice but doesn't really fit there.

**Comment by theotherp** [comment]
Actually, I tried that. Single file results don't contain infos about the file size. I don't support that and don't want to go through the lengths to change it, sorry. This will stay as it is.
