### ISSUE TITLE
You haven't enabled any access restrictions. Auth will not take any effect

### ISSUE THREAD

**Issue by Nobrumski** [theotherp/nzbhydra2#349]
I am sure I am just missing something, but I have been using NZBHydra2 for a while without issues. I went in to add an indexer and now if I try to do anything in config I get the popup leaving me unable to add or change anything.

"You haven't enabled any access restrictions. Auth will not take any effect"

I have no clue what it is referring to or what I need to fix. I don't have it setup for external access and never have. I migrated originally from v1 and this is the first time I have had this message. I can't change anything in the config due to the popup.

At this point I am just lost since I can't do anything and don't see any issues.

**Comment by theotherp** [comment]
Check your auth settings. You have selected either Basic Auth or Form login as auth but have selected not to restrict the search or the admin area.

If that is not the case switch the auth settings on and off or something and try to save then.

**Comment by kramer987** [comment]
i have actually noticed that enabling auth has some really bizarre side effects.  if i have multiple users and i make changes to the auth settings for each user, it is almost arbitrary which user will get the features enabled.  also, changing the password for one may change it for the other.  i've managed to get completely locked out of nzbhydra 3 times.  this could just be a google chrome issue and me not closing the browser out after restarting hydra.  but anyway, editing the yml file manually always fixes the issue.

**Comment by theotherp** [comment]
I haven't encountered any such issues. This may be hard to reproduce but I will do some tests.

**Comment by kramer987** [comment]
yea i mean its probably something weird on my end.  i wouldnt waste time on it until/if others mention it.

**Comment by Nobrumski** [comment]
Thanks this fixed it. I wonder if it flipped in an update or some update enforced the setting since I don't remember ever setting anything for authorization. I don't have it accessible off network and no one currently who I need to lock it access down so I swear I had it on none because I never had to enter a login.
