### ISSUE TITLE
Run docker container as non-root user

### ISSUE THREAD

**Issue by allanak** [theotherp/nzbhydra2#35]
Running your docker image just fine but noticed that it runs as root. Do you plan on providing the ability to run as a non-root user like your linuxserver image of v1?

**Comment by theotherp** [comment]
The linuxserver image is not by me. When I have time I'll take over their solution for that, yes.

**Comment by Cliffield** [comment]
You might want to take a look at "my" docker image. It is based on "lsiobase/alpine.python:3.7" (linuxserver image) and so far it seems to work with ubuntu 17.10 but not with unraid 6.4-rc18f.

https://hub.docker.com/r/cliffield/docker-nzbhydra2/
https://github.com/Cliffield/docker-nzbhydra2

**Comment by theotherp** [comment]
Thank you. Seems to be the same mechanism as used by linuxserver.io

**Comment by vertigo235** [comment]
you could try using the docker user command when you run the container 

https://docs.docker.com/engine/reference/run/#user

-u=1000:1000 , etc

**Comment by fryfrog** [comment]
My experience w/ a handful of docker containers is that on the *inside*, things run as nobody/nogroup and allow passing in the UID and GID to use, allowing it to appear on the outside to run as anything and internally to be not-root.

Sounds like a *bunch* of different, not great Dockers for this are popping up. :/

**Comment by theotherp** [comment]
linuxserver.io seem to be doing the most and most popular. I'll ask them to do an official non-official container with my support. That's probably best.

**Comment by fryfrog** [comment]
Exactly, I concur. :)

**Comment by RXWatcher1** [comment]
They have one but it would use some work: https://github.com/linuxserver/docker-hydra/tree/version2

**Comment by fryfrog** [comment]
They also don't seem to be very open to contributions, the couple times I've tried... they rejected. :/

I'll ping binhex and see if he's going to do one, I like those better personally.

**Comment by vertigo235** [comment]
@RXWatcher1 What's wrong with their version 2 docker that would require some work?

**Comment by RXWatcher1** [comment]
@vertigo235 When I tried it over the weekend it was stuck at an older version of Hydra2 and I couldnt update via the app nor dropping/recreating the container. I had put in an issue for this asking if it could be updated on restart and they closed it saying: "no and as it stands it doesn't work properly anyways"

**Comment by theotherp** [comment]
This seems to support it: https://hub.docker.com/r/binhex/arch-nzbhydra2/

Can't vouch for it. As soon as I get sufficient feedback that it works I'll endorse it and put it in the readme.

**Comment by fryfrog** [comment]
https://github.com/binhex/arch-nzbhydra2

^ This is the github for it, I don't think it works yet. But should be obvious there when it does. :)

**Comment by weirdcrap** [comment]
it is functional now. Currently testing it with sonarr and radarr on UnRAID 6.4-RC18f.

**Comment by kendokan** [comment]
Cranked up the lsio hydra2 container today, it's working fine, running non-root.

**Comment by theotherp** [comment]
So there are at least four different containers out there. Nobody can complain about not enough options...

I'm closing this.
