### ISSUE TITLE
Prioritize results containing certain tags

### ISSUE THREAD

**Issue by realbuz** [theotherp/nzbhydra2#356]
single question

I want to FAVOR any release with the tag multi.  I see option to force specific tags, however I only want to prioritize if possible.

Radarr has this option configured but it seems like it's not working when going through hydra.

**Comment by theotherp** [comment]
What do you expect to happen? Hydra returns all the results found (after some filtering). There is no way to "favor" or prioritize any release. 

Lets say Hydra finds 100 results and 10 of them contain the word "multi". How would you prioritize these results? 

There's no reason why Hydra would prevent the prioritisation in Radarr from working. I suggest you contact the Radarr devs to find out why it doesn't work.

**Comment by realbuz** [comment]
my bad, I had assumed that hydra was doing some sort of filtering.

**Comment by theotherp** [comment]
Hydra does *filter* things but that's not the same as using some kind of scoring for results as it it's not Hydra that picks things to be downloaded.
