### ISSUE TITLE
manual search with movie category selected 6box, nzbplanet 100000 random results

### ISSUE THREAD

**Issue by realbuz** [theotherp/nzbhydra2#357]
using docker inside pgblitz (linuxserver/hydra2)

when selecting movie category and doing a manual search with either 6box and nzbplanet both return 100000 random results

I also have dognzb, nzbgeek and oznzb which do not have the same issues.

issue does not happen when not selecting a category.
[nzbhydra-debuginfos-2019-04-12-09-27.zip](https://github.com/theotherp/nzbhydra2/files/3073463/nzbhydra-debuginfos-2019-04-12-09-27.zip)

**Comment by realbuz** [comment]
sound like issue could be on the backend if they use the same platform as 3 other indexers do not behave like this.  Will submit a ticket linking here

**Comment by realbuz** [comment]
no longer certain of my previous statement, seems like 6box is using nzedb and nzbplanet newsnab+

**Comment by theotherp** [comment]
Not sure what your issue is... What do you expect to happen?

**Comment by theotherp** [comment]
I can work around this but I recommend you contact the affected indexers' admins and ask them to support movie searches using queries (instead of IDs).

**Comment by realbuz** [comment]
I dont see a proper way to contact 6box admins, however I have sent a notification to nzbplanet to refer to this post here.

**Comment by theotherp** [comment]
You could try https://6box.me/forum
