### ISSUE TITLE
Optionally save torrents to blackhole folder

### ISSUE THREAD

**Issue by Bechrissed** [theotherp/nzbhydra2#358]
Hi There,

I would like to have an option to save .torrent files to the Torrent blackhole option. Currently NZBHydra 2 saves .magnet links to the blackhole which are unsupported by my client Transmission (Transmission-daemon to be precise). Could there be an option to save the actual torrent file instead of magnet links? 

Transmission does support magnet links but doesn't pick up .magnet files/links from the blackhole folder. 

I'm asking this because currently the other option (button next to blackhole), save torrent, is not working for my most used torrent search engine (torrentz2.eu). It returns a blank page when clicking on it. I have a chrome plugin which can send torrents/magnet links directly to my Transmission install but it doesn't work either.

If more information is needed please let me know.

Regards,

Chris

**Comment by theotherp** [comment]
<img width="1143" alt="blackhole" src="https://user-images.githubusercontent.com/14368889/56095139-103faa00-5eda-11e9-8dfe-a8963cedc302.png">

**Comment by theotherp** [comment]
Magnet links are inherently different from torrent files. You can't just save a magnet link as a torrent file. Apparently there are some online services that support conversion between the two but I've never tried them and wouldn't implement any built-in conversion.

**Comment by theotherp** [comment]
But I will see what prevents torrentz2 from working.

**Comment by theotherp** [comment]
When I click the download button next to a result the browser sends the magnet link to the program which is registered to handle magnet links.

**Comment by sscraggles** [comment]
I had the same issue with deluge, so wrote a daemon script that watches the blackhole directory for new files then sends them to deluge-console.  You could probably modify it for your download client..

It uses entr to avoid polling the disk:  apt-get install entr


`#!/bin/sh
cat <<-SCRIPT >/tmp/torrent-magnet.sh
#!/bin/sh
cd /downloads/torrents/torrents-watch/
if [ \$(ls -1 *.magnet 2>/dev/null | wc -l) != 0 ] ; then
  for file in *.magnet ; do
    url=\$(cat "\${file}")
    magnet=\$(curl -v "\${url}" 2>&1 | grep Location | sed 's/^.*magnet/magnet/g')
    #/usr/bin/sudo -u somebody deluge-console --config=/config -q add "\${magnet}"
    docker exec -it deluge-openvpn /usr/bin/sudo -u abc deluge-console --config=/config -q add "\${magnet}"
    mv "\${file}" ".\${file}".done
  done
fi
cd - 1>/dev/null
SCRIPT
chmod +x /tmp/torrent-magnet.sh

while $(true); do
  echo /downloads/torrents/torrents-watch/ | entr -d /tmp/torrent-magnet.sh
done;`
