### ISSUE TITLE
Linux on ARM: "./nzbhydra2: cannot execute binary file: Exec format error" (becauxe x86 format)

### ISSUE THREAD

**Issue by sanderjo** [theotherp/nzbhydra2#36]
I have Linux on ARM (ARM64 to be precised). Running `./nzbhydra2` gives

```
-bash: ./nzbhydra2: cannot execute binary file: Exec format error
```
... which is understandable as:
```
$ file nzbhydra2
nzbhydra2: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=373ec5dee826653796e927ac3d65c9a8ec7db9da, stripped
```
I can start on ARM64 with
```
java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=ALWAYS -jar lib/*.jar  --datafolder data
```
... which makes we wonder: what is the added value of the x86-64 executable nzbhydra2? Why not just a one-liner/few-liner script: saves space, and works on different CPUs?

**Comment by theotherp** [comment]
Quite honestly, I know enough for python to get it to run what I want and next to nothing about shell scripting. I also underestimated how complicated it would be to compile binaries for all the different architectures. 

As noted in the readme you can always just run the python script.

I'm also experimenting on a system like sonarr uses it where the program updates itself. The update process is the only reason why I need a wrapper in the first place.

The current situation isn't ideal but it works for most people fine and for those who can't use the binaries there's a fallback.

**Comment by sanderjo** [comment]
From the README: 

> If you cannot run the executables for some reason there's another way: The executables are just compiled python. Download nzbhydra2wrapper.py, put it in the main NZBHydra folder and run it

Ah, so easy! That's a RTFM for me ... ;-)

```
wget https://raw.githubusercontent.com/theotherp/nzbhydra2/master/other/wrapper/nzbhydra2wrapper.py
python nzbhydra2wrapper.py
```
... and it works!
