### ISSUE TITLE
Offer both direct and relay download options

### ISSUE THREAD

**Issue by anoma** [theotherp/nzbhydra2#360]
Currently when you download via hydra2 it introduces the browser directly to indexer. There are several scenarios where this is sub-optimal and whilst I personally believe hydra2 should always control all communications to the indexer I am aware that such a radical change will never be universally agreed.

It seems sensible then to either have a setting to turn of direct download, making hydra2 relay all downloads or present two download links allowing the user to choose each time between downloads directly client > tracker or have hydra2 do it for you .

**Comment by theotherp** [comment]
In the search settings you can select to proxy NZBs, meaning the NZBs will be downloaded by Hydra and then either sent to the browser (or external program) or to the downloader.

**Comment by anoma** [comment]
I should probably post a Mr Magoo meme as punishment for being blind but I will make do with a snip of the very obvious setting I missed.

![NZB Proxy Option](https://i.imgur.com/xlDU7GE.jpg)

Sorry for the noise, but appreciated for the fast answer
