### ISSUE TITLE
Anime coming up as "movies"

### ISSUE THREAD

**Issue by modem7** [theotherp/nzbhydra2#361]
Heya, 

I've just installed NZBHydra2, but when I search anime via Sonarr, it seems that it's coming up as "movies", and as such, doesn't display/search for in Sonarr. 

[nzbhydra-debuginfos-2019-04-15-20-02.zip](https://github.com/theotherp/nzbhydra2/files/3081697/nzbhydra-debuginfos-2019-04-15-20-02.zip)

I've got anime set to category 5070 as standard. Sonarr is able to get results from all other indexers (nzb.su, planet and geek).

![Capture](https://user-images.githubusercontent.com/4349962/56158790-f6c25f00-5fba-11e9-8a63-14e4ac796a38.JPG)

How best to reconfigure to get the appropriate results? 

Thanks!

**Comment by theotherp** [comment]
The reason for this is that Sonarr searches using the categories 2000 and 5070. Hydra tries to find a configured category that uses these newznab categories and finds two conflicting categories (anime and movies) and decides to use movies. I don't know where the 2000 comes from... Did you configure Sonarr to use these categories for Hydra?

**Comment by modem7** [comment]
Looks like you're correct, just checked it. 

I think I did this as some muppets like to put anime movies under movies. 

I've disabled that, and will recheck. Will close if this resolves

**Comment by modem7** [comment]
Seems to all be working as expected after editing the 2000.

Much appreciated!
