### ISSUE TITLE
Popup error when refreshing.

### ISSUE THREAD

**Issue by biship** [theotherp/nzbhydra2#363]
F5/Refreshing any page gives:
```
An error occurred:
500: Internal Server Error

Path: /internalapi/downloader/getStatus

Message: No message available

```
Started with 2.5.1 or 2.5.2.
Windows 10 , running as a service.

[nzbhydra-debuginfos-2019-04-16-11-53.zip](https://github.com/theotherp/nzbhydra2/files/3085758/nzbhydra-debuginfos-2019-04-16-11-53.zip)

**Comment by theotherp** [comment]
That's weird. Looks like sabnzbd doesn't return a downloading rate. I can't reproduce this but it's easy to fix anyway.

**Comment by biship** [comment]
It's newsbin with a sabnzb interface. I've had the dev change newsbins sab API before. What's the query and the response you are looking for? I can ask for him to add or fix it. This query runs on every page change or refresh?

**Comment by theotherp** [comment]
Ohhh... I remember you ;-) That would've been good to know.

I'm querying the queue and use these values:
- status
- kbpersec
- paused
- slots
- mbleft
- timeleft

And for the slots these values:
- filename
- timeleft
- percentage
- mbleft

**Comment by biship** [comment]
It is the queue api call right?
https://sabnzbd.org/wiki/advanced/api#queue
api?mode=queue&start=START&limit=LIMIT&search=SEARCH
If so I'll nicely ask the dev.

**Comment by theotherp** [comment]
Yes.
