### ISSUE TITLE
TVRage ID links from Search History page throw error

### ISSUE THREAD

**Issue by jmooo** [theotherp/nzbhydra2#364]
Search History page gives links to TVRage and TVDB IDs being searched for

* TVDB links work fine:

TVDB ID: 128051, Season: 3, Episode: 29
`http://www.dereferer.org/?https%3A//thetvdb.com/%3Ftab%3Dseries%26id%3D128051`

* TVRage links throw error:

TVRage ID: 22027, Season: 1, Episode: 2
`https://my.server.name/nzbhydra2/internalapi/redirectRid/22027`

*error:*

Path | /nzbhydra2/internalapi/redirectRid/22027
-- | --
Query parameters |  
Error | Bad Request
Exception |  
Timestamp | Wed Apr 17 16:20:46 UTC 2019

*Using server.io docker container v2.5.4

**Comment by theotherp** [comment]
Please post your debug infos ZIP.
