### ISSUE TITLE
Wrong thumbnail is shown

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#365]
When I search a movie named 'Kate Plays Christine' I find it, and using the pulldown I select it. But in the results it is also showing the movie Christine which is another movie. But the thumbnail shown is for 'Kate Plays Christine'. So now I am a bit confused. ;-)

Is it possible to fix this?

I am running v2.5.5

**Comment by theotherp** [comment]
The covers shown are the ones provided by the indexer. The parsing of NZB titles and assignment of titles isn't perfect and some indexers do it better than others. There's nothing I can do here.
