### ISSUE TITLE
How to shrink nzbhydra.mv.db safely?  Nearly 13GB

### ISSUE THREAD

**Issue by BinsonBuzz** [theotherp/nzbhydra2#370]
Love the app - I'm using the linuxserver docker version.

At times it gets unresponsive for me and I'm restoring from a backup after a total lockout.  During the restore I saw my nzbhydra.mv.db file is nearly 13GB, so I'm guessing this is the source of my occassional problems.

What's the safest way to keep the size of this DB down?  Thanks

**Comment by theotherp** [comment]
Yeah, that's a bug that affects a couple of users and so far I haven't been able to reproduce it. Without knowing what causes it I can't report the bug to the database code maintainers.

You can try the following: Go to the debug tab in the system section. Run this command: `SCRIPT TO 'filename.sql'` (upper text area, click "Execute"). This may take a long while. Shut down Hydra and move your existing db file anywhere else. Start Hydra again. Run this command: `RUNSCRIPT FROM 'filename.sql'`. That should restore the whole database content while using less space.

A simpler solution is, of course, to just delete the db file. You'll lose history and stats but that doesn't matter to some users.

**Comment by BinsonBuzz** [comment]
i changed my keep stats from 30 to 7 and it's dropped to 2.5GB - that'll do for now!

Thanks
