### ISSUE TITLE
Invalid Discord-invite

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#371]
When looking in the Version history it shows: 'I was asked for a discord channel. This is it: [https://discord.gg/rMywHv](https://discord.gg/rMywHv)'

When I open that invite I get: 'Invite Invalid'

![image](https://user-images.githubusercontent.com/671621/56853117-b7cdcb00-6923-11e9-8cc0-70588966d180.png)

Btw: I am using version 2.5.7

**Comment by theotherp** [comment]
I'm an idiot. That link expires after one day...

**Comment by theotherp** [comment]
Use this one: https://discord.gg/uh9W3rd
