### ISSUE TITLE
[Enhancement] Report back correct capabilities on Torznab endpoint

### ISSUE THREAD

**Issue by Elehiggle** [theotherp/nzbhydra2#374]
Following scenario:

Hydra cannot convert tvRageId, tvdbId or tvmazeId to imdb.
Torrent trackers often only support IMDB -> Hydra falls back to TV show title for it's search

When I have added my torrent tracker in Sonarr directly (via Jackett), Sonarr calls the Jackett Torznab endpoint in the following way:

_&imdbid=tt1826940&season=7_

When I have added my torrent trackers in Hydra and add Hydra to Sonarr, Sonarr calls the Hydra Torznab endpoint in the following way:

_&tvdbid=248682&rid=28304&tvmazeid=58&season=7_

I think the issue comes from Hydra, or at least is fixable there. I suppose Sonarr is asking the endpoint what capabilities it has, Jackett reports back that it only supports imdb, while Hydra probably reports it supports everything, even though I have only configured IMDB on those trackers. 

This causes various issues and it would improve the search of Hydra a lot if IMDB was used. This has already caused problems for me.

**Comment by theotherp** [comment]
I didn't know of any indexer or whatever that supports IMDB IDs for TV shows. Converting between them might be possible. I'l look into it.

**Comment by Elehiggle** [comment]
Hey, I've meant Torrent trackers. To my knowledge, torrent trackers exclusively support IMDB. Maybe there are a few exceptions, but not many. And after manually checking all my trackers, they all have IMDB added for TV shows and Sonarr searching with IMDB through Jackett yields results. When checking Jackett definitions, at least 39 trackers support IMDB tv show search: https://github.com/Jackett/Jackett/search?p=1&q=tv-search%3A+%5Bq%2C+season%2C+ep%2C+imdbid%5D&unscoped_q=tv-search%3A+%5Bq%2C+season%2C+ep%2C+imdbid%5D

Regardless, the IMDB call should be made first, and when no results are yielded, attempt the title search.

This also does not address the issue that the Torznab endpoint is reporting that it supports providers other than IMDB, even though it does not have any tracker added that has configured those.

**Comment by theotherp** [comment]
I'm pretty sure there was a good reason for that when I implemented it. As I said, I'll look into it.
