### ISSUE TITLE
Favicon Not Showing In Firefox

### ISSUE THREAD

**Issue by lostandlost** [theotherp/nzbhydra2#375]
I am running v 2.6.0  and the favicon is not displaying for me in Firefox 66.0.3 once I log in  It seems to work fine in Chrome. I've tested it on two Windows 10 machines with the same results.  On the second PC I even reset Firefox to the defaults and that seemed to work until I closed the browser and reopened it.  I feel like this is something that just started in one of the more recent updates.  I know this seems picky, but I guess this is a testament to how good the software is if THIS is the issue I decide to open a ticket about. Thanks!

**Comment by theotherp** [comment]
Fixed in next release :-)
