### ISSUE TITLE
Icon missing after switching to SABnzbd and back to nzbget as Downloader

### ISSUE THREAD

**Issue by count00zero** [theotherp/nzbhydra2#376]
Hi,

a small "problem" which might not need a bugfile:
The "send to nzbget"-Icon in the search results is now missing after I switched my default downloader to SABnzbd and now back to nzbget ....

![grafik](https://user-images.githubusercontent.com/14225157/57037635-0b0f8880-6c58-11e9-9ac9-a51f698c002f.png)

The feature is still there, but without a visible indicator (until the mouseover event).

BR,
count

**Comment by theotherp** [comment]
Cannot reproduce. Please send me your debug infos.

Also, when the page is open in your browser press F12, then Ctrl+Shift+C, make a screenshot and post that.

**Comment by count00zero** [comment]
Thanks for the reply!
1st att = screenshot.
![grafik](https://user-images.githubusercontent.com/14225157/57177671-bc840900-6e66-11e9-969a-3e46bea3c9f2.png)

2nd att = debuglog
[nzbhydra-debuginfos-2019-05-04-12-16.zip](https://github.com/theotherp/nzbhydra2/files/3144231/nzbhydra-debuginfos-2019-05-04-12-16.zip)
Thanks again for your patience!

**Comment by theotherp** [comment]
The display of custom icons doesn't work for some reason. You can remove the "atom" value for your downloader to fix this for now.

**Comment by count00zero** [comment]
OK, thank you! That's it!
