### ISSUE TITLE
Disable RSS for specific indexers

### ISSUE THREAD

**Issue by Wdavery** [theotherp/nzbhydra2#377]
I'd love the ability to tune each indexer with the options to turn off/on RSS searches.
I have my main paid indexers, and I, like many others, use the free basic accounts on other indexers to pickup things that may have fallen through the cracks of the main indexers.

Due to the free accounts, they have limited API access, so in an effort to save those precious API searches I've turned down the RSS sync intervals in Sonarr/Radarr/etc. 

I only need those indexers when backfilling older content, so it would be great to only allow actual searches to go through to those indexers

Current workaround options:
- Two instances of Hydra2, a hydraRSS and hydraSearch, and configure each within Sonarr/Radarr/etc to use only for rss/searches. 
- One instance of hydra2 with everything I want to use for RSS and then configure each client with the manual search indexers individually.

**Comment by theotherp** [comment]
Indexer config: <img width="352" alt="2019-05-02_18-28-12" src="https://user-images.githubusercontent.com/14368889/57090881-26d26780-6d08-11e9-8635-fa77533f3baf.png">

**Comment by theotherp** [comment]
Oh, you mean "actual searches", e.g. no update queries...

**Comment by theotherp** [comment]
Oh god, with each request the config gets harder to understand...

**Comment by theotherp** [comment]
But I think I found a way to implement this somewhat easily. Would you be happy with an option "All but update searches"?

**Comment by theotherp** [comment]
You'll have to be ;-)

**Comment by Wdavery** [comment]
Definitely. That seems like a perfectly reasonable solution

**Comment by Wdavery** [comment]
Up and running on the new version and it's working beautifully. Thanks for the quick feature update!
