### ISSUE TITLE
adding NZBKing

### ISSUE THREAD

**Issue by Diabolino** [theotherp/nzbhydra2#378]
it's possible add NZBKing, actually the best usenet search site

**Comment by theotherp** [comment]
The HTTPS site doesn't work as it redirects to https://www.nzbdrive.com/

I wouldn't want to support a site without HTTPS.

**Comment by Elehiggle** [comment]
Maybe they have changed it since you replied here @theotherp , but for me the site is fully HTTPS. I can visit the site, search and download NZBs over HTTPS. https://www.nzbking.com/search/?q=big+buck+bunny

**Comment by theotherp** [comment]
That may have been a bug. I'll take a look. But the results look really bad, search words seem to be combined using OR (in some cases, I don't really understand what's going on).

https://www.nzbking.com/search/?q=the+dark+knight returns a lot of crap. https://www.nzbking.com/search/?q=butch+cassidy+and+the+sundance+kid returns mostly what I'd expect. I'm not convinced it would be worth the effort.

**Comment by Elehiggle** [comment]
Yeah they are infamous for that. If you use quotes the results are better.

**Comment by theotherp** [comment]
Results are shit even with quotes.

**Comment by YenForYang** [comment]
Is this abandoned for good? The search seems to pretty alright if you know exactly what you are looking for; I think it would be a worthwhile addition. It seems to me that setting "Sort Order" to "Magic" is equivalent to searching by relevance. 

```
https://nzbking.com/search/?q=%22the+dark+knight%22&ft=&gr=&po=&so=m

so     Sort Order
    m   Magic
    s     Size
          Default is Date

gr     Group
po     Poster
ft       Filetype
   au    Audio
   vi    Video
   im    Image
   ap    App
         Default is All
```

Dash `-` with the `q` parameter excludes words. Quotes seem to make less of a difference when using the "Magic" sort order, but there is some effect. Also noticed that _Poster_ requires an exact string like `MadeUpName@domain.com (Nehm)` -- `MadeUpName@domain` won't work. But you can browse by poster using `https://nzbking.com/poster/MadeUpName@domain.com%20(Nehm)/`. _Group_, on the other hand, does a simple string match--for the most part. It is pretty inconsistent. For example, `gr=a.b.hdtv` doesn't work, but `hdtv` does (it doesn't seem to like the prefix `a.b.`.) On the other hand, `es.binarios.hd` works, along with fragments like `es.binarios`, `binarios`, `binarios.hd`. You can also only search for 1 group at a time.

**Comment by albino1** [comment]
> That may have been a bug. I'll take a look. But the results look really bad, search words seem to be combined using OR (in some cases, I don't really understand what's going on).
> 
> https://www.nzbking.com/search/?q=the+dark+knight returns a lot of crap. 

Using your previous `The Dark Knight` example combined with @YenForYang's suggestion of using their "Magic" sorting method seems to give pretty decent results currently:

https://nzbking.com/?q=the+dark+knight&ft=&gr=&po=&so=m#

Certainly it's on par with a lot of the second and third tier indexers, and better than Binsearch at the very least.  If too many garbage listings is a concern you could limit it to the first 50 or 100 magic results.

Anyway, just bumping to mention that it might be worth revisiting this as there is a lot of obscure stuff on NZBKing that isn't on any of the traditional indexers.

**Comment by github-userx** [comment]
You can search for only certain file types:

https://www.nzbking.com/?q=&ft=%22ISO%2C+NRG%2C+BIN%2C+IMG%2C+MP4%2C+AVI%2C+DIVX%2C+XVID%2C+MKV%2C+WMV%2C+OGV%22&gr=&po=&so=

Filters out most spam for me (only issue when something is a legit upload but was passworded. But then sorting from file size big to small can help).

**Comment by PietroPizzi69** [comment]
And one advantage of King is the extremely long retention. There I can find stuff which is long gone from the other search engines! Therefor I would also appreciate it if it gets added :)!

**Comment by jagarrison** [comment]
Really, years later and no one can figure out how to scrape the most useful free indexer on the web?
