### ISSUE TITLE
Check capabilities button hidden until api key filled in

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra2#38]
When adding an indexer, the check capabilities button at the bottom is hidden until the api field is filled in (probably also the url too). But *some* indexers like SickBeard's don't have an api key. Maybe only hide while URL is unfilled?

**Comment by theotherp** [comment]
That indexer is newznab based but does not have an API key?

**Comment by fryfrog** [comment]
Yeah, crazy huh? Let me double confirm by adding it back to Sonarr.

**Comment by fryfrog** [comment]
If you like, the url is http://lolo.sickbeard.com/. I was mildly torn about posting it, but if you Google "sickbeard indexer", it is all over the place. I have no idea why they just make it totally open, but I donated once for it in the way way past and don't feel bad about using it. :)

**Comment by theotherp** [comment]
I censored it, who knows.

I'll adapt the GUI code. Pretty sure some people will manage to try other indexers without providing an API and raise an issue...

**Comment by fryfrog** [comment]
Yeah, it is probably the only newznab url w/o api key :/

A white list would probably be better than opening it up to everyone.

**Comment by theotherp** [comment]
Probably a better idea. If the host setting contains that host don't require an API key
