### ISSUE TITLE
HSTS header served by default by NZBHydra

### ISSUE THREAD

**Issue by tom29739** [theotherp/nzbhydra2#380]
A Strict-Transport-Security (HSTS) header is served by NZBHydra: 
`Strict-Transport-Security: max-age=31536000 ; includeSubDomains`

As HSTS is based on the domain/hostname rather than the port this causes problems with other HTTP-only applications on the same server as their webpages cannot be viewed without clearing the HSTS settings in the browser.

Spring appears to serve this header by default, according to the [documentation](https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#headers).

It would be useful if HSTS was disabled by default, or if an option in the config file were given to configure HSTS.

[debug infos ZIP](https://github.com/theotherp/nzbhydra2/files/3169505/nzbhydra-debuginfos-2019-05-11-23-01.zip)

**Comment by theotherp** [comment]
Could you describe a specific scenario where this would cause problems?

**Comment by tom29739** [comment]
I run Transmission which doesn't support HTTPS for its web UI, on the same server as NZBHydra. The 2 apps share the same hostname so browsers redirect all HTTP requests to HTTPS because of HSTS.
This means that I can't access HTTP-only apps running on the same server or that have the same hostname or domain as NZBHydra.

**Comment by theotherp** [comment]
I'll probably just remove the header...
