### ISSUE TITLE
Using double quote for NZBgeek returns a lot

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#382]
When I look for "tralala" I get:
```
Indexer NZBGeek completed search successfully with 2398124 total results
```
I think that is a bit too much? ;-) Not sure if it is a feature or a bug,

I am using version 2.6.3

**Comment by theotherp** [comment]
I'd say that's a bug in their code, not mine.

**Comment by alron** [comment]
It isn't just NZBGeek. I've seen similar happen with other indexers. It might be worth considering filtering out the quotes (' " `).  Or adding a user configurable forbidden character filter.

**Comment by theotherp** [comment]
The filter you're proposing might be a good idea. I'll think about it.
