### ISSUE TITLE
"please select at least one result"

### ISSUE THREAD

**Issue by SNWRbxT** [theotherp/nzbhydra2#383]
Please Ignore my lazyness, just close if you won't accept without logs etc.
------------------

When selecting _different_ NZBs with the same nested title NZBHydra2 gives the message "You should select at least one result..." but what I think it is really saying is "please only select one NZB with the exact same title"

e.g. selecting below will trigger the error:

x - Big Buck Bunny Movies 700MB
x                                Movies 4GB

Thanks for the great software!

**Comment by walterhpdx** [comment]
Actually, this just started happening to me - so if you need logs, etc, let me know and I will provide.
