### ISSUE TITLE
HikariPool-1 - Starting takes an extrodinarly long time

### ISSUE THREAD

**Issue by tehniemer** [theotherp/nzbhydra2#384]
I'm not sure when this started, but I noticed it today, when starting Hydra2 it hangs on 
```
2019-05-13 20:52:35.695  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
```
I don't remember this being an issue in the past.

* Can the problem be reproduced? How?
I've restarted my container, recreated, tried the previous release, it always hangs, but seems to eventually start, though I'm not sure how long it actually takes.

* If you use a docker container please tell me which one.
linuxserver/hydra2:latest (2.6.3)

**Comment by tehniemer** [comment]
It finally started

```
2019-05-13 20:52:35.695  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...

2019-05-13 21:35:05.550  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
```

**Comment by theotherp** [comment]
Each time or just once?

**Comment by tehniemer** [comment]
Each time it seems

**Comment by theotherp** [comment]
Hmm... I've heard about this once but never found out why. Please shut down your instance, temporarily rename your database file in the data folder and see if it starts faster now. You can rename your database file back once the test is done.

**Comment by tehniemer** [comment]
I renamed the database folder and restarted and that solved the issue. 

Is there any downside to running with the new database? What am I losing from the old one? It seems that my indexers are all still there.

**Comment by theotherp** [comment]
You lose history and stats.

**Comment by tehniemer** [comment]
I renamed my original database and restarted and it booted quickly again, is this just something that'll happen from time to time?

```
2019-05-14 06:03:29.862  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...

2019-05-14 06:04:40.631  INFO --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
```

**Comment by theotherp** [comment]
Not that I know of...

**Comment by tehniemer** [comment]
Hmmm, OK, I guess this can be closed for now then. I'll re-open if it happens again.

**Comment by tehniemer** [comment]
It's happened again after updating to 2.6.6

**Comment by theotherp** [comment]
Please post the debug infos zip

**Comment by tehniemer** [comment]
I enabled debug mode in logging, but where do I find the zip file?

**Comment by theotherp** [comment]
System section / bugreport tab. When you created this issue there were instructions on how to do this...

**Comment by tehniemer** [comment]
I jumped the gun on the question and figured it out, so I deleted the comment. I wish github would send a deletion email when a comment gets deleted.

If if ever boots I'll upload the zip, its been "starting" for an hour, so I recreated the container to see if that will allow it to boot, in the meantime, here are some logs.

[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/3182480/nzbhydra2.log)

**Comment by theotherp** [comment]
How big is your database file?

**Comment by tehniemer** [comment]
It was pretty massive, 3.69GB. I ended up having to rename that one and start a new database to get it to boot again.

**Comment by theotherp** [comment]
Should be better with recent updates. Did you notice any improvements?

**Comment by tehniemer** [comment]
I've pretty much abandoned NZBHydra2, I was still getting out of memory errors with an XMX value of 1024. I've had more stable results just putting my indexer info in each application that needs it.

**Comment by theotherp** [comment]
Too bad. Sorry I couldn't help you :-(
