### ISSUE TITLE
Question: Can nzbhydra2 cache responses for X amount of time?

### ISSUE THREAD

**Issue by jamesbroadshaw** [theotherp/nzbhydra2#390]
**What do you want to happen?**

If I do a search and some results are returned, optionally cache those results for X amount of time. I think currently only metadata is cached or so I saw in the options.

**if not clear, why do you want it?**

I have limited number of allowed API hits on an indexer and would like to prevent repeat searches for the same content to count against this quota.

**Do you think it's something only you need or something that might be popular?**

I think others would benefit from enabling caching of responses as it would reduce load on indexers and save API hits.

**Comment by theotherp** [comment]
See the wiki

**Comment by Wdavery** [comment]
I'd also be interested in a global caching option. The `&cachetime=60` option isn't useful in Sonarr/Radarr as far as I can tell, as you can't make them add that to the search URL.

A global option, off by default, could be a good catch-all.
I can open issues on Sonarr/Raddar to allow the current method as well.

**Comment by theotherp** [comment]
You can add the parameter in sonarr to be used. Display the advanced
options.

**Comment by Wdavery** [comment]
Well! Thank you. Must have missed that one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
