### ISSUE TITLE
Remove trailing not working

### ISSUE THREAD

**Issue by ghost2289** [theotherp/nzbhydra2#392]
Feature Remove trailing (Searching, Results Processing) is no longer working. Results are not trimmed of defined substrings. Feature worked in previous versions, not sure when issue started.
I used it to remove "-xpost" from nzb.su results and "-obfuscated" from nzbgeek results as examples but that no longer works. Running in windows as a service + adoptopenJDK

[nzbhydra-debuginfos-2019-05-16-16-18.zip](https://github.com/theotherp/nzbhydra2/files/3187766/nzbhydra-debuginfos-2019-05-16-16-18.zip)

**Comment by theotherp** [comment]
Could you please provide an example title where it doesn't work?

**Comment by theotherp** [comment]
Nevermind.
