### ISSUE TITLE
Using "Invert Selection" or "Select All" causes error "You should select at least one result..."

### ISSUE THREAD

**Issue by 3a07d0c540** [theotherp/nzbhydra2#397]
* What do you expect to happen? What does happen? 
Using the "Invert Selection" or "Select All" dropdown and hitting "add to client" to add results causes a "You should select at least one result..." message. Clicking all the wanted results manually and hitting "add to client" works fine.

* Have you searched for this problem? You don't have to answer, just make sure.
Yes. A similar issue was raised before in relation to duplicate results grouping and selection not working. The above behavior applies to groups of duplicates as well. Works fine if selected manually but doesn't otherwise. Behavior also happens even if no grouped results are present in search results.

* Can the problem be reproduced? How?
Search for anything and try to add via "Invert Selection" or "Select All"

* If you use a docker container please tell me which one.
linuxserver.io - hydra2 is current version: 2.6.9 

debug files:
[nzbhydra-debuginfos-2019-05-20-12-03.zip](https://github.com/theotherp/nzbhydra2/files/3198805/nzbhydra-debuginfos-2019-05-20-12-03.zip)

**Comment by loungebob** [comment]
It’s been like that for a while, at least 2 updates. Makes it unusable for batches. Was just about to report this too since it didn't go away on its own.
