### ISSUE TITLE
Update Docker images on Docker Hub

### ISSUE THREAD

**Issue by jangrewe** [theotherp/nzbhydra2#400]
Hi, my local container keeps on warning me that there's a new version and i should update - but the latest tag on your repository is from 3 months ago. Could you maybe enable automatic builds of Docker images for your releases? Thanks!

**Comment by theotherp** [comment]
Don't use my container, it's outdated as you see and I really don't care
enough about it to update it regularly, to be honest. Use one of those
mentioned in the Readme.
