### ISSUE TITLE
Keep History For ... Option not removing old history.

### ISSUE THREAD

**Issue by FrostyWolf** [theotherp/nzbhydra2#401]
I recently noticed that my nzbhydra.mv.db was 29 gigs.  I did some searching, and found a most saying that storing search results/history seems to be what cause that to inflate. 

So I set my Store results for ... to 1 day, and my Keep history for ... to 1 week.  

When to System->Restart.  Any my database shrunk to 5gb.  

This is a step in the right direction, but still seems very large to me.  

When I go to "History & Stats" I still have entries going back to 2018-04-12 under search history and Download History.

**Comment by theotherp** [comment]
The database growing so large is a bug in a library. I can't guarantee that
reducing the time for which results are kept will help with the database
size.

**Comment by FrostyWolf** [comment]
Anything I can do? Do you need any particular logs, etc?

**Comment by theotherp** [comment]
Thanks, but no.

**Comment by theotherp** [comment]
The setting you refer to does not define for how long downloads and searches are stored but only results. Searches and downloads don't take too much space. My database which has searches and downloads of the last two years takes less than a gigabyte when compressed properly. See #311
