### ISSUE TITLE
Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra2#403]
All my external indexers show the same error:
```
Error while communicating with indexer indexername. Server returned: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

An error occurred while updating or getting update infos: Error while getting latest version: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```
After this the indexer is disabled since it does not work as expected. I am running 2.6.10. Not sure if this problem is introduced in the last update,

I really have no idea how to fix this. All help is appreciated. :-)

**Comment by theotherp** [comment]
Post your debug infos zip

**Comment by pven** [comment]
Can I mail it to you? (I don like to post it online.)

**Comment by theotherp** [comment]
Sure

**Comment by pven** [comment]
Done

**Comment by theotherp** [comment]
Try disabling the option "use packaged cacerts" in the main config.

**Comment by pven** [comment]
> Try disabling the option "use packaged cacerts"

That works. Thanks! :-)
