### ISSUE TITLE
Excessive use of wildcards for removing trailings slows down performance significantly

### ISSUE THREAD

**Issue by D3nn3** [theotherp/nzbhydra2#404]
This shouldn't really be a surprise but I still wanted to create an issue about this. I recently added a new Indexer which posts always end with something like this: `[942736caf]`

I used wildcards to remove such trailings and added `[*********]` as trailing to remove. This worked but the performance took a pretty deep dive and searches didn't even finish properly.
I found entries like these in the log files: `PERFORMANCE: NZBGeek: Parsing of results took 159446ms`

Two things:
1) How can trailings like these be removed with the system in place without crippling the performance? Regex doesn't work right?
2) Maybe limit the use of wildcards per entry to avoid such situations. In my case nzbHydra couldn't get any search results in most cases because it took way to long to process them.

**Comment by theotherp** [comment]
Huh. Well, I do use regexes internally. I never thought that could be an
issue but I have an idea how to improve the performance.

**Comment by theotherp** [comment]
`[*********]` doesn't make sense as * matches any number of characters...

**Comment by D3nn3** [comment]
Yes that's what I thought but here is a test I just did:

```
Original: Fear.The.Walking.Dead.S05E01.FRENCH.HDTV.x264-AMB3R [5422fd841]
With [*]: Fear.The.Walking.Dead.S05E01.FRENCH.HDTV.x264-AMB3R [5422fd8
With [*********]: Fear.The.Walking.Dead.S05E01.FRENCH.HDTV.x264-AMB3R
```

As for the debug.zip: Either nzbhydra tries to generate the zip and takes forever (waited 5+ minutes and it didn't finish) or I get the following error message:

```
An error occurred:
undefined: undefined

Message: undefined
```

Gonna try again tomorrow.

**Comment by theotherp** [comment]
Hm, interesting. I've improved the performance, will be included in next release.
