### ISSUE TITLE
Indexer returns error code 201; "extended" incorrect parameter

### ISSUE THREAD

**Issue by pb1051** [theotherp/nzbhydra2#406]
**Issue**: Headphones indexer not working properly with NZBhydra2; receive the error code below

**Docker Container**: ls.io nzbhydra2

**Resolution attempts**: Googled to no avail; reddited to no avail; emailed the indexer developer - response below; logged issue in Github

**Log**: [nzbhydra-debuginfos-2019-06-18-11-44.zip](https://github.com/theotherp/nzbhydra2/files/3302555/nzbhydra-debuginfos-2019-06-18-11-44.zip)

**Error message in NZBhydra2**:
>  Indexer returned error code 201 and description 'Incorrect parameter' when URL https://indexer.codeshy.com/api?apikey=************************************&t=search&extended=1&q=pink%20floyd&password=0&limit=100&offset=0 was called

**From Headphones indexer developer**: 
> It might be the extended parameter? I can double check in a bit. It's running pynab if that helps (although I might migrate back to nzedb quite soon)

So it sounds like maybe he changed the Newsnab base recently?

**Edit** to remove API key.

**Comment by rembo10** [comment]
It's been on pynab for a while... Just looking through the pynab code it looks like the password parameter is not supported, but passworded releases should be being deleted automatically so it doesn't seem necessary

**Comment by theotherp** [comment]
So I would recommend to ask the indexer developer to ignore that parameter instead of return an error. It's part of the newznab spec.

**Comment by pb1051** [comment]
@rembo10

**Comment by rembo10** [comment]
Hey - I'll fix it on my end

**Comment by theotherp** [comment]
Nice, thanks!

**Comment by rjhilgefort** [comment]
> Edit to remove API key.

@pb1051 You should know that folks can still see your API key in the edit history. I'd recommend regenerating if you haven't already. Just and FYI, cheers!

**Comment by pb1051** [comment]
@rjhilgefort I've not been using nzbhydra for a while now. Thank you for educating me on the edit history
