### ISSUE TITLE
nzbs are downloaded without extension

### ISSUE THREAD

**Issue by sumofatguy** [theotherp/nzbhydra2#41]
I have nzb hydra set behind a proxy using apache. It's also set to proxy from indexer. If I download an nzb after a search, it downloads properly but doesn't append ".nzb" to the end of the file name. It just downloads a file named with random numbers. It's obviously correct, because if I rename it with .nzb, it imports properly into any downloader

Sending links directly to nzbget works fine

**Comment by fryfrog** [comment]
I route my nzbhydra2 through an apache reverse proxy and just did a test search and download of an nzb, it came out named reasonably including the `.nzb` extension. What does your proxy entry look like?

**Comment by sumofatguy** [comment]
Thanks for the info! My apache config is essentially the same as yours:
```
<Location /hydra2>
	ProxyPass http://localhost:5076/hydra2/
	ProxyPassReverse http://localhost:5076/hydra2/
</Location>
```
If I have it set to 'redirect to the indexer', nzbs download properly. It's only when downloads are set to 'proxy nzbs from indexer' where I see this issue.

**Comment by fryfrog** [comment]
Confirmed, does the same for me. Just numbers.

**Comment by theotherp** [comment]
Acknowledged.

Am 09.01.2018 1:00 vorm. schrieb "Donald Webster" <notifications@github.com
