### ISSUE TITLE
Adding NZBHyrda2 to Sonarr and Radarr?!

### ISSUE THREAD

**Issue by ratnose** [theotherp/nzbhydra2#417]
I have just setup NZBHydra2 with the help of linuxservers container image, all seems to work but me adding hydra as a indexer on Sonarr and Radarr fails.
I have tried the api info from hydra, no luck. 
I have nowhere else to turn. Please help.

**Comment by theotherp** [comment]
Sorry, but that is a really bad ticket. What exactly did you do? What went wrong? What are the error messages? Where are the logs? You completely ignored the ticket template.

**Comment by ratnose** [comment]
I did ditch Hydra2 so no worries. :)
