### ISSUE TITLE
 Creation of SecureRandom instance for session ID generation takes way too long

### ISSUE THREAD

**Issue by ftischhauser** [theotherp/nzbhydra2#42]
I'm running 1.0.12 on Ubuntu 17.10 with OpenJDK (but see the same thing with Oracle). CPU is a i5-4250U and probably not the limiting factor.

In around 9 out of 10 times after starting NZBHydra, the initial web call takes ages:
```
2018-01-09 11:10:03.958  INFO --- [           main] org.nzbhydra.NzbHydra                    : Started NzbHydra in 9.978 seconds (JVM running for 10.501)
2018-01-09 11:16:45.889  WARN --- [0.0-5076-exec-1] o.a.c.util.SessionIdGeneratorBase        : [IP: 10.0.0.64] Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [399,055] milliseconds.
```
There appears to be no connection to the config (as it also happens after wiping the data folder) and increasing the memory to 512 MB does not help. Any idea what might be causing this?

**Comment by ftischhauser** [comment]
Well, looks like I should have tried a Google search before opening an issue. However this might be interesting for anyone stumbling over the same issue:

I have changed:
`securerandom.source=file:/dev/random`
to the non-blocking:
`securerandom.source=file:/dev/urandom`

in the file `/etc/java-8-openjdk/security/java.security` and the issue seems to be gone.

**Comment by theotherp** [comment]
Thanks for finding the solution ;-)

**Comment by Hakamad4** [comment]
Didn't work for me. I'm using java 11 with Spring boot 2.7.4, I change my java.security on $JAVA_11_HOME$\conf\security (actually path) but it didn't work for me. :(
Does anybody have a suggestion?

**Comment by karthikdaram** [comment]
> Didn't work for me. I'm using java 11 with Spring boot 2.7.4, I change my java.security on `$JAVA_11_HOME$\conf\security` (actually path) but it didn't work for me. :( Does anybody have a suggestion?

Yes i got a same issuse could any one help me please

**Comment by theotherp** [comment]
Please post debug infos.
