### ISSUE TITLE
Keep getting Invalid remember-me token (Series/token) mismatch. notice every 2nd search v2.6.12

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [theotherp/nzbhydra2#424]
since release v2.6.12 i have been getting the following error very frequently and its been very annoying.

![Screen Shot 2019-08-07 at 2 28 23 am](https://user-images.githubusercontent.com/2242880/62558404-515e2e80-b8bc-11e9-80ba-52b150660800.jpg)

also i'm unable to download the logs from the built in bugreport sectin of nzbhydra as they allways end up as 2Kb corruped zip files.

i have attached most recent logs of each type except for nzbhydra2-log.json as it contains all my API keys... & im not going through thousands of lines to remove them all...

[nzbhydra logs.zip](https://github.com/theotherp/nzbhydra2/files/3473246/nzbhydra.logs.zip)

```
org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.
	at org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices.processAutoLoginCookie(PersistentTokenBasedRememberMeServices.java:119)
	at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.autoLogin(AbstractRememberMeServices.java:136)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:98)
org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.
	at org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices.processAutoLoginCookie(PersistentTokenBasedRememberMeServices.java:119)
	at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.autoLogin(AbstractRememberMeServices.java:136)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:98)
org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.
	at org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices.processAutoLoginCookie(PersistentTokenBasedRememberMeServices.java:119)
	at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.autoLogin(AbstractRememberMeServices.java:136)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:98)
```

my setup:
macOS 10.14.6
i run nzbhydra using the wrapper as a LaunchAgent - wont impact hydra in anyway same thing like running from source via terminal but this way i can have it as a background process similar to docker...
python2 version 2.7.16
java JDK 12.0.2

i use chrome as my main browser, i have cleaned cookies/cache etc no help.

as a temp fix i have to go to main search screen & do a page refresh before every seach otherwise i get error. and if i wait like 2-3 mins and try to use the built in filter function i get error same goes with trying to send nzb's to sabnzb.

also if i wait to long & do another search between searches when i refresh page it brings me to login window again..

it seems something happend with this release on how cookies are handled as they keep timming out/expiring or unable to remember cookies.

**Comment by alron** [comment]
@XxUnkn0wnxX 
I recently have been seeing something similar. It wasn't every other search, more like every 5 or 6 minutes. Into the settings to flail about I went. I set the Config->Authorization->Cookie expiry to 90 days from the 365 days I had it at before, thinking that maybe I was overflowing something with the cookies. It made the problem incredibly worse, like every other search was giving me the remember-me error, which seemed to be about every 90 seconds. 

It seems like it was using seconds instead of days...

This got me thinking, what if I set it to something like 9000. I mean 9000 seconds == 2.5 hours... This seems to have corrected it for me, but YMMV. Give it a whirl.

**Comment by XxUnkn0wnxX** [comment]
well this is still getting very frustrating it literally happens every 2nd-3rd search for me.
but most of the time 2nd search. I would say I have like a min of 3-5 mins before this happens.
but it also occurs during spam searches like I search for one show, take 1-2 min break do next search etc. etc. & then I get error & it kick me back to login forum after page refresh.

@theotherp this is getting beyond frustrating now. having to go to main page & refresh browser between every search...

**Comment by alron** [comment]
Looking through the code changes now that I'm fully awake, [the server.servlet.session. changes here.](https://github.com/theotherp/nzbhydra2/commit/8e7c2acadfa7f5c83198b5c5a7efdaee6f4693f2#diff-a4005e5546d19f491f426846559533e9) look like they're likely the culprit. None of the other commits would impact the cookies and sessions, they're mostly cosmetic or associated with API.

I'm frankly too lazy to build up a local toolchain to build nzbhydra2 and dockerize it to test if reverting the server.servlet.session.* changes result in no cookie issues. This is mostly an educated guess.

**Comment by XxUnkn0wnxX** [comment]
i would not mind testing but i have no idea how to compile the source project. its been many many years since i've worked with java.

**Comment by theotherp** [comment]
@alron Yes, this problem is related to the session timeout changes I did which prevented from sessions being kept open forever which in turn caused memory issues. I tested it on my machine with multiple browsers and it always worked.

@XxUnkn0wnxX You can create a folder `config` in the main folder and there you put a file `application.properties` containing the line `server.servlet.session.timeout=0`. Restart Hydra and see if that helps. Sorry about the inconvenience.

**Comment by theotherp** [comment]
@XxUnkn0wnxX Please try with v2.6.13. Unfortunately I can't reproduce the problem on my machine so I can't say if my changes fixed it...

**Comment by XxUnkn0wnxX** [comment]
i think this has been resolved been testing for a while now & no cookie related issues...
