### ISSUE TITLE
Backups are not deleted

### ISSUE THREAD

**Issue by chemputer** [theotherp/nzbhydra2#426]
I'm sure that anyone who has used the program for a  decent amount of time has seen how quickly those automatic backups add up. They're huge, and almost a years worth for me was about 50GB. 

It would be great to be able to say I want to keep X number of backups (or days, weeks, etc) and then those older than that get deleted when a new backup is made.

**Comment by theotherp** [comment]
![img](https://i.imgur.com/63FVKnS.png)

If they're not deleted after that time there's a something wrong with your instance. Change your log file level to DEBUG, restart, go to the system tab and there to the tasks and execute the Backup task. Wait for it to finish, create the debug infos ZIP and post it here.

**Comment by chemputer** [comment]
Wow, I can't believe I missed that field. I had it set to 52 weeks. I'm dumb. Sorry.
