### ISSUE TITLE
2.6.14 has broken forms based authorisation

### ISSUE THREAD

**Issue by renzzla** [theotherp/nzbhydra2#428]
I have been running 2.6.11 for a while without issues, and have been using forms-based authentication as my NZBHydra2 is accessible from the Internet. I installed 2.6.12 and hit the problem described in bug #424 but adding the config file as suggested worked round that. I have now updated to 2.6.14, but after logging on and using it for a few minutes, I then get popups saying

```
An unknown error occurred while communicating with NZBHydra:

{"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","headers":{"NzbHydra2-Handle-Errors-Generically":true,"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"xxxxxxxxxxxxxxxxxxx"},"url":"internalapi/history/searches/forsearching","cached":false},"statusText":"","xhrStatus":"error"}

```
(I have obscured X-XSRF-TOKEN as I'm not sure if that allows access to my system or not).

If I refresh the page in my browser (Chrome on Windows 7), it throws me back to the forms-based login screen and once logged back in, it works ok for another few minutes before the same thing happens.

However...changing to "HTTPS Basic Auth" everything seems to work ok, and I no longer get the error. Looks like the changes in 2.6.12/3/4 have broken forms auth. Debug log is attached.

[nzbhydra-debuginfos-2019-08-15-12-25.zip](https://github.com/theotherp/nzbhydra2/files/3505358/nzbhydra-debuginfos-2019-08-15-12-25.zip)

**Comment by lostandlost** [comment]
I am also having this issue on v2.6.14 Windows 10.

**Comment by theotherp** [comment]
Hmm... Unable to reproduce this. Will have to play around a bit.

**Comment by lostandlost** [comment]
If it helps, for me it only happens when I am connecting from a different PC. The local machine that the server is installed on is staying logged in.
