### ISSUE TITLE
v1.0.13 update

### ISSUE THREAD

**Issue by danjames92** [theotherp/nzbhydra2#43]
Jan 09 19:32:01 Ubuntu-1604-xenial-64-minimal nzbhydra2[755]: 2018-01-09 19:32:01.608  INFO --- [0.1-5076-exec-3] org.nzbhydra.update.UpdateManager        : Shutting down to let wrapper execute the update
Jan 09 19:32:01 Ubuntu-1604-xenial-64-minimal nzbhydra2[755]: 2018-01-09 19:32:01.915  INFO --- [       Thread-6] org.nzbhydra.NzbHydra                    : Shutting down
Jan 09 19:32:02 Ubuntu-1604-xenial-64-minimal nzbhydra2[755]: 2018-01-09 19:32:02,793  WARNING - Unable to read control ID from /opt/nzbhydra2/data/control.id: [Errno 2] No such file or directory: '/opt/nzbhydra2/data/control.id'. Falling back to process return code 0
Jan 09 19:32:02 Ubuntu-1604-xenial-64-minimal nzbhydra2[755]: 2018-01-09 19:32:02,793  INFO - NZBHydra main process has terminated for shutdown

Borked update maybe? Any ideas?

**Comment by theotherp** [comment]
Some error in the update logic. For now you can just download the latest release and extract it to where ever your hydra instance is installed.

**Comment by theotherp** [comment]
Please post the complete debug infos.

**Comment by danjames92** [comment]
https://pastebin.com/exm9enDb

**Comment by theotherp** [comment]
Thanks.
