### ISSUE TITLE
Sonarr and Hydra connection

### ISSUE THREAD

**Issue by dcazman** [theotherp/nzbhydra2#431]
I am a new user and when I force Sonarr to fetch information or allow it to automatically query   Hydra 2. Hydra 2 finds the item according to the log and does nothing.

If I use other apps like Sick Gear everything occurs as expected. 

The expected result is Hydra gets a query and if it finds the information it sends information to the download client and the item is achieved.
The problem is not finding the information. The problem is Hydra 2 is not doing anything with what it finds from a Sonarr query.
.
I have combed guides and tried forums. This is the only place I can find that might help. Where can I look or what can I do?

**Comment by theotherp** [comment]
Hydra will not trigger any downloads by itself unless you do it yourself
via GUI. It's sonarr's task to search, process the results and send results
to your downloader.

**Comment by dcazman** [comment]
I fixed this but not sure how. Thank you for the information. I am curious to know the answer to my above question.
Also, I stopped using SickGear because of 
https://github.com/SickGear/SickGear/wiki/%5BWarning%5D-Using-External-Search-Tools
If I was you I would take it personally.

**Comment by theotherp** [comment]
Huh, I thought I had replied.

Nah, I don't mind. But thanks for the info, now I can refer future bug reports relating to SG to that page.
