### ISSUE TITLE
Feature Request: Enable for only API update queries

### ISSUE THREAD

**Issue by MassiveDrop** [theotherp/nzbhydra2#433]
Hello. 
* What do you want to happen?
I was hoping that  you could add an option to "Enable for .... Only API update queries". Currently there exists only the option "Enable for ... All but API update queries."

* If not clear, why do you want it?
Many new indexers (e.g. NinjaCentral) are great for grabbing new releases but bad for backfilling. Adding this feature would allow users to save a great number of API hits on such indexers when backfilling.

* Do you think it's something only you need or something that might be popular?
I imagine it would be popular since most users on NZBHydra2 have multiple indexers, and this feature could save a great number of API hits when backfilling. It also could help reduce hits on some free websites, like AnimeTosho, which are great for brand new content but that are redundant for backfilling.

**Comment by theotherp** [comment]
Funny, I didn't even know that I had added that other option...
