### ISSUE TITLE
[Feature Request] Torrent indexer prioritization

### ISSUE THREAD

**Issue by h2xtreme** [theotherp/nzbhydra2#434]
Like the title says would be possible to add torrent indexer prioritization to nzbhydra2?

Currently, all results from torrents, from all torrent indexers are sent to sonarr/radarr/medusa/wtv. A way to mitagate this without going the extra step of actually comparing releases and only sending unique results would be to only send results from the indexer with the highest priority. Example:

Movie A
Movie B

Indexer A - 100 priority
Indexer B - 50 priority

Search for Movie A, indexer A returns results. Only those are sent back. Movie B, indexer A doesn't return results, indexer B returns results. Indexer B results are sent back.

Thoughts?

**Comment by theotherp** [comment]
I'm not sure this would actually work as you'd expect. The fact that indexer A returns *any* results does not mean that any of those are usable by the calling program. If they're all discarded you don't get any download even though indexer B might have results that actually match. Or just say that indexer A returns 1 result and indexer B 100. Would you really rather have that one result than 100?

I guess you want to prefer indexers which don't require you to keep a ratio or stuff like that. But I think that decision would need to be made by the tool. I can't think of many cases where what you propose would result in the wanted results, sorry.
