### ISSUE TITLE
REQ: Ability to prefer HEVC (x265 instead of x264) in addition to resolution.

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra2#435]
Req: Feature enhancement

HEVC encodes are dramatically (50% on average) smaller than the equivalent X264 encode and would be preferred by anyone who has limited bandwidth or is downloading using a block account.  Currently there is no method to indicate a preference to get them first.  You could make "HEVC" an always required keyword but this locks you out of falling back to x264 if no HEVC encodes exist.  Typically they put HEVC in the filename posted but I guess they could put x265 instead.

**Comment by theotherp** [comment]
I mean, you can always just enter it in the title filter...

**Comment by famewolf** [comment]
True but I had in mind more a setting which would be retained and used when called via api from couchpotato, sickcool etc.    If made a permanent keyword you ONLY get HEVC where it would make more sense to PREFER HEVC but fall back to mp4 if no results.

**Comment by theotherp** [comment]
Yeah, I'm not gonna implement that. 

The tool that does the downloading needs to have the capability of preferring one quality over the other.

What you propose is way too specific, sorry.
