### ISSUE TITLE
Category definition - Required Words/Regex usage

### ISSUE THREAD

**Issue by MikClucas** [theotherp/nzbhydra2#437]
I have been using Hydra in docker as the Search engine for Sonarr, Radarr,... for 6 months (and really like it).  
I would also like to have the enhancement to filter by language #155 .
However until this is implemented I am trying to restrict the result set (sent Sonarr/Radarr) to titles that contain the words

 **german** or **deutsch**.
I have set up a new category *Movies (DE)* using *Movies* as a Template.  Then changed the following
- Required words => german
- Newznab categories => 2000, 2010, 2020
![Hydra2_Movies(DE)_Definition 2019-09-27 11-52-33](https://user-images.githubusercontent.com/25286169/65761542-433fc800-e11f-11e9-8dcc-f33db2f7cec5.png)

 The category is being applied correctly in a movies search
- Men.in.Black.International.TS.LD.German.DL.720p.x264 => Category Movies (DE)
- Men.in.Black.International.2019.1080p.Atmos.TrueHD7.1.x264 => Movies HD

Now I'm confused. I expected that using the *Movies (DE)* Category to only show titles that have the *Movies DE* category. However I still get all the Movie categories in the list.
![Hydra_Movies (De)_Search Results 2019-09-27 11-55-40](https://user-images.githubusercontent.com/25286169/65761638-7d10ce80-e11f-11e9-8799-ba7a9d3bf41a.png)
Applying a Category filter for *Movies (DE)* gives me what I want on the screen. 

I have tried 
- using Required Regex instead of words
- making the search type General Instead of Movies

but none of these reduce the list to just the *Movie (DE)* category.

Is there a way to get a list containing only the category *Movies (DE)* sent to Radarr/Sonarr/...?

Have a nice Day

**Comment by theotherp** [comment]
Please post your debug infos ZIP so I can take a look at your config.

**Comment by theotherp** [comment]
I'm closing this issue due to lack of feedback.
