### ISSUE TITLE
[BUG] In Safari titles of settings fields run under the fields

### ISSUE THREAD

**Issue by translit** [theotherp/nzbhydra2#439]
<img width="515" alt="Screenshot 2019-10-05 at 07 52 09" src="https://user-images.githubusercontent.com/4024096/66250676-1fdfd300-e746-11e9-8d4f-1ea272bf195a.png">
 
Hydra2: 2.6.18 (Docker container by Linuxserver)
Safari: 13.0

**Comment by theotherp** [comment]
I'll need to update the bot script to accept [Bug], ignore that.

**Comment by theotherp** [comment]
Can't reproduce that on Firefox or Chrome. I don't have a Mac so I can't test it for myself on Safari.

**Comment by translit** [comment]
Maybe test it in [BrowserStack](http://www.browserstack.com)? If not, no big deal. It's purely cosmetic.

**Comment by theotherp** [comment]
Browserstack requires me to buy a plan to test Safari which I'm not willing to do. Thanks for the report but unfortunately I'll have to deny this issue, sorry.

**Comment by translit** [comment]
Fixed in 2.23.0. Related to https://github.com/theotherp/nzbhydra2/issues/563
