### ISSUE TITLE
Add option to select if one or all required words must be present

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#44]
Alternative: Add some widget that allows to configure multiple tuples where at least one must be present per tuple. Or something like that.

Thoughts?

**Comment by theotherp** [comment]
Hm, didn't think that through.

If I add all the required words to a query of course they will all be required. The alternative would be to not add them at all if the option to only require at least one (or x) to be present. The obvious downside is that the results are only filtered after the indexer was called. Depending on the words this would mean to potentially throw away a lot of results which could result in more API calls.

If I choose to add that option the user should be very certain that that is what he wants.

**Comment by theotherp** [comment]
On the other hand that can "easily" be achieved using required regexes:
`(option1|option2)` matches any result that has "option1" or "option2" in its title.

`(?=.*musthavethis)(?=.*andhavethis)` matches any result that has "musthavethis" and "andhavethis"  in any order in its title.

Ah, the magic of regex. https://xkcd.com/208/

**Comment by TChilderhose** [comment]
I agree with you that the ability of regex might be better suited for this and has the bonus of it already being implemented. While it is less user friendly overall, but definitely more powerful. So I think how it is currently setup is good.
