### ISSUE TITLE
this weekend...

### ISSUE THREAD

**Issue by tc60045** [theotherp/nzbhydra2#441]
Fully functioning Hydra2 installation in LS.io/Docker for a year, with zero issues

Then, this weekend you guys got crazy...

Now, web interface never loads, suspect tables munged in the upgrade that was forced

I don't want to lose my config, and can revert to a snapshot if need be, but is there an easier way to clean the slate from the weekend... please advise.  Totally down now.

https://pastebin.com/xwe3s6cb

**Comment by theotherp** [comment]
Open the latest backup zip and extract the database file into the database folder, overwriting the old. Make sure you're running the latest docker.
