### ISSUE TITLE
Allow disabling dereferer

### ISSUE THREAD

**Issue by Nothing4You** [theotherp/nzbhydra2#442]
Setting the dereferer to $s seems to be the obvious way to disable it, however, when doing that it still gets urlencoded, resulting in the link not working.
Example:
https%3A//myindexer/details/foo
The browser interprets this as https://myhydra/https%3A//myindexer/details/foo

**Comment by theotherp** [comment]
I'd think that just using an empty value would be the obvious way to disable it.

**Comment by Nothing4You** [comment]
Somehow I didn't think of that.
