### ISSUE TITLE
Trap empty blackhole directory error to provide correct error message

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra2#443]
Currently if you leave the torrent blackhole blank but use jackett and lick on the "send to blackhole" option you get a 500 error such as the screenshot.   The message is not at all descriptive and it might be better to trap the error so you could provide a message that says "Torrent Blackhole not defined" or something more descriptive than '500 server error'.
![Screenshot_20191015_135459](https://user-images.githubusercontent.com/4558832/66857052-77efb400-ef54-11e9-966e-e3efcbe79926.png)

**Comment by theotherp** [comment]
Please send me your debug infos ZIP and tell me from which tracker the result came which you clicked.

**Comment by famewolf** [comment]
The issue occurred when using jackett and clicking on the "send to blackhole" option in nzbhydra.  It was MY fault for leaving that blank as I was adding/testing jackett but the error given was just a generic server message that didn't really describe why the issue occurred.   I don't have additional logs because once I added the directory the error went away.  I could remove the dir and try again if this doesn't give you enough info.

**Comment by theotherp** [comment]
I'm pretty sure this isn't related to the empty folder but to the fact that your OS doesn't support magnet links.

Anyway, I'll handle the problem better.
