### ISSUE TITLE
[Question] How does priority work and how to set it up properly?

### ISSUE THREAD

**Issue by a-nunes** [theotherp/nzbhydra2#444]
I'm trying to use NZBHydra2 with Jackett, Sonarr and Radarr. My doubt is: How the priority field works?

I've set up all my trackers in Jackett and then set the torznab in Hydra2. But when I try to search it doesn't shows me in my priority order. Here's an example:

BJ-Share is set to priority 100 (most valueble) and MoreThanTv is set to 99 (second one). When I search, BJ-Share usually appers in first line, but there's two or three other trackers between it and MoreThanTv, even those with priority 30 (worst ones). Looks like to me that it has some relation between priority and age of releases.

And it becomes harder to understand when I go to Radarr, when I use Hydra2 as a torznab over there and it shows all the results in random order (looks like to me, sorry if it doesn't).

Could someone please help me to understand how it works and how to setup it properly to get files from most valueble trackers then, if none of then has my release, go to worst ones?

Thank you.

**Comment by theotherp** [comment]
When searching via API (which Radarr and Sonarr do) the priority only comes into play when multiple duplicate results are found. This is never the case for trackers. Duplicates can only occur when multiple usenet indexers provide results for exactly the same result.

In all other cases Hydra will just return the list of all results to *arr which then picks the best result.

Hydra has no way of knowing if a tracker with a high priority returns results that are also contained by an indexer with a lower priority. It would probably be possible to try to determine that by comparing the titles but I don't think that's worth the hassle.

**Comment by a-nunes** [comment]
Oh, I got you. Thank you very much.
