### ISSUE TITLE
TMDB Caps Check Always Fails

### ISSUE THREAD

**Issue by Incrementing** [theotherp/nzbhydra2#445]
Caps check for TMDB always fails because the expected response doesn't match the ID.
[NewznabChecker.java Line #156](https://github.com/theotherp/nzbhydra2/blob/master/core/src/main/java/org/nzbhydra/indexers/capscheck/NewznabChecker.java#L156)

24428 => Avengers
1399 => GOT (not a Movie ID)

**Comment by theotherp** [comment]
Oops -.-
