### ISSUE TITLE
You are not allowed to visit that section. 5x

### ISSUE THREAD

**Issue by thimslugga** [theotherp/nzbhydra2#448]
## How to create a bug report

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

* Prefix the issue title with "BUG" Done.
* You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 
* What do you expect to happen? What does happen? 

I am unable to search, change settings, etc as I keep receiving a pop-up that mentions "You are not allowed to visit that section.. 5x, 4x, 3x, etc." I use unique internal domain names for all my services. I noticed that CSRF is enabled but I'm unable change as I can't save.

* Have you searched for this problem? You don't have to answer, just make sure. Yes
* Can the problem be reproduced? How? Install the recent update 2.7.4
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message. one
* If you use a docker container please tell me which one. Docker sucks, I don't use it. Podman 4 Life

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

## How to request a new feature
* Prefix your issue title with "REQ".
* What do you want to happen?
* If not clear, why do you want it?
* Do you think it's something only you need or something that might be popular?
* If need be explain the use case.

**Comment by thimslugga** [comment]
I think I'm back in business, I remembered the config file was nzbhydra.yml (I was looking for config.something) under the data dir after I had to fix install recently due to an update. I disabled csrf in nzbhydra.yml file and I can access + use the app once again.

**Comment by antigravity83** [comment]
Also receiving this error all of a sudden. 

You can't change the setting in the UI as it won't allow you to save it. 

Only fix is to change the config file manually.

**Comment by theotherp** [comment]
Oops, sorry. Fixed with next version.

**Comment by xconverge** [comment]
do I need to manually update now if I am on 2.7.4 and not using docker? Pressing update now tells me I am not allowed.

**Comment by theotherp** [comment]
Hydra should update automatically if you didn't disable that. Otherwise
shut it down and extract the latest release into your main hydra folder to
update manually.
