### ISSUE TITLE
All of a sudden Unable to Login running latest linuxserver docker image

### ISSUE THREAD

**Issue by feerlessleadr** [theotherp/nzbhydra2#449]
## How to create a bug report

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

As I am unable to login, I am not sure how I can enable debug logging. If there is a way to do it without login access, I will be happy to do so and upload. 

* What do you expect to happen? What does happen? 
When I try to access my NZBHydra install running on docker in Ubuntu Server, I am given the following error:

> An error occurred. Check the logs.
> Some details:
> Path  /login
> Query parameters
> Error	Forbidden
> Exception	
> Timestamp	Wed Oct 30 03:30:26 GMT 2019

When I check my nzbhydra2.log, I have the following:

> 2019-10-30 03:30:26.371  WARN --- [0.0-5076-exec-5] o.n.auth.AuthAndAccessEventHandler       : [Host: 192.168.1.1] Access denied to IP X.X.X.X: Could not verify the provided CSRF token because your session was not found.

I have tried restarting the container, as well as completely restarting my linux machine running the docker install to no avail.

I have been running this install without issue for the last number of months, so I'm not sure what might have happened. Additionally, it seems that the api is still working as expected, I am just unable to login to the interface itself. 

* Have you searched for this problem? You don't have to answer, just make sure.
I have searched and did not see this particular issue. 
* Can the problem be reproduced? How?
This happens every time I try to login, either from my external domain through nginx, or through local login directly over my local lan. 
* If you use a docker container please tell me which one.

> linuxserver/hydra2:latest

**Comment by feerlessleadr** [comment]
Please note that as I am unable to access the web interface, I am unable to enable debug logging, and also unable to access the link referenced by the nzbhydra2-bot above.

If there is an alternative way to enable/access debugging, I would be happy to do so.

**Comment by theotherp** [comment]
See #448
