### ISSUE TITLE
API Key for every user

### ISSUE THREAD

**Issue by RaymondSchnyder** [theotherp/nzbhydra2#45]
The more information you provide up front the higher the chance that I can help you.

## How to request a new feature
* What do you want to happen?
API Keys for every user i register

* If not clear, why do you want it?
So that a friend, which uses sonarr too, doesnt have to use my api key.

* Do you think it's something only you need or something that might be popular?
I think that would  be a semipopular feature

* If need be explain the use case.
I dont think this is needed.

Im not sure if this feature is already there and i didnt see it, or if you want to bring this into nzbhydra2.
If it is already planned / it exists already, please excuse my issue.

**Comment by theotherp** [comment]
I've had a similar discussion in v1.

But here I don't even understand the use case. What does it help you that you both have different API keys if there's no option to configure them? Do you expect them to appear in the stats or what?

**Comment by RaymondSchnyder** [comment]
@theotherp The use case is the following:
Lets say i have sonarr and my friend does too.
At the moment, we use the same API key, what means, all requests i and he make go through all my indexers.
Now i would like to have that every user has his own api key, so i can lookup in the stats which user used the most hits on my private indexers (In germany, indexers are rare and "elite", you can only join them by invite).

Do you understand what i mean?

**Comment by theotherp** [comment]
The last time a similar feature was discussed some people mentioned that anything that makes account sharing easier could make indexers hostile towards Hydra.

I'm not so sure but I still haven't decided what I think about the matter. I'll leave this open for now but will focus on bug fixes and some other features first.

**Comment by fryfrog** [comment]
This seems like something only a small portion of users would need. Most people will be setting this up for themselves, they won't care. A small number will be setting it up to share with friends and they'll be okay w/ using one api key. They also won't care. The only ones who *need* this are people who want to share, but don't trust who they're sharing with or need some way of differentiating usage.

**Comment by theotherp** [comment]
I agree.

But only a few people needing a certain feature has made Hydra what it is, for better or worse ;-)

**Comment by RaymondSchnyder** [comment]
@fryfrog @theotherp To specify my use case, i will share it with ONE person, which i know personally and is my friend.
I just want this feature for statistics, as its impossible right now to do that, because we share the api key right now.

**Comment by theotherp** [comment]
What stops him from running his own instance using your indexer API keys?

**Comment by RaymondSchnyder** [comment]
@theotherp I dont think private indexers like it when their indexer is visited through different ips on the same account... :/
But good idea.

**Comment by theotherp** [comment]
I'm closing this. Discussing how indexers would react to this feature is moot as it would be too much work for a highly specific use case anyway.
