### ISSUE TITLE
- Hydra2 API RSS Feed Ignoring '&cat='

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#452]
I am trying to produce an RSS feed from Hydra2 with ONLY posts from TV-SPORT (5060) rather than the larger complete/all TV posts (5000).
I have tried the following as per the Hydra2 GitHub docs:
( http://127.0.0.1:5076/api?apikey=myapikey&t=tvsearch&cat=5060 )
but the feed returned contains ALL the TV posts, NOT just the Sport.

Is this supported, if so what am i doing wrong.
If this is not supported, can this functionality be added please?
Thanks, Derek

**Comment by theotherp** [comment]
You need to define a new TV Sport category in Hydra which has only 5060 as newznab category configured.

**Comment by DerekWilliamsUK** [comment]
Simple when you know how !! Many thanks.
My NZBHydra2 RSS feed/search within SABnzbd now works as expected with ONLY TV-SPORT results.
