### ISSUE TITLE
Result filters settings not saving

### ISSUE THREAD

**Issue by stroodle96** [theotherp/nzbhydra2#453]
Hello,
I am trying to set Result Filters (Under config > searching).  I am able to enter my desired values but when I hit save they all get cleared and the fields are blank.  I have done all the standard backup/restore, start from scratch, reinstall common troubleshooting.  My instance is running inside a docker container linuxserver/hydra2.  I attached 2 images.  One image with the text entered before I hit save and one after I hit save when it clears the values.  Not all fields are cleared but the two fields I am trying to use do get cleared.  I am trying to use the forbidden words and posters fields.

The problem can be reproduced.  I tried all different configurations in that menu and the issue happens each time.

![after pressing save](https://user-images.githubusercontent.com/43659890/68074375-aa7d1780-fd70-11e9-80fe-adaac0a8ec40.png)
![Before pressing save](https://user-images.githubusercontent.com/43659890/68074376-aa7d1780-fd70-11e9-8c4f-5cb9b9492672.png)
[nzbhydra-debuginfos-2019-11-02-12-50.zip](https://github.com/theotherp/nzbhydra2/files/3800738/nzbhydra-debuginfos-2019-11-02-12-50.zip)

**Comment by theotherp** [comment]
You need to press the return / enter key to submit a text you put in.

**Comment by stroodle96** [comment]
Yeah that worked great.  Amazing how things function correctly when you follow the instructions lol.  Thank you!
