### ISSUE TITLE
- Manually adding new NZB Indexer not working

### ISSUE THREAD

**Issue by loungebob** [theotherp/nzbhydra2#454]
[nzbhydra-debuginfos-2019-11-03-20-23.zip](https://github.com/theotherp/nzbhydra2/files/3802015/nzbhydra-debuginfos-2019-11-03-20-23.zip)
Trying to add an NZB Indexer manually.

NZBHydra tries to check Caps but fails with error

 “Error while accessing indexer: Error while communicating with indexer WTFNZB. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure”

Using the URL directly works just fine for checking Caps.

https://0ccec98d8962a17294688363537bfe2e.wtfnzb.pw/api?t=caps�

I seem to be unable adding WtFnZb without the Caps check having completed successfully.

What do I need to do to get this solved?

**Comment by theotherp** [comment]
Try using this java version: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_windows_hotspot_11.0.5_10.msi Works fine for me with that on Windows 10.

**Comment by loungebob** [comment]
That did not change anything unfortunately. But uninstalling Java and rebooting as well as reinstalling Java made the error disappear and I was able to add the indexer and let the caps check run and pass. Thanks.
