### ISSUE TITLE
Cannot update to 2.7.7

### ISSUE THREAD

**Issue by HTPProXy** [theotherp/nzbhydra2#455]
I am trying to update NZBHydra 2 from 2.7.5 to 2.7.7 using the automatic update, but it gets stuck at "Downloading update file". I enabled the debug mode for logging, I attached the file because it is to long to be posted :)
[log.txt](https://github.com/theotherp/nzbhydra2/files/3821357/log.txt)

The software is running on a raspberry pi 4 started with the python script. The update file was downloaded and is placed in the update directory.

What could be the issue?

**Comment by theotherp** [comment]
You can just download the latest release from github and extract it into
your main hydra folder. Shut hydra down for that and overwrite any existing
files.

**Comment by HTPProXy** [comment]
Thank you for the help.

It seems that the timeout is just too short - the file size is increasing until the timeout occurs. The update file has now a file size of ~3 MB - I guess the connection could be to slow?

**Comment by theotherp** [comment]
Looks that way. But that is very slow, unusually slow.

**Comment by theotherp** [comment]
Closing this issue. If updates are still slow please let me know.
