### ISSUE TITLE
Track Indexer Expiration

### ISSUE THREAD

**Issue by hamiltont** [theotherp/nzbhydra2#456]
Many indexers have a 'pay once, leave it for a year' model. Would be neat to allow storing this 'premium plan expiration date' in nzbhydra, perhaps even the plan cost, and you could see a summary of your setup on the indexers page. Maybe even start to show warnings when you are getting close to your expiration date

**Comment by theotherp** [comment]
Mhmm... sounds like a premium feature ;-)

I'll think about it.

**Comment by hamiltont** [comment]
Awesome!
