### ISSUE TITLE
Sending to downloaders is permitted for all users

### ISSUE THREAD

**Issue by iruoy** [theotherp/nzbhydra2#459]
At the moment there are settings per user for their access to certain sections of NZBHydra.
I would like to add a settings called "May send to downloaders".

This is useful for me because I want to give 2 friends access, but don't want them adding downloads to my nzbget instance.

**Comment by theotherp** [comment]
The only scenario I can think of where this would make sense is account sharing as you would need to have different downloaders. I won't support that.
