### ISSUE TITLE
() Unexpected status SERVICE_STOPPED in response to START control.

### ISSUE THREAD

**Issue by runawaydevil** [theotherp/nzbhydra2#463]
Trying to install following the wiki.
Using win10.
Some idea?

**Comment by theotherp** [comment]
Start `nzbhydra console.exe` directly and see what it says.

**Comment by runawaydevil** [comment]
> Start `nzbhydra console.exe` directly and see what it says.

hello, I'm trying to find this exe but had no success. Where is located? 

Sorry to bother

**Comment by theotherp** [comment]
In the folder where you installed Hydra...

**Comment by runawaydevil** [comment]
> In the folder where you installed Hydra...

I did not install, I just unzip on my hard drive from github and used the wiki to install... and so this error... :(

**Comment by theotherp** [comment]
Yes, the folder where you unzipped it...

**Comment by runawaydevil** [comment]
> Yes, the folder where you unzipped it...

or I'm very dumb or I can't see it :(

![hydra](https://user-images.githubusercontent.com/8763225/68967856-ef1ca000-07bf-11ea-8294-685075d8ab92.PNG)

**Comment by theotherp** [comment]
You downloaded the source code. Download this: https://github.com/theotherp/nzbhydra2/releases/download/v2.8.4/nzbhydra2-2.8.4-windows.zip
