### ISSUE TITLE
Automatic API limit determination

### ISSUE THREAD

**Issue by brianjmurrell** [theotherp/nzbhydra2#466]
It would be useful if nzbhydra2 automatically determined API hit limits.  It would be a pretty simple algorithm.  nzbhydra2 would just need to keep track of how many API hits have been made to a given indexer over a given period of time.  If a limit is never reached at desired search frequency, it doesn't really matter what the limit is for that indexer -- it's beyond desired search frequency.

However if a limit is hit, looking at the recent history of hits, count how many hits since the last limit was reached to determine how many are allowed in a given time period.  Use that limit/period ratio to ration out API hits to each indexer over the the time period for that indexer.  Every time period should always try to make one more API hit than is currently calculated for that indexer to test for newer/higher limits being given.

**Comment by theotherp** [comment]
It's not as easy as you say. Some indexers reset the limit at midnight, others have a rolling time window. Some count downloads as API hits, others don't. Some count failed requests as API hits, others don't. You may also use the indexers in other programs directly which would affect the number of hits available. 

I like the idea but I'm not sure how reliable the results would be and testing it would potentially be really hard.

Actually at least one indexer software already reports the limits in the results XML. I'll implement a check for that and prefill the limits in the config. If other indexers (programs) support that it would make things a lot easier.

**Comment by brianjmurrell** [comment]
I see.  Rolling/midnight/other-arbitrary-reset-time is probably also determinable over a few days to a week.

One could also probably determine what counts as API hits and or download hits, again, by analysing a history.

But I agree, if that's how much things vary from indexer to indexer, the algorithms would be more difficult.

**Comment by theotherp** [comment]
That's as good as it gets :-)

**Comment by dimqua** [comment]
@theotherp only few indexers currently support automatic detection. Is it possible to add such support for other indexers? Such as abNZB, NinjaCentral, NzBNooB, Tabula-Rasa, NZBs2GO, etc.

**Comment by theotherp** [comment]
No. How would I do that?

You can only as them to implement that.
