### ISSUE TITLE
adding spotweb indexer

### ISSUE THREAD

**Issue by modparts** [theotherp/nzbhydra2#469]
When I want to add my spotweb indexer I get the following error,

> The` connection to the indexer failed: Error while communicating with indexer spotweb. Server returned: java.io.IOException: URL call to http://spot.modparts.be/api?apikey=(apikey)=search returned 403: Forbidden

When I choose "i know what I’m doing", it is disabled because the caps check does not work.

I have tried this:
- spotweb on my hosting webserver
- spotweb on a fresh Ubuntu 18.04
- spotweb in a docker container (jgeusebroek/spotweb) on Ubuntu server
- spotweb in docker container (jgeusebroek/spotweb) on a synology nas

Always the same error.
It did used to work on an old nzbhydra version.

If it can help you, I can give u a login, pass and api key for the spotweb on my hosting webserver, that I can remove again later.

[nzbhydra-debuginfos-2019-11-30-04-13.zip](https://github.com/theotherp/nzbhydra2/files/3906705/nzbhydra-debuginfos-2019-11-30-04-13.zip)

**Comment by theotherp** [comment]
I  guess the API call works from your browser?

Could you please try running NZBHydra inside a docker container and see if it works there?

I had another user who had a similar problem when trying to reach a certain indexer and just reinstalling worked for some reason. There's not much I can do, Hydra does a regular HTTP get call to the URL and returns 403 for some reason.

**Comment by modparts** [comment]
Yes, the api call works on my browser.

I tried 2 docker containers (theotherorp/nzbhydra2) and (linuxserver/hydra2) both latest versions, I get the same error

Is there any other indexer I can use instead of spotweb?

**theotherorp**
[nzbhydra-debuginfos-2019-11-30-12-09.zip](https://github.com/theotherp/nzbhydra2/files/3907065/nzbhydra-debuginfos-2019-11-30-12-09.zip)
**linuxserver**
[nzbhydra-debuginfos-2019-11-30-12-38.zip](https://github.com/theotherp/nzbhydra2/files/3907066/nzbhydra-debuginfos-2019-11-30-12-38.zip)

**Comment by theotherp** [comment]
Animetosho is available in the presets and free to use.

**Comment by modparts** [comment]
that is only for anime?

**Comment by theotherp** [comment]
I thought you wanted to just test the connection. See https://old.reddit.com/r/usenet/comments/e1zer3/black_friday_deals_megathread/ Now is a good time to get access to an indexer or two.

**Comment by modparts** [comment]
Thanks for the link

After 4 days of installing, reinstalling and testing i gave up.
a few hours later i try again and now it's working :)
