### ISSUE TITLE
- Unable to add NZBGet

### ISSUE THREAD

**Issue by nuentes** [theotherp/nzbhydra2#472]
This is not a bug report - I can almost guarantee this is an issue on my end, and just me not fully understanding things.

I can't seem to add NZBGet as a downloader. When I try to add nzbget, I receive a "Connection check failed" error, and the log says "Connection timed out". NZBGet and NZBHydra live on the same server, however nzbhydra is running within docker (Linuxserver.io). I access NZBGet in my laptop browser via http://192.168.1.219:7898/, which is what I'm entering into NZBGet. I am entering the correct username/password, however I'm clearly receiving a connection failure, so that wouldn't point to a credential issue anyway. In NZBGet, I have authorized IPs listed as 192.168.1.*, which is my local network. I also added 172.17.0.* which should include the nzbhydra docker container.

I'm not having any other NZBGet issues. I'm doing something stupid. Anybody have any ideas of what I'm not thinking of? Because I can't find anything.

Nzbget is in version 21.0
Hydra is in version 2.10.0

**Comment by theotherp** [comment]
So, what was it?
