### ISSUE TITLE
Tokenize text input like gmail tokenizes email addresses

### ISSUE THREAD

**Issue by eriksneff** [theotherp/nzbhydra2#474]
After trying and failing to enter forbidden words, googling it, and arriving here:

https://github.com/theotherp/nzbhydra2/issues/453

I felt the desire to request an improvement. The current way of requiring an `enter` keypress to tokenize a forbidden word, while technically works, was for me pretty much the definition of unintuitive, or worse, undiscoverable. I think this may partially be because I'm accustomed to how well gmail handles tokenizing email addresses. There, you type something, hit comma or space, and presto, what you just typed is tokenized. Tab does the same thing. Even paste a bunch of stuff containing commas or spaces, and each element is instantly tokenized as soon as you paste it. Give it a shot - I'm not sure if there's some reason you can't follow that pattern, but hopefully you can, and if so, I think you'll agree it's an improvement on how Forbidden Word entry happens now in hydra2.

Thanks, keep up the incredible work!!

**Comment by theotherp** [comment]
It's a library I use and I don't have control over how it behaves. This is as good as it gets, unfortunately.
