### ISSUE TITLE
Ability to set paths for logging backup functions

### ISSUE THREAD

**Issue by ryanwalder** [theotherp/nzbhydra2#475]
I would like the ability to set the paths for logging and backups (maybe with the ability to specify the filename as well? The space in the backup name kills me as a linux user :smile:)

This would allow more flexibility so I could use `/var/log/nzbhydra/` for logging rather than `$datafolder/logs` and have backups go to a mounted NFS share for example.

**Comment by theotherp** [comment]
I currently don't plan to support that.

Have you tried just creating symlinks?

**Comment by ryanwalder** [comment]
Fair play, I use symlinks at the moment so I'll carry on using symlinks.
