### ISSUE TITLE
Instance matching query does not exist

### ISSUE THREAD

**Issue by PeterPan669** [theotherp/nzbhydra2#476]
[nzbhydra-debuginfo-2019-12-26-04-00.zip](https://github.com/theotherp/nzbhydra2/files/4001196/nzbhydra-debuginfo-2019-12-26-04-00.zip)

* What do you expect to happen? What does happen? 
Medusa -> NZBHydra -> SABNZBD
Medusa sends a fetch to SabNZBD, which then is unable to fetch it. It ends with the error "number of tries exceeded". It says (e.g.) "Trying to fetch from http://localhost:5075/getnzb?apikey=1A5B36393856C6BE4690D26904AA367C&searchresultid=f11f66d60228e316f5fe456dc29", then tries again until it fails. In the logs from NZBHydra it says:

"2019-12-26 04:00:10,006 - ERROR - web - Thread-1624 - Instance matching query does not exist:

SQL: SELECT "t1"."id", "t1"."indexer_id", "t1"."firstFound", "t1"."title", "t1"."guid", "t1"."link", "t1"."details" FROM "searchresult" AS t1 WHERE ("t1"."id" = ?)
"

I expect that Sab should fetch the correct NZB via Hydra.

* Have you searched for this problem? You don't have to answer, just make sure.
Yes, only 1 relative hit from 2 years ago:
https://www.reddit.com/r/usenet/comments/6okcng/nzbhydra_not_working_after_latest_update_02222/

* Can the problem be reproduced? How?
None of the downloads / indexers work. It did work properly a couple of days ago.

Running on a Synology. No issues before yesterday. No changes either.

**Comment by theotherp** [comment]
You're using python based v1 which I don't support anymore. That's the
reason why you can't create a bug ticket on its project page.

**Comment by PeterPan669** [comment]
Hi,
So, what are my options? Would upgrading to Python v3 solve this issue?

**Comment by theotherp** [comment]
You can always upgrade to nzbhydra2.

**Comment by PeterPan669** [comment]
Hi,

Thanks for the reply. I was under the impression I was running NZBHydra2, but it turns out that's not the case. I installed it via DSM (Python version is 2.7, hence I didn't understand your earlier comment), but this explains it. Thanks, I will test with the new version and will open up a new one if required.
