### ISSUE TITLE
 ERROR - Unable to determine java version - Synology DSM6 install

### ISSUE THREAD

**Issue by PeterPan669** [theotherp/nzbhydra2#477]
Hello,

Following your comment on https://www.reddit.com/r/usenet/comments/b1s0hg/nzbhydra2_on_synology_ds214/, I'm trying to install NZBHydra2 on my Synology nas (DSM6). I use this source: https://github.com/theotherp/nzbhydra2/releases/download/v2.3.16/nzbhydra2-2.3.16-linux.zip and this wrapper: https://raw.githubusercontent.com/theotherp/nzbhydra2/master/other/wrapper/nzbhydra2wrapper.py.

I have Java 8 installed, but I get the following error when trying to install it: 

Logging wrapper output to /volume1/@appstore/nzbhydra2/data/logs/wrapper.log
2019-12-27 16:13:49,798  INFO - No file nzbhydra.yml found. Using 256M XMX
2019-12-27 16:13:49,864  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: [Errno 2] No such file or directory

Maybe I am going at it totally wrong, so my real question:
How can I install NZBHydra2 on my Synology nas (not using Docker)?

Thanks again.

**Comment by theotherp** [comment]
The path to your java executable can't be found. Make sure it's contained in the `path` variable. You can also use the `-- java` parameter to provide the full path to the executable.

**Comment by PeterPan669** [comment]
Not sure what happened, but after re-logging into SSH and trying again ca. 1 hour later, it installed. Thanks :)
