### ISSUE TITLE
Starting NZBHydra2 via DMS / Synology

### ISSUE THREAD

**Issue by PeterPan669** [theotherp/nzbhydra2#478]
Hello,

After successfully being able to install / start NZBHydra2 via SSH on DSM6 (Synology), I would like it to run (and keep running) without having to start it via SSH. I created a task to start the package: 
python /volume1/@appstore/nzbhydra2/nzbhydra2wrapper.py --java /var/packages/Java8/target/j2sdk-image/jre/bin/java

It starts well, only to fail with the following output:

[2m2019-12-27 23:21:39.653[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.nzbhydra.tasks.HydraTaskScheduler   [0;39m [2m:[0;39m[35m [0;39m[34m[0;39mScheduling task "Delete old search results" to be run every 1 hour
[2m2019-12-27 23:21:39.873[0;39m [31mERROR[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.b.d.LoggingFailureAnalysisReporter  [0;39m [2m:[0;39m[35m [0;39m[34m[0;39m

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 5001 was already in use.

Action:

Identify and stop the process that's listening on port 5001 or configure this application to listen on another port.

[2m2019-12-27 23:21:39.896[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.nzbhydra.NzbHydra                   [0;39m [2m:[0;39m[35m [0;39m[34m[0;39mShutting down and using up to 15000ms to compact database
[2m2019-12-27 23:21:39.930[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.zaxxer.hikari.HikariDataSource      [0;39m [2m:[0;39m[35m [0;39m[34m[0;39mHikariPool-1 - Shutdown initiated...
[2m2019-12-27 23:21:39.950[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.zaxxer.hikari.HikariDataSource      [0;39m [2m:[0;39m[35m [0;39m[34m[0;39mHikariPool-1 - Shutdown completed.
[2m2019-12-27 23:21:39.981[0;39m [31mERROR[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.nzbhydra.NzbHydra                   [0;39m [2m:[0;39m[35m [0;39m[34m[0;39mAn unexpected error occurred during startup

org.springframework.boot.web.server.PortInUseException: Port 5001 is already in use
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:297)

---

What I don't understand, is why does it start fine using SSH, but when running as a task, it gives an issue regarding port 5001? (DSM runs on this btw).

Thanks again.

**Comment by theotherp** [comment]
I don't know anything about Synology and Tasks. Have you tried just using a different port?

**Comment by PeterPan669** [comment]
Hello,

The task is basically a cronjob that runs a command under a certain user. So it's the same command I use to start NZBHydra2, but via cron, not via SSH / terminal. I can try changing NZBHydra2 from port 5076 to e.g. 5077, but I wonder if that makes any difference. It seems that (according to NZBHydra2's output), it tries to start the webservice on 5001, while via SSH it simply starts on 5076. I'll give it a whirl and post back with the 2 different outputs.

**Comment by theotherp** [comment]
Make sure the process is started from its main directory.

**Comment by PeterPan669** [comment]
Unfortunately, NZBHydra2 still fails to start via cronjob with the error:
"Web server failed to start. Port 5001 was already in use."

The command I use to run it is the same in both SSH and cronjob: "cd /volume1/@appstore/nzbhydra2/ && python /volume1/@appstore/nzbhydra2/nzbhydra2wrapper.py --java /var/packages/Java8/target/j2sdk-image/jre/bin/java"


I tried the following:
- Change into directory (also tested it without changing into directory) via SSH, and via Cronjob; No difference. SSH starts successful, Cronjob fails.
- Changed NZBHydra host & port to something different (192.168.2.10 / 5077). No difference.
- Running under different users (root vs other user); No difference.
- Running different type of cronjob (at bootup vs. triggered start); No difference.

I've enclosed 3 files with output:
failed.txt (started at 2019-12-28 16:15:10,197);
success.txt (started at 2019-12-28 16:18:08,628);
nzbhydra-debuginfos-2019-12-28-16-28.zip; The NZBHydra2 debug logging, capturing both events.


To recap the issue:
Via SSH / Terminal session, it starts without any issues.
Via cronjob, it fails to start the webserver (Port 5001 was already in use).

I'm not sure why there is a difference in this. DSM is running on Port 5001, so why Tomcat tries to claim that port, even when NZBHydra2 has a different port configured, is beyond me.

Hopefully you can find the culprit here; Or, maybe you (or someone else) could advise how to set up NZBHydra2 to auto-start on Synology (like a service).

Many thanks again for your hard work and diligence!

[failed.txt](https://github.com/theotherp/nzbhydra2/files/4007155/failed.txt)
[success.txt](https://github.com/theotherp/nzbhydra2/files/4007156/success.txt)
[nzbhydra-debuginfos-2019-12-28-16-28.zip](https://github.com/theotherp/nzbhydra2/files/4007157/nzbhydra-debuginfos-2019-12-28-16-28.zip)

**Comment by PeterPan669** [comment]
Not sure if it is related, but after installing Python3, and restarting the NAS, suddenly it starts without issues :) I guess this is solved then.... Thanks for your time!
