### ISSUE TITLE
indexers not being added?

### ISSUE THREAD

**Issue by soupy14** [theotherp/nzbhydra2#48]
I noticed a few of my indexers are red when testing them in hydra I get this seems only happening with omg.
Error testing capabilities
An error occurred while contacting the indexer. It will not be usable until the caps check has been executed. You can trigger it manually from the indexer config box.

Than follow by Error testing capabilities
An error occurred while contacting the indexer. It will not be usable until the caps check has been executed. You can trigger it manually from the indexer config box.

I have ran the Check capabilities several times, still same issues, check paste bin not sure of those logs help only thing thus far I found with omg in it. 

https://pastebin.com/ywmad7Mc

**Comment by theotherp** [comment]
Post the debug Infos.

Am 10.01.2018 05:15 schrieb "soupy14" <notifications@github.com>:

**Comment by soupy14** [comment]
https://pastebin.com/stmYiRcB

**Comment by theotherp** [comment]
Yeah, well, your log is full of errors from indexers where you have reached your daily API limits.

**Comment by soupy14** [comment]
odd it wont allow me to even turn it on though when other indexers do, i'll try to delete it than re add. 

thank you
