### ISSUE TITLE
Add option to control how often backups are created

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#481]
Some users with systems crashing often might want to create backups more often.

**Comment by ahughes03** [comment]
Thanks for making this happen so quickly. I'm running the program in a Linuxserver.io container, and just upgraded using the linuxserver/hydra2:v2.10.9-ls1 tag. I'm not seeing an option to set the backup frequency in the config page. 

My logs show I'm running hydra2/lib/core-2.10.9-exec.jar, so I believe I'm upgraded to the newest version. Any thoughts?

**Comment by theotherp** [comment]
You're right, the UI code responsible for actually showing that field wasn't properly compiled. It should be shown now in 2.10.10
