### ISSUE TITLE
Guest Accounts Not Working in Chrome but Working in IE

### ISSUE THREAD

**Issue by kramer987** [theotherp/nzbhydra2#483]
so basically, the title says it all.  If i create a guest account for someone and they try to run it in chrome, hydra doesn't work.  they can log in and begin the search, but when it displays the windows showing the number of hits for each indexer, it just hangs once it reaches the end of the search.  It will just sit there.  

This doesn't happen on my local machine where I run hydra.  But if i navigate to a guest hydra account on Chrome, i also get the hanging issue.  But installing IETab and opening the guest account in chrome through IETab solves the issue.  So the issue is something to do with Chrome.

**Comment by kramer987** [comment]
not sure how to get the debug log for this because this only happens for guest accounts

**Comment by kramer987** [comment]
[nzbhydra-debuginfos-2020-01-08-11-20.zip](https://github.com/theotherp/nzbhydra2/files/4036232/nzbhydra-debuginfos-2020-01-08-11-20.zip)

**Comment by kramer987** [comment]
there's the debug log

**Comment by theotherp** [comment]
Cannot reproduce this, works fine in any browser.

Please provide a more specific example, e.g. what you're searching for, how many indexers involved, etc.

Also check your browser for any errors (press F12, see console).

**Comment by kramer987** [comment]
ok let me be more specific.  first, this happens on chrome on my pc, my father's pc, my friend's pc, etc.  happens on chrome anywhere i try and i tried a bunch of different machines.

here's a specific example.  i open chrome.  i navigate to a guest hydra account, i.e. http://login:password@myip:5076.  i search for let's say expanse s02 or something.  and it will begin the search and then just sit there.  see pic below.

![image](https://user-images.githubusercontent.com/42621656/72013806-9bad5800-322c-11ea-8b9e-e6e486334b6d.png)

HOWEVER.  here's another example.  I open chrome on the same machine.  i navigate to the admin hydra account, i.e., http://localhost:5076.  i search for exapnse s02 and its fine.  the search completes no problem.

and here's a final example.  I open IE or Firefox on the same machine.  i navigate to the guest hydra account, i.e., http://login:password@myip:5076.  i search for expanse s02.  the search completes without any issue.

**Comment by theotherp** [comment]
Still can't reproduce this, sorry. The only way I can think of to debug this would be if you sent me username and password and the URL to your instance (provided it can be reached via internet).
