### ISSUE TITLE
Main Search not showing torznab results, unless NZB indexers unchecked

### ISSUE THREAD

**Issue by PeterPan669** [theotherp/nzbhydra2#486]
* What do you expect to happen? What does happen? 
I have several NZB indexers, amongst others NZBGeek and 2 Torznab indexers via Jackett.
When searching, it does find Tornzab results, but doesn't show them in the results list if NZBGeek indexer is also checked.
If I uncheck NZBGeek, it does show the Torznab results.

* Can the problem be reproduced? How?
Add NZBGeek as indexer, add Torznab indexers MVGroup via Jackett. Search for something.

OS:
Synology, no docker.

[nzbhydra-debuginfos-2020-01-11-13-31.zip](https://github.com/theotherp/nzbhydra2/files/4049327/nzbhydra-debuginfos-2020-01-11-13-31.zip)

**Comment by theotherp** [comment]
Please make full screenshot of the browser tab with NZBHydra and the indexer statuses tab expanded. Create new debug infos and post them as well.

**Comment by PeterPan669** [comment]
Hello,

I've solved it by setting up a second instance of NZBHydra and dedicating it to the Torznabs.

Thanks!

**Comment by theotherp** [comment]
Well, that's one way...
