### ISSUE TITLE
NZBFinder RSS Updates

### ISSUE THREAD

**Issue by mikestecker** [theotherp/nzbhydra2#488]
I received an email from NZBFinder about their RSS URL updates. Here is a link to their updated info: https://nzbfinder.ws/rsshelp

**Comment by theotherp** [comment]
Thanks for the info. Did you just want to let me know? I don't think I need to change anything for Hydra to work with nzbfinder.

**Comment by mikestecker** [comment]
> Thanks for the info. Did you just want to let me know? I don't think I need to change anything for Hydra to work with nzbfinder.

Yeah, I was just passing this along. I didn't know if you needed to change anything or not.

**Comment by theotherp** [comment]
Alright, thanks. If it doesn't work for you please let me know.
