### ISSUE TITLE
Private API hit / downlad limit in indexer status

### ISSUE THREAD

**Issue by jayme-github** [theotherp/nzbhydra2#489]
It would be nice to have an overview of hydras state on API / download hits per indexer and reset time on the "indexer statuses" page.

When doing an internal search indexers with API / download limit reached are marked accordingly (in the "Indexer statuses" widget after search) but this is not reflected in the "indexer statuses" page.

Checked with hydra 2.11.2

**Comment by theotherp** [comment]
Good idea, I like it. Shouldn't be hard to do.
