### ISSUE TITLE
Cannot check caps on NZBGeek due to trustAnchors error

### ISSUE THREAD

**Issue by Routhinator** [theotherp/nzbhydra2#491]
Since NZBGeek upgraded their minimum TLS version to 1.2 this month I have been unable to check caps on their indexer due to the following error:

```
Error while accessing indexer: Error while communicating with indexer NZBGeek. Server returned: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```
I have tried reinstalling my java, rolling back to a previous snapshot of the vm, and upgrading to java 11, with no change in the error.

**Comment by Routhinator** [comment]
[nzbhydra-debuginfos-2020-01-19-08-37.zip](https://github.com/theotherp/nzbhydra2/files/4082949/nzbhydra-debuginfos-2020-01-19-08-37.zip)

**Comment by theotherp** [comment]
I've just released a version with better debugging of SSL issues.

Please do the following:
1. Update to 2.11.1
2. In the main config enable the logging marker "HTTPS"
3. Restart Hydra
4. Execute the caps check for nzbgeek
5. Create the debug infos zip and post them here again
6. Disable the logging marker again and restart Hydra (otherwise it will write a huuuge file in the logs folder).

Thank you.

It's not a general issue with NZBHydra as it works fine on my machine.

**Comment by Routhinator** [comment]
Ah, needed a restart after enabling that, missed that bit on the other post. I was already on latest.

I've applied the changes and restarted, unfortunately there's no more useful info in the error. Looks exactly the same...

![Screenshot from 2020-01-20 07-47-22](https://user-images.githubusercontent.com/727535/72740387-6a9d2380-3b5a-11ea-8269-642e902860ae.png)

![Screenshot from 2020-01-20 07-54-10](https://user-images.githubusercontent.com/727535/72740396-6d981400-3b5a-11ea-83ce-8decad8a4dc1.png)
[nzbhydra-debuginfos-2020-01-20-07-55.zip](https://github.com/theotherp/nzbhydra2/files/4086960/nzbhydra-debuginfos-2020-01-20-07-55.zip)

**Comment by theotherp** [comment]
The SSL infos are in a different file, all good.

**Comment by theotherp** [comment]
It looks like there's something wrong with your java installation or, to be more precise, with its certificates.

Java loads the file `/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts` but the root certificate needed to validate nzbgeek's is missing there. Could you please post that file here so I can reproduce it?

On your end you could copy the file somewhere as a backup and replace it with this one: [cacerts.zip](https://github.com/theotherp/nzbhydra2/files/4087306/cacerts.zip)

Restart NZBHydra and see if it works now.

**Comment by Routhinator** [comment]
Here is my copy of the cacerts file

[Uploading cacerts.zip…]()

It should be noted that as part of the troubleshooting process, I installed the openjdk-11-jdk packages from the Ubuntu repositories from scratch, it was not on the system previously, so not likely to be corrupt, but maybe out of date.

Switching it for your copy resolves the issue, and NZBGeek works again.

Oh java, if only you would use the systems PKI certs, instead of shipping your own. :)

**Comment by Routhinator** [comment]
[cacerts.zip](https://github.com/theotherp/nzbhydra2/files/4087546/cacerts.zip)

**Comment by theotherp** [comment]
Well, that's good to hear (I guess?)

I tested it with your cacerts file and it doesn't work and then I enabled the usage of the packaged cacerts file and it works now. 

So it looks we didn't only find a solution for you but a general one for everyone else with that problem, right?

**Comment by Routhinator** [comment]
Ahhh didn't see that packaged cacerts option before, tried it and it works for me as well

I call this resolved.
