### ISSUE TITLE
500: Internal Server Error  Path: /internalapi/downloader/SABnzbd/categories

### ISSUE THREAD

**Issue by iqy90** [theotherp/nzbhydra2#493]
Message: I/O error on GET request for "http://XXXXXX-sabnzbd.cloud.seedboxes.cc/api": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Hi, can you please check for this error??
I'm using nzbhydra in my seedboxes. Since the technical support team cannot identify and fix this problem, they ask me to issue the problem here.
Everytime when I click the "send to sabnzbd" , the occurs above appear.
This is my first time, please tell me what should I provide ?

**Comment by theotherp** [comment]
Looks like the same as #494. Closing this
