### ISSUE TITLE
: Failed to add Sabnzbd downloader. (seedboxes.cc)

### ISSUE THREAD

**Issue by iqy90** [theotherp/nzbhydra2#494]
Hi, I have problem to add sabnzbd in download section.
The error sounds:
The connection to the downloader failed: I/O error on GET request for "http://xxxxxxxx-sabnzbd.cloud.seedboxes.cc/api": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Can you please check??
[nzbhydra-debuginfos-2020-01-26-13-20.zip](https://github.com/theotherp/nzbhydra2/files/4113176/nzbhydra-debuginfos-2020-01-26-13-20.zip)

**Comment by theotherp** [comment]
Please try with latest release

**Comment by iqy90** [comment]
> Please try with latest release

Thank you so much! The error gone.
