### ISSUE TITLE
Titles with apostrophe is not returning results in Hyrda

### ISSUE THREAD

**Issue by timc6896** [theotherp/nzbhydra2#498]
[nzbhydra-debuginfos-2020-02-01-18-18.zip](https://github.com/theotherp/nzbhydra2/files/4143644/nzbhydra-debuginfos-2020-02-01-18-18.zip)
I have Hydra2 configured in Sonarr.  The search in Sonarr returns the correct result for "Winter's Tale".  The search within Hydra2 returns the correct result in Winter's Tale.  The search from Sonarr to Hydra2 does not return anything.  Upon looking at the log, it looks like it is getting rid of the apostrophe and searches for Winters Tale which doesn't return anything.  Is there a config somewhere that I missed to fix this?

**Comment by theotherp** [comment]
I NEED THE DEBUG INFOS ZIP!!!

**Comment by timc6896** [comment]
Just attached the zip

**Comment by theotherp** [comment]
Fixed in new release.

**Comment by timc6896** [comment]
Confirmed working!  You rock :)

**Comment by theotherp** [comment]
Could you please tell me which of the trackers required the apostrophe? It looks like the majority of trackers prefer the apostrophe to be removed. I might add some logic that does not remove the apostrophe for certain trackers.
