### ISSUE TITLE
Dognzb keeps showing up as disabled

### ISSUE THREAD

**Issue by AtariBaby** [theotherp/nzbhydra2#499]
On Windows 10 Pro 1903

I keep finding that DogNZB is disabled. Here is what it says on the indexer stats page, and the little brown x means disabled right? I can manually re-enable it in config and save but then within a moment I go to this page and find the brown x.

DogNZB |   | 2020-02-03 20:29 |   | 157/3000 | 1

[nzbhydra-debuginfos-2020-02-03-20-27.zip](https://github.com/theotherp/nzbhydra2/files/4151425/nzbhydra-debuginfos-2020-02-03-20-27.zip)

**Comment by theotherp** [comment]
The connection times out very often, even with a timeout of 20 seconds. You should contact the admins and try and find out why.

**Comment by AtariBaby** [comment]
Lol it’s the least i can do. It’s amazing work you’ve done.

**Comment by AtariBaby** [comment]
Quick update. A lot of people are complaining about timeouts in recent months, with no real response from their support. Probably having server woes. I guess close it since it’s not the fault of hydra

**Comment by theotherp** [comment]
I haven't had an active account on there for years but even then the API was often unreachable for a while. When it was the connection was very slow.
