### ISSUE TITLE
Create packages for NAS, etc.

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#5]
No packages exist for Synology or any other distrubutions. I have no idea how to do that.

**Comment by fryfrog** [comment]
Some time today, I'll create an Arch AUR package for it. :)

**Comment by theotherp** [comment]
Nice

**Comment by fryfrog** [comment]
https://aur.archlinux.org/packages/nzbhydra2/

^ It is up and it works.

I have some concerns about the `lib` dir, which is going to end up containing extra core files when the *package* updates. Right now, nzbhydra2 errors on this condition. For the package, I could clean the directory post installation of all but that versions file. Or maybe nzbhydra2 could just use the latest one? :/

I'm also having migration issues, but will post a new issue for that.

**Comment by theotherp** [comment]
Thank you.

See #22

**Comment by Thefrank** [comment]
BSD or Freshports package would be nice too
thanks!

**Comment by fryfrog** [comment]
If there is already an nzbhydra package, I'd ping the maintainer.

**Comment by fryfrog** [comment]
And binhex has a docker image up, I'm confident this will be the best one available.

https://hub.docker.com/r/binhex/arch-nzbhydra2/

**Comment by theotherp** [comment]
I have no idea how that container works and where it gets the actual code/package from...

**Comment by fryfrog** [comment]
I think he's just copied over and started a skeleton, the [Dockerfile] (https://github.com/binhex/arch-nzbhydra2/blob/master/Dockerfile) has an unfilled section for install the app. I suspect he'll download releases and extract to the right place.

**Comment by titocr** [comment]
binhex/arch-nzbhydra2 does seem to be working now.

**Comment by theotherp** [comment]
I'm also working with the people of linuxserver.io to get their docker to run with unRAID which seems to make some problems.

**Comment by fryfrog** [comment]
@theotherp: Is the `nzbhydra2wrapper.py` script going to be a stable part of nzbhydra2? I'd like to modify my AUR package to use it so that it will work on box x86 and arm.

**Comment by theotherp** [comment]
It should stay for a while and hopefully not need any more updates for some
time.

Am 15.01.2018 4:33 vorm. schrieb "Donald Webster" <notifications@github.com

**Comment by theotherp** [comment]
Considering this closed until specific requests come in.
