### ISSUE TITLE
Also use NZBGET hidden results for Download status 

### ISSUE THREAD

**Issue by crypto-vault** [theotherp/nzbhydra2#500]
Why not support NZBGET hidden history also for download status results?

Currently nzbhydra2 only searches not hidden results for the download status, but if user has “Remove from history” option enabled in Sonarr/Radarr then nzbhydra2 will not know about the download status. 

Anyway, “Remove from history” moves the result to hidden status so it’s still queryable. 

With this change, Download status in Download History and Success rate in Stats would work regardless of “Remove from history” in Sonarr/Radarr being enabled or not.

**Comment by theotherp** [comment]
Yeah, that's just an oversight - good point, thanks.

**Comment by crypto-vault** [comment]
I tested this in v2.13.4+ but still doesn't seem to be fixed. It's still not marking download status if result are in NZBGET hidden history:

v2.13.4 (2020-02-08)
Fix Include hidden results from NZBGet history when checking download status. That way entries removed by *arr and other programs will be considered, too.

**Comment by theotherp** [comment]
I've updated the code to request hidden items from the history. Are you sure they're actually just hidden and not removed completely?

**Comment by crypto-vault** [comment]
Yes, I triple checked this now. version now is v2.13.5.

Items that stay in history (not hidden) are marked as downloaded/failed correctly.

Items that go to the hidden history are simply not marked at all, they just stay as NZB_ADDED.

I have Dupecheck ON (default value) in NZBGET which correctly moves items to hidden (instead of deleting them completely from history) and have confirmed those items not marked in nzbhydra2 are indeed in hidden history with respective success/failure/deleted status.

**Comment by theotherp** [comment]
You're right. The issue was that the hidden entry has different entries filled which prevented a proper matching. Should've tested it (better). Should work now.

**Comment by crypto-vault** [comment]
It's working now with v2.13.6. One more thing. If a download fails with a certain filename in one indexer.. but right after it gets a successful download on another indexer then history marks both as sucessful.

I presume this happens because nzbhydra2 is looking up based on filename. Doesn't it lookup history based on ID? Not sure if NZBGET history ID is first know to nzbhydra2 in the first place, so that it can lookup based on ID instead of filename (which could be the same but different indexers/downloads).

**Comment by theotherp** [comment]
You're right, I forgot about that scenario.

If Hydra is the one adding the download to the downloader then it has an ID by which it can identify the history entry. When *arr downloads it and sends it to the download then it doesn't know the ID.

Nevertheless, currently I identify matching history entries whenever the name *or* ID match. I'll update it so that the ID is checked first so that, when it exists, other entries with the same name won't be matched.

**Comment by theotherp** [comment]
Hm, I realized it's a bit more complicated than that. I'll have to to take closer look on the weekend.

**Comment by crypto-vault** [comment]
You are right, if it’s an arr* downloader it would make things harder for nzbhydra2 to know the ID. Well, it’s not critical, it’s just stats. :)
