### ISSUE TITLE
Use Query Generation When ID unsupported

### ISSUE THREAD

**Issue by Elehiggle** [theotherp/nzbhydra2#503]
Sometimes I get the following error when searching for a TV show: "Indexer returned error code 203 and description 'Function Not Available: imdbid is not supported for TV search by this indexer'"

But I also have Generate queries set to "All searches" (Generate queries for indexers which do not support ID based searches). 

This error comes from a misconfigured indexer (in my case, Torrenttracker via Jackett), because I have checked TVIMDB as Search IDs, even though it does not support it.

What I propose is that Hydra retries with the query instead of the unsupported imdb when this error is returned. Given, its a comfort feature. But this has gone unnoticed to me for a year and I finally had the time to look why certain results weren't appearing even though they are on the tracker itself when I manually search there. 

Cheers

**Comment by theotherp** [comment]
When you add an indexer Hydra checks for its capabilities, recognizing all supported IDs. So if I understand you correctly you manually enabled TVDB IDs in the indexer's config. Why did you do that?

The error you describe is the result of misconfiguration so I don't see why I would implement a feature that only is needed when the program's proposed config is "willfully" changed by the user.

**Comment by Elehiggle** [comment]
It is possible that the tracker changed their supported capabilities. I'm not sure whether I manually set that or not (other trackers didn't have it enabled in Hydra). 

If you don't plan on implementing this feature, I would suggest to change the description of the Generate queries function to "Generate queries for indexers which do not support ID based searches, unless it is overridden by the indexer's capabilities you have specified" to make it more clear what it does and what it does not. I probably would have checked a second time if the description was a bit more detailed. 

Thanks!
