### ISSUE TITLE
Set a default Search Category

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#505]
Would it be possible to have an Option to select a Default Search Category. Whenever i open the Search tab 'Search - All' is the default. I would like the Option to select any available Category as the default - I would choose 'TV HD' as this is what i have to manually select most of the time.
Thanks for your consideration.
![Preselect TV-HD Search Category](https://user-images.githubusercontent.com/18551763/74732184-9ab31180-5241-11ea-88c1-1d1ed1d4e513.jpg)

**Comment by theotherp** [comment]
Done

**Comment by DerekWilliamsUK** [comment]
Excellent - works great.
Thanks
