### ISSUE TITLE
Downloading stopped working (failed: 404 Not Found)

### ISSUE THREAD

**Issue by Miicker** [theotherp/nzbhydra2#506]
Since a few days ( 2 or 3 days) not a single download completes. I use Medusa to search for a episode. It snatches the episode from Hydra and sends it to NZBGet. This has always worked.

Now all of the suddon every download fails. I can see in NZBGet that this is the message:
URL name.of.the.episode @ hydra failed: 404 Not Found

When I perform a manual search in Hydra and send it to NZBGet it also fails. But when I download an NZB file and upload it to NZBGet it does work. Any idea on how to solve this and why this became a problem all of the sudden?

I am running Hydra in docker version: 2.13.1
I am using the Linux server version.

**Comment by theotherp** [comment]
Please post your debug infos zip as requested.

**Comment by Miicker** [comment]
[nzbhydra-debuginfos-2020-02-19-13-29.zip](https://github.com/theotherp/nzbhydra2/files/4225026/nzbhydra-debuginfos-2020-02-19-13-29.zip)
Is this what you are looking for?

**Comment by rizzoboy** [comment]
Having the same issue since updating to v2.13.13 BETA (2020-02-17).  SonarrV3, Radarr V2, Lidarr all having same error.  No errors reported on NZBHydra2 logs.  Error from Radarr pasted below.  All are Docker images in same container.  No issues prior to this.


"Downloading nzb for movie 'xxx' (2019) 1080p' failed (http://xxxxxxxxx.xxxxxxxxx.me/getnzb/api/-7046214161503512589?apikey=(removed): HTTP request failed: [404:NotFound] [GET] at [http://xxxxxxxxx.xxxxxxxxx.me/getnzb/api/-7046214161503512589?apikey=tbnBLv14imUSI5VGijisBtTX]"

"HTTP Error - Res: [GET] http://xxxxxxxxx.xxxxxxxxx.me/getnzb/api/-7046214161503512589?apikey=(removed) 404.NotFound"

**Comment by jalmansor** [comment]
I did some testing and the last version that works properly is v2.13.11, so looking at the change log it would seem like something in the X-Forwarded-For commit is the culprit here.

**Comment by ranasats** [comment]
For me this issue was resolved by properly handling HTTP -> HTTPS redirect. I did not have this enabled in my reverse proxy, and the API now looks like it's sitting on http://<domain> instead of https://<domain>. 

After enabling global HTTPS redirect on traefik I'm able to fetch using API again.

**Comment by theotherp** [comment]
I'm aware of the issue.

There currently two ways around it:

1. Use the local HTTP address for Hydra in *arr or Medusa or whatever. There's no need to access the reverse proxy.
2. Revert to 2.13.11

**Comment by alron** [comment]
Too bad neither of those options is possible for those of us in docker setups (unless there is a way to disable beta that appeared and I missed).

**Comment by theotherp** [comment]
What does option 1 to do with docker?

Fixed in new version.

**Comment by jalmansor** [comment]
@alron if you're using the linuxserver images then it's as easy as changing the tag you use to the desired version:

`docker pull linuxserver/hydra2:v2.13.11-ls11`

**Comment by alron** [comment]
@theotherp 

> What does option 1 to do with docker?

It means that some of us (myself especially) prefer not to directly expose the docker host to the internets. I share my hydra with friends who are too cheap to buy their own indexer access, and I'm totally not terribly keen on disabling TLS (or using the implementation provided by hydra2 in java). :)

Generally my response to being told to do away with my HTTPs reverse-proxy is a vulgarity laden string of expletives. But seeing you've been doing all the hard work without costing me cent, I'll keep that garbage to myself. :)

**Comment by alron** [comment]
@jalmansor 

> linuxserver/hydra2:v2.13.11-ls11

Good call. I totally derped on that side. Now we just need to convince the fine folks that produce the linuxserver images to throw an environment flag in place to disable the beta releases.

**Comment by theotherp** [comment]
Eh, I never told you to expose your hydra instance to the internet. But when you have Sonarr (for example) and Hydra running on the same machine they can communicate via the local network. You can still contact either via the reverse proxy when you're outside your local network.

If you have other computers outside your network contacting Hydra for *API calls*, then that's not anything I want to support anyway.

**Comment by ranasats** [comment]
> If you have other computers outside your network contacting Hydra for _API calls_, then that's not anything I want to support anyway.

May I know why this funcationaly isn't encouraged? I have hydra exposed via traefik. A handful of friends chipin to buy premium for 4-5 indexers and we aggregate them in my hydra instance and I share the API w/ them.

**Comment by rizzoboy** [comment]
Just updated to v2.13.14.  Working now.  Thank you!

Have never been able to get the container to connect locally.  Tried several different methods but either connection refused or timed out.  Usually using localhost works for the other containers but can only connect via reverse proxy with Hydra.

**Comment by Miicker** [comment]
I just updated to 2.13.14, for me it's also solved! 👍
