### ISSUE TITLE
py3 wrapper using python2 'file' function

### ISSUE THREAD

**Issue by AdamHertzberg** [theotherp/nzbhydra2#507]
Trying to start the application in a FreeBSD Jail (FreeNAS 11.2) with python 3.7 using the new py3 wrapper. I get an error indicating that 'file' is not defined. Per some googling, file was removed in python 3. I switched back to python 2.7 with the old wrapper and everything works fine.

`Starting nzbhydra2.
Logging wrapper output to /config/logs/wrapper.log
2020-02-19 19:21:33,432  INFO - Daemonizing...
Traceback (most recent call last):
  File "/usr/local/share/Nzbhydra/nzbhydra2wrapperPy3.py", line 576, in <module>

    daemonize(args.pidfile, args.nopidfile)
  File "/usr/local/share/Nzbhydra/nzbhydra2wrapperPy3.py", line 112, in daemonize
    file(pidfile, 'w').write("%s\n" % pid)
NameError: name 'file' is not defined`

**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 
I expect nzbhydra to launch - I get an error instead.
* Have you searched for this problem? You don't have to answer, just make sure.
I searched the error and found that 'file' is legacy python code.
* Can the problem be reproduced? How?
Make sure that python 2 is not installed and try to launch with py3 wrapper.
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
* If you use a docker container please tell me which one.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

**Comment by theotherp** [comment]
Thanks, I didn't test the daemonize command with py3.

**Comment by AdamHertzberg** [comment]
I've validated your fix on a newly created freenas jail. Thank you very much!
