### ISSUE TITLE
Update list of indexers

### ISSUE THREAD

**Issue by hr1232** [theotherp/nzbhydra2#508]
Some of the preset indexers are not available anymore. Some other good ones are missing

Please remove the following ones, that are no longer available:
- 6box (domain unregistered)
- 6box Spotweb (domain unregistered)
- anizb (domain unregistered)
- newz69.keagaming (domain unregistered)
- NZBs.io (domain unregistered)
- oznzb (domain still exists, www puts out database errors, api is just a wordpress login)

Modify the following one:
- Animetosho (Newznab) is an anonymous indexer without API-Key. Use the form, used for Binsearch.

Add the following ones (API-URLs are in brackets):
- Spotweb.me (https://spotweb.me)
- NZBNation (http://www.nzbnation.com)
- ABNzb (https://abnzb.com)

**Comment by albino1** [comment]
>     * NZBNation (http://www.nzbnation.com)

Is this a working site?  It looks like it hasn't been updated since 2008 and I can't find any NZBs on the site with or without an account.

**Comment by hr1232** [comment]
For me, the site is working just fine.

**Comment by albino1** [comment]
It says on the index page:

>Total NZB Files: 0

Maybe I'm missing something obvious though.
