### ISSUE TITLE
Inconsistent SEARCH Results

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#510]
Example:
I want to find the all **New TV Series**, so i am looking for Episode 1 of Season 1 (S01E01).
If i use 'Search TV-HD' with the Search field blank and set the 'S' and 'E' fields to 1 (and/or 01) i get incorrect/unexpected  results, with various Seasons and Episodes listed.
See this first image as an example.
  
![Results-BAD](https://user-images.githubusercontent.com/18551763/75146899-fa069b00-56f3-11ea-848b-1f3cc4afe63a.jpg)

If i use 'Search TV-HD' with S01E01 in the Search field and leave 'S' and 'E' fields blank i get the correct/expected results listed.
See this second image as an example.

![Results-GOOD](https://user-images.githubusercontent.com/18551763/75147154-9c268300-56f4-11ea-8e58-944f7f425c49.jpg)

Am i doing something wrong, or is the Search logic wrong?

Thanks for your support. Derek

**Comment by theotherp** [comment]
Most likely the indexers don't support searches with season and episode set
but without providing an ID for a show. The second scenario involves a word
based search which is different.

**Comment by DerekWilliamsUK** [comment]
OK, that makes sense.
Would it be worth making the optional 'S' and 'E' fields
unavailable/non-selectable (greyed out) UNLESS the Search field is
non-blank (ie. contains a Show ID)?

**Comment by theotherp** [comment]
Yeah, I could do that, but... why would you search for *any* release with a given season and/or episode anyway? Collecting pilots?

**Comment by albino1** [comment]
If you're going to search for only `S01E01` then don't even change the search type, just use `All` since anything that contains `S01E01` will either be in the TV category anyway or miscategorized and you wouldn't find it otherwise.

**Comment by DerekWilliamsUK** [comment]
Exactly, looking for new shows/pilots.

**Comment by DerekWilliamsUK** [comment]
Fair point, that would work for me.
