### ISSUE TITLE
missing 'Help' pop-up

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra2#514]
When I click on the 'Help' button on the 'Config -> Downloading' page, it shows an error instead of the help pop-up.  The other 'Help' buttons in the 'Config' section work fine. I'm on version 2.14.1

```
An error occurred:
500: Internal Server Error
Path: /nzbhydra2/internalapi/help/Downloading
Message: resource /help/downloading.md relative to org.nzbhydra.web.HelpWeb not found.
```

**Comment by theotherp** [comment]
Well, at least that means that somebody actually clicked the button ;-)

**Comment by translit** [comment]
> Well, at least that means that somebody actually clicked the button ;-)

Of course! :-) I wished to know what 'Update statuses' does and came across the same error message.

**Comment by theotherp** [comment]
"Update statuses" means that Hydra will query the downloader's queue and history to update the status of downloads and show it in the history. It will also be used for stats.
