### ISSUE TITLE
Add option to not supply category in search, indexer based

### ISSUE THREAD

**Issue by Elehiggle** [theotherp/nzbhydra2#516]
Related to https://github.com/theotherp/nzbhydra2/issues/515 I found another issue why I don't get certain results. 

NZBHydra2 queries the torrent tracker with &cat=5000 when I search for a show called Da Vinci's Demons. Completely normal. However, the releases related to that show on that torrent tracker are categorized under ID 100010, this is a release group called TVR. They also have the ID 2040 (Movies HD). The main problem is that the tracker categories all TVR releases as Movies, even though they do both.

I thought about adding 100010 to the TV category in Hydra as a workaround, but there are many more release groups where this is happening, and it might not be the only torrent tracker that does this.

Is it possible to add an indexer specific option to not provide &cat / categories when searching that indexer? This fixes the issue. I would definitely enable this for all torrent trackers in Hydra. This might return some unwanted releases sometimes (in my case, I tested, and all results were clean of unwanted results), but Sonarr checks for file size of the release and does additional parsing to filter unwanted results. And in the end, it should be up to the user.

Many thanks in advance!

Cheers

EDIT: Also HDCenter

**Comment by theotherp** [comment]
Might be easier to have an option not to use categories on any torznab indexers.

**Comment by Elehiggle** [comment]
Yes, that would be acceptable :)
