### ISSUE TITLE
High CPU when idle

### ISSUE THREAD

**Issue by translit** [theotherp/nzbhydra2#522]
**Issue**
After a day or so of running, Hydra starts consuming 30-40% of CPU when idle (java process). I'd expect it to be lower. After a restart the CPU goes down, but then shoots up again.

**Research**
The issue is similar to [#96](https://github.com/theotherp/nzbhydra2/issues/96) which was fixed long ago, so I think mine must have a different cause. Something similar is also [mentioned](https://github.com/linuxserver/docker-hydra2/issues/30) for the Docker container I use but I was unable to follow the solution.

**System**
Synology NAS • NZBHydra 2.14.1 • Linuxserver Docker [container](https://registry.hub.docker.com/u/linuxserver/hydra2/)

**Logs**
[nzbhydra-debuginfos-2020-03-09-21-02.zip](https://github.com/theotherp/nzbhydra2/files/4308709/nzbhydra-debuginfos-2020-03-09-21-02.zip)

**Comment by theotherp** [comment]
Please follow the instructions here: https://github.com/theotherp/nzbhydra2/issues/512#issuecomment-591091535

**Comment by translit** [comment]
I fail at point 2 ```sudo apt-get update```: ```bash: sudo: command not found```.

**Comment by theotherp** [comment]
Yeah, sorry.

1. Connect to the docker container: `sudo docker exec -it hydra2 /bin/bash`
2. Install JRE11 `sudo apt-get update`, `apt-get install openjdk-11-jdk-headless`
3. `exit`
4. `sudo docker exec --user=abc -it hydra2 /bin/bash`
5. Find out the java process PID `ps aux | grep java`
4. Create the thread dump `jstack PID > threads.txt`
6. Get the txt file (use scp or something or just copy the content to the clipboard)
7. Post the thread dump

**Comment by translit** [comment]
I failed to figure out how to create a thread dump, but I think I have resolved the issue by increasing the JVM memory from 256 MB to 2 GB. The container has been running for four days now and the CPU is low.

**Comment by theotherp** [comment]
Wow, that's a lot... The database isn't very large and the number of entries is comparable to mine. My instance has never needed more than 200MB.

**Comment by jasongordon** [comment]
> 
> 
> I failed to figure out how to create a thread dump, but I think I have resolved the issue by increasing the JVM memory from 256 MB to 2 GB. The container has been running for four days now and the CPU is low.

How did you end up doing this for the linuxserver docker image?  I am having the same CPU issue.

**Comment by theotherp** [comment]
@jasongordon It's a setting in the main config (at the bottom).
