### ISSUE TITLE
REQ: Indexer API custom reset time shorter than 24h

### ISSUE THREAD

**Issue by mrginogit** [theotherp/nzbhydra2#524]
Certain indexers like [a private one] now have shorter hit rate limits:
"If you exceed 300 API calls per 5 minutes, you will be be banned from the API for 1h"
This is separate from the daily limit of 10,000 hits for VIP users.
When triggering large backlog searches in clients like Medusa/Sickrage, the 5 minute limit is quickly hit.  

From what I can find, NZBHydra2 only allows configuring a daily limit. A workaround for this problem is to set the daily limit to 300, but that is less than ideal.

It would be great for NZBHydra2 to allow users to define custom hit rate limits and reset times for indexers.

**Comment by theotherp** [comment]
Just leave it empty, that should have the same effect.

**Comment by theotherp** [comment]
Sorry, I misread. I'd rather ask the developer of these tools to do a proper rate limiting.

**Comment by mrginogit** [comment]
But the individual tools don't have knowledge of each other's API calls.  I've consolidated them all into using NZBHydra2 and letting NZBHydra2 manage all the indexers, rate limits, and reset times.

**Comment by theotherp** [comment]
Yeah, you're right. I'll think about it, it's not trivial to implement.

**Comment by theotherp** [comment]
Sorry it took so long :-/

**Comment by mrginogit** [comment]
> Sorry it took so long :-/

Oh awesome! No worries, thanks for doing it!!  I just went in and re-enabled the indexer yet again, glad to hopefully never have to worry about that again!

I see in the commit where you hard-coded the limits and indexer URL. Just curious, why not make it configurable within the indexer settings?  Is it too unique for this particular indexer?

**Comment by theotherp** [comment]
I think it's unique and I'd rather not clutter the UI even more. Where
known for indexers I might as well put it in the code.
