### ISSUE TITLE
REQ Accept NZBLNKs

### ISSUE THREAD

**Issue by grasshide** [theotherp/nzbhydra2#529]
NZBLNKs (https://nzblnk.info/) are out there now for a while. And they are quite popular and handy.
Downside is that they require the end-user-device to understand those links. If a user has a lot of devices, this is quite annoying. And for some browsers/os'es there aren't any.

Since hydra is already able to use utilize search engines to fulfill the heavy lifting part that is required to get the according nzb for the NZBLNK it only needs hydra to rename the title and supply the download client with the password (if any). These are also functions that are already available in hydra.

The use case would be:
1 User gets an NZBLNK from somewhere
2 User posts link into the hydra search field
3 hydra processes the NZBLNK (simmilar to the end-device reference solution https://github.com/nzblnk/nzb-monkey). But without the need for any local software.

**Comment by theotherp** [comment]
Never seen that one before. Where do you get the links from?

As far as I understand it you'd paste the link and Hydra would search binsearch and nzbindex and you'd get a result with the title provided by the link?

**Comment by grasshide** [comment]
> Never seen that one before. Where do you get the links from?

Those links are used mainly in forums for convenience.

> As far as I understand it you'd paste the link and Hydra would search binsearch and nzbindex and you'd get a result with the title provided by the link?

Yes, but at lease with the addition that it also renames the nzb so that it includes the correct title and the password from the link.
I think it is enough to supply the password in curly brackets as download clients are set to use that part of the name as password.

Currently you'd have to search nzbindex via hydra and then either:
1. download the nzb locally, rename it and upload it to the download client or
2. you add it to your download client directly via hydra, then go there and rename it and set the password.

**Comment by grasshide** [comment]
closed because nothing is happening
