### ISSUE TITLE
Can you detail the regex field format?

### ISSUE THREAD

**Issue by nrk666** [theotherp/nzbhydra2#53]
Can you provide some examples of how to fill in the Forbidden Regex field? I've been trying unsuccessfully to forbid some things and even though I can save the regex, I still see those results when searching. I checked the wiki and there was no mention of those fields. 

For example, just for testing I've been inputting `\.720p\.HDTV\.x264\.` to stop seeing 720p results from being displayed. Do I need to put in the leading/trailing slashes like `/\.720p\.HDTV\.x264\./` or are they assumed? Since the title is converted to lowercase, does my regex need to be `\.720p\.hdtv\.x264\.`? Or can I do `/\.720p\.HDTV\.x264\./i`? 

I realize I can set a 1080p requirement in whatever client software I'm using, I am just using this as an example.

**Comment by theotherp** [comment]
Turns out still had a subtle bug in the code.

For reference: Enter the regex without slashes and in any case you want. Go crazy. 

Example: 
`\.(mp4|MKV)$` matches any result ending with `.mp4` or `.mkv` ignoring the case, e.g. it will match "Movie.MP4" and "AnyShow.720p.mkv" but not "PoorRip.avi" or even "film.about.mkv.avi",

**Comment by nrk666** [comment]
Got it, will upgrade and test soon. Thanks.

**Comment by nrk666** [comment]
There still seems to be an issue, for example, I entered `\.(SD|2160p)\.` and `.Sd.` still turns up in search results. (Again, just an example.) I don't think my example search turned up and 2160p content, so maybe that's a poor search choice...

**Comment by theotherp** [comment]
I'll check it again tomorrow, perhaps some information is lost between
client and server, I've only tested it on the backend.

Am 11.01.2018 23:20 schrieb "nrk666" <notifications@github.com>:

**Comment by nrk666** [comment]
Forbidden regex is : `\.(SD|2160p)\.`

On front page search, use category drop down to say XXX (cuz porn makes awesome examples) and search for "XXX MP4". Still see ".SD." and ".2160p." results.

**Comment by theotherp** [comment]
Send me your debug infos.

**Comment by nrk666** [comment]
[nzbhydra-debuginfos-2018-01-12-15-21.zip](https://github.com/theotherp/nzbhydra2/files/1627367/nzbhydra-debuginfos-2018-01-12-15-21.zip)

**Comment by theotherp** [comment]
There are no debug outputs in the log.

**Comment by nrk666** [comment]
How do I turn on debugging info then?

**Comment by theotherp** [comment]
Nope, still debug level and no logging markers.

**Comment by nrk666** [comment]
Maybe I'm not clear on what I should be doing. I've started it with "nzbhydra2 --debug", done my search, then hit the log generator button. If thats not correct, then tell me what I should be doing here.

**Comment by theotherp** [comment]
Go to the config, main section, find the logging secction a.d make it look like this:

![img](https://i.imgur.com/uqeV5tu.png)

Save and restart. Search again. Then create the debug infos and send them.

**Comment by nrk666** [comment]
Ah, sorry, I didn't even see that section. Here you go : 
[nzbhydra-debuginfos-2018-01-12-16-00.zip](https://github.com/theotherp/nzbhydra2/files/1627472/nzbhydra-debuginfos-2018-01-12-16-00.zip)

**Comment by theotherp** [comment]
You selected "Never" as value for the setting "Apply word filters" so none of the values below that setting are used.

I'll add validation that will prevent this from happening.

**Comment by nrk666** [comment]
lol. So I did. Thanks for pointing that out.
