### ISSUE TITLE
[FR] Catch Indexer with 10000 results as no results

### ISSUE THREAD

**Issue by reloxx13** [theotherp/nzbhydra2#530]
* What do you want to happen?
If an indexer returns 10000 results for a search, catch it and overwrite it as 0 results.
An optional flag at indexer settings would be nice.

* If not clear, why do you want it?
Some indexer (eg miatrix) return everything if nothing matches the query.

* Do you think it's something only you need or something that might be popular?
Everyone which use those bugged indexers

* If not clear, explain the use case.
Search something, the indexer returns 10000 results cause nothing matched. 
radarr only scans 1000 results, those 10000 wrong results are removing the other good results.

**Comment by theotherp** [comment]
What kind of shitty indexer does that?

**Comment by theotherp** [comment]
Could you please provide debug infos with an example?

I'm afraid that if I implement that some tools that e.g. just look for the newest MP3s will get 0 results because a search for "mp3" might actually return 10_000 results.

**Comment by reloxx13** [comment]
Heya,
movie 10540242
looks like it only happens with imdb id searches.

[nzbhydra-debuginfos-2020-04-19-12-07.zip](https://github.com/theotherp/nzbhydra2/files/4498767/nzbhydra-debuginfos-2020-04-19-12-07.zip)

**Comment by theotherp** [comment]
Alright, in that case I will make sure to only return 0 results with ID based searches and 10_000 results.

**Comment by reloxx13** [comment]
yep, that would be nice and it should trigger the text query search afterwards to have more movie matches at the end 👍
