### ISSUE TITLE
Color-code results per tracker

### ISSUE THREAD

**Issue by apcrcom** [theotherp/nzbhydra2#532]
* What do you want to happen?

in results list, to discern a particular tracker, requires reading through the list or toggling sort away from whatever the original preferred sort is set to. It would be great to have the option to 'highlight', for example, private tracker, or those with low ratio, or whatever, based on whatever preference. For example an option on each indexer just for 'color' or 'highlight'. 

* If not clear, why do you want it?

-

* Do you think it's something only you need or something that might be popular?

No idea. Seems to me like it would make using the application easier. I am doing a lot of searches today, and there are two trackers in particular I need to single out. When doing a lot of consecutive searches, its quite a bit of reading for each search to isolate them. 

* If not clear, explain the use case.

**Comment by theotherp** [comment]
Interesting idea. Will have to see how that would work with themes and stuff.
