### ISSUE TITLE
Fallback to generated queries does not trigger

### ISSUE THREAD

**Issue by reloxx13** [theotherp/nzbhydra2#533]
Im on latest beta nzbhydra2.
`Fallback to generated queries` is on.

Indexer SceneNZB supports ID search.
Calling `https://scenenzb.com/api?apikey=XXX&t=movie&extended=1&imdbid=1790809&password=1&cat=2000&limit=100&offset=0`

`SceneNZB: Successfully executed search call in 803ms with 0 results`

Now nzbhydra should try another call with a generated search query/movie name, but it wont.
Happens for other indexers aswell.

[nzbhydra-debuginfos-2020-04-12-12-24.zip](https://github.com/theotherp/nzbhydra2/files/4466154/nzbhydra-debuginfos-2020-04-12-12-24.zip)

**Comment by theotherp** [comment]
Debug infos...?

**Comment by reloxx13** [comment]
added already :p

**Comment by theotherp** [comment]
Sorry, didn't show up in the mail.

**Comment by theotherp** [comment]
Yeah that's weird. I'll update the debug logging in the next version to find out why no fallback is made.

**Comment by theotherp** [comment]
Please update, try again and post the new debug infos.

**Comment by theotherp** [comment]
Got it.

**Comment by reloxx13** [comment]
Im sorry, did not got or see the first notification.
In case still needed:
[nzbhydra-debuginfos-2020-04-19-10-59.zip](https://github.com/theotherp/nzbhydra2/files/4498674/nzbhydra-debuginfos-2020-04-19-10-59.zip)

I restarted and then searched for 1790809

**Comment by theotherp** [comment]
I found the problem and will release a fix today.
