### ISSUE TITLE
Not Torrent Peer info shown

### ISSUE THREAD

**Issue by marc0janssen** [theotherp/nzbhydra2#534]
When I use NZBhydra2 for TorNab, all peer info in Radarr/Sonarr is lost.
No seeder/leecher info is shown in the results.

This not implemented yet? Or IS this a bug?

**Comment by theotherp** [comment]
NZBHydra forwards all attributes provided by the trackers it calls. You should ask the *arr devs why the data is not shown.

**Comment by marc0janssen** [comment]
Ok, But when I add the indexers to *arr the info is shown... But hey I understand why you make the comment because you do provide the info... Ok. Sorry to bother you.. Thanks for your reply!

I guess if you make contact with them (as a dev) they might change it. What do you think?

**Comment by marc0janssen** [comment]
Do you think the missing seeder/leecher info in *arr is not a problem for *arr anyway?

**Comment by theotherp** [comment]
Not sure. But this is the torznab from a jackett search:

```
    <item>
      <title>True Life S22E05 Im Living Anime REAL 720p HDTV x264-W4F</title>
      <guid>https://eztv.io/ep/353839/true-life-s22e05-im-living-anime-real-720p-hdtv-x264-w4f/</guid>
      <jackettindexer id="eztv">EZTV</jackettindexer>
      <comments>https://eztv.io/ep/353839/true-life-s22e05-im-living-anime-real-720p-hdtv-x264-w4f/</comments>
      <pubDate>Tue, 17 Apr 2018 18:27:27 +0200</pubDate>
      <size>1026042112</size>
      <description />
      <link>magnet:?xt=urn:btih:30aa69b785e5650f51b0e6785cf59e83fb44a39d&amp;dn=True.Life.S22E05.Im.Living.Anime.REAL.720p.HDTV.x264-W4F%5Beztv%5D.mkv%5Beztv%5D&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969</link>
      <category>5000</category>
      <category>100001</category>
      <enclosure url="magnet:?xt=urn:btih:30aa69b785e5650f51b0e6785cf59e83fb44a39d&amp;dn=True.Life.S22E05.Im.Living.Anime.REAL.720p.HDTV.x264-W4F%5Beztv%5D.mkv%5Beztv%5D&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969" length="1026042112" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="100001" />
      <torznab:attr name="magneturl" value="magnet:?xt=urn:btih:30aa69b785e5650f51b0e6785cf59e83fb44a39d&amp;dn=True.Life.S22E05.Im.Living.Anime.REAL.720p.HDTV.x264-W4F%5Beztv%5D.mkv%5Beztv%5D&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969" />
      <torznab:attr name="seeders" value="0" />
      <torznab:attr name="peers" value="0" />
      <torznab:attr name="minimumratio" value="1" />
      <torznab:attr name="minimumseedtime" value="172800" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
```

and this from Hydra:

```
 <item>
            <title>True Life S22E05 Im Living Anime REAL 720p HDTV x264-W4F</title>
            <link>http://127.0.0.1:5076/gettorrent/api/371371895985850862?apikey=apikey</link>
            <enclosure url="http://127.0.0.1:5076/gettorrent/api/371371895985850862?apikey=apikey" length="1026042112" type="application/x-bittorrent"/>
            <pubDate>Tue, 17 Apr 2018 16:09:50 +0000</pubDate>
            <guid isPermaLink="false">371371895985850862</guid>
            <description></description>
            <comments>https://eztv.io/ep/353839/true-life-s22e05-im-living-anime-real-720p-hdtv-x264-w4f/</comments>
            <category>TV</category>
            <size>1026042112</size>
            <torznab:attr name="category" value="100001"/>
            <torznab:attr name="downloadvolumefactor" value="0"/>
            <torznab:attr name="guid" value="371371895985850862"/>
            <torznab:attr name="magneturl" value="magnet:?xt=urn:btih:30aa69b785e5650f51b0e6785cf59e83fb44a39d&amp;dn=True.Life.S22E05.Im.Living.Anime.REAL.720p.HDTV.x264-W4F%5Beztv%5D.mkv%5Beztv%5D&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969"/>
            <torznab:attr name="minimumratio" value="1"/>
            <torznab:attr name="minimumseedtime" value="172800"/>
            <torznab:attr name="peers" value="0"/>
            <torznab:attr name="seeders" value="0"/>
            <torznab:attr name="size" value="1026042112"/>
            <torznab:attr name="uploadvolumefactor" value="1"/>
            <torznab:attr name="hydraIndexerScore" value="0"/>
            <torznab:attr name="hydraIndexerHost" value="127.0.0.1"/>
            <torznab:attr name="hydraIndexerName" value="EZTV"/>
        </item>
```

As you can see the seeders/peers info is contained. I don't know why Radarr doesn't show it.

**Comment by marc0janssen** [comment]
Thanks for you help..

Yes that is weird... Those xmls you show here would point to a display of that data in *arr.

**Comment by theotherp** [comment]
Screenshot from my sonarr:
<img width="220" alt="peers" src="https://user-images.githubusercontent.com/14368889/80301216-1af67580-87a3-11ea-8a9a-dceeb1695814.png">

Works fine for me.

**Comment by marc0janssen** [comment]
Is it a setting that I am missing then??

**Comment by theotherp** [comment]
Make a manual search from *arr which shows no peer info, then create the debug infos in hydra and post them.

**Comment by marc0janssen** [comment]
<img width="291" alt="Schermafbeelding 2020-04-26 om 10 02 18" src="https://user-images.githubusercontent.com/5788988/80301584-36fb1680-87a5-11ea-9b87-47bd2578a201.png">
[nzbhydra-debuginfos-2020-04-26-10-02.zip](https://github.com/theotherp/nzbhydra2/files/4534878/nzbhydra-debuginfos-2020-04-26-10-02.zip)

**Comment by marc0janssen** [comment]
Just good to know I add my torrent-indexers to hydra via jackett

**Comment by theotherp** [comment]
Is the info missing for all trackers or only some? Which program is this (Sonarr, Sonarr v3, Radarr)?

**Comment by marc0janssen** [comment]
I  used SONARR, all trackers via hydra are missing.. If I add the trackers direct to Sonarr they are giving results.

**Comment by marc0janssen** [comment]
Sonarr Ver. 2.0.0.5344

**Comment by theotherp** [comment]
Please temporarily disable all indexers in hydra but eztv (that's what I tested with). Make another manual search and verify the info is missing. Then check the hydra log for the URL that was called. It should look like this: `http://127.0.0.1:9117/api/v2.0/indexers/eztv/results/torznab/api?apikey=<apikey>&t=search&extended=1&q=Jett&password=1`. Use the jackett API key. The browser should start a file download. Save that file anywhere and post it here.

**Comment by marc0janssen** [comment]
Now Hydra gives no results...... weird


<img width="801" alt="Schermafbeelding 2020-04-26 om 10 38 21" src="https://user-images.githubusercontent.com/5788988/80302399-184b4e80-87aa-11ea-9439-c9043d7efcc4.png">

**Comment by theotherp** [comment]
Test the search by searching in hydra directly.

**Comment by marc0janssen** [comment]
That works perfectly!

**Comment by marc0janssen** [comment]
Fixed the Sonarr problem: I needed at least also 1 NZB indexer in hydra enabled.

**Comment by theotherp** [comment]
That doesn't make sense.

Are you sure you used the hydra torznab URL when adding it to sonarr?

**Comment by theotherp** [comment]
If not none of your trackers are actually searched. In the hydra config click the "API?" button. Use the shown torznab URL in sonarr.

**Comment by marc0janssen** [comment]
> That doesn't make sense.
> 
> Are you sure you used the hydra torznab URL when adding it to sonarr?

Where can I find that Torznzb URL??

**Comment by marc0janssen** [comment]
OOOPPPPSSS>... I feed complete stupid!

I just read on your GitHub. I need to add "/torznab"

SO sorry to waste your time!!

**Comment by theotherp** [comment]
In that case none of your trackers ever were searched. Unfortunately there is no way for me to recognize that the wrong endpoint was called.

Closing this, I'll choose to be glad there's no bug here ;-)

**Comment by marc0janssen** [comment]
Thanks Sir for your help!
