### ISSUE TITLE
maxing out cpu

### ISSUE THREAD

**Issue by apcrcom** [theotherp/nzbhydra2#535]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

https://we.tl/t-3dd2aiODv4

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 

Just started happening in the last week or so. When I run Hydra it bogs the machine down and cpus both run at 100%. This is when the app is idle. 

Normally the cpus would sit at about 50%. When the app is running its 100%. When the app is closed the cpus return to about 50%

**Comment by apcrcom** [comment]
I figured it out. Mem was set too low. Upped it to 1048 and it fixed the
problem.

By way of feedback, an error message saying low mem setting causing
performance issue, would be helpful in this instance.

Im not sure how easy that is to implement, and Im sure there are other
things on your to do list. This would be very useful though.

Thanks

**Comment by theotherp** [comment]
I don't think there's any way of finding that out automatically, sorry. But I'll give it a try.
