### ISSUE TITLE
The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.

### ISSUE THREAD

**Issue by spylex** [theotherp/nzbhydra2#537]
I thought i'd put the error to help searching when others have the issue.

* What do you expect to happen? What does happen? 

Manual search in *arr, results from a certain tracker are show, but sending the download to NZB client fails with the following error:
The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.

The error is visible in the *arr but not in NzbHydra2.

* Have you searched for this problem? You don't have to answer, just make sure.

Yes, seems like Jackett has the same issue and has resolved it. https://github.com/Jackett/Jackett/issues/7456

Seems to be a change in the way the newznab URL might be handled?

* Can the problem be reproduced? How?

Search for something manually in an *arr, this indexer will find results but downloads won't be sent to client.

* If you use a docker container please tell me which one.

Hotio docker.

**Comment by theotherp** [comment]
You mean animetosho?

Please post your debug infos zip.

**Comment by spylex** [comment]
I thought i attached them, clearly forgot. Here they are.

No its an indexer directly added. Its one that could be mistaken as located in India.
[nzbhydra-debuginfos-2020-04-18-19-03.zip](https://github.com/theotherp/nzbhydra2/files/4497266/nzbhydra-debuginfos-2020-04-18-19-03.zip)

**Comment by theotherp** [comment]
I guess you have everything configured as described in their forum?

In this particular case NZBHydra returns the actual link to the indexer to *arr which then is either downloaded by *arr or sent to the downloader. If that link doesn't work it means that either the link is invalid or downloads from the indexer don't work for some reason.

You can try the following:

- In the download history in Hydra find the failed download and try to download it (click the icon to the left of the title) and see if that works and if not what error (page) you get.
- Check the indexer's dashboard to make sure that your API access works as intended. 
- Enable trace logging in *arr, try another download and then check the logs for the actual content of the NZB that is trying to be downloaded.

**Comment by spylex** [comment]
In the end, it was an issue on my side with a misconfigured parser in my docker image. Appreciate the help theotherp!
