### ISSUE TITLE
error after rescanning jackett config

### ISSUE THREAD

**Issue by alculete** [theotherp/nzbhydra2#539]
I've used the option to scan jackett config to add indexes and later I've added more, and when I scan again I receive an error saying there are duplicates.
Shouldn't this duplicates be automatically handled?
![image](https://user-images.githubusercontent.com/2129497/79772058-ec564600-832f-11ea-9140-47a517a73f29.png)

**Comment by theotherp** [comment]
The comparison is done by the host. Have you used another jackett host when reading the config? Compare the hosts of the old and new entries.

**Comment by alculete** [comment]
I was using docker before, so I moved the database. Can this be the reason?

**Comment by theotherp** [comment]
No

**Comment by theotherp** [comment]
In Jackett copy the torznab URL of an indexer to the clipboard and compare it with the host of that indexer in hydra. They should be the same. If not post them.

**Comment by alculete** [comment]
Tested at least 4 and are the same

**Comment by theotherp** [comment]
Load the config from jackett, delete all but one of the duplicates, rename one of the renaming duplicates, save the config, create the debug infos zip and post it here.

**Comment by alculete** [comment]
[downloadlog.log](https://github.com/theotherp/nzbhydra2/files/4505031/downloadlog.log)
The duplicates are **torrentz2** and **torrentz2a**

**Comment by theotherp** [comment]
I need the debug infos (go to the system section, bugreport tab, create the infos, attach zip).

**Comment by alculete** [comment]
[nzbhydra-debuginfos-2020-04-20-19-45.zip](https://github.com/theotherp/nzbhydra2/files/4505192/nzbhydra-debuginfos-2020-04-20-19-45.zip)

**Comment by theotherp** [comment]
In one you used http://127.0.0.1:9117 and http://192.168.0.200:9117 in the other. That's different.

**Comment by alculete** [comment]
I think that one didn't pass, so I changed to the second one

**Comment by theotherp** [comment]
What?

**Comment by alculete** [comment]
The localhost IP, so anyway it's working fine now. Thank you
