### ISSUE TITLE
[BUG] Manual backup / Automatic backup not working

### ISSUE THREAD

**Issue by Desolator-FRL** [theotherp/nzbhydra2#542]
The backup function doesn't work anymore.
Docker container: "https://hub.docker.com/r/linuxserver/nzbhydra2"

When I try to make a manual backup there is an error and this is the log output : "Unexpected error when client tried to access path /internalapi/backup/backup. Error message: Could not find acceptable representation" 

and:

"java.io.IOException: Unable to create backup target folder /app/nzbhydra2/backup" 
(rest in attached zip file).

I tried to change the backup target folder in Hydra (program and yml) and tried to change the path in the Docker container.

[nzbhydra-debuginfos-2020-04-22-09-55.zip](https://github.com/theotherp/nzbhydra2/files/4514650/nzbhydra-debuginfos-2020-04-22-09-55.zip)

**Comment by theotherp** [comment]
See https://old.reddit.com/r/nzbhydra/comments/fwm4r2/cant_create_backup/

Seems to be a problem with the docker container. Please get help from the maintainers.

**Comment by theotherp** [comment]
It was my fault. Should be fixed with 2.19.6. Sorry about that.

**Comment by Desolator-FRL** [comment]
It is working again, thanks!
