### ISSUE TITLE
Cannot trust downloader signed with local CA

### ISSUE THREAD

**Issue by bablat** [theotherp/nzbhydra2#546]
Hello, and thank you for building this amazing piece of software.

I am using a deployment which involves TLS introduced by Traefik. I'd like to have nzbhydra access my NzbGet service via HTTPS, traefik uses my local CA.

When I ignore SSL in the configuration, I believe it only applies to indexers but not downloaders.
I get this exception when adding my downloader:
```
The connection to the downloader failed: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException:
unable to find valid certification path to requested target
Do you want to add it anyway?
```

I believe the java keystore doesn't trust the hosts' certificates, so I couldn't even inject my CA from the outside.

Could I ask for a way to have hydra trust a CA certificate file either by command line argument, or UI configuration?

**Comment by theotherp** [comment]
Please post your debug infos zip.

**Comment by theotherp** [comment]
Nzbget?

**Comment by theotherp** [comment]
Nvm, found a solution.

**Comment by bablat** [comment]
Thanks for the quick workaround, I see you've added the option for Hydra to disregard SSL validation when connecting to NzbGet.
While this would work, it removes the benefit which SSL certificates provide. The proper solution (which all of my other +20 container images support) is the ability to TRUST a provided CA certificate.

Ideally, Hydra should allow the user to upload a CA certificate, and add it to the local trusted certificate store, this would allow SSL connections to be established and verified between Hydra and all other services.

Thanks again!

**Comment by theotherp** [comment]
Yes, I know - I've experimented with a solution to import other certificates but it's not complete yet.

**Comment by theotherp** [comment]
Included in the next version.
