### ISSUE TITLE
Version number in UI

### ISSUE THREAD

**Issue by bablat** [theotherp/nzbhydra2#548]
This is a tiny improvement really, and I might be missing this some other place, but the about page doesn't show hydra's version. I'm using linuxserver's docker images and had to go to docker's logs to know what version I was on.

**Comment by theotherp** [comment]
Just go to the updates tab. But yeah, I could also display it on the about page.

**Comment by theotherp** [comment]
Decided not to do this. The info is just a click away ;-)

**Comment by bablat** [comment]
Perfectly acceptable.
