### ISSUE TITLE
500: Internal Server Error  Path: /internalapi/updates/installUpdate  Message: Circular loading of installed providers detected

### ISSUE THREAD

**Issue by AtariBaby** [theotherp/nzbhydra2#550]
version 2.17.6 trying to update to 2.20
Windows 10 Pro
The aforementioned errors occurs 100% percent of the time, when clicking on Update. Logs attached. 
[nzbhydra-debuginfos-2020-04-27-14-21.zip](https://github.com/theotherp/nzbhydra2/files/4542112/nzbhydra-debuginfos-2020-04-27-14-21.zip)

**Comment by theotherp** [comment]
Restart any try again.

**Comment by AtariBaby** [comment]
damn it, that solves so many issues, maybe i'll remember to always try that first, some day!

one little note: the post installation message is "an update was automatically installed". technically, an update had to be manually installed lol. Thank you!

**Comment by theotherp** [comment]
Yeah, I noticed that. It's supposed to only appear after an automatic update...

**Comment by theotherp** [comment]
Fixed.
