### ISSUE TITLE
Request: Make UI More Mouse Friendly

### ISSUE THREAD

**Issue by Copyrites** [theotherp/nzbhydra2#551]
I'd like to request two changes to the UI that will save mouse clicks:

1. Add a button to clear the "Search" input field.  Linux supports paste with middle-button click so a button that clears the field is a big help, otherwise you have to select the text and then control-v or right-click and pick paste off the menu.

2. Replace the drop-down menu for mass reset/select-all/deselect-all/invert of indexers to a set of buttons.  Taking the menu out of the path saves a click and some fine-motor-control mouse movements.  There is a lot of available screen space so it shouldn't clutter up the interface.

Thanks for considering these requests.

**Comment by theotherp** [comment]
I can do 1 but would find 2 too cluttered.

**Comment by albino1** [comment]
Also for 1, you can just click the Search button at the top and it will reset with a cleared input box.

**Comment by Copyrites** [comment]
Yeah.  The word "reset" is key.  Having to reselect the indexers, and set the max/mins for dates and sizes, is a lot of clicks.
