### ISSUE TITLE
Provide contextual help for settings

### ISSUE THREAD

**Issue by Minituff** [theotherp/nzbhydra2#554]
I really like how clean the UI is. And for the most part, everything is explained really well. If I could request one improvement it would be to contextualize the detailed settings explanations with their respective description under the "help" tab. 
I often found myself opening and closing this modal often to try to align the setting and its detailed description. 

My feature request would be to have a little (?) icon or button next to each individual setting that has a detailed description. I think the brief descriptions are great as is!

To provide a little more detail, I created this image to show how the setting and its respective description "kinda" line up and makes it hard to figure out which goes to which. Maybe an easy fix would be to simply put the setting title next to the detailed description in the help tab?

I appreciate all the work.

![NZBHydra_2_Config_Searching_](https://user-images.githubusercontent.com/8152401/80547473-24333e00-896d-11ea-9193-bafb980bc83d.jpg)

**Comment by theotherp** [comment]
I'm attempted to do this only to reward you for that graphic ;-)

I had already considered such a feature. It may also reduce support tickets because I don't think many users actually read that help...

**Comment by theotherp** [comment]
I'll move the searching settings to more separate fieldsets (with headlines). Then I can show a question mark for each fieldset.

**Comment by Minituff** [comment]
> I'll move the searching settings to more separate fieldsets (with headlines). Then I can show a question mark for each fieldset.

Sounds great. I'd love to see.

**Comment by Minituff** [comment]
I just received the 2.20.2 update. This is an excellent improvement! Great work!
