### ISSUE TITLE
Enlarge the movie cover image on click

### ISSUE THREAD

**Issue by freender** [theotherp/nzbhydra2#556]
TC:
1. In search field hit [Go]
2. In search results left click on Movie cover image
**Actual Result:** This is currently not supported. As WA we can right click and open image in new tab. 
**Expected Result:** It would be nice if we can enlarge the movie cover image on left click

**Comment by theotherp** [comment]
By the way, I recommend https://www.google.com/search?q=imagus which shows images in original size on hover.

**Comment by freender** [comment]
Thanks!
