### ISSUE TITLE
api key per user

### ISSUE THREAD

**Issue by ndaringer** [theotherp/nzbhydra2#558]
* What do you want to happen? create an api key per user under authorization. So each user has their own independent access to nzbhydra
* If not clear, why do you want it? To allow others to be able to use a different api key that uses the restrictions 
* Do you think it's something only you need or something that might be popular? I think it could be popular as it allows people to share the access to nzbhydra without giving out the main password or api key.
* If not clear, explain the use case.

**Comment by theotherp** [comment]
See #140
