### ISSUE TITLE
Restrict non-admin user actions a bit more

### ISSUE THREAD

**Issue by TheOnlyYogo** [theotherp/nzbhydra2#560]
When creating a user, add the option to disable sending the search result to a downloader, only to download the nzb/torrent or copy magnet (something like "Disable Download client access")

I think it may be popular for those that want to share their Hydra installs, and possibly split the cost for indexers/torrent hosts if they all have their own download clients/bandwidth, without opening up their own downloader...

**Comment by theotherp** [comment]
That's exactly what I won't support. If you use it as a family or a couple of friends in a flat, fine. If you all have your own downloaders get your own API keys. Or be fine to make your downloader accessible to them.
