### ISSUE TITLE
BUG Search Screen Layout Errors with v2.20.4 [Not Fixed]

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#561]
![NZBhydra - Search Page Layout Errors](https://user-images.githubusercontent.com/18551763/81185922-1e131200-8faa-11ea-9496-db12edcb2c94.jpg)

**Comment by theotherp** [comment]
Woops.

**Comment by theotherp** [comment]
Please provide more info when reporting stuff like this. OS, browser, screen resolution, etc. It obviously worked fine on my machine...

**Comment by DerekWilliamsUK** [comment]
Still broken after update v2.20.6
Windows 10 Pro
Screen Res: Full HD 1080p
Browser: Chrome Version 81.0.4044.129 (Official Build) (64-bit)
Browser: Edge Microsoft Edge 44.18362.449.0 / Microsoft EdgeHTML 18.18363

**Comment by theotherp** [comment]
Try pressing Ctrl+F5.

**Comment by DerekWilliamsUK** [comment]
Tried CTRL+F5 & PC Reboot. Stiil the exact same layout error on Search page. All other pages look normal.

**Comment by theotherp** [comment]
Please try with new v2.20.7

**Comment by DerekWilliamsUK** [comment]
v2.20.7 fixed the problem. Thanks.
