### ISSUE TITLE
RuTracker.org caps check causes "failed to execute script nzbhydra2wrapperPy3" error on 2.20.5

### ISSUE THREAD

**Issue by Turbogame** [theotherp/nzbhydra2#562]
Updated to **2.20.5** this morning and kept receiving the following error when trying to execute NZBHydra2.exe:

![image](https://user-images.githubusercontent.com/5041840/81228982-11e48000-8fbd-11ea-883c-6d8d42ed7d72.png)

Tried restoring from a backup and kept getting the same error until I decided to delete the **nzbhydra.yml** in the data folder (after backing it up of course). The program then loaded fine, but of course I had no configuration.

I then proceeded to meticulously go through all of the config process again while routinely restarting the program until a crash/error occurred, which didn't happen until after I reloaded all of my indexers again using the preset: **read from Jackett config**.

Long story short... after a caps check on RuTracker, the mapping in the yml file becomes insanely long - my particular **-allCapsChecked: true** entry in the file for RuTracker takes up 4,616 lines. Not sure if anyone else is having this problem. I *temporarily* fixed it by deleting out the **categoryMapping** field in the nzbhydra.yml for RuTracker up to the color field.

I'm on Windows 10 x64 bit version 1909 if that matters, but I'm wondering if this might affect other platforms as well. I didn't upload a log since I figured out the problem for myself, but if you'd like me to provide you with a safe log, please give me instructions on how to do so as I can replicate the error quite easily. Otherwise, it's as simple as adding RuTracker as an indexer via Jackett, doing a caps check, and then restarting the program that caused the grief for me. 

Hope this information helps anyone.

**Comment by kawells** [comment]
Thank you for providing the workaround. I did the same as you and was able to start NZBHydra again. I'm also on Windows 10 x64 bit version 1909 and also use RuTracker.
