### ISSUE TITLE
Safari layout issue

### ISSUE THREAD

**Issue by gussyboy** [theotherp/nzbhydra2#563]
There are so many minor bugs with the css when browsing in Safari on MacOS and iOS.

For example:
![image](https://user-images.githubusercontent.com/2124400/81235585-a93de780-903e-11ea-8b3d-0bfd14f71502.png)

To fix the text issue, need to simply add `overflow: hidden` on the `legend`.

**Comment by theotherp** [comment]
I'm tempted to say "deal with it" or use Chrome or Firefox. I don't have a mac and testing the layout using a web service that shows me the layout rendered with Safari is really cumbersome.

**Comment by gussyboy** [comment]
Well as a web developer myself I so with you there on your "deal with it" comment. I can tell you for sure that adding `overflow: hidden` to the `legend` will fix the layout issue that annoys me the most. Could you squeeze that one in?

**Comment by theotherp** [comment]
Sure

**Comment by gussyboy** [comment]
@theotherp the legend doesn't always sit nested within `repeatWrapperClass`. So the overflow style doesn't get applied.

![image](https://user-images.githubusercontent.com/2124400/81625138-58156580-943b-11ea-8c82-4730111ec136.png)

**Comment by theotherp** [comment]
Fixed.
