### ISSUE TITLE
Layout/CSS issue in search box

### ISSUE THREAD

**Issue by myopenflixr** [theotherp/nzbhydra2#565]
Hello,

Using Chrome and experiencing an issue where the css appears to be misaligned when searching for a title (per the picture).
![nzbhydra-error](https://user-images.githubusercontent.com/33140130/81307159-5b30e000-904e-11ea-9a59-111cc94ae65f.jpg)

**Comment by theotherp** [comment]
Please read and follow the instructions. For GUI bugs *at least* post resolution, browser (that you did), OS and version.

**Comment by myopenflixr** [comment]
Looks to have been fixed in 2.20.7

Thank you!

**Comment by myopenflixr** [comment]
> Please read and follow the instructions. For GUI bugs _at least_ post resolution, browser (that you did), OS and version.

Sorry...Resolution is 1020x1080, Chrome Browser, Win 10 Home, version 2.20.6
