### ISSUE TITLE
api url

### ISSUE THREAD

**Issue by mike-gracia** [theotherp/nzbhydra2#57]
Not sure if this a bug or a feature but it looks like for the url for the api is behind the url base now. So when adding hydra2 as a  sonarr/radarr newsnab indexer, the source url would be something like http://hydra2:5076/hydra2 instead of the original way http://hydra:7075. This took me a couple minutes to figure out and it might be something to look into.

**Comment by theotherp** [comment]
Uh what?

The url is http://127.0.0.1:5076 or perhaps http://127.0.0.1:5076/nzbhydra2.

Unless you set your host to nzbhydra2.

How do you run Hydra? Also post the debug infos.

**Comment by fryfrog** [comment]
The `./api` has always been "behind" the url_base. Your example should be more like http://ip:port, unless you've set a url base and then it'd be http://ip:port/url_base. I think you're doing something wrong or misunderstanding something.

**Comment by mike-gracia** [comment]
Everything is in docker container and I am giving hydra its own hostname (hydra2) but that is getting too complicated. The issue is the old url for api was  http://127.0.0.1:5075/api and now it is  http://127.0.0.1:5075/nzbhydra2/api

![image](https://user-images.githubusercontent.com/1455154/34894583-0233ddce-f7b0-11e7-8ea5-f4401d82ca3e.png)

vs

![image](https://user-images.githubusercontent.com/1455154/34894599-14a328c0-f7b0-11e7-8553-f6a71ed4f172.png)

**Comment by mike-gracia** [comment]
Ok new discovery. For hydra1, both http://ip:port and http://ip:port/base work but with hydra2 only http://ip:port/base works

**Comment by theotherp** [comment]
There's no need to enter any API path,

The help text for the URL base clearly says "Always use when calling Hydra, even locally.".

**Comment by fryfrog** [comment]
Ah, that I'd believe. I've seen some daemons that require url_base, but also some that continue to work at both / and /url_base. I don't think either behavior is terrible.
