### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#572]
Windows 10 Pro.
Would it be possible for you to include your Publisher/Copyright information in the **NZBhydra2.exe** file information.
This is just some 'nice to have' housekeeping. I have attached a couple of examples to show what i mean & when/where this information is displayed and would be useful. Thanks

![Win10 Startup Apps List](https://user-images.githubusercontent.com/18551763/82755413-2dc49000-9dcb-11ea-954d-3bbf681a0ef8.jpg)

![CCleaner Startup List](https://user-images.githubusercontent.com/18551763/82755414-34530780-9dcb-11ea-90d4-e34d304972fb.jpg)

![NZBhydra2 exe File Properties Display](https://user-images.githubusercontent.com/18551763/82755416-3d43d900-9dcb-11ea-8368-49bbc3d8eceb.jpg)

![File Properties Good Example](https://user-images.githubusercontent.com/18551763/82755418-3fa63300-9dcb-11ea-838c-7226c53e38da.jpg)

**Comment by theotherp** [comment]
Will add infos the next time I change the files.

**Comment by theotherp** [comment]
Btw I'd say this is a feature request... :-)
