### ISSUE TITLE
NZBHydra spam 169.200.120.82 - Wells Fargo & Company

### ISSUE THREAD

**Issue by pinkfloydFR** [theotherp/nzbhydra2#574]
Hi,

I am using linuxserver/nzbhydra2 docker image and I wonder why NzbHydra is callings this ip ( 169.200.120.82 )  always and always ?

NetRange:       169.200.0.0 - 169.200.255.255
CIDR:           169.200.0.0/16
Organization:   Wells Fargo & Company (WFB-2)
Address:        420 Montgomery ST
City:           San Francisco

![2020-05-26_21-34-05](https://user-images.githubusercontent.com/49475899/82942931-10452100-9f99-11ea-9897-a93118413e83.png)

Thanks !

**Comment by pinkfloydFR** [comment]
sorry need to check my configuration again

**Comment by theotherp** [comment]
Ok then.
