### ISSUE TITLE
nzbhydra2 migration

### ISSUE THREAD

**Issue by nathan0726** [theotherp/nzbhydra2#576]
Currently running nzbhydra v1 version 0.2.233. Installed the latest version at the time of this writing (v2.22.4) and found I could not migrate. Removed everything and installed v2.10.2 as instructed and attempted to migrate again, but the same message about migration being removed in v2.10.3 appeared. Tried several other older version to no avail. Would really like to run v2, but currently cannot get migration to work.

**Comment by theotherp** [comment]
When running 2.10.3 create the debug infos zip and post it here.
