### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by danjames92** [theotherp/nzbhydra2#58]
Visual glitch. v1.0.17 Log required in this case?

![firefox_2018-01-13_18-22-55](https://user-images.githubusercontent.com/16107603/34908854-e068e218-f88e-11e7-983f-57ab0aa87247.png)

**Comment by theotherp** [comment]
Ooops

**Comment by theotherp** [comment]
No

**Comment by theotherp** [comment]
Fixed

**Comment by theotherp** [comment]
No automated tests that could catch that...

**Comment by danjames92** [comment]
You’re welcome :)
