### ISSUE TITLE
Are duplicate results displayed incorrectly?

### ISSUE THREAD

**Issue by dimqua** [theotherp/nzbhydra2#581]
I discovered that indexers priorities don't work as I expect. Let me give an example.

![](https://i.imgur.com/Nm5kAI9.png)

According to my settings, Finder has the highest priority number, then Dog and Omg. But as you can see, Dog's result is displayed first. Is there a reason for that?

I expect it should work like this:
> The result from the indexer with the highest number is shown first in the GUI and returned for API searches.
-----------
And what duplicate result is displayed first if all indexers have the same priority?

**Comment by theotherp** [comment]
Impossible to say from the fact that cropped screenshot.

**Comment by dimqua** [comment]
https://i.imgur.com/gelRiTv.png

@theotherp let me know if you need more information.

**Comment by theotherp** [comment]
Those are not duplicates but just results with the same title.

**Comment by dimqua** [comment]
I see, my bad.
@theotherp, is it possible to sort such results according to indexers priority numbers? If not, could you please implement such an option? I would be very useful, IMHO.

**Comment by theotherp** [comment]
Not possible and it wouldn't work with the sorting by any other value.

**Comment by dimqua** [comment]
Isn't it possible to treat results with the same title as duplicates regardless of their size? Quite often they are the same files.

**Comment by theotherp** [comment]
Duplicates are results that link to the same upload. All results that are not considered and shown as duplicates are not duplicates (to a certain degree of confidence).

**Comment by dimqua** [comment]
Yes, duplicates link to the same upload, but I personally don't care much about who made an upload and when. I want to download a movie in selected quality (just like most users I think). And quite often uploads with the same name (but different sizes) contain exact the same files: encodes, remuxes, etc.

**Comment by albino1** [comment]
Because it's duplicate _posts_ not duplicate _files_.

If a post fails then all the duplicate posts would obviously also fail, but if a duplicate file fails then another file might still work.  If you hide all of the duplicate _files_ and one fails then you wouldn't be able to see if there's any others that might still work.

**Comment by dimqua** [comment]
@albino1 got it, thank you. But I don't suggest to make it the default behaviour, it can be an option. Currently you have you expand all the grouped (by name) results to select preferred source (indexer) of a nzb file. If the first result is always come from indexer with highest priority, you don't have to do this.

**Comment by albino1** [comment]
I actually agree that I would prefer sort by priority, and it's been brought up before.

I'm always for more options, but I think if that gets added it needs to buried in the menu with a big warning making sure users know what they're doing before they turn it on, otherwise they might start getting failed downloads without knowing that there's alternates they can try instead :)

**Comment by dimqua** [comment]
I've noticed that there's an option `Use sum of grabs / seeders for filtering / sorting of groups`. A similar option can probably be added, but for sorting by priority of an indexer.

**Comment by theotherp** [comment]
> I actually agree that I would prefer sort by priority, specifically within duplicates, and it's been brought up before.

Duplicates *are* sorted by priority with the result from the indexer with the highest priority being shown.

**Comment by albino1** [comment]
> 
> 
> > I actually agree that I would prefer sort by priority, specifically within duplicates, and it's been brought up before.
> 
> Duplicates _are_ sorted by priority with the result from the indexer with the highest priority being shown.

I just rechecked and you're right of course, so never mind :)
