### ISSUE TITLE
Show freeleech torrents

### ISSUE THREAD

**Issue by digitaldelboy** [theotherp/nzbhydra2#583]
In jackett it shows something like this

![Capture](https://user-images.githubusercontent.com/33402113/84057202-dddaf100-a9a6-11ea-9f96-3240c8394366.PNG)

would it be possible for you to add freeleech, 75%, 50%, 25% to hydra.

Thank you

**Comment by theotherp** [comment]
Looks like the values `downloadvolumefactor` and `uploadvolumefactor` are used for that. If the first is 0 and the latter 1 then it's a freelech. Please make a torznab API search with HDBits in jackettt using the title shown in your screenshot and post the values for `downloadvolumefactor` and `uploadvolumefactor`. My guess would be that it's 0.5/1 or something like that.
