### ISSUE TITLE
Immediate error when clicking "Send to SABnzbd" from search

### ISSUE THREAD

**Issue by biship** [theotherp/nzbhydra2#585]
nzb actually gets added to SAB, and it downloads fine.

nzbhydra2 2.23.0 on Win10 x64.
sabnzdb v3 (develop) up to commit **9155ade937f21a88d5c7c3b3ff9abe83d8871088**
https://github.com/sabnzbd/sabnzbd/commit/9155ade937f21a88d5c7c3b3ff9abe83d8871088

I can upload full debug logs if required.

I don't think it's related, but I also see in nzbhydra2.serv.log:
```
2020-06-11 06:15:10.422 SERV --- POST /nzbhydra2/internalapi/search HTTP/1.1 : status code: 200 | bytes: 4788 | elapsed ms: 12487 | local: 10.19.15.2 | remote: 192.168.0.44
2020-06-11 06:15:10.654 SERV --- GET /nzbhydra2/static/img/sab.png HTTP/1.1 : status code: 304 | bytes: - | elapsed ms: 1 | local: 10.19.15.2 | remote: 192.168.0.44
```

nzbhydra2-log.json:
```
{"@timestamp":"2020-06-11T06:15:10.038-04:00","@version":"1","message":"Returning results 1-1 from 1 results in cache. A total of 1 results is available from indexers of which 0 were already rejected","logger_name":"org.nzbhydra.searching.Searcher","thread_name":"http-nio-192.168.0.13-5099-exec-3","level":"INFO","level_value":20000,"IPADDRESS":"192.168.0.44","SEARCH":"17347"}
{"@timestamp":"2020-06-11T06:15:10.419-04:00","@version":"1","message":"Web search took 12473ms","logger_name":"org.nzbhydra.searching.SearchWeb","thread_name":"http-nio-192.168.0.13-5099-exec-3","level":"INFO","level_value":20000,"IPADDRESS":"192.168.0.44","SEARCH":"17347"}
{"@timestamp":"2020-06-11T06:15:12.580-04:00","@version":"1","message":"Error while adding NZB(s): Error while extracting response for type [class org.nzbhydra.downloading.downloaders.sabnzbd.mapping.AddNzbResponse] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token\n at [Source: (PushbackInputStream); line: 1, column: 29] (through reference chain: org.nzbhydra.downloading.downloaders.sabnzbd.mapping.AddNzbResponse[\"nzo_ids\"])","logger_name":"org.nzbhydra.downloading.downloaders.Downloader","thread_name":"http-nio-192.168.0.13-5099-exec-2","level":"ERROR","level_value":40000,"IPADDRESS":"192.168.0.44"}
{"@timestamp":"2020-06-11T06:15:14.611-04:00","@version":"1","message":"NZB download request for \"<removed>\" from indexer omgwtfnzbs","logger_name":"org.nzbhydra.downloading.FileHandler","thread_name":"http-nio-192.168.0.13-5099-exec-4","level":"INFO","level_value":20000,"IPADDRESS":"192.168.0.13"}
{"@timestamp":"2020-06-11T06:15:15.526-04:00","@version":"1","message":"NZB download from indexer successfully completed in 914ms","logger_name":"org.nzbhydra.downloading.FileHandler","thread_name":"http-nio-192.168.0.13-5099-exec-4","level":"INFO","level_value":20000,"IPADDRESS":"192.168.0.13"}
{"@timestamp":"2020-06-11T06:15:29.616-04:00","@version":"1","message":"Title: \"<removed>". Downloaded unique result from: omgwtfnzbs. All other indexers without result: altHUB, NZB Finder, nzbplanet, LuluNZB, NZBGeek, NzBNooB, DogNZB, NZBCat, FastNZB","logger_name":"org.nzbhydra.downloading.IndexerUniquenessScoreSaver","thread_name":"http-nio-192.168.0.13-5099-exec-4","level":"INFO","level_value":20000,"IPADDRESS":"192.168.0.13"}
```

**Comment by theotherp** [comment]
Please post the debug infos zip

**Comment by theotherp** [comment]
Also, which sabnzbd version are you using?

**Comment by biship** [comment]
sabnzbd version is in fist post.
I searched for 'test':

zip uploaded[
[nzbhydra-debuginfos-2020-06-11-16-18.zip](https://github.com/theotherp/nzbhydra2/files/4767182/nzbhydra-debuginfos-2020-06-11-16-18.zip)
](url)

**Comment by theotherp** [comment]
>sabnzbd version is in first post.

Yes it is. Sorry, missed it.

Please open http://192.168.0.13:8084/sabnzbd/api?apikey=<apikey>&output=json&mode=addurl&name=http://htpc:5099/nzbhydra2/getnzb/api/7153668026714252466?apikey%3Dugsjmofohdscu3390uqsgmbrb8&nzbname=Sammy_Brue-Crash_Test_Kid-WEB-2020-ENTiTLED.nzb&priority=-100&cat=MP3 in your browser and post the result.

**Comment by biship** [comment]
{"status": false, "error": "API Key Required"}

**Comment by theotherp** [comment]
It looks like v3 changed the format of the output. I don't support v3 (yet). I can't find any information about the API either.

You should tell them that the change in the response will break compatibility with NZBHydra (and perhaps some other programs, I don't know).

**Comment by biship** [comment]
Ok, well they are not the nicest devs to interact with, so I'll wait for either you to support sab v3, or for them to make a change on their own. I've been running sab v3 for months, and this literally only broke on 6/10 or 6/11. Thanks.

**Comment by theotherp** [comment]
https://github.com/sabnzbd/sabnzbd/commit/2f45a87f125aa1bf6c2b595b767f3eb0c4b247e5#diff-614fad822638826b499d3440a6e29bb8
is the culprit. I can try supporting both old and new format but I won't
guarantee that hydra works with v3 at all.

**Comment by Safihre** [comment]
Alright, I will restore it to returning an array. This keeps it similar to the other API-calls.

**Comment by Safihre** [comment]
@biship If you pull the latest `sabnzbd/develop` it should work again.

**Comment by biship** [comment]
Fixed: {"status": true, "nzo_ids": ["SABnzbd_nzo_0i5auafm"]}
Thanks!
