### ISSUE TITLE
Java options break version check

### ISSUE THREAD

**Issue by ted46045** [theotherp/nzbhydra2#588]
With the limited support for additional java options setting any option using the JAVA_JDK_OPTIONS env variable (jdk11) will give a version error when it does the java version check

I tried to put it in a java comamnd wrapper (bash) but it also threw an error.  Something with with the string check is not passing.

OS/version info:
Ubuntu 18.04.4 LTS (linux-generic-hwe-18.04  5.3.0.59.113)
JDK11  (openjdk-11-jdk-headless:amd64 11.0.7+10-2ubuntu2~18.04)

Error:
```

# export  JDK_JAVA_OPTIONS="-Dnetworkaddress.cache.ttl=10"
# /opt/nzbhydra2/nzbhydra2 --nobrowser --datafolder /opt/nzbhydra2/data
Logging wrapper output to /opt/nzbhydra2/data/logs/wrapper.log
2020-06-17 19:27:22,593  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string NOTE: Picked up JDK_JAVA_OPTIONS: -Dnetworkaddress.cache.ttl=10

```
Example java wrapper (used with --java option, will not replace /usr/bin/java)
```
#!/bin/bash
/usr/bin/java -XX:+AlwaysPreTouch -Xss1m -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=30 -XX:G1ReservePercent=25 -Xms256m -Xmx256m -Dnetworkaddress.cache.ttl=10 -XX:-HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC $@

```

```
# /opt/nzbhydra2/nzbhydra2 --nobrowser --datafolder /opt/nzbhydra2/data --java /opt/nzbhydra2/java
Logging wrapper output to /opt/nzbhydra2/data/logs/wrapper.log
2020-06-17 19:41:32,359  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string /bin/bash: /tmp/_MEIDDt9qC/libtinfo.so.5: no version information available (required by /bin/bash)
```

**Comment by theotherp** [comment]
What java options do yo need to set and why?

**Comment by ted46045** [comment]
Im running on a vm and memory managemnt currently matters and some random networking issues can be avoided with some extra options

-Xms256m -Xmx256m -XX:+AlwaysPreTouch (set fixed allocated heap space, common java opt)
-Dnetworkaddress.cache.ttl=10 (dont forever cache dns lookups, forever by default)
-XX:-HeapDumpOnOutOfMemoryError (turn off heap dumps, would rather app restart quickly, can reenable id needed to debug)
-XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=30 -XX:G1ReservePercent=25 (GC tuning for java9+, G1GC should be the preferred gc and it should prevent the app from OOM as long as heap is reasonable)

**Comment by theotherp** [comment]
I'm doubtful that the GC matters in this context and that the one chosen by the JVM works properly. But I also don't know or care enough about it to stop you from changing it.

Updating the wrapper is always a big hassle so I won't do it just for this case. I'll keep it in mind and fix it when I need to change the wrapper anyway.

**Comment by theotherp** [comment]
By the way, works fine on my machine...

**Comment by ted46045** [comment]
> 
> 
> By the way, works fine on my machine... And what do you mean by "used to work"? I haven't changed the wrapper in more than a month.

Yea I dunno what changed other than a kernel update but the java wrapper used to work fine with the standard linux wrapper (although i hadnt updated since 2.21 until recently).  Must just be me.  It seems to just take the first line of output and parse it as the version string.  Anyways you can close this then.  I just changed my unit file to use the py3 wrapper and the java wrapper works fine so I can stay with the mainline still.  Thanks for the quick responses and great tool!
