### ISSUE TITLE
Search window fails to close if file size is specified

### ISSUE THREAD

**Issue by translit** [theotherp/nzbhydra2#589]
When searching with size specified (minimum or maximum) the search window doesn't close. It says, e.g., "Indexers finished: 5/5" and "This window will close automatically when searching is finished" but it never does. If I press Cancel the windows closes and the results are displayed. The window does close if size is left blank.

Hydra has behaved like this as long as I remember. I'm reporting now because I got annoyed enough.

Running from Linuxserver's Docker container. Debug logs attached.

[nzbhydra-debuginfos-2020-06-23-21-03.zip](https://github.com/theotherp/nzbhydra2/files/4821402/nzbhydra-debuginfos-2020-06-23-21-03.zip)

**Comment by theotherp** [comment]
Which search in the log causes the problem? Works fine for me.

**Comment by translit** [comment]
The last one. But I think it's a browser issue. I've narrowed the issue down to Safari. Both Firefox and Chrome work fine.

**Comment by theotherp** [comment]
This might be fixed in v3.7.0.

**Comment by translit** [comment]
Alas, it isn't. Updated to v3.8.0 but the issue persists.

**Comment by theotherp** [comment]
Too bad.

**Comment by theotherp** [comment]
I'll add some logging.

**Comment by translit** [comment]
Tell me, if I can help.

**Comment by theotherp** [comment]
Sorry, this is hard to debug. The next time this happens please check the browser console for messages. Post them along with the debug infos and tell me which search (which timestamp) caused it.

**Comment by translit** [comment]
Of course. No problem.
