### ISSUE TITLE
allow downloaders only for certain users

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [theotherp/nzbhydra2#592]
Hi,

it would be great if you could select which users are able to see/use the "send to *downloader*" button.
Or maybe even better at the "downloaders" section of the settings select which users can use a downloader.

I'm sharing my hydra install with friends and I have added my sabnzbd to hydra but I would like to limit the use of the downloader to specific people so not everybody can download files to my sabnzbd.

cheers!

**Comment by theotherp** [comment]
See #459 

If you trust your friends enough to have access to your hydra instance you need to trust them with add-access to your downloader.

**Comment by tofuSCHNITZEL** [comment]
> 
> 
> See #459
> 
> If you trust your friends enough to have access to your hydra instance you need to trust them with add-access to your downloader.

sure there was never any issue... just thought it could be implemented fairly easy... but judging by the #459 comments you don't want it as a matter of principle?

**Comment by theotherp** [comment]
Correct.
