### ISSUE TITLE
ADD x265/HEVC Filter Option to Search Results List

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#593]
Would this be possible...

![2020-07-09_18-03-58](https://user-images.githubusercontent.com/18551763/87069612-6996a600-c20f-11ea-85c6-a3aca96034f0.jpg)

**Comment by theotherp** [comment]
Sure.

**Comment by DerekWilliamsUK** [comment]
Great, thanks.

**Comment by albino1** [comment]
On a related note, would it be possible to make a Display Option (or config option) to enable this little filter bar when searching with All and not just TV/Movies?

**Comment by theotherp** [comment]
Sure.
