### ISSUE TITLE
Download area still shows 2+ hours OLD SABnzbd activity

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#594]
Windows 10 x64 Pro with all updates plus latest Google Chrome browser. Latest NZBhydra (but it has always happened) with SABnzbd.

These 2 screen grabs show what i mean.
SABnzbd shows last download activity was 2+ hours ago...
![SABnzbd](https://user-images.githubusercontent.com/18551763/87131787-d3a16080-c28c-11ea-9805-af8debab245e.jpg)

BUT switching to NZBhydra still shows previous download activity even 2 hours later. Shouldn't this be 'flushed' after a short period?
![NZBhydra](https://user-images.githubusercontent.com/18551763/87131894-fe8bb480-c28c-11ea-85b6-15e0b0fcfc8a.jpg)

Hope this makes sense - it is repeatable. Regards, Del.

**Comment by theotherp** [comment]
Yeah, to be honest, I've noticed that a couple of times but it's so hard to fix I never bothered... Might take another look.

**Comment by DerekWilliamsUK** [comment]
No problem. If it is too much work, just leave it. I just wanted to point it out. ;-)

**Comment by theotherp** [comment]
This should be fixed with the new release.
