### ISSUE TITLE
Bug: nzbsu + nzbseek - error checking capabilities

### ISSUE THREAD

**Issue by mogodon** [theotherp/nzbhydra2#596]
* What do you expect to happen? What does happen? 

I expect indexers to work.  Recently the two I mainly use have disabled:

- NZBGeek
- nzb.su

When i try to recheck caps I receive the following error:

_Error testing capabilities
An error occurred while contacting the indexer. It will not be usable until the caps check has been executed. You can trigger it manually from the indexer config box_

I haven't changed config, although I did reset an API key and try that but to no avail.  Also installed newer qpkg to see if that made any difference but no.

Both indexers are up and running.

I also get errors on the news page or hitting force update.  

NAS can reach internet.

* Have you searched for this problem? You don't have to answer, just make sure.
Yes

* Can the problem be reproduced? How?
By clicking either check capabilities within the indexer config or recheck caps for selected indexers

* If you use a docker container please tell me which one.
QNAP qpkg
https://www.qnapclub.eu/en/qpkg/521

Any help would be gratefully appreciated.

**Comment by theotherp** [comment]
Please post the debug infos zip.

**Comment by mogodon** [comment]
[nzbhydra-debuginfos-2020-07-16-14-47.zip](https://github.com/theotherp/nzbhydra2/files/4931853/nzbhydra-debuginfos-2020-07-16-14-47.zip)

**Comment by mogodon** [comment]
Acidentally closed. Debuginfos above

**Comment by theotherp** [comment]
Should be fixed by now.
