### ISSUE TITLE
Request API V2 Support for NNTmux

### ISSUE THREAD

**Issue by DrakeJones** [theotherp/nzbhydra2#597]
I want to use NZBHydra 2 with NNTmux.  NNTux uses API V2 and NZBHydra 2 does not currently support API V2.

NNTmux API V2 docs are here: [https://documenter.getpostman.com/view/3059471/RW8FGS9E?version=latest#intro]

 Do I think it's something that might be popular? Yes, I think so.

**Comment by theotherp** [comment]
Which indexers actually support that? Which other software supports it? What's the benefit? 

I don't see anything in the specs that's not already supported by / possible with v1.

**Comment by DrakeJones** [comment]
I guess that begs the question "Why even have API V2 at all? "  It looks like NZBHydra 2 can't pull caps from NNTmux build, but I'm just a novice.  DariusIII is indexer master.  Which indexers actually support API V2?  Well, usenet-crawler and nzbcat appear to be NNTmux builds now.  The were nZEDb builds until very recently, I think.

By the way, I like NZBHydra 2 a lot.  It was a good concept and it's good software.  Thank you,

**Comment by theotherp** [comment]
@DariusIII Can you shed some light? Does nntmux suddenly require v2 API? Any software that uses it?

**Comment by DariusIII** [comment]
No, NNTmux has no such requirement. Both APIv1 and APIv2 can be used, although no software uses APIv2 for now. 
I would love to see software support for API V2, but that is not in my hands at all :)

@DrakeJones I have just checked UC and it is newznab and nzbcat is still nZEDb (kingcat mentioned he will switch to NNTmux, but that is still not happening).

**Comment by DrakeJones** [comment]
Thank you both.

**Comment by theotherp** [comment]
@DrakeJones I'll keep it in mind and perhaps implement v2 at some point (someone has to start) but I don't consider it urgent. I didn't want to outright reject your request and am sorry if I came of as rude. I just wanted to make sure if there's a need to do it right now.

**Comment by DrakeJones** [comment]
Understood.  No offense taken.
