### ISSUE TITLE
Added with WAIT in SABnzbd when using "Send to SABnzbd" from search

### ISSUE THREAD

**Issue by danielb2** [theotherp/nzbhydra2#599]
* What do you expect to happen? What does happen? 

Just want to add something to the queue from a search. It's added to the queue just fine, but it's stuck indefiniately on WAIT. 

* Have you searched for this problem? You don't have to answer, just make sure.

Yes

* Can the problem be reproduced? How?

Happens every time I try to add something

* Do you know the problem ?

Yes, I figured it out.

* Describe the issue, please. OMG

So what's happening is that I'm using a dns shortcut to my server. It's been defined in /etc/hosts so instead of typing out the IP address of my server to access hydra, I use the shortname of the server. It appears Hydra uses that instead of the IP address specified in `/config/downloading`.   When I switch to accessing hydra by IP, everything works just fine. However, the docker container hydra/sabnzbd lives in doesn't have access to the shortname so sab tries to access via shortname and is stuck forever more.

**Comment by theotherp** [comment]
You didn't add me the debug infos zip.

I guess you're sending links to sab? Try sending the nzb instead. Or use
the full address instead of that shortcut.

**Comment by danielb2** [comment]
How about this ?

**Steps to repro:**
1.  Create a dns alias in /etc/hosts called 'hydra' that points to the host of your nzbhydra  server.
2. use the alias to access your hydra instance
1. search and add search result to nzb

<br><p>

<img width="88" alt="Screen Shot 2020-07-21 at 12 36 12" src="https://user-images.githubusercontent.com/26678/88098813-37f6d680-cb4f-11ea-8a02-380a6174bbb7.png">
_add using nzb_

<p>
<img width="780" alt="SABnzbd" src="https://user-images.githubusercontent.com/26678/88098905-578dff00-cb4f-11ea-8767-90524499819c.png">

_note server having issues with finding the host_


Again, be sure that the host doesn't have the alias in it's own `/etc/hosts` otherwise it will resolve just fine.

**Comment by danielb2** [comment]
Out of curiosity, why doesn't hydra send the full link from the search result to sab instead of a link to itself ?

**Comment by theotherp** [comment]
POST YOUR DEBUG INFOS. Jesus, is that so hard?

**Comment by danielb2** [comment]
I thought the issue was self-explanatory with it not resolving the DNS. I do go through logs just to double-check, so it's absolutely more effort.

[nzbhydra-debuginfos-2020-07-22-08-12.zip](https://github.com/theotherp/nzbhydra2/files/4960789/nzbhydra-debuginfos-2020-07-22-08-12.zip)

**Comment by theotherp** [comment]
Well, there's a reason I ask for them in the first place and then asked again.

The point is that I need to see the config you're using. You've configured Hydra to send links to your downloader and to redirect the requests to the actual indexer. If I sent the actual link directly to the download Hydra would be unable to get notified of the actual download.
You can select to upload the NZBs to the downloader instead of sending links. That way sab does not need to connect to hydra.

**Comment by danielb2** [comment]
Ah, I got a workaround :) But it's still a bug, right ?

**Comment by theotherp** [comment]
Not really, no. Hydra uses the URL you use to call it to determine its address. That address needs to be resolvable by your downloader if you want to send links instead of NZBs.

You could add a script or something to the downloader container to add the same hosts entry there.

**Comment by danielb2** [comment]
@theotherp  why does it use the URL vs the configured value?

<img width="598" alt="Screen Shot 2020-07-22 at 09 54 53" src="https://user-images.githubusercontent.com/26678/88205313-6df49300-cc01-11ea-941a-0aaee28552fc.png">

After all, I am specifying it here

**Comment by theotherp** [comment]
The problem is with sab connecting to hydra. The connection from hydra to
sab obviously works as you're successfully sending links to it.

**Comment by danielb2** [comment]
🤦  right
