### ISSUE TITLE
Feature request: Ability to have endpoints for each indexer

### ISSUE THREAD

**Issue by nameproof** [theotherp/nzbhydra2#600]
* What do you want to happen?
Ability to have endpoints for each indexer. End goal is to be able to add each indexer as separate entrys in *arr but still run them through NZBHydra.

* If not clear, why do you want it?
I want to be able to use Hydras stats and not worrying about my entire indexer stack going down if only one indexer fails.

* Do you think it's something only you need or something that might be popular?
There seem to be a following in Discord.

* If not clear, explain the use case.
Recently a indexer API had issues, it resolved to an old IP for a few months (for me and a bunch of others atleast). During this time *arr would give connection timeout error and disable the entire newznab endpoint. I had to (at this point I wasn't aware of what the issue was), go into *arr and click test indexer until it worked again. Then it would work for a search or two before disabling it again due to connection timeout.

**Comment by nemchik** [comment]
Potentially related https://github.com/Sonarr/Sonarr/issues/3132

**Comment by theotherp** [comment]
You can provide the parameter `indexers` to the API request, e.g. `http://127.0.0.1:5076/api?apikey=apikey&t=search&q=whatever&indexers=Binsearch` or `http://127.0.0.1:5076/api?apikey=apikey&t=search&q=whatever&indexers=NZBGeek,nzbcat`

**Comment by nemchik** [comment]
> You can provide the parameter `indexers` to the API request, e.g. `http://127.0.0.1:5076/api?apikey=apikey&t=search&q=whatever&indexers=Binsearch` or `http://127.0.0.1:5076/api?apikey=apikey&t=search&q=whatever&indexers=NZBGeek,nzbcat`. Set `&indexers=Binsearch` (or similar) as additional parameter in sonarr.

Is this new or has this always been available?

**Comment by theotherp** [comment]
That's been in there since August 2019.

**Comment by nameproof** [comment]
Thank you for digging this up! Been testing for a few days now in Radarr/Sonarr v3 and not a single hiccup. Now of course my failing indexer is not failing anymore but I assume *arr will only disable the failing indexer and use the rest if it happens again.
