### ISSUE TITLE
Dragging a search history item into search field copies search words into it

### ISSUE THREAD

**Issue by Goram** [theotherp/nzbhydra2#603]
At the moment you can drag the search history item into the search field and it pastes the url into the search field aka "http://localhost:5076/#" in my case. It would be nice to have the actual search words of the item copied instead.

Use case:
I downloaded my "favorite show s01e01", but now I want "favorite show s01e02". I can click the search history item and change it afterwards, but it starts a search and hits the search engines without need.

At the moment I always have to copy the search words from other files or type em out aka I'm lazy. 

I think we are all lazy and it would help to be more lazy, and it's a QOL feature. I would use it a lot.

**Comment by albino1** [comment]
Maybe I'm missing something, but instead of dragging/dropping from the search history, just click it?

**Comment by Goram** [comment]
I updated the issue above, I spoke with TheOtherP on Discord and thought this was enough.

**Comment by albino1** [comment]
That makes more sense, thanks for updating it.

**Comment by theotherp** [comment]
This was a bit tricky but I got it done.

**Comment by Goram** [comment]
Very nice, thanks!

**Comment by Goram** [comment]
Hi again,

when I drag the item into the search field I have to click twice to actually change it. 
one time for closing the search history drop down and a second time to focus the search to change it.

Can you close the search history after the drag and focus directly?

**Comment by theotherp** [comment]
>Should this be a new issue?
No.
