### ISSUE TITLE
Settings in 'Display Options' aren't sticky and always revert back to default.

### ISSUE THREAD

**Issue by dingdongbingbong** [theotherp/nzbhydra2#605]
Hello, 

The settings under display options seem to always reset themselves and changes aren't permanent as one would expect. 

I have searched and can't seem to find any issues like mine on the repo. 

I have nzbhydra2 running in a docker container with its own persistent volume. I am running Docker version 19.03.12, build 48a6621, and the latest nzbhyra2 image from linuxserver.

There are no entries in the log file that refer to this either so I'm not entirely sure what is happening. 

Please let me know if you need any further information, thanks!

**Comment by theotherp** [comment]
The display options are stored in your browser. Try with a different one and make sure that you're not preventing the browser from storing the infos.

**Comment by dingdongbingbong** [comment]
I see, so if the cache is cleared by the browser the settings don't stick. I have tried it on Firefox and Edge. 

Is there a way to make these settings permanent by any chance? 

Thanks!

**Comment by albino1** [comment]
If you're using Firefox maybe try turning off the enhanced tracking protection for your NZBHydra URL by clicking on the shield icon to the left of the URL.  Also it probably wouldn't hurt to disable anything else like uBlock Origin or NoScript for NZBHydra as well.

**Comment by theotherp** [comment]
They *are* permanent if the browser stores the data properly. The idea is that the display options are per user and keeping the data in the browser makes this easy.

**Comment by theotherp** [comment]
Can't reproduce.
