### ISSUE TITLE
shutdown cleanly via command-line? (SIGINT, WM_CLOSE, Rest API, TASKKILL /T)

### ISSUE THREAD

**Issue by Andy2244** [theotherp/nzbhydra2#606]
This is on Windows 10:

I'm looking for a way to script the shutdown behavior of NZBHydra and can't find a clean way to-do this?
So basically i would like a way to trigger the task-icon option "Shutdown" from a script.

I tried via:
TASKKILL /T /FI "IMAGENAME eq NZBHydra2*"
[SendMessage64.exe](https://github.com/stefankueng/sendmessage) /message:WM_CLOSE /processname:"NZBHydra2.exe"
[windows-kill](https://github.com/alirdn/windows-kill) -1

In contrast Sabnzb has a rest API and we can send `http://localhost:8080/shutdown/?apikey=`, alternative the process reacts to `SIGBREAK` and `SIGINT` signals and can be cleanly shutdown via the [windows-kill](https://github.com/alirdn/windows-kill) helper:

from the CMD:
`for /f tokens^=2^ delims^=^,^" %G in ('TASKLIST /FO CSV /NH /FI "IMAGENAME eq SABnzbd*"') do windows-kill -2 %G`

log output:
`WARNING::[__init__:188] Signal 0 caught, saving and exiting...`
and
`WARNING::[__init__:188] Signal 1 caught, saving and exiting...`

_I think adding the SIGINT/SIGBREAK logic similar to Sabnzb would be to easiest way?_

PS: I don't want to run NZBHydra as service, but still would like to control startup/shutdown, without forcefully killing the process.

**Comment by theotherp** [comment]
You can send an HTTP GET to `/internalapi/control/shutdown`.

For some reason `taskkill` only seems to work with `Nzbhydra2 Console.exe`, not `Nzbhydra2.exe`.
