### ISSUE TITLE
Lifetime expiry

### ISSUE THREAD

**Issue by modem7** [theotherp/nzbhydra2#608]
Under indexer status, would it be possible to have a "lifetime" option under VIP expiry? 

It would allow things to be a bit neater with those few indexers that allow for lifetime VIP membership rather than a blank value

**Comment by theotherp** [comment]
I'll keep it in mind but it's not quickly done.

**Comment by modem7** [comment]
Just a single text label saying "lifetime" would suffice in that particular field. 

Nothing fancy would be required.
