### ISSUE TITLE
Bug Realllllllly Slowwwwwww

### ISSUE THREAD

**Issue by AtariBaby** [theotherp/nzbhydra2#609]
How to create a bug report
[nzbhydra-debuginfos-2020-08-11-22-15.zip](https://github.com/theotherp/nzbhydra2/files/5060288/nzbhydra-debuginfos-2020-08-11-22-15.zip)
Hydra version 2.25.0, Windows 10 Pro
I restarted nzbhydra and for about ten minutes searches in apps like sonarr were immediately returning the message “no results”. When it finally did start working, a search took about 20 minutes. I attached the logs. Perhaps they will reveal something.
100% repeatable

**Comment by theotherp** [comment]
Disable the mapping of IPs to hosts in the logging config. See if that helps.
