### ISSUE TITLE
Add Atmos and DTS:X Flags to search result filter

### ISSUE THREAD

**Issue by dshokouhi** [theotherp/nzbhydra2#616]
* What do you want to happen? 

Just like it was requested in #593 lets add some custom audio flags!!

* If not clear, why do you want it? 

I want to quickly search for 3d audio stuff in atmos or dts:x

* Do you think it's something only you need or something that might be popular? 

I am sure everyone who has a 3d audio sound system will want this

* If not clear, explain the use case. 

Just to do quick searches for other things we care about

**Comment by theotherp** [comment]
You can do that yourself now. There's an option for custom filters in the
searching config.

**Comment by dshokouhi** [comment]
Thank you!
