### ISSUE TITLE
Custom Quick Filters not working

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra2#617]
* What do you expect to happen? What does happen? 

User created custom quick filters to filter results when searching All.  Instead it doesn't work.

* Can the problem be reproduced? How?

To reproduce the problem: create a quick filter called something very specific like `S01E01` and then search for a recently released show like `Star Trek Lower Decks`.  Then try clicking the `S01E01` filter which displays zero results.

Here's a screenshot of my custom filter:

![al-nzbh0](https://user-images.githubusercontent.com/12164957/91347107-a2c2af80-e796-11ea-92ba-85d660ee81f0.jpg)

Here's a screenshot of a search showing that there should be a result to successfully filter:

![al-nzbh1](https://user-images.githubusercontent.com/12164957/91347151-b1a96200-e796-11ea-83a1-dc52efb6dcbd.jpg)

And here's a screenshot showing no results after using the custom quick filter:

![al-nzbh2](https://user-images.githubusercontent.com/12164957/91347181-bf5ee780-e796-11ea-9cd5-00cd789c68bb.jpg)

Here's the logs in case there's anything useful:

[nzbhydra-debuginfos-2020-08-26-12-18.zip](https://github.com/theotherp/nzbhydra2/files/5132406/nzbhydra-debuginfos-2020-08-26-12-18.zip)

**Comment by theotherp** [comment]
Well that's weird.

**Comment by theotherp** [comment]
The filter values are applied to lowercase titles but aren't converted to lowercase themselves. Stupid mistake. As a workaround just define lowercase filter values (e.g. `Test=s01e01`).

**Comment by albino1** [comment]
That makes sense based on my previous tests I was doing before the `S01E01` example above.

I can confirm that changing it to `s01e01` works.

Thanks!

**Comment by albino1** [comment]
Confirmed fixed.  Thanks!
