### ISSUE TITLE
Configure hydra in *arr

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#618]
Add a dialog to automatically configure NZBHydra2 in Radarr, Sonarr, Lidarr:

- as one entry (default)
- one entry per indexer configured in hydra

**Comment by reloxx13** [comment]
heya,
do you plan it for radarr v3 aphrodite?

`Error: configuration for v2 but returned version is 3.0.0.3544`

**Comment by reloxx13** [comment]
thank you :+1:

**Comment by reloxx13** [comment]
nope :D

`Error: configuration for v3 but returned version is 3.0.0.3544 `

**Comment by reloxx13** [comment]
https://github.com/theotherp/nzbhydra2/blob/448d4dfd83e4b3d3edf90eb9619701fdc568492a/core/src/main/java/org/nzbhydra/externaltools/ExternalTools.java#L180-L184

it must be 3 not 10 :)
10 is windows 10 

/api/system/status
```
{
  "version": "3.0.0.3544",
  "buildTime": "2020-08-30T21:51:42.7381093Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": true,
  "isUserInteractive": true,
  "startupPath": "C:\\ProgramData\\Radarr-V3\\bin",
  "appData": "C:\\ProgramData\\Radarr-V3",
  "osName": "Windows",
  "osVersion": "10.0.19041.0",
  "isNetCore": true,
  "isMono": false,
  "isLinux": false,
  "isOsx": false,
  "isWindows": true,
  "branch": "aphrodite",
  "authentication": "none",
  "sqliteVersion": "3.32.1",
  "migrationVersion": 180,
  "urlBase": "",
  "runtimeVersion": "3.1.7",
  "runtimeName": "netCore"
}
```

**Comment by theotherp** [comment]
Argh. The current `aphrodite` source build (from source) returns 
```
{
  "version": "10.0.0.7637",
  "buildTime": "2020-09-01T02:15:01.7579899Z",
  "isDebug": true,
  "isProduction": false,
  "isAdmin": false,
  "isUserInteractive": true,
  "startupPath": "C:\\temp\\radarrv3\\_output\\netcoreapp3.1",
  "appData": "C:\\ProgramData\\Radarr",
  "osName": "Windows",
  "osVersion": "10.0.19041.0",
  "isNetCore": true,
  "isMono": false,
  "isLinux": false,
  "isOsx": false,
  "isWindows": true,
  "branch": "develop",
  "authentication": "none",
  "sqliteVersion": "3.32.1",
  "migrationVersion": 180,
  "urlBase": "",
  "runtimeVersion": "3.1.6",
  "runtimeName": "netCore"
}
```

**Comment by darthShadow** [comment]
Afaik, builds from the source are meant to be dev builds only and have the version number set to 10.x for the following reasons:
* Separation of analytics for production/dev builds.
* No accidental upgrades from dev to production builds.
* Explicit separation of production & dev builds via version numbers.

**Comment by darthShadow** [comment]
I think Sonarr builds from source also have the same version number, in case you want to add the same check there too.

**Comment by theotherp** [comment]
Ah, thanks for the info, I'll just check for 3.x and 10.x
