### ISSUE TITLE
Support for readarr

### ISSUE THREAD

**Issue by xconverge** [theotherp/nzbhydra2#619]
https://github.com/Readarr/Readarr

Might be a bit early, but would be nice if nzbhydra supported readarr.

I currently get:

"Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

And am wondering if there is something nzbhydra2 specific that needs to be done to support it (since I saw radarr v3 was recently added as supported, maybe a similar change is necessary?)

**Comment by theotherp** [comment]
You mean to be configured externally?

**Comment by xconverge** [comment]
When I added nzbhydra as an indexer to readarr I get:

"Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

I then noticed the changes in ExternalTools.java for sonarr and radarr and was wondering if not having readarr included in there was related? Not sure, I might be off here/have done something wrong but I don't think so...

**Comment by theotherp** [comment]
Those two are not related.

NZBHydra doesn't and doesn't have to support any tools for them to use it. Check the hydra log which should tell you why no results were returned for the search. It's a matter of configuration.

**Comment by xconverge** [comment]
Thanks, it looks like EBOOK is not supported by a bunch of indexers so I had to enable Query Generation. The log statement mentioning query generation was super helpful. I wonder if there is a better way of telling the user about something like this. I have no good ideas really, but things seem to work, so thanks for the hint and sorry for the noise!
