### ISSUE TITLE
Support for Medusa 

### ISSUE THREAD

**Issue by thesugarat** [theotherp/nzbhydra2#620]
Medusa, https://pymedusa.com/ is a very popular program for managing/autodownloading TV shows and Anime. I use mine with NZBHydra2 now as the sole aggregator of my indexers and absolutely love the combination. I noticed that in the Config main screen there is a dropdown option to "auto configure as an indexer in an external tool" but several great programs are missing including Medusa. Would love it if that option were available. It'll make it easier for people using Medusa to incorporate when I suggest it to them. I figured it out myself but I probably have something mis-configured and I just don't know it. I'd like to see what you're auto setup function might look like for Medusa.

**Comment by theotherp** [comment]
With the *arr "product line" all have the same API so I only had to implement it once. Supporting another program will take a lot of time for each one. I need to download it, install it, understand it, analyze the API and check if it's even possible to support it. And it might break with any release.

I'll keep it in mind.

**Comment by thesugarat** [comment]
Understood. I'm not 100% certain but the API for SICKRage/SickChill/Medusa should be the same as they are all forks. Might be worth the effort like the *arr product line... Thanks for keeping it in mind though.

**Comment by theotherp** [comment]
The API is absolutely horrible to use. I'm pretty sure I won't be able to support it.

**Comment by thesugarat** [comment]
Thanks for looking into it.
