### ISSUE TITLE
Add suffix or prefix to API / RSS request url to ex- / include certain content

### ISSUE THREAD

**Issue by Rawh** [theotherp/nzbhydra2#622]
* What do you want to happen?
Only show downloadable releases which aren't passworded.

* If not clear, why do you want it?
Several indexers include passworded files in their API or RSS (search) results. You can't remove this via the config on their cpanel. Instead you could add custom text, like `&pw=2`, to the API or RSS url, to exclude those results.

* Do you think it's something only you need or something that might be popular?
Might be popular for those people who use indexers with certain functionality.

**Comment by theotherp** [comment]
See the [pw attribute](https://newznab.readthedocs.io/en/latest/misc/api/#predefined-attributes). It should already work but isn't supported by all indexers.

**Comment by Rawh** [comment]
Are you saying it's already possible, or are you saying it understands the query-results and will filter out the passworded releases?

**Comment by theotherp** [comment]
Both?
