### ISSUE TITLE
Add several presets for different instances of the arrs in the add to the arrs dialog.

### ISSUE THREAD

**Issue by jpalenz77** [theotherp/nzbhydra2#626]
* What do you want to happen?
The chance to keep the preset of each instance of the arrs stored in hydra
* If not clear, why do you want it?
* Do you think it's something only you need or something that might be popular?
I think it might be popular since there are lots of people using several instances of the arss
* If not clear, explain the use case.

Thank you!

**Comment by theotherp** [comment]
Next time please include which programs you mean...:

Readarr I can do. Radarr4k and Sonarr4k seem to be plex plugins and I don't have plex. That would be too much work for me to get working and it seems to be * really* niche...

**Comment by jpalenz77** [comment]
I did not express myself properly, what I mean is now you have radarr, radarrv3, sonnarr, sonnarv3 and lidarr... would be fantastic to have (in addition) radarr(b), radarr(b)v3, sonarr(b) and sinarr(b)v3 so people like me that run 2 instances of radarr and 2 instances of sonarr could save both configs

**Comment by jpalenz77** [comment]
Radarr4k is a way of calling a second instance of raddar people use to get 4k content

**Comment by theotherp** [comment]
Oohh... that still seems a bit niche. It would also probably be confusing for the majority of people running only one instance who would then wonder which they're supposed to use... I'm afraid you'll have to manually change the data each time. It's not like you configure these tools every day...
