### ISSUE TITLE
generating query as failback causes search to fail and crash against torrent indexers

### ISSUE THREAD

**Issue by johnwchambers** [theotherp/nzbhydra2#629]
Searching for TV show "Because This is My First Life" through sonarr didn't yield any results, so I tried the search manually within nzbhydra2. I have the option set to generate queries never but to generate them as a failback. What happens is it errors out against all the torrent trackers added from jackett and then gets stuck on the search pop-up screen, my only option at this point is to click the cancel button. However, if I repeat the search again and don't use the drop-down for the TV show which means the search is just text based, I get the results I was looking for.

Debug log is attached. If there is anything else at all you need please let me know and thank you.

[nzbhydra-debuginfos-2020-09-15-10-25.zip](https://github.com/theotherp/nzbhydra2/files/5221966/nzbhydra-debuginfos-2020-09-15-10-25.zip)

**Comment by theotherp** [comment]
Should be fixed in the next release.

For the record: You do have query generation enabled.

Please disable all logging markers.
