### ISSUE TITLE
Feature Request: Notifications

### ISSUE THREAD

**Issue by angrycuban13** [theotherp/nzbhydra2#631]
* What do you want to happen?

I don't check Hydra often enough to know when my indexers are expiring so a Discord notification would be a great reminder and I would not have to remember to check Hydra every month.

It might work also for health notifications when indexers are down and such.

* Do you think it's something only you need or something that might be popular?

I believe this would be a very popular addition. Most services offer some type of notification (*arrs, SABnzbd, NZBGet, Jellyfin, Tautulli, Ouroboros, Watchtower, etc.) and it would benefit end users greatly to know if something is coming due or something isn't' working.

**Comment by angrycuban13** [comment]
There are some libraries that are freely available for implementation:

[Apprise](https://github.com/caronc/apprise)

[Shoutrrr](https://github.com/containrrr/shoutrrr)

**Comment by theotherp** [comment]
Notes for me:

Apprise seems to be more popular. I could either call the CLI or require https://github.com/caronc/apprise-api. The former is probably easier for the end user but the latter easier for me.

**Comment by nemchik** [comment]
Notification ideas:

- all indexers with limits have consumed all available API hits for the day. reset in X minutes
- all indexers with limits have consumed all available downloads for the day. reset in X minutes
- vip renewal for indexer X required in the next 30 days
- indexer X disabled due to REASON (this one might get annoying)

Hopefully each type of notification can be individually enabled/disabled. Not too concerned with notification type per indexer, just globally. Others might prefer to enable/disable per indexer though.

**Comment by nemchik** [comment]
Also I actually do like the https://github.com/caronc/apprise-api idea. That way if a user has other apps that might also want to use apprise they can run just one instance (local install or docker depending on the user) and all the apps can send notifications to it. This also technically leaves hydra open to the idea of general webhooks.

**Comment by theotherp** [comment]
Todos for me:

- [ ] Apprise API integration
- [ ] VIP expiration detection
- [ ] API hit exhaustion detection
- [ ] Download hit exhaustion detection
- [ ] Indexer disabled detection
- [ ] Indexer reenabled detection
- [ ] Notification history
- [ ] Show notifications in GUI

**Comment by theotherp** [comment]
API / download exhaustion detection is a bit more complicated. I'll try to get it working later.

**Comment by rodalpho** [comment]
I have apprise working fine from the CLI with a verified functional URL, but get a 500 error sending notifications from nzbhydra2. Grepped for "apprise" in the logs but nothing came up. 

![Screenshot 2020-10-19 152924](https://user-images.githubusercontent.com/747832/96502542-f1814880-121f-11eb-8d8d-da428fdae691.jpg)
![Screenshot 2020-10-19 152945](https://user-images.githubusercontent.com/747832/96502567-f9d98380-121f-11eb-8c24-894ade916c89.jpg)

**Comment by freiheit** [comment]
The inline docs there probably need a little help...  I have to use `http://localhost:8000/notify/` for the Apprise API URL, but it's not obvious that the URL isn't `http://localhost:8000/`

**Comment by rodalpho** [comment]
Wait, so apprise isn't running as a module inside NZBhydra2, it needs to be a daemon running somewhere accessible?

An "Apprise API URL" looks like the below for Pushover notifications.

pover://{user_key}@{token}

**Comment by theotherp** [comment]
@rodalpho There's a link to https://github.com/caronc/apprise-api in the help, you should click that.

@freiheit You're right, I'll add that.

**Comment by rodalpho** [comment]
I did, but I assumed I wouldn't be asked to run a separate daemon for notifications. If that is indeed the case, I would make that clear in the docs. And I mean, consider changing that?

**Comment by angrycuban13** [comment]
@rodalpho this is a beta release, not a master release. It is the second release at that, so documentation would clearly not be up to date.

Additionally, read through the issue and understand why the dev chose to use Apprise API instead of baking Apprise into the application, not just tell the dev what he should do.

**Comment by rodalpho** [comment]
"Consider changing that?" is not an order. Your handle checks out. 👍

**Comment by theotherp** [comment]
I wrote "If you want to send notifications you need an instance of Apprise API running which is what NZBHydra uses to communicate with the actual notification providers." I'm not sure how I could make it clearer but I'm open for suggestions.

Apprise is originally a python script. I couldn't embed it into NZBHydra because it requires a python installation. I could ask the docker container maintainers to install it but anyone already using docker would probably have no problem with having another run for notifications. That leaves non-docker installations and here you'd need an external script which would require a manual installation anyway.

**Comment by rodalpho** [comment]
You're right, that is pretty clear. "A separate instance of Apprise API" would be slightly better but I clearly misread it. 

I have the Apprise CLI installed and working, you could just call that.

**Comment by theotherp** [comment]
I'll add an option to define a runnable to call.

rodalpho <notifications@github.com> schrieb am Di., 20. Okt. 2020, 15:30:

**Comment by rodalpho** [comment]
Thank you, that would be excellent!

**Comment by rodalpho** [comment]
CLI notifications work great! Thanks again, you are a prince amongst men.

**Comment by ajhorvath20** [comment]
> CLI notifications work great! Thanks again, you are a prince amongst men.

I have already apprise installed inside the container and need little help to configure the notification via CLI. Thank you

**Comment by theotherp** [comment]
Do you have a concrete question? Put the full path of the executable into the "Apprise runnable" field.

**Comment by DrSeussFreak** [comment]
> The inline docs there probably need a little help... I have to use `http://localhost:8000/notify/` for the Apprise API URL, but it's not obvious that the URL isn't `http://localhost:8000/`

thank-you, I have been futzing with this for an hour trying to figure out why I could not sent a notification.  That did the trick!

**Comment by DrSeussFreak** [comment]
> The inline docs there probably need a little help... I have to use `http://localhost:8000/notify/` for the Apprise API URL, but it's not obvious that the URL isn't `http://localhost:8000/`

thank-you, I have been futzing with this for an hour trying to figure out why I could not sent a notification. That did the trick!

**Comment by BrandonG777** [comment]
> > The inline docs there probably need a little help... I have to use `http://localhost:8000/notify/` for the Apprise API URL, but it's not obvious that the URL isn't `http://localhost:8000/`
> 
> thank-you, I have been futzing with this for an hour trying to figure out why I could not sent a notification. That did the trick!

This should be included in the wiki. Took me way too long to track this down.

**Comment by pikeas** [comment]
I've just added some findings to https://github.com/theotherp/nzbhydra2/issues/660 that may be useful to followers of this issue.
