### ISSUE TITLE
[FR] Individual proxy settings

### ISSUE THREAD

**Issue by dimqua** [theotherp/nzbhydra2#632]
I would like to be able to use indexers with different proxy servers. For that reason, I think it can be useful to add a possibility to override the default proxy setting for each particular indexer, just like it can be done with User Agent currently.

Some indexers do not allow proxy usage (Tor, for example) or block certain countries and it would be useful to configure them differently from others.

**Comment by theotherp** [comment]
That sounds like a very, very specific issue... I'll think about it.

**Comment by dimqua** [comment]
Indexers that block Tor access: DrunkenSlug, NZBFinder, Tabula-Rasa, SimplyNZBs and NinjaCentral. Not sure about other proxies.

And regional indexers tend to restrict access for certain countries only.

**Comment by theotherp** [comment]
It's just that it will make configuration even more complex. At some point I have to stop adding fields to the config dialog, it's alrealy hard to understand. If that many indexers don't allow it I'd recommend not to use a proxy. Or use a system wide one which is configured to exclude those.

**Comment by theotherp** [comment]
If the indexers don't allow proxy usage can't you just add their hosts to
the exclusion list?

**Comment by dimqua** [comment]
@theotherp in hydra2 settings? I can't find where.

**Comment by theotherp** [comment]
![https://i.imgur.com/nBIVdnC.png](https://i.imgur.com/nBIVdnC.png)

**Comment by dimqua** [comment]
@theotherp after I save the settings domains that I entered disappear.

**Comment by theotherp** [comment]
You need to press enter

dimqua <notifications@github.com> schrieb am Mi., 7. Okt. 2020, 09:06:

**Comment by dimqua** [comment]
Thanks, it wasn't obvious to me.

This option basically solved my issue.
