### ISSUE TITLE
Error when trying to add indexers to radarr v3

### ISSUE THREAD

**Issue by hokagemedia** [theotherp/nzbhydra2#636]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 
Expect indexers to be added to radarr v3
Instead, error.

* Have you searched for this problem? You don't have to answer, just make sure.
Didn't see an open case.

* Can the problem be reproduced? How?
yes, add indexers to radarr v3

* If you use a docker container please tell me which one.
linuxserver/nzbhydra2:latest

Error below:

  "description": "System.NullReferenceException: Object reference not set to an instance of an object.\n   at Radarr.Http.ClientSchema.SchemaBuilder.<>c.<GetValueConverter>b__8_6(Object fieldValue) in D:\\a\\1\\s\\src\\Radarr.Http\\ClientSchema\\SchemaBuilder.cs:line 218\n   at Radarr.Http.ClientSchema.SchemaBuilder.<>c__DisplayClass5_2.<GetFieldMapping>b__2(Object t, Object v) in D:\\a\\1\\s\\src\\Radarr.Http\\ClientSchema\\SchemaBuilder.cs:line 124\n   at Radarr.Http.ClientSchema.SchemaBuilder.ReadFromSchema(List`1 fields, Type targetType) in D:\\a\\1\\s\\src\\Radarr.Http\\ClientSchema\\SchemaBuilder.cs:line 49\n   at Radarr.Api.V3.ProviderResourceMapper`2.ToModel(TProviderResource resource) in D:\\a\\1\\s\\src\\Radarr.Api.V3\\ProviderResource.cs:line 67\n   at Radarr.Api.V3.Indexers.IndexerResourceMapper.ToModel(IndexerResource resource) in D:\\a\\1\\s\\src\\Radarr.Api.V3\\Indexers\\IndexerResource.cs:line 45\n   at Radarr.Api.V3.ProviderModuleBase`3.GetDefinition(TProviderResource providerResource, Boolean includeWarnings, Boolean validate) in D:\\a\\1\\s\\src\\Radarr.Api.V3\\ProviderModuleBase.cs:line 101\n   at Radarr.Api.V3.ProviderModuleBase`3.CreateProvider(TProviderResource providerResource) in D:\\a\\1\\s\\src\\Radarr.Api.V3\\ProviderModuleBase.cs:line 73\n   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__42_0(Object options) in D:\\a\\1\\s\\src\\Radarr.Http\\REST\\RestModule.cs:line 190\n   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)\n   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)\n   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)\n   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)\n   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)\n   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)",
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69) [4 skipped],
java.io.IOException: Radarrv3 returned error message: Object reference not set to an instance of an object.,
	at org.nzbhydra.externaltools.ExternalTools.executeConfigurationRequest(ExternalTools.java:354),
	at org.nzbhydra.externaltools.ExternalToolsWeb.configureExternalTool(ExternalToolsWeb.java:50),
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) [3 skipped],
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158) [7 skipped]

**Comment by theotherp** [comment]
1. Set the log level for the log file to debug
2. Enable the logging marker for external tools configuration
3. Try to add configure hydra in radarr again
4. Post your debug infos
5. Post the radarr version
