### ISSUE TITLE
Unable to delete color for indexer

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra2#637]
Unfortunately a lot harder to fix than it seems.

You can shutdown hydra, open the file `data/nzbhydra.yml` (or something like that) and set the color value for the indexer to `null`. Save and start hydra.

**Comment by albino1** [comment]
I just finally messed with the color feature today and thought it was really cool, but now I have a bunch of indexers with random colors that I can't get rid of other than to make them black :)

There's no reason to rush in fixing this bug, but in the meantime is there a temporary workaround where I can just edit a file to blank out the color setting for individual indexers?

**Comment by albino1** [comment]
I just started trying to use this feature and got hit with the cannot delete color bug and came here to report it :)

After initially having a rainbow while playing with it I've just set everything to black, but I wonder if there's a workaround in the meantime to just edit a file and delete the color preference manually?

Also, I noticed an additional bug with the colors in that they only work when the indexer is the primary top level result.  If the result is grouped and not the top level one then the color isn't set once you expand the +.
