### ISSUE TITLE
[FR] Custom title mapping

### ISSUE THREAD

**Issue by reloxx13** [theotherp/nzbhydra2#638]
* What do you want to happen?
A possibility to let the user override specific series or movie title
Additional: Import/Export of this overrides for community shares

* If not clear, why do you want it?
Mostly series or anime series are named wrong in tvdb or releasers. With this user mapping it would be possible to fix this.
Some examples:
`The Haunting of Bly Manor` is listed as `The Haunting`
`Station 19` is released with the german (very diffrent meaning) title `Seattle.Firefighters.Die.jungen.Helden`

Not an example, but animes got alot of problems, too, with eng and jap titles.

* Do you think it's something only you need or something that might be popular?
I think it could get very popular cause it often happens that release titles does not match databases.

* If not clear, explain the use case.
The user can input a source and target title.
If a text search query arrives or get started by nzbhydra, it should look for the entered source strings and replace them with the target strings.
it should only apply to series/movies(/animes)

**Comment by theotherp** [comment]
I find the problem interesting although I've never encountered it. But
wouldn't it make more sense to fix these issues on tvdb?

**Comment by reloxx13** [comment]
it would, but just check their stubborn answers for the failed ordered new south park pandemic episode. they give a fuck.
