### ISSUE TITLE
FEATURE REQUEST: Enlarge Fonts from Category Selection

### ISSUE THREAD

**Issue by hernandito** [theotherp/nzbhydra2#639]
Hi,

I use my tablet quite often to browse web and search for media. After I have searched something and I click to add the NZB to my queue, the "Select Category" screen pops up.

![hydra1](https://user-images.githubusercontent.com/787317/98034033-5de57580-1de4-11eb-8b12-865964fc1b65.jpg)

The issue is that the category names are so small and so close together, that when selecting with my finger, its very easy to select the wrong one.

Can you please enlarge these category names.... or better yet, make each one a nice button with plenty of breathing room for the fingers.

Thank you for this awesome application!

H.

**Comment by theotherp** [comment]
Sure, why not.

To be clear, you use hydra on a touch device? And you can control everything fine, just this dialog's font is too small?

**Comment by hernandito** [comment]
That is correct.... Thank you!
