### ISSUE TITLE
BUG? Unable to determine java version from string openjdk version "11.0.9.1"

### ISSUE THREAD

**Issue by j-remy11** [theotherp/nzbhydra2#641]
I updated my openjdk to version "11.0.9.1" on my linux machine and nzbhydra2 won't start. The log says:

ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string openjdk version "11.0.9.1"  

Version 11.0.9 was working fine but not with 11.0.9.1 so I switched to openjdk 8 and that made nzbhydra2 boot again. Not sure if this is an openjdk issue or nzbhydra2 issue.

**Comment by theotherp** [comment]
Please run java --version and post the output.

**Comment by garrettben** [comment]
I have the same issue after upgrading openjdk.  Here is the requested output:

$ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by garrettben** [comment]
I replaced openjdk with the Oracle JDK and I was able to start nzbhydra.  Here is the new output from java--version for reference:

$ java --version
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

**Comment by theotherp** [comment]
What about `java -version`?

**Comment by theotherp** [comment]
I tested it with the latest adaptopenjdk and it works fine. I suggest you use that: https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=openj9#linux-pkg

**Comment by Viper911** [comment]
I am getting same error and adaptopenjdk for version 11 didn't seem to fix it.

java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode)

Logging wrapper output to /opt/nzbhydra2/data/logs/wrapper.log
2020-11-14 13:29:45,386  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string openjdk version "11.0.9.1" 2020-11-04

**Comment by pockets78** [comment]
Definitely a bug in the wrapper (nzbhydra2wrapper.py line 496) with the java version matching.  I think it should be
(java|openjdk) version "(?P<major>\d+)((\.(?P<minor>\d+)\.(?P<patch>\d+)(\.\d+)+))?([\-_\w]*)?".*
based on the results from regex101.com (I'm not a regex expert).

This will match with multiple patch levels (major.minor.patch.patch), etc.

**Comment by pushih** [comment]
Just to report that I am experiencing the same problem:

Logging wrapper output to /home/pushih/nzbhydra/data/logs/wrapper.log
2020-11-14 20:20:28,989  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string openjdk version "11.0.9.1" 2020-11-04

java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by theotherp** [comment]
Post java -version output, notice the single '.

I'll release an update tonight.

**Comment by sienar1** [comment]
just want to say thanks for fixing this so quick. had to manually update to 3.5.1, but my install was good to go after that!

**Comment by garrettben** [comment]
Confirming 3.5.1 solves the issue. I had to reinstall and restore from
backup, but all is working with openjdk.

**Comment by pushih** [comment]
I also want to express my gratitude to @theotherp for fixing this problem so swiftly. Everything is working now.
