### ISSUE TITLE
Unexpected error while preparing search

### ISSUE THREAD

**Issue by cphmichael** [theotherp/nzbhydra2#642]
"no usable search IDs could be found"

Does that mean that DogNZB don't know any of the cat 5020, 5040, 5045, 5090?

`Received external newznab API call: NewznabParameters{t=TVSEARCH, cat=[5020, 5040, 5045, 5090], imdbId=tt11794642, tvdbId=378023, tvmazeId=46062, season=1, ep=1, offset=0, limit=100, raw=false, o=XML, attrs=[], extended=true, indexers=[]}`

`DogNZB: Unexpected error while preparing search: Aborting searching for indexer because no usable search IDs could be found and no query was generated`

**Comment by theotherp** [comment]
Please post your debug infos (as requested in the bug template).

**Comment by cphmichael** [comment]
NZBHydra2: Version: 3.5.1
Container version: release-922da1d-106
Container release type: Release
Container author: hotio

Sonarr: Version 3.0.4.1011
Package Version nightly-ff6abd6-213 by hotio

- - - - - - -

In "Config > Main" I have set the logfile level to 'Debug'.

At 13:34 I restarted the NZBHydra2 docker container and right after that I did a search for "Big Sky (2020)" in Sonarr:

https://www.thetvdb.com/series/big-sky-2020

Debug logfile:
[nzbhydra-debuginfos-2020-11-19-13-35.zip](https://github.com/theotherp/nzbhydra2/files/5566750/nzbhydra-debuginfos-2020-11-19-13-35.zip)

**Comment by theotherp** [comment]
According to the determined caps DogNZB only supports movie search by IMDB ID and TV search by TVRage ID. TVMaze (which I use to convert TV show IDs) is [unable to provide a TVRage ID for that show](http://api.tvmaze.com/shows/46062).

As you configured hydra to only generate queries for internal searches it can't search DogNZB given the information provided by the API call.

I haven't had a DogNZB account in some time but I guess you should recheck the caps, it should at least support TVDB IDs.

**Comment by cphmichael** [comment]
Thank you for your reply.

I did a 'Check capabilities'.

I seems like DogNZB response very slowly. NZBHydra says:

`The capabilities of the indexer could not be checked completely. 
You may use it but it's recommended to repeat the check at another time.
Until then some search types or IDs may not be usable.`

After several not-successful checks - NZBHydra at last decided to only enable TVRage.

Does that mean that I can not use DogNZB?

- - - - -

"queries for internal searches" - Is that the options in Media IDs / Query generation?

I don't think I have changed them.

What setting would you advise me to use?

![image](https://user-images.githubusercontent.com/45288008/99824842-885e5f00-2b56-11eb-928e-c1e082f011ef.png)

**Comment by theotherp** [comment]
DogNZB's API server has been shit for ages. It's one of the reasons I don't use it anymore.

You can just manually set the IDs and search types for DogNZB:
IDs: TVRage, TVDB, IMDB
Types: Search, Movies, TV, Audio

Enable the "Fallback to generated queries" and you shouldn't have any issues.

**Comment by cphmichael** [comment]
I use DogNZB because, when it answers, it have a lot of 2160p 4k. And normally as one of the first so they isn't taken down.

I have enabled the "fallback" to 'All searches'.

Thank you for your advices :-)
