### ISSUE TITLE
Question: Transform newznab categories?

### ISSUE THREAD

**Issue by cphmichael** [theotherp/nzbhydra2#643]
I don't understand the:

Transform newznab categories:
Map newznab categories from API searches to configured categories and use all configured newznab categories in searches.

Is there a prefered setting here (On/Off)?

I have one TV category with 5020, 5040, 5045, 5090

I still receive a lot of 5010 from NZBFinder - I have therefore created an extra TV category where I have set 5010 as 'Ignore results'.

For that to function - Is that related to the on/off in Transform newszab categories?

**Comment by theotherp** [comment]
Say you have configure a category "TV Other" which has the newznab categories 5020, 5050, 5060.

Now hydra gets an API query for any results with category 5020. 

With "Transform newznab categories" **off** hydra will query all the indexers for results with category 5020 only. With "Transform newznab categories" **on** hydra will query all the indexers for results with category 5020, 5050, 5060. 

If you search manually it doesn't make a difference as hydra will use exactly the newznab category of the category you selected.

If any external tool queries hydra it makes sense to let it only search the categories from which you want results and you're fine. So in this case set the sonarr categories to 5020, 5040, 5045, 5090.

**Comment by cphmichael** [comment]
When I do a search for "His Dark Materials S02E03" in Sonarr > NZBHydra2, it founds one from DrunkenSlug (see screenshot)
When I do an Internal search for the same series, NZBHydra2 do not find the series from DrunkenSlug.

I can see in the log that NZBHydra2 does 5 x Newznab to DrunkenSlug for the same series with (offset=0, offset=100, offset=200, offset=300, offset=400)

I have manually done the 5 x Newznab in a browser and can see that the Newznab with offset=0 includes the series, but the other ones do not include it. 

* For some reason I can not see result from the offset=0 search in the internal search?

In the Categories I have "Forbidden words" and "Required regex" but have set "Apply restrictions" = API searches, because I would like to see all the returned series without restrictions, when I do a manually search. This way I can check if there is an error in my regex or a "Forbidden word" is the reason Sonarr don't find a series.

**NZBHydra-debuginfos**:
[nzbhydra-debuginfos-2020-11-24-11-24.zip](https://github.com/theotherp/nzbhydra2/files/5589118/nzbhydra-debuginfos-2020-11-24-11-24.zip)


`New search request: SearchRequest{source=INTERNAL, indexers=[abNZB, NZB Finder, NZBGeek, nzbplanet, SimplyNZBs, Tabula-Rasa, Drunken Slug, NZBCat, DogNZB], searchType=TVSEARCH, category=TV, offset=0, limit=100, identifiers={TVDB=360295, TVIMDB=tt5607976, TVMAZE=7626}, title=His Dark Materials}`

`Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<removed>&t=tvsearch&extended=1&tvdbid=360295&imdbid=5607976&tvmazeid=7626&password=1&cat=5020,5040,5045,5090&limit=100&offset=0`

`Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<removed>&t=tvsearch&extended=1&tvdbid=360295&imdbid=5607976&tvmazeid=7626&password=1&cat=5020,5040,5045,5090&limit=100&offset=100`

`Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<removed>&t=tvsearch&extended=1&tvdbid=360295&imdbid=5607976&tvmazeid=7626&password=1&cat=5020,5040,5045,5090&limit=100&offset=200`

`Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<removed>&t=tvsearch&extended=1&tvdbid=360295&imdbid=5607976&tvmazeid=7626&password=1&cat=5020,5040,5045,5090&limit=100&offset=300`

`Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<removed>&t=tvsearch&extended=1&tvdbid=360295&imdbid=5607976&tvmazeid=7626&password=1&cat=5020,5040,5045,5090&limit=100&offset=400`

![image](https://user-images.githubusercontent.com/45288008/100083197-67915480-2e49-11eb-9eed-3640da719ede.png)

![image](https://user-images.githubusercontent.com/45288008/100078462-d66baf00-2e43-11eb-901b-999cc9135fbd.png)

**Comment by theotherp** [comment]
For some reason words are required from the internal search results but I can neither reproduce the problem nor can I explain why that would happen.

Please enable debug level for the log file and enable the log marker "Rejected results".

**Comment by cphmichael** [comment]
As you can see on the internal search screenshot, DogNZB found the series from 'blutonium' that's missing from DrunkenSlug.

Here is the new debug-log:
[nzbhydra-debuginfos-2020-11-24-14-15.zip](https://github.com/theotherp/nzbhydra2/files/5590075/nzbhydra-debuginfos-2020-11-24-14-15.zip)

![image](https://user-images.githubusercontent.com/45288008/100099439-bc3fca00-2e5f-11eb-9a0a-c5caa1e0ef6a.png)

**Comment by theotherp** [comment]
Sorry, should've said that you need to restart hydra. I'll update the code to notify of that.

**Comment by cphmichael** [comment]
Ahh, that why you asked for a debug-log, because the first one I attached was also a debug-log, but without restart.

Here is a debug-log with restarted hydra and a new internal search:
[nzbhydra-debuginfos-2020-11-24-14-50.zip](https://github.com/theotherp/nzbhydra2/files/5590276/nzbhydra-debuginfos-2020-11-24-14-50.zip)

**Comment by theotherp** [comment]
Ah ok, I shot myself in the foot with one logging output which I only put out on debug level.

You searched manually for "s02e03" and using titles. Don't do that. Use the season and episode input fields and the indexers will be searched for that episode specifically (that's what sonarr does). The way you do it hydra will search the indexers for all episodes of that series and then afterwards throw away all results without "s02e03" in the title (which means that you need more API requests and that stuff like "2x03" is thrown away as well).

**Comment by mailingUS** [comment]
I select TV - enter search text “His Dark Materials” - and in the “S” I enter ‘2’ and in the “E” I enter ‘3’ - and click on Go!

I am still only seeing the WEB-DL / BLUTONIUM from DogNZB - as in the search screenshot I attached earlier.

But now I’m seeing much less search entries in the log.

When I search from Sonarr I’m still seeing the one from DrunkenSlug.

**Comment by cphmichael** [comment]
I select TV - enter search text “His Dark Materials” - and in the “S” I enter ‘2’ and in the “E” I enter ‘3’ - and click on Go!

I am still only seeing the WEB-DL / BLUTONIUM from DogNZB - as in the search screenshot I attached earlier.

But now I’m seeing much less search entries in the log.

When I search from Sonarr I’m still seeing the one from DrunkenSlug.

**Comment by theotherp** [comment]
Make another search from sonarr and another from the GUI. Note the current time for each. Then create new debug infos. It's easy for me to get lost in the log otherwise.

When I search manually I see the blutonium release from DS.

**Comment by cphmichael** [comment]
If you can see the blutonium from DrunkenSlug and I can not, then there must be something I have setup wrong.
I tried to change the TV categories to [5000], but that didn't change anything.

The series got updated to WEBDL-2160p from DrunkenSlug - and that one I can see in Hydra when I do a manually search.

I can give you remote access to my Hydra if you want to investigate further - But I fully understand if you don't want to spend more time on this.

It is after all not a big problem. 

![image](https://user-images.githubusercontent.com/45288008/100234753-d515b180-2f2b-11eb-86d5-7c1e48d56b5c.png)

![image](https://user-images.githubusercontent.com/45288008/100234867-f8d8f780-2f2b-11eb-8a08-c244ad0bc5df.png)

**Comment by theotherp** [comment]
I imported your config and enabled a couple of other indexers and still get the 1080p blutonium release.

Sorry, no idea.
