### ISSUE TITLE
Errors are still reported in XML with ?o=json

### ISSUE THREAD

**Issue by nyuszika7h** [theotherp/nzbhydra2#644]
# Steps to reproduce 
* Make a request to NZBHydra that results in an error (e.g. wrong API key). Use the `?o=json` parameter.

# Expected behavior
The response should be in JSON format.

# Actual behavior
The response is in XML format, disregarding the specified preference.

```
❯ curl -s 'https://nzbhydra.example.com/api?t=search&q=test&offset=0&o=json&apikey=test'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error xmlns:atom="http://www.w3.org/2005/Atom"  xmlns:newznab="http://www.newznab
.com/DTD/2010/feeds/attributes/" code="100" description="Wrong api key"/>
```

# Environment
* NZBHydra 3.5.1
* Debian 10

**Comment by theotherp** [comment]
Is that something that actually affects you? How?

**Comment by nyuszika7h** [comment]
Yes, it is. I have a Telegram bot that uses NZBHydra's search API and it
just throws an exception when trying to decode the error as JSON. I mean I
was able to work around it by falling back to XML on parse error (since I
did not want to rewrite the whole parser in XML), but that's a hacky
solution and it's definitely a bug that NZBHydra ignores the ?o= option in
this case,and even if I specify something like `Accept:
application/json;q=1.0`, it returns XML instead of at least returning HTTP
406 Not Acceptable per the standard, if not returning JSON as requested.

**Comment by theotherp** [comment]
I understand but usually nobody uses it the json output. Many indexers
don't support it. I wouldn't put any effort into it if it was just
something you noticed so I wanted to be sure.
