### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by jamie-stinson** [theotherp/nzbhydra2#645]
* What do you want to happen?

I'm currently running a Kubernetes cluster running multiple replicas of NZBHydra. For high availability it would be great to have MySQL support to store the full configuration.

* Do you think it's something only you need or something that might be popular?

I believe this could be quite a popular feature as there is a lot people that don't like using flat file and prefer to use an external database.

**Comment by theotherp** [comment]
No can do. The complexity to support another database would be too much, I
can barely keep the one running. I *might* support h2 database servers but
even that would be quite some work.

**Comment by YouveGotMeowxy** [comment]
What if ya swapped sqlite for mysql entirely? :P Then you'd still only be supporting 1 db. 

(redis for caching would be an extra nice bonus, too, but I wont mention that, hehehe)

**Comment by theotherp** [comment]
I don't use sqlite but h2.
