### ISSUE TITLE
BUG - Docker instance wont start after upgrade to 3.6.0

### ISSUE THREAD

**Issue by EC58** [theotherp/nzbhydra2#646]
After upgrading my docker instance to the latest version it wont start anymore.
Maybe the database got corrupted or something. I do not know.

I tried a number of things like a new docker instance, backed up database etc. But it did not help.

I have an export of the logs. I am using the linuxserver image.

[nzbhydra2.zip](https://github.com/theotherp/nzbhydra2/files/5652796/nzbhydra2.zip)

**Comment by theotherp** [comment]
The database is indeed corrupted. You can try manually restoring it from the latest backup ZIP. Sorry for the late response.

**Comment by EC58** [comment]
> The database is indeed corrupted. You can try manually restoring it from the latest backup ZIP. Sorry for the late response.

Restoring a much older backup did the trick. I think the latest backup was also corrupt. Thanks!
