### ISSUE TITLE
REQ - Support extended/custom variables

### ISSUE THREAD

**Issue by neofright** [theotherp/nzbhydra2#647]
Hi TheOtherP,

Thank you for all that you do, and congratulations on 5(!) years.

Do you know if it is currently possible to support extended variables for indexers?

For example (pre'd releases only):
https://api.url.tld/api?t=search&apikey=00000000000000000000000000000000&pred=1

or (exclude passworded releases):
https://api.url.tld/api?t=search&apikey=00000000000000000000000000000000&pw=0

etc.

Thanks in advance.

**Comment by theotherp** [comment]
`pw` is already supported. `pred` is not part of [the spec](https://newznab.readthedocs.io/en/latest/misc/api/). Which indexers do you know that support it?

**Comment by neofright** [comment]
It appears `pred` is only accepted for "XML Search API" and "JSON Search API".

One must supply `&extended=1` and then the additional attributes are returned.

I'll PM you shortly.

**Comment by theotherp** [comment]
I see.

What would you want to happen with it? I could add the `pred` parameter so that it will be forwarded (i.e. a query to hydra using that parameter will result in a query to the indexer with the same parameter value). Or do you want to configure hydra so that it will always be set to a certain value for any indexer?

**Comment by neofright** [comment]
I think I was imagining, instead of an additional column or a toggle on the indexer, that I would add the same indexer twice - with different options.

My workflow is often to search on srrdb - find the release and then search indexers. Being able to filter results like this on a first pass would be awesome!

Do you think this makes sense as a worthwile thing to add?

**Comment by theotherp** [comment]
Right, so you want a switch for the indexer to always use `pred=1`?

**Comment by neofright** [comment]
Yes, I think that would be ideal, thank you.

**Comment by theotherp** [comment]
Sorry this took so long. The next version will allow you to define custom (static) parameters.

**Comment by neofright** [comment]
Thank you very much!
