### ISSUE TITLE
Option to remove "Results as Zip" from search screen

### ISSUE THREAD

**Issue by greg2126** [theotherp/nzbhydra2#650]
It would be nice to see a configuration option that allows a user to remove the "Results as Zip" button from the search screen.

This is not something that I expect many people need, but there are indexers our there that require NZBHydra to "send nzb link" to Nzbget/Sab instead of downloading the Nzb directly. When you select results as zip then nzbhydra will download the NZB instead of NZBGET/SAB and indexers can get angry.

**Comment by theotherp** [comment]
I don't understand the issue - just don't click the button?

**Comment by greg2126** [comment]
Yes, I know it sounds silly, but the buttons are right next to each other, which can make it easy to accidentally click the "Results as Zip" button instead of "+Nzbget" button. There is no prompt, and it just starts the download process, bypassing any configurations set to ensure the NZBs are not downloaded by NzbHydra directly.

**Comment by theotherp** [comment]
Ah, they disabled your account, eh? I'll think about it.

**Comment by greg2126** [comment]
That's all I can ask for, thanks for your consideration.
