### ISSUE TITLE
Alternate UI Colors

### ISSUE THREAD

**Issue by curiousstyles** [theotherp/nzbhydra2#654]
Hi,

I love NZBHydra2.... I'm in it all the time. So much that I see two bright green horizontal lines when I close my eyes... Doctors have warned that I could start seeing the same green bars with my eyes open.

All kidding aside, being the graphic designer tinkerer that I am, I used the **Stylus** Add-On for Firefox. This add-on allows one to customize specific site's CSS code so you can change the design a bit. I have made modifications for a _calmer_ UI.

![image](https://user-images.githubusercontent.com/56490391/102409276-c1a2b700-3fbc-11eb-81bf-c39bd8e305ec.png)

![image](https://user-images.githubusercontent.com/56490391/102409508-2bbb5c00-3fbd-11eb-88f4-79c545578d26.png)

If you or anyone prefers a calmer version, I am pasting the CSS code changes that get you there. I would love this as an option in  settings.

Thank you for your awesome work!

`body, html {
    height: 100%;
    background: #f7f7f7;
    color: #595959;
    font-family: sans-serif;
}

.navbar-default {
    background-color: #979797;
    border-color: #1a1a1a;
}
.nav-tabs {
    border-bottom: 1px solid #a6a4a4;
}

.btn-default {
    color: #555;
}

.btn-success {
    background-color: #4b845e;
}

.config-button {
    border: 1px solid #a6a4a4;
    border-bottom-color: rgb(28, 30, 34);
    border-bottom-color: transparent;
    border-radius: 8px 8px 0 0;
    margin-top: 7px;
}

.btn-info {
    background-color: #2767a4;
    border-color: #2767a4;
}

.btn-info.active, .btn-info.focus, .btn-info:active, .btn-info:focus, .btn-info:hover, .open > .dropdown-toggle.btn-info {
    color: #fff;
    background-color: #89b9e8;
    border-color: #89b9e8;
}

.indexer-button.config-incomplete {
    background-color: #c81c12;
    border-color: #c81c12;
    color: #fff;
}

#banner {
    height: 100px;
    margin-top: 50px;
 filter: grayscale(20%);

}

.nav-tabs > li.active > a, .nav-tabs > li.active > a:focus, .nav-tabs > li.active > a:hover {
    color: #555;
    background-color: #f7f7f7;
    border: 1px solid #a6a4a4;
    border-bottom-color: rgb(5, 129, 32);
    border-bottom-color: transparent;
    border-top-right-radius: 9px;
    border-top-left-radius: 9px;
    padding-left: 24px;
    padding-right: 24px;
    padding-top: 5px;
   
}

.navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:focus, .navbar-default .navbar-nav > .active > a:hover {
    color: #ffd01e;
    background-color: #4a4a4a;
    font-size: 18px;
    font-weight: 550;
    
}

.navbar-default .navbar-nav > li > a:focus, .navbar-default .navbar-nav > li > a:hover {
    color: #fff;
    background-color: #4e9754;
}

.form-control {
    background-color: #fbf8ee;
    background-image: none;
    border: 1px solid #919191;
    border-radius: 6px;
    border-top-left-radius: 6px;
    border-bottom-left-radius: 6px;

}

.input-group-btn2 {
    border: 1px solid #919191;
    border-radius: 6px;
    border-top-right-radius: 6px;
    border-bottom-right-radius: 6px;
}

.input-group-btn1 {
    border: 1px solid #919191;
    border-left-width: 1px;
    border-left-width: 0;
    border-radius: 6px;
}

.input-group-addon {
    background-color: #eee;
    border: 1px solid #919191;
    border-right-color: #919191;
    border-right-style: solid;
    border-right-width: 1px;
    border-radius: 6px;
    border-top-right-radius: 6px;
    border-bottom-right-radius: 6px;
}

a {
    color: #3f8e59;
}
a:focus, a:hover {
    color: #b91f1f;
}

.dropdown-menu {
    background-color: #fff;
    border: 1px solid #919191;
    border-radius: 12px;
    -webkit-box-shadow: 6px 6px 12px rgba(0,0,0,.175);
    box-shadow: 6px 6px 12px rgba(0,0,0,.175);
    background-clip: padding-box;
}

.search-results-table {
    border: 1px solid #cacaca;
    border-radius: 6px;
}

.pagination > li > a, .pagination > li > span {
    color: #444;
    background-color: #eee;
    border: 1px solid #bbb;

}

.pagination > .disabled > a, .pagination > .disabled > a:focus, .pagination > .disabled > a:hover, .pagination > .disabled > span, .pagination > .disabled > span:focus, .pagination > .disabled > span:hover {
    color: #777;
    border-color: #bbb;
    cursor: not-allowed;
}

.pagination > li > a:focus, .pagination > li > a:hover, .pagination > li > span:focus, .pagination > li > span:hover {
    border-color: #bbb;
}

.panel {
    border-color: #919191;
}

[ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate) {
    display: none !important;
    color: beige;
}

.glyphicon {
    color: #eaeaea;
}

.nvd3 .nv-multibarHorizontal .nv-groups rect {
    fill: #3e914a !important;
}
.nvd3 .nv-discretebar .nv-groups rect {
    fill: #3e914a !important;
}

.bootstrap-switch .bootstrap-switch-handle-on.bootstrap-switch-primary {
    background-color: #5b9563;
    color: #fff;
}

.bootstrap-switch {
    border: 1px solid #6cab75;
}

.panel-default > .panel-heading {
    background-color: #3e914a;
}

.btn-danger {
    color: #fff;
    background-color: #c10d02;
    border-color: #c10d02;
}

.chip-control {
    margin-top: 3px;
    border: 1px solid #d9d9d9 !important;
}
`

**Comment by curiousstyles** [comment]
A side by side comparison...

![image](https://user-images.githubusercontent.com/56490391/102410677-de3fee80-3fbe-11eb-9ec0-fcd2c158dd07.png)

**Comment by theotherp** [comment]
You do know that there other themes? Check the main config.

**Comment by curiousstyles** [comment]
Hi, Yes thank you.... They are all very high-contrast themes.... something more subtle would help. 

I would be very happy to take a stab at editing the CSS of one of the themes to come up with one or two themes.... but in the downloaded code on my NZBH Docker, I cannot locate any CSS files. 

I got the css style names using FF's "Inspect Element (Q)". Then I pasted those in the Stylus code with the changes.

I would not call myself a coder, but I can do CSS, html and PHP.

**EDIT:**
I just noticed something about Theme.Park, where one can inject additional themes. If the above is not possible with the code for NZBH2, I could try to clone that repo and come up with additional variations. 

Please let me know your thoughts.

Thanks.

**Comment by theotherp** [comment]
https://github.com/theotherp/nzbhydra2/wiki/Development-of-frontend-resources

It's not easy. I don't think the grey theme is "high contrast" and you wrote about "bright green lines".

Anyway, I'm not opposed to new / more themes. Give it a try.

**Comment by curiousstyles** [comment]
Great... 

I found CSS files in the repo which I saved locally and renamed. I entered/edited all the modifications I did in Stylus. 

However, I don't know what to do to test. I use NZBH2 in a Docker. When I SSH into the docker, I cannot locate any of the CSS files. Is the CSS info compiled into some other file?  

I would love to test and then submit for your review.

Thanks,

H.

**Comment by theotherp** [comment]
All the colors for the bright theme are defined in https://github.com/theotherp/nzbhydra2/blob/master/core/ui-src/less/bright.less

Opening them in a proper editor should show previews of the color and allow you to edit the colors in a color picker. Send me the resulting `.less` file and I'll add it as a "less bright" theme. 

If you want to see the resulting CSS file you'll have to compile it using [LESS](http://lesscss.org/). It should look something like this: `lessc bright.less bright.css`.  You will probably need to install the bower components for the imports to work. But all that might not be necessary, the variable names are relatively self explanatory.

**Comment by theotherp** [comment]
Closing this due to lack of feedback. You may send me LESS files or use the Stylish browser extension to adapt hydra's look.
