### ISSUE TITLE
NZBGeek returns "handshake_failure" in Docker

### ISSUE THREAD

**Issue by ShawnHardwick** [theotherp/nzbhydra2#656]
Noticed that NZBGeek was not working in my primary NZBHydra instance that runs in Docker.

`Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer NZBGeek. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

I've reproduced the issue by performing the following:
- Create new docker container from scratch
- Add NZBGeek as indexer with API key
- Check capabilities when adding indexer returns above error in log.

**Other notes**
Executing curl against the NZBGeek API within the container returns a proper response:
`https://api.nzbgeek.info/api?t=caps`

API calls work from Sonarr/Radarr.

Using Docker image:
https://hub.docker.com/r/linuxserver/nzbhydra2

Debug file:
[nzbhydra-debuginfos-2020-12-23-01-18.zip](https://github.com/theotherp/nzbhydra2/files/5733674/nzbhydra-debuginfos-2020-12-23-01-18.zip)

Version: 3.8.0

**Comment by TimBailey-pnk** [comment]
I'm seeing this too, probably something to do with their current outage?  I've tried 4 different docker images with the same result

**Comment by ShawnHardwick** [comment]
Front end has an outage, but the API is still functional. Sonarr/Radarr
works fine.

**Comment by theotherp** [comment]
Something with their certificate is weird. Not saying it's their fault but
no other indexer has caused this much trouble.
Can't do anything about it as I'm not at home for the holidays.

**Comment by silentguy256** [comment]
I have the same problem on windows. *sigh* That's what I get for never bothering to set up sonarr and radarr and stuff and always going with the "their webinterface is enough for me" approach :-(

**Comment by incognit-o** [comment]
I'm getting the same thing here now. It was working just fine before.

**Comment by othbert** [comment]
I had the same issue. Funnily enough, removing nzbgeek.info from disable_sni in the main settings seems to have fixed it for me, checking caps worked and indexer added again

**Comment by ShawnHardwick** [comment]
I can verify that removing nzbgeek.info from the disable sni setting fixes the issue.

**Comment by mmackenny** [comment]
Dumb question on my part, where do I go to find the "main setting" to disable the SNI? Looked at the GUI and can't see it, at least for me, anywhere that jumps out. Tried 'config -> main' and didn't see it.

**Comment by ShawnHardwick** [comment]
Turn on advanced settings which is a slider button at the top.

**Comment by othbert** [comment]
sounds like you may need to "Show advanced" settings on that config -> main page.

**Comment by mmackenny** [comment]
Aha, it was dark and barely noticeable. That fixed my issue. Thanks all!

**Comment by theotherp** [comment]
Glad you found an easy fix!

**Comment by kiseliok** [comment]
> I had the same issue. Funnily enough, removing nzbgeek.info from disable_sni in the main settings seems to have fixed it for me, checking caps worked and indexer added again

Thank you! This worked.
