### ISSUE TITLE
Unable to determine java version from string openjdk version "11.0.9.1" in 3.8

### ISSUE THREAD

**Issue by pugfantus** [theotherp/nzbhydra2#657]
After upgrading from 3.5.1 to 3.8 I get the following error starting up.  It looks like there's a repeat of #641 

2020-12-27 17:47:04,023  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string openjdk version "11.0.9.1" 2020-11-04

/opt/nzbhydra2/lib$ ls -l
total 61348
-rw-r--r-- 1 nzbdrone media 62818330 Dec 27 17:21 core-3.8.0-exec.jar
/opt/nzbhydra2/lib$ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

**Comment by pugfantus** [comment]
I was able to get the service running again by switching the nzbhydra2.service over to use the python3 wrapper.

**Comment by theotherp** [comment]
Sounds like the wrapper was outdated.
