### ISSUE TITLE
[Question] Priority of Indexers

### ISSUE THREAD

**Issue by marc0janssen** [theotherp/nzbhydra2#658]
Maybe I am mistaken but for me the priority of the indexers is reversed.

"The result from the indexer with the highest number is shown first in the GUI and returned for API searches."
This text is found in the sofware.

But if order the indexers like

NZB1 - 90
NZB2 - 80
NZB3 - 70

The results of NZB3 will always be send first to the NZBGET.
I thought the results of NZB1 would be the first to be send.

Am I mistaken or am I doing something wrong here?

**Comment by marc0janssen** [comment]
What happens:

1. Sonarr requests a result from NZBHydra2
2. NZBhydra2 send result to the Sonarr (this is always a result from NZB3)
3. Sonarr sends this result to downloader.
4. This download fails because NZB3 has crappy quality
5. The Sonarr requested a replacement NZB
6. NZHhydra2 sends a new result (this is always a result from NZB1)

You would expect is the order is:
NZB1 - 90
NZB2 - 80
NZB3 - 70

that NZBHydra would have send a result from NZB1 in the first go. Since NZB3 had 70 which is lower than 90.

**Comment by theotherp** [comment]
Indexer priority only affects duplicate results, i.e. results from different indexers which link to the same upload. It has no effect on which NZBs are requested by sonarr.

**Comment by marc0janssen** [comment]
Ok clear on that.

But I have:
NZB1 - 90
NZB2 - 80
NZB3 - 70

NBZ1 is not the one that will be use for primary result. and then NZB2 and then NZB3... 
NZB2 could be questioned before NZB1?

**Comment by theotherp** [comment]
Hydra will just return a list of results. It's up to sonarr to decide which result should be downloaded.

Don't pay too much attention to the score, it doesn't allow you as much control as you might wish.

**Comment by marc0janssen** [comment]
Thanks Theotherp.. Yes was under the impression that I could control the indexer used.
I have 4 payed ones at the moment, and would like more control the get one "nominated" as least one. And skip it from the list.


Thanks for your info.

Have a great new years eve!!

**Comment by DerekWilliamsUK** [comment]
@marc0janssen You can set priorities for indexers within Sonarr, but this will mean not using Hydra. I use Hydra for everything EXCEPT Sonarr. See image.
![2020-12-29_8-05-07](https://user-images.githubusercontent.com/18551763/103269267-6229ab80-49ad-11eb-9550-e099a5795e07.jpg)

**Comment by marc0janssen** [comment]
Thanks for your advice Derek!!

**Comment by theotherp** [comment]
You can add each indexer to be used via hydra. You'll get the stats and advanced filtering and what not. Just use the "Configure in..." button and choose to add the indexers separately.

Closing this as I think the question's answered.

**Comment by marc0janssen** [comment]
" to add the indexers separately"

That was exactly what I needed.... no I keep the filtering en stats!!!! THANKS!!! 

Best wishes for 2021!!
