### ISSUE TITLE
Unable to log in after adding first user. 'POST' not supported

### ISSUE THREAD

**Issue by Serneum** [theotherp/nzbhydra2#659]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen?

> I added a user during my first use of NzbHydra. At some point I got kicked back to a login page, at which point I started getting errors about POST not being supported:
> ```
> Unexpected error when client tried to access path /login and parameters password=<password>&BSbjk87GAX8, username=<username> Error message: Request method 'POST' not supported
> ```

* Have you searched for this problem? You don't have to answer, just make sure.

> Yes, I briefly searched for `login` and `POST` in the open and closed issues but did not find anything useful

* Can the problem be reproduced? How?

> Try to log in again

* If you use a docker container please tell me which one.

> I am currently using the latest version available at https://hub.docker.com/r/linuxserver/nzbhydra2

* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.
It probably doesn't matter, but:

> Ubuntu 20.04.1 LTS
> Brave browser, Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Comment by theotherp** [comment]
You can shut down hydra and open the file `nzbhydra.yml` and set the auth method to `BASIC`. Then log in using basic auth. Then you can try again enabling form auth.

After seeing the login error open the browser console (F12), switch to the network tab and select the failed request. You might need to reload the page to see it appear. Post the full link to the URL.
It might look like this: https://i.imgur.com/4TGLkL7.png

**Comment by Serneum** [comment]
Well, to keep moving forward I originally just removed the `yml` file and started over as I hadn't done much. I just re-added my user, restarted the app, and now I can log in. It must have just been a fluke, possibly caused by me not waiting long enough between button presses somewhere. If it happens again I'll re-open this with info from the console
