### ISSUE TITLE
Upated to 1.1.0 and Sickrage doesn´t work anymore

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#66]
updated to v1.1.0 and have severe problems with Sickrage (Couchpotato works flawless):

- in the search history i can see the search and some results from the indexers
- Sickrage suddenly doesn´t get any result from nzbhydra
- Sickrage just shows no results, but no error messages in the SR log

[nzbhydra-debuginfos-2018-01-16-08-57.zip](https://github.com/theotherp/nzbhydra2/files/1634212/nzbhydra-debuginfos-2018-01-16-08-57.zip)

**Comment by theotherp** [comment]
Enable debug logging level for the log file and in the logging markers
setting choose URL calculation. Do another search and send me the debug
infos.

Am 16.01.2018 09:45 schrieb "Hobbabobba" <notifications@github.com>:

**Comment by Hobbabobba** [comment]
[nzbhydra-debuginfos-2018-01-16-11-43.zip](https://github.com/theotherp/nzbhydra2/files/1634706/nzbhydra-debuginfos-2018-01-16-11-43.zip)

**Comment by theotherp** [comment]
I'm an idiot... The algorithm hiding the sensitive information in the log is also hiding all the information that I'd need to debug the issue... I'll try to find the problem tonight.

**Comment by theotherp** [comment]
Did you enter the same address in SR that you entered in CP?

**Comment by Hobbabobba** [comment]
all the settings are exactly the same. and i tried without reverse proxy settings, same problem

**Comment by theotherp** [comment]
You mean it doesn't even work when you enter hydra's local address into SB?

Am 16.01.2018 12:35 schrieb "Hobbabobba" <notifications@github.com>:

**Comment by Hobbabobba** [comment]
in hydra i deleted the settings for base-path and external URL.
From SR and CP i used hydra through 192.168.0.5:5076 instead of https://www.mydomain.com/nzbhydra/
same effect: CP works, SR not.

**Comment by theotherp** [comment]
Jesus, I thought Hydra was complicaed to configure.

**Comment by theotherp** [comment]
Yeah, no idea. The URL it calls works fine and Hydra returns results matching the request. The XML returned is valid. The debug output by SR doesn't really help. As you say CP works and so does Sonarr.

You'll need to ask the SR devs.

**Comment by theotherp** [comment]
Unfortunately knowing the problem is not the same as solving it. It might take a couple of days, sorry about that.

**Comment by Hobbabobba** [comment]
just tried Sonarr. As you said, works perfect. I think i will just switch to Sonarr, gives you less of a headache ;)

**Comment by theotherp** [comment]
I think you won't regret it. I'll still try to solve this issue.

Am 17.01.2018 09:17 schrieb "Hobbabobba" <notifications@github.com>:

just tried Sonarr. As you said, works perfect. I think i will just switch
to Sonarr, gives you less of a headache ;)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/66#issuecomment-358229770>,
or mute the thread
