### ISSUE TITLE
Drunken slug api hit warnings

### ISSUE THREAD

**Issue by AtariBaby** [theotherp/nzbhydra2#664]
[nzbhydra-debuginfos-2021-01-05-19-11.zip](https://github.com/theotherp/nzbhydra2/files/5792208/nzbhydra-debuginfos-2021-01-05-19-11.zip)
Currently on the free tier of DrunkenSlut. I have adjusted my DrunkenSlug settings to 25 hits and 5 downloads, but I’m getting the error “ {'code': '500', 'description': 'You have reached your daily limit for API requests! Please upgrade your account'}” I had my hit reset time at 0, so I tried blank, and it happens either way.

**Comment by theotherp** [comment]
Post your debug infos.

**Comment by AtariBaby** [comment]
Sorry I downloaded them but forgot to attach 😅

**Comment by theotherp** [comment]
Hm, sorry, can't see anything unusual in there. Plase set the log level for the log file to debug and enable the logging marker "API hits". Let it run a day or two and the next time you encounter the error please post the new debug infos.

**Comment by AtariBaby** [comment]
I will thank you. And if I was supposed to do that already I apologize.

**Comment by theotherp** [comment]
No way for you know.

**Comment by AtariBaby** [comment]
Here we go. Has occurred about once per day 
[nzbhydra-debuginfos-2021-01-15-16-19.zip](https://github.com/theotherp/nzbhydra2/files/5823521/nzbhydra-debuginfos-2021-01-15-16-19.zip)

**Comment by theotherp** [comment]
You made no changes to the config. The log file level is still INFO and no markers are enabled. Set the file log level to debug, enable the logging marker "API hits". Restart hydra to be sure.

I'll try to make sense of the logs, it's really big even without debug level...

**Comment by AtariBaby** [comment]
Hopefully i did it right this time! I also see an update that addresses an issue with api limits...
[nzbhydra-debuginfos-2021-01-16-10-57.zip](https://github.com/theotherp/nzbhydra2/files/5824933/nzbhydra-debuginfos-2021-01-16-10-57.zip)

**Comment by theotherp** [comment]
Still no logging marker...

**Comment by AtariBaby** [comment]
Oh I’m sorry! I missed the part about “api hits”. I’ll do it again. Unless the update fixed something, I should have results within 24 hours.

**Comment by AtariBaby** [comment]
🙏
[nzbhydra-debuginfos-2021-01-17-13-25.zip](https://github.com/theotherp/nzbhydra2/files/5826869/nzbhydra-debuginfos-2021-01-17-13-25.zip)

**Comment by AtariBaby** [comment]
From an end user perspective, much of the design of nzbhydra2 is revolutionary and has inspired other the design of other projects in the genre. But setting up and sending debug info was very unintuitive. In part because when you download these logs, it’s got “debug” everywhere even though it’s not, unless you find your way to settings/general and scroll down and change those settings. Not a complaint, just letting you know my experience just now.

**Comment by theotherp** [comment]
I can't really explain why that happens.

Hydra keeps a short term storage of all API hits made to an indexer. When it selects an indexer it gets the last x hits (where x is the limit). 
If the earliest of these hits is less than 24 hours old the indexer is not selected.
If the earliest of these hits is more than 24 hours old then the indexer is selected. This is what happens. It works once or twice and then DS suddenly says that the limit is reached even though the oldest of the 25 hits is older than 24 hours.

I've updated the logging some more. I'll also add some code that will allow me to post a link that will automatically set the logging config as needed.

I'll ask the DS admin if he has an idea when I have more time.

**Comment by AtariBaby** [comment]
Incredible. Thanks!

**Comment by AtariBaby** [comment]
You are one nimble dev. I saw your new update. I’ll let you know if any change.

**Comment by AtariBaby** [comment]
I still get the error. Just as an experiment I lowered the hydra settings from 25 hits to 24, still got the error, so I reduced it to 23, and I also lowered the priority in my indexer order, so maybe that will do it.

**Comment by theotherp** [comment]
Post new debug infos.

**Comment by AtariBaby** [comment]
I got this email from them today. Those warnings may actually be a nag to encourage the user to re-up their subscription: 

“ Hey,
Your account expired over a month ago at DrunkenSlug.  In another month's time you will drop down to the free role, and after that you won't get any more of these reminders.
Cheers,
AutoSlug”

**Comment by AtariBaby** [comment]
Sorry to reopen. I wanted to correct the record for you and anyone searching out my problem in the future. For some reason I had slug set up for rss in sabnzbd plus. I contacted slug support and they helped me figure it out.
![4E3954FC-33CA-4D23-A03D-9A6912C5D37A](https://user-images.githubusercontent.com/97095/106659846-1f329900-6554-11eb-8066-b747fe99efc5.jpeg)

**Comment by theotherp** [comment]
Aaargh. But thanks for letting me know 😉
