### ISSUE TITLE
Send Link missing from 3.8.1 for Downloaders? 

### ISSUE THREAD

**Issue by coolspot18** [theotherp/nzbhydra2#665]
Hello,

Running 3.8.1 in a LinuxsServer Docker Container, and I noticed the Downloader -> SABNZBd -> Send Link option is no longer on the page.

Was this feature removed? 

Thanks.

**Comment by theotherp** [comment]
It's an "advanced" feature an due to a bug it's not being displayed even with advanced features enabled. I'll try to get it fixed on the weekend.
