### ISSUE TITLE
Loaded 1 (1 filtered, 0 duplicates) of 1 results (rejected 0) Nothing shown

### ISSUE THREAD

**Issue by zorin1** [theotherp/nzbhydra2#666]
Version 3.8.1
Search all for:
Star.Trek.Discovery.S03E13.iNTERNAL.1080p.WEB.h264-KOGi

Result list is empty but you see this above where the list would be: Loaded 1 (1 filtered, 0 duplicates) of 1 results (rejected 0)

**Comment by theotherp** [comment]
So? What am I supposed to do with this? You didn't follow the template, you didn't post the debug infos, you didn't ask a question.

The message says that 1 result was found but it was filtered. You can check the log to see the reason why it was filtered out. #663 is about showing the reason in the GUI.
