### ISSUE TITLE
AnimeTosho indexer not returning all results

### ISSUE THREAD

**Issue by ShawnHardwick** [theotherp/nzbhydra2#667]
When executing a search using the AnimeTosho indexer, the amount of results returned is not complete.

For example, when searching for "Attack on Titan" only 83 results are returned. 
![image](https://user-images.githubusercontent.com/5496527/104034963-8fd9d600-519f-11eb-8daf-01abfb9b24f8.png)
![image](https://user-images.githubusercontent.com/5496527/104034944-89e3f500-519f-11eb-8120-2b2782e3b947.png)

When querying the AnimeTosho API (and searching from their web interface), there are 720 results.
`https://feed.animetosho.org/api?t=search&extended=1&q=Attack%20on%20titan&password=1&limit=100&offset=700`

The log shows that only the below API query is sent:
`Animetosho (Newznab): Calling https://feed.animetosho.org/api?t=search&extended=1&q=Attack%20on%20Titan%20S&password=1&limit=100&offset=0`

Followed by a number of similar entries to the below:
`Animetosho (Newznab): Unable to find URL for result Attack On Titan S 1-3 [10Bit][1080p][BD][5.1][ENG DUB]. Will skip it.`

Whether by design, the application appears to not be paging the results and there is a small subset of results being skipped.

Running version 3.8.1 in Docker
[nzbhydra-debuginfos-2021-01-08-10-40.zip](https://github.com/theotherp/nzbhydra2/files/5788072/nzbhydra-debuginfos-2021-01-08-10-40.zip)

**Comment by theotherp** [comment]
Their API response doesn't provide a "total" value so hydra can't page the results properly. Ask the dev/admin to implement the `total` value as described here: https://newznab.readthedocs.io/en/latest/misc/api/#search

**Comment by ShawnHardwick** [comment]
I agree with you that they should implement the total attribute. Do you see
value in checking the other pages/offsets if the current response returns
the limit amount?

**Comment by theotherp** [comment]
I'd rather have them implement them it properly. If they refuse let me know and I'll work around it.

**Comment by ShawnHardwick** [comment]
I reached out to the AnimeTosho administrator and was able to get them to implement the `total` newznab attribute.

```
<newznab:response offset="0" total="748"/>
```

You can find the conversation here:
https://animetosho.org/feedback#comment16387

**Comment by theotherp** [comment]
Great! Can you confirm that this solves your search problems (and gets rid of the warning message)?

**Comment by ShawnHardwick** [comment]
Looks like the indexer returns back the correct number of results now.
![image](https://user-images.githubusercontent.com/5496527/105206946-ee467300-5b14-11eb-9e2d-7ae7aea27366.png)

I do still the warning about skipping entries, but that may be a separate issue.
`Animetosho (Newznab): Unable to find URL for result [WhiteE] Attack on Titan – SEASON 1 (01-24) – [CrunchyRoll 1080p WEB-DL AAC]. Will skip it.`

**Comment by theotherp** [comment]
That message should not be shown as a warning. I've fixed that.
