### ISSUE TITLE
NZBGet - Add NZBs paused

### ISSUE THREAD

**Issue by DunklerPhoenix** [theotherp/nzbhydra2#669]
Heho.
It would be nice if we can say that the nzb get added paused to nzbget.
Sonarr, Radarr and Lidarr have this feature and I'm using it to collect downloads, if my drive is full.

Greetings

**Comment by theotherp** [comment]
On-demand or as a configuration parameter?

**Comment by DunklerPhoenix** [comment]
I would be nice as config parameter like in radarr, sonarr anf lidarr.

**Comment by DunklerPhoenix** [comment]
Thanks
