### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by LennyM8472** [theotherp/nzbhydra2#67]
Hi,

any way to support same SSL configuration as in NZBHydra 1.
Very annoying to convert Letsencrypt certificates to new format.
Maybe integrate automatic conversion of old SSL config into NZBHydra 2.

best regards
Lenny

**Comment by theotherp** [comment]
No.

**Comment by theotherp** [comment]
It's not that I wouldn't like to make it easier but the framework doesn't support it and automatic renewal of Let's encrpt certificates is everything but trivial. Run a reverse proxy, it's not that hard and more secure.
