### ISSUE TITLE
Crowdsource combined indexer scores for the community

### ISSUE THREAD

**Issue by DeftNerd** [theotherp/nzbhydra2#671]
As you work on some of the other issues regarding indexer scores (such as breaking them out by category), it might be useful to the community to add a feature where NZBHydra2 instances could (optionally) report indexer scores weekly to a hosted API. This could be used to generate useful statistics on what indexers people should get accounts on.

Another useful bit of aggregate data would be keeping track of index errors to make a note of indexers that have high failure rates. Possibly also average response times too.

**Comment by theotherp** [comment]
I want to make clear that you shouldn't put too much weight on these scores. They depend (among other things) on your indexer priorities. And failures depend on your providers.

I like the theory in general but am not convinced that the results would be meaningful.

**Comment by theotherp** [comment]
Closing this because I don't want to overstate the importance of these stats. Thanks for the suggestion though.
