### ISSUE TITLE
Ability to not display the 'What's New' banner after updates

### ISSUE THREAD

**Issue by sammcj** [theotherp/nzbhydra2#672]
* What do you want to happen?

At present, after every update there is a banner shown with a 'What's New' button.

It would be great if this could be disabled as there are frequent (great!) updates but I don't really need a banner on the page for every one - perhaps only things requiring user input / actions?

Note: I did expected having 'Show News' disabled to prevent this - but it doesn't seem to.

![screenshot 2021-01-19 at 3 17 21 pm](https://user-images.githubusercontent.com/862951/104987444-dd8cf300-5a69-11eb-9e2c-25498bb25b1d.jpg)

**Comment by theotherp** [comment]
To be honest I was tempted not to do this but it's your loss ;-)

**Comment by sammcj** [comment]
Thank you! Appreciate that great software!
