### ISSUE TITLE
Indexer section colorpicker doesn't accept direct input via field

### ISSUE THREAD

**Issue by jca2112** [theotherp/nzbhydra2#674]
**The colorpicker UI in the Indexers config section for "Color:" used to mark the indexer's results with a color doesn't seem to work as expected.**

The field will not accept inputting colors directly (Example: _rgba(106,7,7,0.5)_) -- it will only accept the color selection via the javascript eyedropper function. The field will not save any rgba color code, HEX color code, etc. This is a problem if you wanted several Indexers to use the same color, since it isn't possible to get the exact same rgba color code via the eyedropper UI each time.

Is the _bootstrap-colorpicker-module.js_ used for the colorpicker based on [angular-bootstrap-colorpicker](https://github.com/buberdds/angular-bootstrap-colorpicker)? That script's github Issues page seems to describe similar issues and appears that the code hasn't been updated in 2017.

Can anyone else reproduce this issue?

**Comment by theotherp** [comment]
Yeah, that control is a pain in the ass to use. I managed to fix it It updates very slowly, but it works.
