### ISSUE TITLE
Calling /internalapi/downloader/getStatus every second wasteful

### ISSUE THREAD

**Issue by klische** [theotherp/nzbhydra2#675]
* What do you want to happen?
Checking internalapi/downloader/getStatus every second is a waste of resources. Even if running locally, these are still requests that have to be parsed. If running over network or accessing from a mobile device, this eats battery and bandwidth.
* If not clear, why do you want it?
Reduce energy and bandwidth usage by either letting users configure it, disable it, use a webhook or have an advanced setting to be per minute

**Comment by theotherp** [comment]
You can disable the footer in the settings.

**Comment by theotherp** [comment]
I wouldn't want to make the interval configurable but I'll try to make the payload smaller.

**Comment by klische** [comment]
> You can disable the footer in the settings.

If disabling the footer stops the network call, this is a great solution. Thanks!

**Comment by theotherp** [comment]
As of v3.10.0 NZBHydra will use WebSocket to transport the downloader status. A connection is kept open and data will only be transferred if the downloader status actually changes.
