### ISSUE TITLE
False Success when adding Sabnzbd

### ISSUE THREAD

**Issue by kihaji** [theotherp/nzbhydra2#678]
I ran into this while setting up NZBHydra2 and Sabnzbd, both using docker images from Linuxserver.io on Ubuntu with docker and docker compose.

Setting up Sabnzbd I set External internet access to "No Access" then listed my local ip ranges. I only initially put in the 192.168.1. range.

I then set up NZBHydra2, and added Sabnzbd as the downloader. The initial add passed, and in the logs you'll see that the connection check succeeded, but then shortly after in the logs there will be an exception throw stating empty response from Sabnzbd. 

It turned out that I needed to add in the internal docker ip range of 172.21.0. as well. Once that is added, it succeeds, and you are able to send directly from Hydra to Sabn.

I'm not sure if it's a fault on NZBHydra or Sabnzbd, but I would expect that if a capabilities check passes, then access should work, and the opposite. 

[log.txt](https://github.com/theotherp/nzbhydra2/files/5877153/log.txt)

**Comment by theotherp** [comment]
The connection is tested by making a `mode?get_cats` query to the URL. It will try to parse the response as JSON. I don't see how that could succeed without sabnzb actually being reachable.

**Comment by theotherp** [comment]
I've improved the connection check.
