### ISSUE TITLE
[FR] Validate backup dir

### ISSUE THREAD

**Issue by reloxx13** [theotherp/nzbhydra2#679]
I just realized that after some restructure (new ssd), nzbhydra2 stopped making backups.    
on accident i entered a completly wrong path to the backup dir config.   

it still aved the backup dir and unward just stopped to make backups and updates ( error while creating backup ).   

this was nowhere shown.    

i would like to suggest to validate or check the path and show a big error alert on the ui if backups fail or path is not writeable/existent.

**Comment by theotherp** [comment]
Good point.
