### ISSUE TITLE
Frequency of docker image updates

### ISSUE THREAD

**Issue by bablat** [theotherp/nzbhydra2#68]
Thanks for producing a solid, well refined piece of software - and sharing it with the rest of us.

What is your current policy of pushing updates to the docker image?
I've been testing Hydra2 for a few weeks, and while the software works flawlessly I'd love for the docker image updates to be in sync with the releases. Otherwise this tempts users to upgrade from inside the container which is nothing but bad news and more issue reports (that popup inviting your to upgrade is pretty tempting after a few days of dismissing it... perhaps Hydra should identify it runs inside a container and not offer the upgrades?)

Thanks again!

-bab

**Comment by theotherp** [comment]
I recommend using the containers by linuxserver.io or binhex. I don't know
how often they update and if it's automated. Because I thought most people
had switched or hadn't used my container I neglected updating it...

My first foray into docker wasn't really successful so I'd rather leave it
to others to keep it running and updated.

Am 17.01.2018 2:05 nachm. schrieb "bablat" <notifications@github.com>:

**Comment by theotherp** [comment]
I can already somewhat reliably recognize if it's running inside docker:
disabling the update or at least making it opt-in with a disclaimer is a
good idea, thanks.

Am 17.01.2018 2:39 nachm. schrieb "Simon Str" <stratmann.simon@gmail.com>:

**Comment by theotherp** [comment]
Just released a new one :-)

**Comment by fryfrog** [comment]
If you don't want to maintain a Dockerfile, I'd retire it and point at the two options. :)

**Comment by theotherp** [comment]
Already have...

Am 18.01.2018 19:57 schrieb "Donald Webster" <notifications@github.com>:

**Comment by theotherp** [comment]
I'm closing this. I'll try to remember to update the container whenever I release a new version but will expect users to eventually switch to other containers.

**Comment by bablat** [comment]
Personal, I prefer to use a docket container provided by the project owner, unless the alternative image is by a reputable individual/team.

If you should still consider providing the docket image yourself, building automatically upon code commits is very easy:

https://docs.docker.com/docker-hub/builds/

**Comment by theotherp** [comment]
Hmm... Good idea. Unfortunately it seems that I cannot convert the existing container to an automated build. I would need to create a new one.

**Comment by bablat** [comment]
btw, I think your first attempt was perfectly successful, I've been using your image with absolutely no issues for about 2-3 weeks. Moreover, containers are so cool and it's worth getting to know that technology well.

In any case, great work.

**Comment by theotherp** [comment]
Thanks, but it seems to be missing some requested features like running it with non-root or whatever. I'll think about it.

**Comment by theotherp** [comment]
The automated build unfortunately doesn't work with my setup. When I have time I'll experiment with my CI config to have it push new versions automatically.

**Comment by theotherp** [comment]
I fucked up my VM when reinstalling Windows. Might take a while for me to set it up.

**Comment by bablat** [comment]
Somehow Microsoft always ends up messing everything up...

**Comment by theotherp** [comment]
No this was my doing. I'm just too lazy to repair some grub shit right now.

Am 21.01.2018 19:22 schrieb "bablat" <notifications@github.com>:
