### ISSUE TITLE
BUG: API/RSS call to a category, is defaulting to All

### ISSUE THREAD

**Issue by psyciknz** [theotherp/nzbhydra2#680]
Trying to get an api/rss call to nzbhydra from sabnzbd.   Where i used to have the rss feed to a category directly in sab, I've moved this to an rss call on hydra.

If I put in:
```
https://localhost:7076/api?apikey=<key>&category=Ebook&t=book
```
I exepcted to look in nzbhydra search history and see it had performed a Ebook category search (as if I did it in the web ui).  But it set the category to All and I saw results reflecting this.

What I finally worked out, was then I could search for:
```
https://localhost:7076/api?apikey=<key>&cat=7010,8010&t=book
```
And that searches the nzbhydra category Ebook....but it relied on me matching the category numbers as defined in the category.  Is that the expected method it should be used?   I was hoping that in hydra I could define the category, and assign the index categoryies, and in my api call use the nice name, rather than the category numbers.

**Comment by theotherp** [comment]
NZBHydra follows the [newznab API spec](https://newznab.readthedocs.io/en/latest/misc/api/) which uses numbers for certain categories which can also be combined. All other programs and indexers follow this spec (to a degree).

I might consider allowing to also provide the category name but I'll have to think how this would affect the "regular" functionality.

**Comment by psyciknz** [comment]
So the way I’m calling it with the category numbers the intended way I should call it?

**Comment by theotherp** [comment]
Yep
