### ISSUE TITLE
No indexers were enabled for this search

### ISSUE THREAD

**Issue by nickhx** [theotherp/nzbhydra2#681]
Hi after upgrading to 3.11.0 from 3.9.1, I am suddenly receiving the following error message:

No indexers were selected for this search. You probably don't have any indexers configured which support the provided ID type or all of your indexers which do are currently disabled. You can enable query generation to work around this.

I have tried enabling query generation, but the error message persists.  Debug logs attached below.
[nzbhydra-debuginfos-2021-01-31-11-52.zip](https://github.com/theotherp/nzbhydra2/files/5899643/nzbhydra-debuginfos-2021-01-31-11-52.zip)

**Comment by tuningman9790** [comment]
I have exact issue. Before on 3.9.1 this is working perfectly!

**Comment by DanULE1** [comment]
Hi, I can confirm I too am experiencing the behaviour since upgrading to 3.11.0 from 3.9.1.

**Comment by reflex790** [comment]
Have the same issue after updating to 3.11.0.

**Comment by theotherp** [comment]
Oops. Fixed.
