### ISSUE TITLE
DNS PTR lookups

### ISSUE THREAD

**Issue by gdtms247** [theotherp/nzbhydra2#682]
nzbhydra2 
unraid docker
NIC: custom bridge w/ IP of 192.168.37.222
DNS: AdGuard (also unraid docker)

AddGuard reports nzbhydra performing the following query thousands of times a day:

```
25.38.168.192.in-addr.arpa
Type: PTR, Plain DNS
```

I've looked through the GUI/logs but don't see any reference to the IP being sent in the query. The network 192.168.38.0/24 is a client network only my laptops/mobile devices etc are in that space. Any ideas/places to look?

**Comment by theotherp** [comment]
No idea, sorry.

**Comment by gdtms247** [comment]
Figured it was worth a quick check. Gonna spin up a 2nd with no config see what it does.

**Comment by theotherp** [comment]
Did you find out what's going on?
