### ISSUE TITLE
Authorization - a dumb question

### ISSUE THREAD

**Issue by dma9** [theotherp/nzbhydra2#687]
Apologies in advance as this is likely a dumb question. I am relatively new to nzbhydra2 but have managed to install it successfully. I just wanted the ability to require authorization before accessing it. However, when I try to enable authorization, either through basic or the login form, I get an error message: "You haven't enabled any access restrictions. Auth will not take any effect." I guess what's perplexing me is that I don't want to set any access restrictions for the account I'm creating - just want all functionality to be accessible once I log in, but nzbhydra2 doesn't seem to permit that. Am I perhaps missing something? Any suggestions would be most appreciated.

**Comment by theotherp** [comment]
![image](https://user-images.githubusercontent.com/14368889/108882653-ec386e00-7604-11eb-8a7c-f18aa2ad680f.png)

"Restrictions" configures which sections / features of Hydra are not allowed to be used without login. In your case just leave them all enabled.

I'll add a sentence to the tooltip.
