### ISSUE TITLE
Stuck On Finished searching. Preparing results... when searching anything in the GUI

### ISSUE THREAD

**Issue by daniel-tp** [theotherp/nzbhydra2#690]
When searching for anything in the main GUI (such as "test") with all indexers selected, it gets results from all the indexers I have enabled, but then stops (with no loading bar at the top) and doesn't complete after "Finished searching. Preparing results..." It doesn't seem to matter how many results. Problem was intermittent before but constant now. Problem does not occur with only a few indexers selected for search.

Using Hotio/nzbhydra2 docker container

Console errors:

![X7plx2pt83](https://user-images.githubusercontent.com/231185/108719847-fb8dbd80-7517-11eb-9b6c-a29f0d130cfe.png)
[nzbhydra-debuginfos-2021-02-22-14-12.zip](https://github.com/theotherp/nzbhydra2/files/6022481/nzbhydra-debuginfos-2021-02-22-14-12.zip)

**Comment by theotherp** [comment]
I can't explain why this happens. According to my analysis this is only possible if a result's title is empty which should've been filtered out already. I don't have access to all the indexers you used in your search so without knowing which indexer returned this result it will be hard for me to reproduce this.

I'll add some debug logging which should hopefully identify the result causing the problem.

**Comment by daniel-tp** [comment]
Thanks for looking into it, I'm happy to supply the debug info again when the extra logging is in.

**Comment by theotherp** [comment]
You could try the search for each indexer separately and see which one causes the problem.

**Comment by daniel-tp** [comment]
I tried that and the culprit seems to be Binsearch.

I have attached the debug info after doing a search with binsearch. Binsearch was added with just the preset given.
[nzbhydra-debuginfos-2021-02-23-19-30.zip](https://github.com/theotherp/nzbhydra2/files/6031404/nzbhydra-debuginfos-2021-02-23-19-30.zip)

As I really don't care about Binsearch, I'm going to delete it from my indexers.

**Comment by theotherp** [comment]
Got it.
