### ISSUE TITLE
Torrent & magnet links

### ISSUE THREAD

**Issue by entryb** [theotherp/nzbhydra2#691]
An option to "show link" for torrents that would just give you the magnet link or url of torrent would be nice to have instead of having to browse or download to the torrent site and finding the link, for people that dont use download programs

**Comment by theotherp** [comment]
That's what this button does: 
![image](https://user-images.githubusercontent.com/14368889/109430134-fb9e2980-79ff-11eb-8b1f-c29bff4f92d1.png)

**Comment by entryb** [comment]
That redirects to http://ip:port/gettorrent/user/12396718234 which doesnt show anything. Any requirement for that to work i should be aware of ?

**Comment by entryb** [comment]
It did for one out of some 5 trackers manage to provide me a torrent file if i saved the torrent to a folder, a magnet link was provided inside that file, wouldn't that be possible to show without having to download it to a folder and then open it ?

**Comment by theotherp** [comment]
Magnet links are a pain in the ass to handle. 
The hydra link fowards to the proper link. Your client may not support it but that's not up to me.

**Comment by entryb** [comment]
I closed it for that reason, it was the indexer that was not working correctly it wasn't that obvious so i thought it was nzbhydra first

**Comment by theotherp** [comment]
A comment explaining that would've been nice 😉
