### ISSUE TITLE
Slow Startup on Windows 10 Pro x64

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#692]
As reported by Glary Utilities Startup Manager/Monitor. Not sure if anything can be done to reduce the startup time of NZBhydra as it is markedly longer than any other startup app on my system.
Both Windows 10 and NZBhydra are up-to-date.
Thanks for looking. Del
![2021-03-07_18-23-54](https://user-images.githubusercontent.com/18551763/110250436-37db0800-7f73-11eb-9bc6-d5fbddc9678e.jpg)

**Comment by theotherp** [comment]
Nope, it just takes that long. It's not like it's a text editor that needs
to be snappy.

**Comment by DerekWilliamsUK** [comment]
OK. No problem, thanks for the feedback.
As for NZBhydra, everything continues to work great for me.
I much appreciate your time & effort developing this great/powerful application.
