### ISSUE TITLE
BUG: Failed to add NZBGeek, returned no results.

### ISSUE THREAD

**Issue by kihaji** [theotherp/nzbhydra2#695]
* What do you expect to happen? What does happen? 
NZBGeek does not successfully add and wont enable. I had to use the "I know what I am doing" option to add it, then check capabilities, but even though it gets capabilities it does not enable.

I'm rebuilding this server, and these credentials worked a few days ago in the old setup, with the same docker container. I tried it with SSL verify off as well, same problem.

* If you use a docker container please tell me which one.
Using Linuxserver.io docker

[nzbhydra-debuginfos-2021-03-14-13-45.zip](https://github.com/theotherp/nzbhydra2/files/6137237/nzbhydra-debuginfos-2021-03-14-13-45.zip)

**Comment by theotherp** [comment]
Please call https://nzbgeek.info/api?t=search&apikey=<yourapikey> in your browser and see if it returns any results. If not post the result.

**Comment by theotherp** [comment]
Or do the following:
Call NZBHydra using in your browser using `http://127.0.0.1:5076/internalapi/debuginfos/setLoggingConfig?markersToEnable=HTTP` (or whatever the correct host and IP are).
Restart hydra, recheck the nzbgeek caps, create new debug infos and send them to me via PM on discord. Full disclaimer: This will contain the nzbgeek API key. You may change it afterwards or just trust me not to use it.

**Comment by kihaji** [comment]
When calling  https://nzbgeek.info/api?t=search&apikey= it takes me to the dashboard page, both with, and without 2FA on. But if I do https://api.nzbgeek.info/api?t=search&apikey=  I get [result.txt](https://github.com/theotherp/nzbhydra2/files/6166248/result.txt)

And here is the new debuginfo you asked for. I set debug/http restarted, then re-added nzbgeek, and it went red and incomplete like before. Used the check capabilities on incomplete indexers on the indexer list, and nothing happened, then went into NZBgeek entry and hit the check capabilities and it came back, and now is enabled. 

[nzbhydra-debuginfos-2021-03-18-14-02.zip](https://github.com/theotherp/nzbhydra2/files/6166355/nzbhydra-debuginfos-2021-03-18-14-02.zip)

**Comment by theotherp** [comment]
Hm, that looks weird. Perhaps they don't support an empty search? Try https://api.nzbgeek.info/api?t=search&apikey=<apikey>&q=mp3

**Comment by theotherp** [comment]
I tried getting a VIP account for nzbgeek but seeing as the bitcoin transfer fee would be nearly as high as the membership fee I didn't.
