### ISSUE TITLE
If indexerSearchResult.getTotalResults() is more than 0, make it bold and green for better visibility and contrast.

### ISSUE THREAD

**Issue by EmreYYZ** [theotherp/nzbhydra2#696]
See the screenshot. After a certain amount of active indexers, it can be difficult to read if there is a search result or not during the actual search process. (A user might decide to cancel before the search is finished after seeing the better Indexers return with no result.) Especially when searching for a rarer item.

<img width="1422" alt="NZBHydra2-Enhancement" src="https://user-images.githubusercontent.com/6238977/111541621-18986380-8747-11eb-8857-e4441b873378.png">

It is difficult to notice the one indexer that has a result:
```
Indexer Hahah completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer HahahL completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer Hah completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer Hahah completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer HahaLol completed search successfully with 0 total results
Indexer Hahah completed search successfully with 0 total results
Indexer Hahaol completed search successfully with 1 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer HahahL completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
Indexer HahahLol completed search successfully with 0 total results
```

The numbers are aligned differently due to Indexers' name lengths, which is another factor that causes difficulties to read. However, that shouldn't be a problem as long as the numbers bigger than 0 have a bold green styling.

`core/src/main/java/org/nzbhydra/indexers/Indexer.java` includes the lines I am referencing. Lines 134 and 136 that include `indexerSearchResult.getTotalResults()`

So my suggested enhancement is that _if getTotalResults() is more than 0, it should be in a different color than the generic text._ 

Example CSS:
```
.searchResultNo {
color: green,
font-weight: bold,
}
```

**Comment by theotherp** [comment]
Yeah, why not. I mean, you can see the one indexer in the indexer results later but it wouldn't be much work to do this.

**Comment by EmreYYZ** [comment]
> Yeah, why not. I mean, you can see the one indexer in the indexer results later but it wouldn't be much work to do this.

Yes, this may not be a widespread need. But for some of my searches I cancel the search halfway if I see that certain indexers don't have it, because if they don't, there's a 0 chance the others will. (pre-selecting indexers is often time-consuming, and indexers sometimes don't abide by the categories, so selecting "all" yields better results for certain types of content.) So this change would bring convenience in these situations.

Thanks again, awesome project and I appreciate it!
