### ISSUE TITLE
Nzbhydra2 is incompatible with AdoptOpenJDK jre16 hotspot  16.0.0.36 

### ISSUE THREAD

**Issue by smcclosr** [theotherp/nzbhydra2#697]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen?  I expect Nzbhdra2 to to run, 
* What does happen? it does not run, errors out with Java error
* Have you searched for this problem? Searched for problem, did not see any answer
* Can the problem be reproduced? 

-Install Adopt Open java via chocolatey command: choco install adoptopenjdkjre. (https://www.chocolatey.org/packages/adoptopenjdkjre)  
-Java installs, but when running Nzbhydra2, Java errors out.  
-Need to roll back to previous version of Java.  Install previous version with this chocolatey command, and does work: choco install adoptopenjdkjre --version 15.0.2.7
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/6173444/nzbhydra2.log)

* If you use a docker container please tell me which one. No docker
* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/6173446/nzbhydra2.log)

**Comment by theotherp** [comment]
Due to a core library not being compatible with Java 16 I can't support it for now. I can't imagine there's a reason to run Java 16 at the moment so it's low priority for me anyway.

**Comment by smcclosr** [comment]
Thanks for getting back to me, and updating the documentation, will work with a version that is supported.  I have no issue using either Version 15 or LTS 11 because they are both being updated on a regular basis.
