### ISSUE TITLE
Limit search Interval

### ISSUE THREAD

**Issue by SSoft7** [theotherp/nzbhydra2#702]
* What do you want to happen?
I can't seem to find a way to limit the search interval. At this moment I am using hydra in docker which is executing search in every minute.
`INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.api.ExternalApi             : [ID: 07860, Host: 172.17.0.42] Search took 2848ms. Returning 18 results`
This search is taking 100% CPU usage when running.
So, any way to limit the search interval?

**Comment by theotherp** [comment]
You quote access from an external tool. How would hydra limit that? Hydra itself doesn't make any searches by itself.
The limiting needs to be done by the tool that's making the request.
