### ISSUE TITLE
Add max size as API filter

### ISSUE THREAD

**Issue by dantebarba** [theotherp/nzbhydra2#705]
* What do you want to happen?

Set an option for each indexer to filter out files that are less than or greater than a specified size. (same as seeders but for size)

* If not clear, why do you want it?

In my case for example: I have a VPS that only has 60 GB of storage. With NZB I can only download 30GB files because it has to unpack, but with torrent I can download files greater than 30GB because no unpacking is needed.

* Do you think it's something only you need or something that might be popular?

I think it's a cool option and it isn't hard to implement.

* If not clear, explain the use case.

Explained above.

**Comment by theotherp** [comment]
That's already supported: https://github.com/theotherp/nzbhydra2/blob/master/shared/mapping/src/main/java/org/nzbhydra/mapping/newznab/NewznabParameters.java

Use `minsize`, `maxsize`, `minage`, `maxage`, etc.

**Comment by dantebarba** [comment]
@theotherp I'm adding maxsize like this in radarr but it's not working when using interactive search:

![image](https://user-images.githubusercontent.com/6656541/119242923-817dcc80-bb38-11eb-9328-f3343ffcbe4c.png)

**Comment by theotherp** [comment]
You're right, sorry about that. Fixed in 3.14.2
