### ISSUE TITLE
Feature Request: Add alphabetical sort to title in search results

### ISSUE THREAD

**Issue by DarrenPIngram** [theotherp/nzbhydra2#706]
For a search made it would be desirable to have the ability to sort the TITLE (left-field in results) by alphabetical order, both ascending and descending. It would complete the other sort options that appear in the header row.

Believe it would be universally useful. Even with the setting to "group" search results, not all results are necessarily grouped together due to minor name changing differences (e.g. uploaders, capture formats etc) and by allowing a sort it will enable one to quickly view results and "de-dupe"/identify what one needs, especially with popular references being returned.

**Comment by albino1** [comment]
Maybe I'm misunderstanding, but if you just click the word `Title` it sorts both alphabetically and in reverse:

![nzbh](https://user-images.githubusercontent.com/12164957/116850211-15e1b880-aba5-11eb-8a95-03ffebcac0c1.jpg)

**Comment by DarrenPIngram** [comment]
You are right. For some reason in my browser it was not showing a twisty
nor has it been doing so for some time. The search bar sits over the twisty
symbol for some reason (Chrome/MacOS). Once I clicked on the word itself
and made a new search it seemed to clean up its act and show a twisty.

(red face).

I wonder what corrupted the display over a long period of time. The "issue"
had been frustrating for some time and I hadn't got around to making the
request.

Thanks!
‌

**Comment by albino1** [comment]
Sounds like another bug that might be worth a new issue ;)

**Comment by DarrenPIngram** [comment]
> Sounds like another bug that might be worth a new issue ;)

OK I could replicate it in Safari (I hadn't visited NZBHydra in that) so I will file a report under a new issue per your advice.

Thanks!
