### ISSUE TITLE
Remove dereferer in browsers that support Referrer-Policy

### ISSUE THREAD

**Issue by Daniel15** [theotherp/nzbhydra2#712]
* What do you want to happen?
In modern browsers, you can send a `Referrer-Policy: no-referrer` header and it'll block the referrer for all outbound links. This avoids the need to redirect through `dereferer.org`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy which has details on the possible values for the header, and browser support. You could do browser detection and use `Referrer-Policy` for newer browsers, falling back to `dereferer` for older browsers.

* If not clear, why do you want it?
Speeds up connecting to other sites (don't have to wait a few seconds for dereferer to redirect)

* Do you think it's something only you need or something that might be popular?
People like stuff being faster 😄

**Comment by theotherp** [comment]
Sounds like a good idea but I have no idea how to set that header when just
providing a link for you to click.

**Comment by Daniel15** [comment]
> I have no idea how to set that header when just providing a link for you to click.

@theotherp The header applies to all links on the page. You'd just have to set it when serving NZBHydra pages. There's a few options:
 - NZBHydra's web server could set the header when rendering the page, and then every link on the page will have its referrer removed.
 - If it's hard for you to add extra headers with whatever framework you're using, you could instead use a meta tag: `<meta name="referrer" content="no-referrer">` and it'd apply to every link on the page, similar to setting a header
 - Alternatively, if you only want it to apply to particular links, you can add a `referrerpolicy="no-referrer"` or `rel="noreferrer"` to links (eg. `<a href="https://example.com/" referrerpolicy="no-referrer">Example</a>`)

**Comment by theotherp** [comment]
The HTML page already has a `<meta name="referrer" content="no-referrer">` tag and it's already applied: 
![image](https://user-images.githubusercontent.com/14368889/122201181-11930580-ce9c-11eb-8c3f-b094d7220a63.png)

So it looks I already implemented this and just forgot about it.
