### ISSUE TITLE
API caps doesn't include Magazines category

### ISSUE THREAD

**Issue by Daniel15** [theotherp/nzbhydra2#714]
Hitting /api?t=caps doesn't include the Magazines category (7010) even though the indexers I've added support magazines. Is there a way I can add it? I couldn't find anything in the settings. 

It does have ebooks and comics, but not magazines:

```
<category id="7020" name="Ebook"/>
<category id="7030" name="Comic"/>
``` 

This breaks NZBHydra in Lazylibrarian (for magazines) as it thinks NZBHydra does not support searching for magazines. 

I searched but couldn't find anything relevant. 

I'm using the Linuxserver.io Docker container.

**Comment by Daniel15** [comment]
I tried manually adding the magazines category, and it works in NZBHydra, but Lazylibrarian still doesn't like it for whatever reason.

**Comment by theotherp** [comment]
You'll have to ask the LL developer for the reason. As you said with an added magazine category the caps produces the expected output:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<caps>
    <server title="NZBHydra 2" email="theotherp@posteo.net" url="https://github.com/theotherp/nzbhydra2" image="https://raw.githubusercontent.com/theotherp/nzbhydra2/master/core/ui-src/img/banner-bright.png"/>
    <limits max="100" default="100"/>
    <retention days="3000"/>
    <searching>
        <search available="yes" supportedParams="q,cat,limit,offset,minage,maxage,minsize,maxsize"/>
        <tv-search available="yes" supportedParams="q,season,ep,cat,limit,offset,minage,maxage,minsize,maxsize,rid,tvdbid,tvmazeid,imdbid"/>
        <movie-search available="yes" supportedParams="q,cat,limit,offset,minage,maxage,minsize,maxsize,imdbid,tmdbid"/>
        <audio-search available="no" supportedParams=""/>
        <book-search available="yes" supportedParams="q,author,title,cat,limit,offset,minage,maxage,minsize,maxsize"/>
    </searching>
    <categories>
        <category id="7010" name="Magazines"/>
    </categories>
</caps>
```
