### ISSUE TITLE
Unable to connect to sabnzbd - Hydra2 is not at fault but could help in diagnosing

### ISSUE THREAD

**Issue by opentoe** [theotherp/nzbhydra2#718]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section]([nzbhydra-debuginfos-2021-07-18-19-22.zip](https://github.com/theotherp/nzbhydra2/files/6837101/nzbhydra-debuginfos-2021-07-18-19-22.zip)). If other tools are involved post their logs as well.**

Ok, this is an odd one. First, want to say I love this program. I've donated twice and think it fills a great void in the indexer search system we have. I have sabnzbd as my own downloader, since that is all I use. I also use Sonarr for all my TV shows. 

The main settings that are configured for sabnzbd that Hydra connects to are:
Name: SABnzbd
URL: http://blackred:8080  ( my computer name is blackred )
API key: API key from sabnzbd
Default Category: empty
NZB adding type: Ask when downloading
NZB adding type: Upload NZB
Add Pause: OFF
Icon CSS Class: Default

Ok, when I do a simple search for anything, example would be an old movie called THE MATRIX. Can be anything. I will eventually get lots of results. I do use filtering. I'll filter out so I only get back a couple weeks worth and also filter out the minimal size. I'll get back a nice list of what I was searching for. On the right hand side there is a small sabnzbd icon I can click which would usually bring up all my set categories I have configured in sabnzbd. I would love that function since the finished downloaded file would sitting in an exact patch I can expect. These days when I click on that little icon sabnabd takes its time to respond and pops up the error I attached.  This process use to work perfectly all the time. Now I temporarily have to use a "watchfolder" that is lined up with those same categories.

MIND you, I have been seeing weird errors with sabnzbd on their latest version 3.3.1. Within my own LAN I would be able to access the sabnzbd UI no problems. Something was done sonewhere or changed that now prohibits me from accessing sabnzbd  via my own LAN. Been at the sadnzbd forums, no one really has any idea...but since the last sabnzbd update all I've had are small issues. Hydra is running as a docker on my unraid box for months with no problems. Sab, Sonarr and every thing else is running on my main powerful desktop. Has anyone seen anything like this? Could anyone point me in the right direction to fixing this mess? I really would appreciate anyone's suggestions or comments. I will try anything 

Well, thanks for reading and I hope I spark something in someone that could lead me like a horse so I can get this issue resolved. I take care of my stuff and keep my programs in order and make sure they are all up to date and running properly, this one really has been baffled. Thank you very much!
[nzbhydra-debuginfos-2021-07-18-19-22.zip](https://github.com/theotherp/nzbhydra2/files/6837128/nzbhydra-debuginfos-2021-07-18-19-22.zip)

![hydra error](https://user-images.githubusercontent.com/3084652/126085912-f0e2b785-f157-4a40-a5ee-81821bf2287a.png)

**Comment by theotherp** [comment]
So if I understand you correctly your issue is that you're not able to connect from hydra (running as docker on a box) to sab (running on your desktop machine).

Can you access sabnzbd from your unraid box using the shell (or browser or whatever)? Can you access any or the other programs running on your desktop? Have you tried using the IP instead of the host?

**Comment by opentoe** [comment]
I turned on DEBUG and here are the results attached.
[nzbhydra-debuginfos-2021-07-19-06-20.zip](https://github.com/theotherp/nzbhydra2/files/6840036/nzbhydra-debuginfos-2021-07-19-06-20.zip)

**Comment by opentoe** [comment]
> So if I understand you correctly your issue is that you're not able to connect from hydra (running as docker on a box) to sab (running on your desktop machine).
> 
> Can you access sabnzbd from your unraid box using the shell (or browser or whatever)? Can you access any or the other programs running on your desktop? Have you tried using the IP instead of the host?

Yes, I can access sabnzbd from my unraid box. I installed Firefox for some testing. And I can access the sabnzbd shell just the same too. I have no problem going back and forth from unraid to any of my networked workstations and each workstation can easily connect to my unraid box. 
UPDATE: I'm almost embarrassed to post this but I believe I have JUST found the problem. IDIOT me wanted to try Windows 11, so instead of using my beautiful built-in VM capability on my unraid server I downloaded Oracle VirtualBox like a dummy. Need I say more? My power computer that runs all my programs and services has a DHCP reservation, so it will always pick up the same IP address on my network.  After you stab me in the eye with a pencil Virtual Box was changing that IP address with some sort of process that was running in memory, so it was picking up a completely different IP. I just tried Hydra, clicked on the sabnzbd icon and all my nice categories showed up like normal. Ok, you can now stick me in my other eye with a blow poke from a fireplace. Sometimes I can miss such the small things and it drives me nuts. As I shake my head back and forth I'm still trying to find a reason why in the world I would ever even use VirtualBox when unraid has all the VM capabilities built right in. 
Well, I want to thank all of you who tried to help me and were going to help me. I really do appreciate all the work that's put into this program and how good it runs, even in a docker. Ok, you can now shoot me. If I wasn't so tired I believe I would be beating myself up.

**Comment by theotherp** [comment]
Hey, it's all good. We've all been there and I'm glad you got it sorted out
😊
