### ISSUE TITLE
Periodically gets in a state where it hits my hard drive repeatedly until i stop the process.

### ISSUE THREAD

**Issue by woodpost** [theotherp/nzbhydra2#719]
i sit next to my Synology NAS, and every few days i'll hear it just chewing away at my drives.  i've had it go like this for over 24 hours, and i assume it'll continue indefinitely.  the culprit is always nzbhydra2.  as soon as i stop the process (i run it in a Docker container), the churning stops.  i restart nzbhydra2, it runs fine for a while, but inevitably after 1-4 days, it gets in the state again.  it's been doing this for months.

i've attached 2 screenshots of the last entries in the log before i kill the process.

i'm using the linuxserver/nzbhydra2:latest image.

![hydra2](https://user-images.githubusercontent.com/28311630/126229443-97d508e1-c4c6-4631-8516-1f899756b8bb.jpg)
![hydra](https://user-images.githubusercontent.com/28311630/126229446-cd524b62-68da-4044-a40d-b820bb68b77d.jpg)

**Comment by woodpost** [comment]
![hydra3](https://user-images.githubusercontent.com/28311630/126889681-bd0cdec8-853e-4876-a6e9-1cd7d2719824.jpg)

**Comment by theotherp** [comment]
Sorry, I kinda missed this one.
In the main config enable the display of advanced options. Set the "Database retention time" to 20000. Restart hydra and see if that helps. If not please post your debug infos (see the system section).

**Comment by woodpost** [comment]
i made the change 5 days ago and it hasn't gotten into that state since.  looks good, thanks!  can you explain what was happening?

**Comment by theotherp** [comment]
That value determines how long data is kept in memory before it's written to the hard drive. Short periods are usually not an issue and make the database more resilient but in some cases (like yours) it can result in data being written all the time.
