### ISSUE TITLE
Expose child categories as subcat instead of category and set description=parent category

### ISSUE THREAD

**Issue by alron** [theotherp/nzbhydra2#72]
Currently nzbhydra2 exposes all categories as primary category entries, and does not associate them with the search type. This causes problems with things like the Anime (or Documentary, if you're into that type of thing) category showing up in pyMedusa (and potentially all of the other Sick forks). Currently to get the extra cats to show up in pyMedusa (and probably the other sicks), you need to set the name of the category in hydra2 to have the word TV somewhere in the name like "Anime (TV)", or "Documentary (TV)", etc.

Excerpt from capabilities query against current hydra2 install. Only showing TV related stuff:

```
<categories>
  <category id="5070" name="Anime"/>
  <category id="5000" name="TV"/>
  <category id="5040" name="TV HD"/>
  <category id="5030" name="TV SD"/>
</categories>
```

Excerpt from a nzbgeek caps query (tv sections only):
```
<categories>
  <category id="5000" name="TV">
    <subcat id="5020" name="Foreign" description="TV"/>
    <subcat id="5030" name="SD" description="TV"/>
    <subcat id="5040" name="HD" description="TV"/>
    <subcat id="5045" name="UHD" description="TV"/>
    <subcat id="5050" name="Other" description="TV"/>
    <subcat id="5060" name="Sport" description="TV"/>
    <subcat id="5070" name="Anime" description="TV"/>
    <subcat id="5080" name="Documentary" description="TV"/>
  </category>
</categories>
```

It may work properly with just a description=search type from categories page, without the hierarchical setup with subcats. But I've not done any tests in that direction to verify, so pure postulation on my part.

API docs for newznab:
http://newznab.readthedocs.io/en/latest/misc/api/

Caps queried using ```curl http://IP:PORT/nzbhydra/api?t=caps\&apikey=<APIKEY>```

**Comment by theotherp** [comment]
I could add the description property. 

Using subcategories would probably require a major rewrite of the category handling which I honestly don't want to do. Before releasing Hydra I tested it with CP, Sonarr/Radarr, Watcher, NZB 360, Mylarr and LL. I've never even heard about pyMedusa. All the tools I tested Hydra with didn't have a problem with the caps site. I also didn't understand the newznab spec to actually require subcategories to be listed. 90% of indexers don't follow it one way or the other anyway.

I'll see what I can do.

**Comment by alron** [comment]
pyMedusa is one of the primary active forks of the whole Sick* thing and can be found at https://github.com/pymedusa/Medusa 

I'm not sure if subcats required or not. I just saw them in use in the indexers I use, and in the API documentation. I just know that if I'm seeing this on a fresh install, other people will too. :)

Hopefully the description change will be enough to make things work. If not, I've no problem manually setting the keywords that Medusa (and sick*) look for in the category name. 

Cheers.

**Comment by alron** [comment]
Nzb Cat: 
```
   <category id="5000" name="TV">
    <subcat id="5070" name="Anime"/>
    <subcat id="5080" name="Documentary"/>
    <subcat id="5020" name="Foreign"/>
    <subcat id="5040" name="HD"/>
    <subcat id="5999" name="Other"/>
    <subcat id="5030" name="SD"/>
    <subcat id="5060" name="Sport"/>
    <subcat id="5045" name="UHD"/>
    <subcat id="5010" name="WEB-DL"/>
   </category>
```

Nzbfinder:
```
   <category id="5000" name="TV">
    <subcat id="5070" name="Anime"/>
    <subcat id="5080" name="Documentary"/>
    <subcat id="5020" name="Foreign"/>
    <subcat id="5040" name="HD"/>
    <subcat id="5999" name="Other"/>
    <subcat id="5030" name="SD"/>
    <subcat id="5060" name="Sport"/>
    <subcat id="5045" name="UHD"/>
   </category>
```

Simplynzbs:
```
   <category id="5000" name="TV"> 
     <subcat id="5070" name="Anime"/>
     <subcat id="5080" name="Documentary"/>
     <subcat id="5020" name="Foreign"/>   
     <subcat id="5040" name="HD"/>
     <subcat id="5999" name="Other"/>
     <subcat id="5030" name="SD"/>
     <subcat id="5060" name="Sport"/>
     <subcat id="5045" name="UHD"/>
     <subcat id="5010" name="WEB-DL"/>
   </category>
```

Nzb su:
```
<category id="5000" name="TV">
  <subcat id="5070" name="Anime"/>
  <subcat id="5080" name="Doc"/>
  <subcat id="5020" name="Foreign"/>
  <subcat id="5040" name="HD"/>
  <subcat id="5050" name="Other "/>
  <subcat id="5030" name="SD"/>
  <subcat id="5060" name="Sport"/>
  <subcat id="5045" name="UHD"/>
</category>
```

Unfortunately, it looks like all of the indexers I have access to expose their newznab categories this way. Doesn't look specific to TV cats either. 

Movie categories from nzb cat:
```
   <category id="2000" name="Movies">
    <subcat id="2050" name="3D"/>
    <subcat id="2060" name="BluRay"/>
    <subcat id="2070" name="DVD"/>
    <subcat id="2010" name="Foreign"/>
    <subcat id="2040" name="HD"/>
    <subcat id="2999" name="Other"/>
    <subcat id="2030" name="SD"/>
    <subcat id="2045" name="UHD"/>
    <subcat id="2080" name="WEBDL"/>
   </category>
```

nzbfinder audio categories:
```
   <category id="3000" name="Audio">
    <subcat id="3030" name="Audiobook"/>
    <subcat id="3060" name="Foreign"/>
    <subcat id="3040" name="Lossless"/>
    <subcat id="3010" name="MP3"/>
    <subcat id="3999" name="Other"/>
    <subcat id="3020" name="Video"/>
   </category>
```

simplynzbs xxx categories:
```
   <category id="6000" name="XXX">
    <subcat id="6010" name="DVD"/>
    <subcat id="6060" name="Imageset"/>
    <subcat id="6999" name="Other"/>
    <subcat id="6070" name="Packs"/>
    <subcat id="6080" name="SD" description="XXX SD Releases"/>
    <subcat id="6045" name="UHD"/>
    <subcat id="6090" name="WEB-DL" description="XXX WEBDL Releases"/>
    <subcat id="6020" name="WMV"/><subcat id="6030" name="XviD"/>
    <subcat id="6040" name="x264"/>
   </category>
```

**Comment by theotherp** [comment]
I've decided to not determine the caps output by the configured categories. They're for parsing and internal search only anway. 

Half of the categories differ between indexers . TV and HD and their subcategories seem to be the same (probably due to automation tools requiring the standard to be kept).

I was finally able to get Medusa to somewhat work and recognize Hydra and it reported all the expected categories.
