### ISSUE TITLE
Possibility that CGI might be vulnerable to SQL Injection

### ISSUE THREAD

**Issue by pagnutti** [theotherp/nzbhydra2#723]
Way out of my league here, but a recent security scan has shown the following POSSIBLE vulnerability:

+ The following resources may be vulnerable to blind SQL injection :

+ The '_csrf' parameter of the /login CGI :

/login?username=&password=&_csrf=858478ab-3b1c-4385-bd86-4d1c2f41ed82'||
'&password=&_csrf=858478ab-3b1c-4385-bd86-4d1c2f41ed82

-------- output --------
HTTP/1.1 200
-------- vs --------
HTTP/1.1 400
------------------------

+ The 'password' parameter of the /login CGI :

/login?username=&_csrf=858478ab-3b1c-4385-bd86-4d1c2f41ed82&password='||
'&_csrf=858478ab-3b1c-4385-bd86-4d1c2f41ed82&password=

-------- output --------
HTTP/1.1 200
-------- vs --------
HTTP/1.1 400
------------------------

/login?username=&_csrf=858478ab-3b1c-4385-bd86-4d1c2f41ed82&password='||
'&_csrf=858478ab-3b1c-4385-bd86-4d1c2f41ed82&password= {2}

-------- output --------
HTTP/1.1 200
-------- vs --------
HTTP/1.1 400
------------------------

**Comment by theotherp** [comment]
Thanks for the note but I don't think so. The login page is implemented by the most widely used security library for java. It also doesn't even access the database. If you have a concrete example for a vulnerability please let me know.
