### ISSUE TITLE
BUG: SSLPeerUnverifiedException (NZBNOOB)

### ISSUE THREAD

**Issue by LeeThompson** [theotherp/nzbhydra2#728]
NZBNoob's SSL certificate seems to be okay with Chrome/Edge but not so much with NZBHydra's Java base.

The issue appears in the debug log as "`NzBNooB: Hostname www.nzbnoob.com not verified`".

The exception appears in the results and not in the log, it is:

`Error while communicating with indexer NzBNooB. Server returned: javax.net.ssl.SSLPeerUnverifiedException: Hostname www.nzbnoob.com not verified: certificate: sha256/LaV2REoHJZETqKdTqCCSZyKMHrJPeOeuCwFeAaQEmLE= DN: CN=ip199.ip-54-37-46.eu subjectAltNames: [ip199.ip-54-37-46.eu, nzbnoob.com]`

It would be nice if it was verify the certificate, if that can't be done for some reason having an option to have it ignore this and parse results anyway would be okay.  (It can even default to off).

I am running this in a docker container, although I don't think that would cause this issue.  The image is `linuxserver/nzbhydra2:latest`.   It is up to date.

[nzbhydra-debuginfos-2021-09-16-22-04.zip](https://github.com/theotherp/nzbhydra2/files/7182788/nzbhydra-debuginfos-2021-09-16-22-04.zip)

**Comment by theotherp** [comment]
Try disabling SNI got that host.

**Comment by LeeThompson** [comment]
Disabling SNI didn't work but disabling SSL did.  Thanks.
