### ISSUE TITLE
Radarr nightly (4.0.0) has no v2 API, only V3

### ISSUE THREAD

**Issue by lunks** [theotherp/nzbhydra2#731]
I'm trying to add indexers to Radarr on the latest nightly, 4.0.0.5309, but the /system/status call has to use the correct namespace on /api/v3 instead of just /api.

Error message in log is:

```
URL call to http://<radarr-ip-address>:7878/api/system/status returned 404: Not Found
{
  "message": "NotFound"
}
```

Manually calling /api/v3/system/status does work:

```json
{
   "version":"4.0.0.5309",
   "buildTime":"2021-09-28T04:11:02Z",
   "isDebug":false,
   "isProduction":true,
   "isAdmin":false,
   "isUserInteractive":true,
   "startupPath":"/app/radarr/bin",
   "appData":"/config",
   "osName":"ubuntu",
   "osVersion":"20.04",
   "isNetCore":true,
   "isLinux":true,
   "isOsx":false,
   "isWindows":false,
   "isDocker":true,
   "mode":"console",
   "branch":"nightly",
   "authentication":"none",
   "sqliteVersion":"3.31.1",
   "migrationVersion":197,
   "urlBase":"",
   "runtimeVersion":"5.0.10",
   "runtimeName":"netCore",
   "startTime":"2021-09-30T09:38:34Z",
   "packageVersion":"4.0.0.5309-ls122",
   "packageAuthor":"linuxserver.io",
   "packageUpdateMechanism":"docker"
}
```

I think all that's needed to do is update this conditional to handle radarr v3 specifically:

https://github.com/theotherp/nzbhydra2/blob/6e879d635f2db24c711580f4fcc50365057ffa40/core/src/main/java/org/nzbhydra/externaltools/ExternalTools.java#L193-L197

**Comment by theotherp** [comment]
If I were nitpicky I'd say it's a feature request to support the nightly branch of another tool. I'll try to get it working soon.

**Comment by lunks** [comment]
> If I were nitpicky I'd say it's a feature request to support the nightly branch of another tool. I'll try to get it working soon.

Semantics are hard haha feel free to change the labels
