### ISSUE TITLE
BUG Search Result Quick Filters Issue

### ISSUE THREAD

**Issue by DerekWilliamsUK** [theotherp/nzbhydra2#732]
Quick Filters (for TV & Movies) are active by default when searching for other categories. For example, when searching for Ebook titles ALL results are filtered out in error.
 
![EbookSearch](https://user-images.githubusercontent.com/18551763/135825208-c76d6979-d937-48c2-8ac0-5a9cdb4cab07.jpg)

I have these Configuration Settings which would seem to indicate that the Quick Filters should ONLY apply to TV & Movie searches, or have i got that wrong? I want my specified pre-selections (1080p & 2160p) to ONLY apply for TV & Movies search results.

![QuickFilters](https://user-images.githubusercontent.com/18551763/135825412-fd62ad51-0274-41dd-afcf-7b17c772e503.jpg)

Hope the images help to explain what is happening. Regards.

**Comment by theotherp** [comment]
Please post your debug infos zip

**Comment by clevnumb** [comment]
Can you please add the XXX category that this filter still can be set to appear? I have been using that all the time, and it's very helpful. Thank you.

**Comment by theotherp** [comment]
@clevnumb Please create a new ticket and describe the problem. I think I already told you that you can enable the quick filters to always be shown.

**Comment by clevnumb** [comment]
Hi. I could not find the option to enable ALL filters... that option slider
says to enable it for TV and movies only....

**Comment by theotherp** [comment]
![image](https://user-images.githubusercontent.com/14368889/159254504-33f6b32f-c277-42b8-a817-e8fb795e4a05.png)
![image](https://user-images.githubusercontent.com/14368889/159254542-b673132f-4b1f-4aff-b0cd-a880d9294c99.png)

**Comment by Adamb859** [comment]
Missed that. Thanks again!

**Comment by clevnumb** [comment]
Thank you! I missed the Advanced slider. Yay!
