### ISSUE TITLE
Benefits of adding Hydra as a Single Aggregate Endpoint

### ISSUE THREAD

**Issue by bakerboy448** [theotherp/nzbhydra2#739]
https://github.com/theotherp/nzbhydra2/blob/6e879d635f2db24c711580f4fcc50365057ffa40/core/ui-src/html/configure-in-modal.html#L19

Why is it recommended to have hydra as a single aggregate endpoint?

Does this not have all the same downsides as Jackett's all endpoint?  (Answer is yes)

what benefits does a single aggregate endpoint add over having each indexer properly added?

**Comment by sienar1** [comment]
I think it's pretty obvious that if you use multiple *arr packages with multiple indexes, it's a big time saver to manage all the indexes in a single spot. and then on top of that when you want to do manual searches against multiple indexes you have a single pane of glass to do that AND send whatever downloads to your downloader.

If that's not valuable to you, no big deal, just move along.

**Comment by bakerboy448** [comment]
> it's a big time saver to manage all the indexes in a single spot. and then on top of that when you want to do manual searches against multiple indexes you have a single pane of glass to do that AND send whatever downloads to your downloader.


false

1) Hydra can sync to \*arrs thus negating any time saving for managing

2) a single aggregate endpoint is nothing but issues, especially for usenet where categories are not consistent and worse for if you have Jackett passing through hydra.  Aggregate endpoints serve no benefit when combined with \*arr sync abilities.

searching multiple indexers in hydra's UI as you mention has nothing at all with using hydra's aggregate endpoint in \*arrs

**Comment by bakerboy448** [comment]
@theotherp apologies in the ping; any thoughts in this?

Maybe default to multi and update the helptext :)

**Comment by theotherp** [comment]
I'm not sure enough which one is better and thus will keep it the way it was originally conceived.

**Comment by bakerboy448** [comment]
> I'm not sure enough which one is better and thus will keep it the way it was originally conceived.

There's no benefits to a single aggregate endpoint. 

You have the same issues that Jackett /all does.

- you lose control over indexer specific settings (categories, search modes, etc.)
- mixing search modes (IMDB, query, etc.) might cause low-quality results
- slow indexers will slow down the overall result
- total results are limited to 1000

I believe you worked around 1 indexer failing causing the entire endpoint to fail, correct?

So what benefits does using hydra's aggregate endpoint provide over using multi and having it sync each indexer?

**Comment by theotherp** [comment]
Yes, you may be right. I don't know. I kinda just don't care at the moment, sorry. My motivation is at a low and anything apart from simple support tickets and little improvements I just don't wanna think about. I'll come back to this when I have the energy.

**Comment by John-Gee** [comment]
@theotherp Do you have any opinion on this now?

**Comment by theotherp** [comment]
Nah.
