### ISSUE TITLE
Windows- Fails to launch

### ISSUE THREAD

**Issue by jfarso** [theotherp/nzbhydra2#745]
I've used this before for quite some time now, but recently did a Windows reinstall and am having issues getting it to launch now. For what its worth, I don't remember what JDK I had before.

I am on Windows 10, and currently have OpenJDK 11 in the path.

_openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)_

Here is the only information from the logs:

> 2021-12-01 14:22:44,684  INFO - Determined java version as '11' from version string 'openjdk version "11" 2018-09-25'
> 2021-12-01 14:22:44,686  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=C:\Applications\nzbhydra2-3.18.0-windows\data\logs -jar C:\Applications\nzbhydra2-3.18.0-windows\lib\core-3.18.0-exec.jar --datafolder C:\Applications\nzbhydra2-3.18.0-windows\data in folder C:\Applications\nzbhydra2-3.18.0-windows
> 2021-12-01 14:22:45,371  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it

When I try to launch it with the above command line as suggested, I get the following exception:

> Exception in thread "main" java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
>         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
>         at org.nzbhydra.mapping.SemanticVersion.stateMajor(SemanticVersion.java:151)
>         at org.nzbhydra.mapping.SemanticVersion.setAsString(SemanticVersion.java:277)
>         at org.nzbhydra.mapping.SemanticVersion.<init>(SemanticVersion.java:43)
>         at org.nzbhydra.NzbHydra.main(NzbHydra.java:94)

Any suggestions?

**Comment by theotherp** [comment]
Why the fuck does every JDK have to return a different version format?

New update incoming. When it's there manually update the .jar file in the lib folder with the one from the ZIP.

**Comment by jfarso** [comment]
Works, thank you so much for the quick fix!
