### ISSUE TITLE
Unable to send nzb file back to download client from Download History page

### ISSUE THREAD

**Issue by jaywk** [theotherp/nzbhydra2#75]
* What do you expect to happen? What does happen? 

When trying to send an nzb back to the download client by clicking the nzbget icon under ``History & Stats > Download history`` I get the following error:
```
Unexpected error when client tried to access path /internalapi/downloader/addNzbs. Error message: JSON parse error: Can not deserialize instance of java.lang.String out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token

 at [Source: java.io.PushbackInputStream@683744cf; line: 1, column: 81] (through reference chain: org.nzbhydra.downloading.AddNzbsRequest["searchResults"]->java.util.ArrayList[0]->org.nzbhydra.searching.SearchResultWebTO["indexer"])
```
* Can the problem be reproduced? How?

To try and rule out if there was a problem with my existing database, I deleted it (after making a backup) and performed the same actions with a brand new database. I sent one api call from sonarr then went back to ``History & Stats > Download history`` and tried to click the nzbget icon but I was presented with the same error message.

Log files attached.
[nzbhydra-debuginfos-2018-01-18-18-07.zip](https://github.com/theotherp/nzbhydra2/files/1644829/nzbhydra-debuginfos-2018-01-18-18-07.zip)

**Comment by theotherp** [comment]
Can confirm.
