### ISSUE TITLE
Proxy "Download NZB" Requests

### ISSUE THREAD

**Issue by budgetfermium** [theotherp/nzbhydra2#750]
* What do you want to happen?
I want "Download NZB" requests to be proxied. 

* If not clear, why do you want it?
Currently, when you press "Download NZB" in the very right-hand side of a search result, NZBHydra2 redirects the browser to the direct download link. This behavior is unexpected.

* Do you think it's something only you need or something that might be popular?
I imagine most people who enabled a proxy would want "Download NZB" requests to be proxied.

**Comment by theotherp** [comment]
![image](https://user-images.githubusercontent.com/14368889/147869333-81587623-3050-4e23-874d-f51ac57a1d83.png)
