### ISSUE TITLE
Hide dead torrents?

### ISSUE THREAD

**Issue by AmazingYan-1** [theotherp/nzbhydra2#757]
Hi right now when I do a search trackers returning those torrents which has 0 seeders also  - which is fine. But if we can have an option to turn off 0 seeders results by default it will help sort the list even more. 

Thanks

**Comment by theotherp** [comment]
It's in the indexer config box.

**Comment by AmazingYan-1** [comment]
thank you i totally missed that setting. this can be closed :)
