### ISSUE TITLE
Info link going to download url

### ISSUE THREAD

**Issue by AmazingYan-1** [theotherp/nzbhydra2#758]
Hi team

My setup is very simple. Nzbhydra2 retrieving records from jackett.

I'm using http://www.dereferer.me/?$s as my dereferrer url and it's working fine.  However when I search for a torrent, and when i click the "i" icon next to the download icon, it should take me to the details page right? 95% its working fine. But so far I've identified when you;re using torrentleech and Blutopia as your tracker, that "i" icon is directly going to the download url. like this - 

http://www.dereferer.me/?https%3A//www.torrentleech.org/download/2019509/torrentname.torrent

So when i click the "i" icon the torrent file is getting downloaded. I don't want that instead I need to go to the details page. It's working fine with all other trackers but only these 2 giving problems. Any idea why?

* What do you expect to happen? What does happen? 

When you click the i icon I'd expect it to redirect me to the torrents details page.

* Have you searched for this problem? You don't have to answer, just make sure.

Yes

* Can the problem be reproduced? How?

Simply select Torrentleech or Blutopia as your Indexers and search something. You will see the results. From there select any one of the listing and click the "i" icon. Screenshot - https://www.imagebam.com/view/ME7QNLS

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

OK

* If you use a docker container please tell me which one.

I'm using Ubuntu vps just for jackett and nzbhydra2

* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
Using chrome latest version. 

The issue is quite simple. When you click the "i" icon it should take you to that particular indexers details page - which is working fine. But only with 2 trackers its downloading the torrent instead going to the details page.

Let me know if you need more details.

**Comment by theotherp** [comment]
Remove the dereferer, it's not needed anymore with any modern browser as hydra sets a header that instructs the browser to remove the referer information.

I can't test it as torrentleech is private. Anyway, if the details page works for some indexers but not for others it is probably a problem with jackett. I just show the information provided by the indexer which is in this case jackett. https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/torrentleech.yml looks fine though.

**Comment by AmazingYan-1** [comment]
Hi @theotherp I just did a test again and I was able to replicate it. 

So I also went to jackett and searched for an episode which correctly linked to his details page. For example in nzbhydra if i compare 2 tracker results -

HD torrents (i) icon is linked to - https://hd-torrents.org/details.php?id=XXXXXXXXXXXXXXXXXXXXXXXXXX

Whereas Torrentleech  (i) icon is linked to - https://www.torrentleech.org/download/123123123/XXXXXXX.torrent

I have around 20 indexers and noticing this issue with torrenleech and Blutopia only...

You told me you're showing the info provided by jackett, may i know from where you're pulling that info url? 

Thanks

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13002#issuecomment-1053670859

**Comment by AmazingYan-1** [comment]
Hi @theotherp pls see the comment above.. I contacted jackett devs and they have provided a solution to this problem :) Hopefully there will be an update soon.

**Comment by benfishbus** [comment]
THANK YOU!
