### ISSUE TITLE
Ability to filter notifications given a list of keywords

### ISSUE THREAD

**Issue by phyzical** [theotherp/nzbhydra2#761]
* What do you want to happen?
some sort of config option or env that allows the ability to filter blacklist keywords or strings that will prevent the notification from being sent

* If not clear, why do you want it?
just want a way to disable notifications on a per indexer basis (due to certain indexers being a bit more aggressive)

* Do you think it's something only you need or something that might be popular?
i dont see why others may not find it useful

as per the discussion i requested it from apprise side https://github.com/caronc/apprise/issues/534 but was told they cannot

the suggested workaround was something like the following

```
#!/bin/sh
INPUT="$@"
echo "$INPUT" | egrep -q "some text"
if [ ! $? -eq 0 ]; then
   # text not matched
   apprise -t "my title" -b "$INPUT" -g mytag
fi
```

**Comment by theotherp** [comment]
Sorry, forgot about that one.

**Comment by phyzical** [comment]
@theotherp its okay figured i should create the issue just incase :)

thanks for the speedy implementation, ill give it a test tomorrow afternoon to confirm it as working 👍

**Comment by phyzical** [comment]
just to confirm should the value be lost after saving?

**Comment by theotherp** [comment]
Huh? No

**Comment by phyzical** [comment]
no rush if your AFK, added a gif showing whats happening for me :) let me know if there anything else i need to look into
![test](https://user-images.githubusercontent.com/5182053/155145225-ddad85eb-7945-4e99-88e5-6329c30161bf.gif)

**Comment by theotherp** [comment]
See the text to the right that says "Apply values with return key"? Do that.

**Comment by phyzical** [comment]
ah derp sorry i am clearly blind >< sorry for wasting your time 👍  

can confirm it is working a charm <3

**Comment by theotherp** [comment]
You're not the first one to not get it. I don't know how to make it any clearer. If you have an idea how to word it better I'm open for it.
