### ISSUE TITLE
Grouping Display Bug

### ISSUE THREAD

**Issue by AmazingYan-1** [theotherp/nzbhydra2#763]
I have noticed some weird filtering bug. 

Let me explain. This is my current filter settings - https://www.imagebam.com/view/ME8CJHG

Now, when I search for a movie, it's grouping the same title and showing like this - https://www.imagebam.com/view/ME8CJI8

I don't want it to be like this. I want it to display all the duplicated release name as well. So when i untick "[Group TV results by season/episode]" nothing is changing. The weird part is, after unticking Group TV results by season/episode and if i tick that option again its listing properly like this - https://www.imagebam.com/view/ME8CJJG (this is what I want by default). 

I don;t understand why unticking and ticking the same option is changing the results table format.. How can I have a permanent results view with all the duplicated titles are listed? 

I tried by ticking this option and unticking this option before searching a title. In both scenarios its just hiding the similar title. The only way to show the titles again, is to untick and tick this option again - Group TV results by season/episode.

I even did a test with a tv series episode and was able to replicate this same issue... 

* What do you expect to happen? What does happen? 

When we select a Display filter, it should work.

* Have you searched for this problem? You don't have to answer, just make sure.

Couldnt find this particular issue

* Can the problem be reproduced? How?

Set your display options like this - https://www.imagebam.com/view/ME8CJHG and search a popular movie. It will hide the duplicated titles from being displayed even though the actual result is there

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

Done

* If you use a docker container please tell me which one.

I'm using a Debian VPS

* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.

My current version is 4.1.0 using win 10 - 4k monitor

**Comment by theotherp** [comment]
It's actually a bug that it's displayed the way you want sometimes...

**Comment by AmazingYan-1** [comment]
> It's actually a bug that it's displayed the way you want sometimes...

haha :D I kind of guessed that. if it possible for you to add an option to show names and hide names in grouping if its not that difficult? I dont know why I kinda like when the release name is displayed even though it's the same name. 

But if it's a difficult task then I understand.

**Comment by theotherp** [comment]
Shouldn't be a problem.

**Comment by AmazingYan-1** [comment]
awesome bud appreciate it :)
