### ISSUE TITLE
hydra use so much resource

### ISSUE THREAD

**Issue by Monirzadeh** [theotherp/nzbhydra2#765]
* in docker
hydra use so much cpu on my server. by default when all 24 container is running idle it is work with around 2-5 percent of CPU usage. but when i start [nzbhydra2](https://github.com/theotherp/nzbhydra2) it jump around 55-75 percent all the time even idle.
i think something is wrong with nzbhydra2. log not show any error is it normal?
any suggestion for more investigation?

**Comment by theotherp** [comment]
Please:
1. Enable the display of advanced options in the config
2. Set the log file level to debug
3. Enable the logging marker "Performance"
4. Go to the debug report tab in the system section
5. When the CPU usage is high click the "Log thread dump" button
6. Create and upload the debug infos zip and post the link here
