### ISSUE TITLE
Crashing on java jdk v18

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [theotherp/nzbhydra2#767]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 

when running nbzhydra2 via `nzbhydra2wrapperPy3.py` wraper on java 18 jdk it crashes after a few hours.

* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?

just set JAVA_HOME to java 18 & let it run for a few hours

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
* If you use a docker container please tell me which one.
* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.

```text
macOS Big Sir 11.6.5
python 3.8.13
java 18 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Nzbhydra2 Version: 4.2.1
```
![Screen Shot 2022-03-26 at 2 27 41 pm](https://user-images.githubusercontent.com/2242880/160223141-18cd10f8-dda5-4de8-ac4d-04e8165ddcdf.jpg)
[All Logs.zip](https://github.com/theotherp/nzbhydra2/files/8354604/All.Logs.zip) <-- Logs

also when doing create & download debug info's from the web UI I get this error
![Screen Shot 2022-03-26 at 2 31 57 pm](https://user-images.githubusercontent.com/2242880/160223180-72e0c7d3-627c-42b5-a501-64cbadfc1224.jpg)

**Comment by theotherp** [comment]
As described in the Readme Java 18 is not supported. There's a barely any
reason to use it at the moment anyway...
