### ISSUE TITLE
Unable to determine java version

### ISSUE THREAD

**Issue by anonvoy** [theotherp/nzbhydra2#768]
Hydra (fully updated) won't start (using the wrapper) with Java 11:

    2022-04-03 13:23:31,689  ERROR - Unable to determine java version; make sure Java is installed and callable. Error message: Unable to determine java version from string openjdk version "11.0.14.1" 2022-02-08

There's no such problem when I set the Java version to be used (alternatives) to 8, 14 or 16 (i. e. Hydra is starting with these). This is on OpenSUSE Linux Leap 15.3. Java 11.0.14.1 was recently installed as an update by the distribution; the previous versions were 11.0.14.0, 11.0.13.0, 11.0.12.0 and 11.0.11.0; Hydra worked with all of these.

**Comment by jpapp25** [comment]
I had a similar issue Ubuntu 20.04 and I had to change ExecStart in the nzbhydra2.service file to point to the nzbhydra2wrapperPy3.py instead of the nzbhydra2 file in the root nzbhydra2 directory.

**Comment by flatlinebb** [comment]
It seems that the recommended fix from the linuxserver.io folks for the java errors is to update docker to version 20.10.14, as per [this comment](https://github.com/linuxserver/docker-nzbhydra2/issues/20#issuecomment-1117897705). This appears to resolve the issues running the latest nzbhydra2 release v4.3.1-ls52.
