### ISSUE TITLE
past feature now gone/moved

### ISSUE THREAD

**Issue by Adamb859** [theotherp/nzbhydra2#769]
Was the selection bar above the search results taken away? The one where you could click x264-x265-1080p-2160p and it would filter only those results. Don't know if its gone now or moved. Thanks

**Comment by theotherp** [comment]
https://github.com/theotherp/nzbhydra2/issues/732#issuecomment-1073795114

**Comment by Adamb859** [comment]
Missed that. Thanks again!

**Comment by theotherp** [comment]
No worries, I should have announced it in the news or something.
