### ISSUE TITLE
Trying to use 2.10.2 to migrate from Hydra 1 crashes before startup

### ISSUE THREAD

**Issue by slydog3333** [theotherp/nzbhydra2#770]
Ultimate fix would to be able to migrate with the current version, but with 2.10.2 I'm getting: 
An unexpected error occurred during startup

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nzbsOrg': Unsatisfied dependency expressed through field 'unmarshaller'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'marshaller' defined in class path resource [org/nzbhydra/web/WebConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null

This is with ibm-semeru-open-jdk_x64_windows_17.0.2_8 installed so maybe the old version of hydra2 doesn't work with the new Java?

[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/8500198/nzbhydra2.log)

**Comment by theotherp** [comment]
That's because Java 17 is not supported
Even if then that hydra version can't migrate from v1 (not sure which one
supports that) but when you start it it will tell you 😉

**Comment by slydog3333** [comment]
The popup says starting in version 2.10.3 migration was removed and then it directs you to 2.10.2

But you're right that version doesn't support migration. I got it to work after installing java 8.

I installed 2.0 and migration works.

Thanks for pointing me in the right direction. You might want to change that migration popup though.
