### ISSUE TITLE
BUG Usenet Cap Check Failure

### ISSUE THREAD

**Issue by DeepSpaceK9** [theotherp/nzbhydra2#771]
I'm upgrading from version 4.2.1 (version specific tag) to 4.3.0 (latest tag), using the Docker package from Linuxserver.io. My docker environment is running on Ubuntu Server 20.04.4 LTS. This upgrade first, causes a database corruption of some kind (we spoke about this over Discord). Deleting the database file fixes that issue, which is fine as a workaround for me but the cap check failure on the Usenet indexers makes it unreasonable for me to use 4.3.0. I can reproduce this issue 100% of the time with this upgrade path. I can also completely remove the config directory I have assigned, re-pull the image, and still experience the cap check failure.

If you need additional info, logs, or anything from my end please let me know. I'm willing to work this issue and make this as mutually beneficial as possible.

[nzbhydra-debuginfos-2022-04-27-04-23.zip](https://github.com/theotherp/nzbhydra2/files/8571612/nzbhydra-debuginfos-2022-04-27-04-23.zip)

**Comment by DeepSpaceK9** [comment]
Note, this only happens with Usenet indexers. Jackett/Torrents are fine.

**Comment by dmwyatt** [comment]
Getting exact same issue down to the original database corruption.

I wiped my hydra2 data volume so I'm working from a fresh start.  I then added an indexer and had same problem.  Here's the debug info (note that the "upload to file share" also resulted in an error):

https://www.dropbox.com/s/wyvr9nofsxhdtiw/nzbhydra-debuginfos-2022-05-01-17-28.zip?dl=1

**Comment by dmwyatt** [comment]
Of note, if I delete my data directory, switch my docker-compose to:

`image: lscr.io/linuxserver/nzbhydra2:v4.2.1-ls46`

to get back on 4.2.1, everything works fine.

**Comment by theotherp** [comment]
Please roll back to docker image 4.3.0-ls47. It seems to be an error in the container. I can reproduce it wil 4.3.0-ls50 but not with 4.3.0-ls47. Let me know if it helps.

**Comment by dmwyatt** [comment]
4.3.0-ls47 seems to work correctly.

**Comment by jsgjunk** [comment]
Thank you! I've been struggling for a while with this. Rolled back to 4.3.0-ls47 and can confirm that version seems to work fine so far.

**Comment by flatlinebb** [comment]
The linuxserver.io people are recommending upgrading docker to at least the release version 20.10.14, which fixes the issues with the nzbhydra2 container version v4.3.1-ls52 both with java issues and the bugged searches. Please see [this issue](https://github.com/linuxserver/docker-nzbhydra2/issues/20#issue-1224775150) for details.

**Comment by DeepSpaceK9** [comment]
> The linuxserver.io people are recommending upgrading docker to at least the release version 20.10.14, which fixes the issues with the nzbhydra2 container version v4.3.1-ls52 both with java issues and the bugged searches. Please see [this issue](https://github.com/linuxserver/docker-nzbhydra2/issues/20#issue-1224775150) for details.

Nothing here resolved the issue for me. I was already running Docker v20.10.14, but I did a full update to my host anyway and this did not resolve the issue. v4.3.0-ls47 is working for me at this time.

**Comment by DeepSpaceK9** [comment]
dev-v4.3.1-ls64 is also working. Something fixed between v4.3.0-ls47 and dev-v4.3.1-ls64.

**Comment by DeepSpaceK9** [comment]
As of 4.6.1 this issue no longer exists for me. This is an old and stale issue that appears to no longer be present in the latest release. I'm closing this for cleanup.
