### ISSUE TITLE
High Thread CPU Usage

### ISSUE THREAD

**Issue by jtweedie** [theotherp/nzbhydra2#775]
Hi there,

I'm aware this seems to have been reported already so if this is a duplicate I'm happy for it to be closed.

I'm experiencing an issue where nzbhydra2 running in a docker container (maintained by linuxserver.io) is consuming extremely high amounts of CPU while idling.
This is a recent issue and only ocurrs after the container has been running for a while, restarting the container settles it for a while.

top -H shows the thread to be consistently a java thread "H-Delete old search".

I've attached a debug info zip with performance markers enabled and a thread dump while this occurs: [nzbhydra-debuginfos-2022-05-21-20-34.1.zip](https://github.com/theotherp/nzbhydra2/files/8748331/nzbhydra-debuginfos-2022-05-21-20-34.1.zip)

If you need any futher info I'm happy to provide it.

Jonathan

**Comment by gmoler** [comment]
same issue, i had to delete my DB for this to go away, likely something when the DB gets too big or something?

here are my history settings 

![firefox_aU5nYd3bBQ](https://user-images.githubusercontent.com/7731882/173683692-43f43269-2ee5-45bf-ad57-fe901a7b4ffa.png)

**Comment by theotherp** [comment]
Should hopefully be fixed with new version.
