### ISSUE TITLE
1.1.1 update broke a working system with Nginx reverse proxy

### ISSUE THREAD

**Issue by adx442** [theotherp/nzbhydra2#78]
URLs are being written as https://site.com:80/nzbhydra when sent to NZBget, which fails.  Actual URL  for my system should be https://site.com/nzbhydra.  Additionally, I can't set the external URL any more, as entering the value, saving, and restarting shows that the configuration item is always set back to blank now. 

Searches still work, but my download can't get anything from Hydra since 1.1.1.  I double checked my working Nginx config, nothing wrong there.  I'm having to roll back to 1.0.18, which works perfectly.

**Comment by theotherp** [comment]
Have you read https://github.com/theotherp/nzbhydra2/wiki/Exposing-Hydra-to-the-internet-and-using-reverse-proxies ?

The external URL setting is obsolete and I just forgot to remove it from the config page.

To get more information about how Hydra determines the URL to use set the log level to Debug and enable the logging marker "URL calculation".

When you've read the wiki and it hasn't helped please do the logging steps and check the log file. As all the relevant information in the log is anonymized you'll have to tell me what's going wrong.

**Comment by theotherp** [comment]
My guess is that you just need to the set x-forwarded-port header.

**Comment by adx442** [comment]
Yeah, it's set as specified in Nginx, per your docs.  Same results.  Reverse proxy has always been in place, only this update broke it. I'll check the logging. 

-Jack (sent from mobile)
________________________________

**Comment by theotherp** [comment]
I've further modified the code, the next version might fix this. Very hard to get this right as there are so many possible variations of tools, environments and configurations out there.

**Comment by adx442** [comment]
This should probably be closed.  The issue was nginx configuration, but the wiki settings for NZBHydra didn't work.  What worked for me was _removing_ x-forwarded-port entirely and changing x-forwarded-proto to https rather than $scheme (it wasn't picking up the scheme correctly.  

Working as intended now with those two changes.

**Comment by theotherp** [comment]
Weird, that's the settings I used on my machine while developing. With the next version it might've worked. 

In any case I'm glad it works now.
