### ISSUE TITLE
Allow Unlimited downloads per indexer

### ISSUE THREAD

**Issue by reloxx13** [theotherp/nzbhydra2#781]
Some indexer have no download limit.   

Its not possible to set this in nzbhydra´s indexer config. It requests to be min. 1.

if left empty, the indexer status page will show 5 (the old value?).

![grafik](https://user-images.githubusercontent.com/14855001/174434444-db6feadc-ca91-4a52-a9e4-6f7182f7ca34.png)

![grafik](https://user-images.githubusercontent.com/14855001/174434478-3db347f2-2a02-4242-b64f-4cc4f6de2894.png)

![grafik](https://user-images.githubusercontent.com/14855001/174434506-9d628fbb-eaa4-4365-98ef-cedcfa95c8dc.png)

![grafik](https://user-images.githubusercontent.com/14855001/174434531-6320de45-ecf2-4224-9e7d-ed0ba92320a5.png)

**Comment by albino1** [comment]
I think you can just delete the 0 and leave it blank.  All of mine are blank.

**Comment by reloxx13** [comment]
> I think you can just delete the 0 and leave it blank. All of mine are blank.

![grafik](https://user-images.githubusercontent.com/14855001/174498091-868f8c03-8477-4daa-91d6-cc0c4425b541.png)   
its still either a display bug or it limits by 5, i didnt test this.

**Comment by albino1** [comment]
Too bad that didn't fix it.  Looks like @theotherp will having to look into it himself then.

**Comment by theotherp** [comment]
Can't reproduce this. Deleting the download limit from the config (i.e. removing the value) also hides it in the indexer status page. Give it a day or two and see if it goes away...
