### ISSUE TITLE
Internal API Access/Scheduled Searches

### ISSUE THREAD

**Issue by anonuser69** [theotherp/nzbhydra2#782]
I have a use case where I have multiple search terms that I frequently search for and download all the results for.

NZBHydra is great for this because it remembers what's already been downloaded and hides those results. This means I can just make the searches, select all and send to the download client.

I'm currently trying to find a way to automate this. I've found the internal API and was hoping to use that to make the search and send all non-filtered results to my download client but the internal API requires some credentials(?) and I'm not sure if this would be the best way to approach it anyway.

Do you have any plans to open up the internal API to make it accessible for use cases like this or is there a better solution for what I'm attempting?

**Comment by theotherp** [comment]
You can check http://127.0.0.1:5061/v3/api-docs/ for autogenerated documention of the internal API. If you save that response as JSON you can import it here: https://editor.swagger.io/ for a UI.

You should not need any authentication apart from the one configured in NZBHydra. Although you may get problems calling some of the requests if hydra is running on another host.

**Comment by anonuser69** [comment]
Perfect, thanks! Now managed to get an automated solution working.

**Comment by theotherp** [comment]
Awesome! Didn't honestly expect that...

**Comment by anonuser69** [comment]
The code's pretty janky to get the correct headers being sent, there's absolutely no error checking and it won't go through all the pages of the results but it does the job good enough for me for now. Code below for anyone that needs a jumping-off point. Thanks again @theotherp.

```js
import axios from "axios";

const baseUrl = 'http://192.168.86.55:5076';
const indexers = ['Indexer 1','Indexer 2'];
const queries = [
    'Query 1',
    'Query 2'
];

const homepage = await axios.get(`${baseUrl}`);
const rawCookies = homepage.headers["set-cookie"];
let cookies = [];
let xsrfToken;
for (let i = 0; i < rawCookies.length; i++) {
    const cookie = rawCookies[i];
    cookies.push(cookie.substring(0, cookie.indexOf(';')));
    if (cookie.includes('XSRF-TOKEN')) {
        xsrfToken = cookie.substring(cookie.indexOf('=') + 1, cookie.indexOf(';'));
    }
}
const headers = {
    Cookie: cookies.join('; '),
    "X-XSRF-TOKEN": xsrfToken
};

for (let i = 0; i < queries.length; i++) {
    const query = queries[i];
    const search = await axios.post(`${baseUrl}/internalapi/search`, {
        query: query,
        category: "linux_distros",
        mode: "search",
        indexers: indexers,
        maxage: 5
    }, {
        headers
    });
    if (search.status === 200) {
        const newReleases = search.data.searchResults.filter(result => {
            return result.downloadedAt === null;
        });
        if (newReleases.length) {
            let titles = [];
            const downloadList = newReleases.map(release => {
                titles.push(release.title);
                return {
                    searchResultId: release.searchResultId,
                    originalCategory: release.originalCategory,
                    mappedCategory: release.category
                }
            })
            const addNzb = await axios.put(`${baseUrl}/internalapi/downloader/addNzbs`, {
                downloaderName: "SABnzbd",
                searchResults: downloadList,
                category: "default"
            }, {
                headers
            });
            if (addNzb.status === 200) {
                console.log('Grabbed:\n' + titles.join('\n'));
            }
        }
    }
}
```

**Comment by theotherp** [comment]
I think you can disable csrf in the main config.

**Comment by Tsims61** [comment]
Enhancement to ×20
