### ISSUE TITLE
Add support for "NZB access type" Per indexer not just global.

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [theotherp/nzbhydra2#784]
its come to my attention that some indexers l" **temporarily suspend** your API key if redirect is not being used instead of "Proxy NZB's"

* What do you want to happen?
allow the ability to choose "NZB access type" per indexer on the indexer's config page rather than restricting it to a global option where you are forced to use one or the other for all indexers.

* If not clear, why do you want it?
so I can continue to proxify NZB's for "Fallback for failed downloads" to work with all my other indexers except for those who impose restrictions.

* Do you think it's something only you need or something that might be popular?
if more indexers follow suit or start imposing ridiculous restrictions then yes it may become an needed feature..

* If not clear, explain the use case.
not sure how much clearer I can get.

**Comment by theotherp** [comment]
Removed references to a certain indexer...

I'll look into it.
