### ISSUE TITLE
Getting error with nzb.su - java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [theotherp/nzbhydra2#786]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 
 ㅤI get the error: `Server returned: java.lang.NumberFormatException: For input string: ""`
* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
 ㅤset nzb.su as the only indexer & search for the exact string: `Shadowhunters 1080p S01`
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
* If you use a docker container please tell me which one.
 ㅤN/A - I use the wrapper to run it. `nzbhydra2wrapperPy3.py`
* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.
```text
macOS 11.6.7
Python 3.9.13
Java Ver: jdk-17.0.3.1.jdk
Hydra Ver: Version: 4.5.0
```
<img width="723" alt="Screen Shot 2022-07-29 at 10 33 03 pm" src="https://user-images.githubusercontent.com/2242880/181763404-a55ca92b-1e28-43e7-b64d-86364ae29861.png">
I still get search results, just this error showing up..

[nzbhydra2 Logs.zip](https://github.com/theotherp/nzbhydra2/files/9219984/nzbhydra2.Logs.zip) - full debug, all markers on.

Also sidenote I also get this error when trying the DL the logs from the GUI:
<img width="654" alt="Screen Shot 2022-07-29 at 10 46 52 pm" src="https://user-images.githubusercontent.com/2242880/181763603-78db8ce9-bccf-4ea1-a51d-322c59691a6b.png">
I'm using Google Chrome: `Version 103.0.5060.134 (Official Build) (x86_64)`

**Comment by theotherp** [comment]
Sorry for the late response. Does this still happen? If so, could you please post your debug infos?

**Comment by XxUnkn0wnxX** [comment]
nah i don't get it anymore, been through many updates since that issue 1st arose.
