### ISSUE TITLE
Block list

### ISSUE THREAD

**Issue by DarrenPIngram** [theotherp/nzbhydra2#787]
* What do you want to happen?
Ability to set up a blocklist within NZBH, e.g. one entry per line, that would block results automatically if searched.

So if I searched for "Dog Dinners" it could give me results but AUTOMATICALLY remove the blocklist if any matches are found. So I could put HebDub for example on the blocklist and never then see Dog Dinners series1 blah blah Hebdub apper.
 
* Do you think it's something only you need or something that might be popular?
 For heavier users I could see a utility.
* If not clear, explain the use case.

**Comment by theotherp** [comment]
That's what the forbidden words and regex settings are for in the searching
config.
