### ISSUE TITLE
Ignore update not working, version 1.0.18

### ISSUE THREAD

**Issue by adx442** [theotherp/nzbhydra2#79]
On selecting "Ignore update", I get the following message:
```
An error occurred:
500: Internal Server Error

Path: /nzbhydra/internalapi/updates/ignore

Message: could not execute batch; SQL [insert into generic_storage_data (data, key, id) values (?, ?, ?)]; nested exception is org.hibernate.exception.DataException: could not execute batch

```
It used to work.  Actually updating the system works fine, I only get the error on trying to ignore an update, and it doesn't disable the permanent banner at the bottom asking to update.

**Comment by theotherp** [comment]
Works fine for me. Please post your debug infos.

**Comment by theotherp** [comment]
Closing this. If you have more to add please do so.
