### ISSUE TITLE
Redirect to correct url when using base

### ISSUE THREAD

**Issue by bskrtich** [theotherp/nzbhydra2#791]
## What do you want to happen?

When settings a URLBase such as /nzbhydra2 and you go to `http://10.1.1.25:8864/` will only return a 404

Most apps (such as radarr, sabnzbd etc) will auto redirect you if you try to access the root without the URLBase 

## Do you think it's something only you need or something that might be popular?

This is a nice to have

**Comment by theotherp** [comment]
Unfortunately this is not possible with the web server framework I'm using.
