### ISSUE TITLE
Extend Query/Search Regex Functionality to Search Results 

### ISSUE THREAD

**Issue by astro7467** [theotherp/nzbhydra2#794]
* What do you want to happen?
Parse Search Results text/title and being able to manipulate via RegEx to fix common errors - primary use-case is results with bad naming hygiene causing mis-id'ing of quality in *arr
```
e.g. "ABC.S01E01.1080pBluray.AAC5.1-group"
Match: {prefix:.*1080p}{suffix:[bw].*}
Return: {prefix}.{suffix}
Delivering: "ABC.S01E01.1080p.Bluray.AAC5.1-group"
```

> (using this style as it re-uses the functionality of "Custom mappings of queries and titles")

* If not clear, why do you want it?
Ability to manipulate search results beyond per "Remove trailing...", similar to what was delivered in  _Custom text search for indexers #700_ & what was _CustomSearchRequestMapping.java_

* Do you think it's something only you need or something that might be popular?
Popular in the sense that it can be used to fix a few commons scenarios (e.g. a few pre-configured "fixes" can be included as examples)

* If not clear, explain the use case.
Fix common "errors" in NZB titles that cause issues in *arr.
I would also use it to fix non-std conventions
```
e.g. "[group] ABC.S01E01.1080p.Bluray.AAC5.1" or "ABC.S01E01 (1080p Bluray AAC5.1 group)"
to "ABC.S01E01.1080pBluray.AAC5.1-group"
```
Can foresee common scenarios others may find it useful - especially if option to apply before duplicate checks

**Comment by theotherp** [comment]
I'll look into it.
