### ISSUE TITLE
New version possibly creates problems with indexer

### ISSUE THREAD

**Issue by DarrenPIngram** [theotherp/nzbhydra2#795]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 
Standard operation. But now with the new version and indexer O M G it stops working. When the indexer changes their requirements they gave a workaround, only part worked but they accepted that as valid. The new version of Hydra seems, I understand, to be clever and implement their needs. Howeveer my Hydra installation is behind a proxy and the proxy cannot get the records.

It passes to SAB but now it cannot get the "given" nzb as it is full of

https://my.host.address/sabnzbd/getnzb/api/(numbers deleted)?apikey=(API deleted) | URL Fetching failed; Unauthorized access
-- | --

So the past couple of days additions are effectively lost and, of course, you can't see what it was you've sent there :(

How to roll back to stop this "enhancement" or "override" it? I no longer see 

Respectfully, I've not changed anything else, SAB has not updated etc, and the only change is the recent auto-updates of Hydra.

I will email you the logs.

* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
* If you use a docker container please tell me which one.
* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

**Comment by theotherp** [comment]
I was told by the indexer that approach is the only accepted one so anything else would result in API blocks or bans.

I don't completely understand the problem - sabnzbd cannot connect with hydra? At all? You can configure the URL under which hydra is visible via the "External URL" parameter in the downloading config.
