### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by tuningman9790** [theotherp/nzbhydra2#799]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/9598253/nzbhydra2.log)
[nzbhydra2.2022-09-18.log](https://github.com/theotherp/nzbhydra2/files/9598255/nzbhydra2.2022-09-18.log)

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 
It seems today when opening nzbhydra, it just doesn't load anymore, Error 502 Bad Gateaway.
When checking Htop & the logs i see lots of java errors.
This is only a recent issue.

Simply restarting doesn't seem to work at all

* Have you searched for this problem? You don't have to answer, just make sure. 
Havn't found anything recent to mine.

* Can the problem be reproduced?
 How? It's consistent atm 

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
Error 502 Bad Gateaway

* If you use a docker container please tell me which one. 
no docker

* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.
Debian 10 / server

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

**Comment by theotherp** [comment]
Please replace the jar file in the lib folder with the one from the latest release: https://github.com/theotherp/nzbhydra2/releases/tag/v4.7.1

Thanks for beta testing and sorry for the inconvenience
