### ISSUE TITLE
Docker detection confirmation

### ISSUE THREAD

**Issue by hotio** [theotherp/nzbhydra2#80]
Running NZBHydra2 inside suitarr docker container, docker seems to be detected OK.

![hydra](https://user-images.githubusercontent.com/26902309/35195941-691b4b0e-fecb-11e7-8726-e50da5e5750b.png)

**Comment by theotherp** [comment]
Thanks for the feedback!

Am 21.01.2018 4:52 nachm. schrieb "hotio" <notifications@github.com>:

**Comment by Elfman72** [comment]
So can I ask why this is the preferred method of updating?  

I am running this within a Synology Docker and updating the container would require me to rebuilt the container.  I know I don't have to delete the db or cfg but it is nowhere near as elegant as simply updating from within the app itself.

**Comment by theotherp** [comment]
I agree. But
a) it's "not the docker way" (I was told) but you don't need to care about
that and
b) see
https://github.com/theotherp/nzbhydra2/issues/60#issuecomment-358294742

Because I know that the internal backup is so convenient I still left an
option to use it and you're free to do so and ignore the warning.

Am 23.01.2018 05:20 schrieb "Elfman72" <notifications@github.com>:

**Comment by titocr** [comment]
In this screenshot, I'm being shown different current and latest versions, and it is also telling me "You're up to date!".  I do think that 1.1.3 is the latest version available to docker, but that maybe 1.1.4 is available on github?

![screen shot 2018-01-23 at 5 56 34 pm](https://user-images.githubusercontent.com/10543061/35310670-5f4a0dca-0067-11e8-98d6-3834171e0e1c.png)

**Comment by theotherp** [comment]
@titocr What docker?

The update mechanism works independently from docker. It might happen that there's a new release that's displayed but docker is not up to date but that it shows a newer "Latest version" but doesn't allow you to update is rather weird.

**Comment by titocr** [comment]
Docker version 18.01.0-ce, build 03596f5 -- on ubuntu 17.10

At the time of the screenshot, I had done "docker pull" which brought me up to 1.1.3. About 3hrs after posting this issue, hydra2 got updated (by v2tec/watchtower), so this morning I'm on 1.1.4 and things look all right. So, there's a not-serious little something in there somewhere.

**Comment by theotherp** [comment]
Hm.. I'll take a further look. Closing this for now as the main issue seems to be solved.
