### ISSUE TITLE
Typo in NotificationHandler method callAppriseApi

### ISSUE THREAD

**Issue by armanatz** [theotherp/nzbhydra2#805]
The specific typo can be found on [Line 163 of the NotificationHandler class](https://github.com/theotherp/nzbhydra2/blob/master/core/src/main/java/org/nzbhydra/notifications/NotificationHandler.java#L163) at the end of the line where it is replacing `"/notify/notify"`.

It should say:

```
final String notifyUrl = UriComponentsBuilder.fromHttpUrl(notificationConfig.getAppriseApiUrl()).path("/notify").toUriString().replace("/notify/notify", "/notify");
```

**Comment by theotherp** [comment]
Thanks!
