### ISSUE TITLE
Fatal error!

### ISSUE THREAD

**Issue by leonardr629** [theotherp/nzbhydra2#808]
Hello everyone.. i have no idea for coding or java script...but after downloaded nzbhydra 2...when i click nzbhydra2.exe...
there is one error nzbhydra2wrapper returned -1...
Edition	Windows 10 Pro
Version	21H2
Installed on	‎8/‎25/‎2022
OS build	19044.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0

Thanks...

**Comment by theotherp** [comment]
Have you installed Java?
