### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by Sky12019** [theotherp/nzbhydra2#810]
Hello.
First of all, many congrats for the app. You have set the standards very high for the rest to follow! Keep it up there!

My question is about the warning message for the java version.

I have nzbhydra2 running as a windows service under windows 10 and I have already updated Java to latest version 1.8.0_351.

However when accessing nzbhydra2 from another computer in my Lan I get the usual message concerning outdated Java version!

How can this be resolved?

Thanks in advance.

**Comment by theotherp** [comment]
Thanks! :-)

Hm, that's weird, the information should be loaded from the one instance and should be reloaded on every start (and every hour or so). Could you please try restarting your service?

**Comment by Sky12019** [comment]
Hi there!
This is on a windows machine that auto-restarts every day, so the service is restarting normally.
I am open to your ideas.
Cheers!

**Comment by trsmith78** [comment]
Hello,
I have the same setup as mentioned above.  I too am getting the warning.
I've restarted several times.
I have the same version of Java installed. (build 1.8.0_351-b10)

**Comment by aphelion1** [comment]
i am also having this problem, what the message means? we will need in the future use java 17? or it is just a mistake, because i don't want delete or reconfig my settings again in the future, i tried also installing java 19, but obviously it doesn't work because the app is made for java 8, very weird message

**Comment by theotherp** [comment]
@Sky12019 @trsmith78 Please confirm it's fixed.

@aphelion1 You need to install Java 17 in order for future updates to work.

**Comment by Sky12019** [comment]
Sorry. 
Same message...

![Capture](https://user-images.githubusercontent.com/56899277/207728713-02f1b9d6-18b0-478b-9402-b225bd83965e.JPG)

**Comment by Sky12019** [comment]
Could it be that I am running java x86 on a x64 system?

**Comment by ipkpjersi** [comment]
If you guys aren't running Java 17 or above for nzbhydra2, I'd imagine that's why you're getting the message.

**Comment by theotherp** [comment]
Please post debug information zips

**Comment by aphelion1** [comment]
i installed java from here `https://adoptium.net/temurin/releases/` and worked and the message doesn't appear anymore, i tried previously installing java 19 from here `https://www.oracle.com/java/technologies/downloads/` and the app didn't open, i guess both are not the same

**Comment by theotherp** [comment]
No, Java 17 is not the same as Java 19 which is why it says you need to
install Java 17 :-)

Java programs are designed to run a certain java version. Usually all
versions equal or higher than that can run them but in some cases newer
versions won't work which seems to be the case. To be honest I never tested
Java 19 as 17 is new enough and newer ones are not necessarily better or
more secure. Many, many java programs (in banking, manufacturing, etc.)
still run Java 8.

**Comment by Sky12019** [comment]
Hi once again.
I downloaded the msi installer for x64 version Windows from https://adoptium.net/temurin/releases/ and ran it.
I then restarted nzbhydra service and am still getting the error. 
There is an option in the installation process about changing the variable for JAVA_HOME that I didn't select since it comes inactive  by default. Maybe I must select it?

**Comment by ipkpjersi** [comment]
This is working as expected for me on Ubuntu 22.04 Linux with Java 17 modifying the systemd service file to point to Java 17 as a parameter.

**Comment by MrMxyzptlk** [comment]
I get the same thing as well. 
Running the latest Java on Windows Server 2019 with latest NZBHydra 2.

**Comment by theotherp** [comment]
@MrMxyzptlk What is "the same thing"? What is your java version? If "the latest" is 19 you need to install 17.

**Comment by ipkpjersi** [comment]
The latest Java is not 17, are you running Java 17 or newer than 17? If you are running Java 17 you shouldn't be getting the popup, otherwise you will get the popup.

**Comment by MrMxyzptlk** [comment]
OK.

**Comment by Sky12019** [comment]
Hi guys.
Quick update: On Windows 10; I had to install java 17 from https://adoptium.net/temurin/releases/ and remove my previous installation so that environment variables could point to the new java path.
After restarting Windows, nzbhydra2 is running fine!

Thanks for the help @theotherp

**Comment by theotherp** [comment]
Glad you got it working.
