### ISSUE TITLE
nzbhydra won´t start - possible java issue

### ISSUE THREAD

**Issue by dragonsclaw2nd** [theotherp/nzbhydra2#811]
First I want to thank theotherp for his hard work and this really helpful tool. It is much appreciated!

unfortunately since 2 days nzbhydra will not start anymore. Just before update to latest version was performed via auto updater sucessfully. After next restart of the machine the programm didn´t start anymore as it did before the update for month. Apart from hydra no new programm was installed.

wrapper log says:

`2022-12-20 11:13:42,658  INFO - Determined java version as '17' from version string 'openjdk version "17.0.5" 2022-10-18'
2022-12-20 11:13:42,660  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=C:\Program Files\Nzbhydra2\data\logs -jar C:\Program Files\Nzbhydra2\lib\core-4.7.4-exec.jar --datafolder C:\Program Files\Nzbhydra2\data in folder C:\Program Files\Nzbhydra2
2022-12-20 11:13:43,094  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
`

error message if I used wrapper command is

`C:\Users\**********>java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=C:\Program Files\Nzbhydra2\data\logs -jar C:\Program Files\Nzbhydra2\lib\core-4.7.4-exec.jar --datafolder C:\Program Files\Nzbhydra2\data restarted in folder C:\Program Files\Nzbhydra2
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Fehler: Hauptklasse Files\Nzbhydra2\data\logs konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: Files\Nzbhydra2\data\logs`

machine is windows 10 x64 which is regulary restarted. I used the search and tried the following fixes:

- update Java
- removed and reinstalled java (java 8 which worked before, JDK 17 from official site) several times with restarts before and after each un/-install
- removed java from official site and used https://adoptium.net/de/temurin/releases/ JDK 17 version as recommended in other cases
- started with complete new hydra setup with old setup backed up but with same error

I am out of ideas what to do. If any logs are required please tell me and I will upload. As I cannot access the programm I cannot change any log settings

**Comment by theotherp** [comment]
Don't install hydra in the programs folder. Please move it somewhere else.
Make sure the whole folder path does not contain a space. Usually the space
gets escaped but apparently not in this case.

**Comment by dragonsclaw2nd** [comment]
Wow that kind of a speedy and fully working solution is impressive! 
Transferred the install folder and everything works fine now. I am still wondering why it stoped working after month of no problems, but as it works now this is just a academic discussion...

Thanks for the quick answer and keep up the great work.
