### ISSUE TITLE
BUG - v5 won't open - "Failed to execute script nzbhydra2wrapperWindows"

### ISSUE THREAD

**Issue by ewan58385** [theotherp/nzbhydra2#818]
Upon installing V5 on Windows 11, NZBHydra2 won't open with an error message "Failed to execute script nzbhydra2wrapperWindows". I would expect the program to open the WEBUi and show the "add indexer" screen. I have, of course, installed the correct version of Java17. I can't find the Log file - presumably because it hasn't created one yet as this error prevents the application from running. The latest v4 release works just fine.

**Comment by theotherp** [comment]
Try running the console window exe, it should work for now.

**Comment by ewan58385** [comment]
I didn't read your updating from 4.x.x to 5.x.x, and thus realize you don't need Java 17. Regardless, running the console version worked fine for me. Thanks for your quick response.

**Comment by theotherp** [comment]
5.0.1 should hopefully work

**Comment by theotherp** [comment]
I'm closing this, sorry for the inconvenience.
