### ISSUE TITLE
V5 Issue - Ubuntu Linux - Failed to start NZBHydra2 Daemon.

### ISSUE THREAD

**Issue by myopenflixr** [theotherp/nzbhydra2#821]
Hello,

New version installed according to instructions but nzbhydra service fails after starting.

I deleted the lib folder.
I downloaded the nzbhydra2-5.0.0-linux.zip and extracted in my nzbhydra2 folder.
I had to run the following command to make these two files executable: `chmod +x nzbhydra2 core`
Verified ownership of the nzbhydra2 folder and it's contents are `nzbhydra:nzbhydra`

Here's my startup script:
```
[Unit]
Description=NZBHydra2 Daemon
Documentation=https://github.com/theotherp/nzbhydra2
After=network.target

[Service]
# Create this user by running: adduser --system --group nzbhydra
User=nzbhydra
Group=nzbhydra
Type=simple
# Set to the folder where you extracted the ZIP
WorkingDirectory=/opt/nzbhydra2
# NZBHydra stores its data in a "data" subfolder of its installation path
# To change that set the --datafolder parameter:
# --datafolder /var/local/lib/nzbhydra
ExecStart=/opt/nzbhydra2/nzbhydra2 --nobrowser
Restart=always

[Install]
WantedBy=multi-user.target
```

Here's the only relative log entry:
`2023-01-20 12:23:00,751  INFO - Starting NZBHydra main process with command line: ./core -Xmx1024M -DfromWrapper=true -DinternalApiKey=epwxxfbqgfuirxwerygp -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /opt/nzbhydra2/data in folder /opt/nzbhydra2`
`2023-01-20 12:23:01,637  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it`

Here's the error message after running `service nzbhydra status`
```
nzbhydra.service - NZBHydra2 Daemon
     Loaded: loaded (/lib/systemd/system/nzbhydra.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-01-20 12:23:01 EST; 4min 16s ago
       Docs: https://github.com/theotherp/nzbhydra2
    Process: 6657 ExecStart=/opt/nzbhydra2/nzbhydra2 --nobrowser (code=exited, status=255/EXCEPTION)
   Main PID: 6657 (code=exited, status=255/EXCEPTION)
        CPU: 1.103s

Jan 20 12:23:01 NZBHydra systemd[1]: nzbhydra.service: Consumed 1.103s CPU time.
Jan 20 12:23:01 NZBHydra systemd[1]: nzbhydra.service: Scheduled restart job, restart counter is at 5.
Jan 20 12:23:01 NZBHydra systemd[1]: Stopped NZBHydra2 Daemon.
Jan 20 12:23:01 NZBHydra systemd[1]: nzbhydra.service: Consumed 1.103s CPU time.
Jan 20 12:23:01 NZBHydra systemd[1]: nzbhydra.service: Start request repeated too quickly.
Jan 20 12:23:01 NZBHydra systemd[1]: nzbhydra.service: Failed with result 'exit-code'.
Jan 20 12:23:01 NZBHydra systemd[1]: Failed to start NZBHydra2 Daemon.
```

Any suggestions or anything else I can do to help troubleshoot?

**Comment by theotherp** [comment]
Please post the nzbhydra.log file from the data/logs folder.

**Comment by myopenflixr** [comment]
The only similarly named log file I have is nzbhydra2.log and it hasn't been written to for several days. The only log file that is getting written to is wrapper.log and nzbhydra2-log.json.

The log entry I included above was from wrapper.log. That same entry repeats every time I try to restart.

**Comment by theotherp** [comment]
What do you get when you run the executable directly from the console?

If you have auth enabled that is the reason. There's a bad bug. You can switch to the generic release or try to move back to 4.7.6

**Comment by myopenflixr** [comment]
Here's the error when executing from command line:
```
Logging wrapper output to /opt/nzbhydra2/data/logs/wrapper.log
2023-01-20 12:53:57,872  INFO - Determined release type: native
2023-01-20 12:53:57,876  INFO - Starting NZBHydra main process with command line: ./core -Xmx1024M -DfromWrapper=true -DinternalApiKey=vbsryxhdxflescrqxcxt -Dspring.output.ansi.enabled=ALWAYS --datafolder /opt/nzbhydra2/data in folder /opt/nzbhydra2
./core: /tmp/_MEItILgrD/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
2023-01-20 12:53:58,741  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
```

If it makes any difference, I'm running Ubuntu 20.04.5

Do you recommend I try the generic release or go back to 4.7.6? I can easily restore from a Proxmox Snapshot in a matter of seconds to go back to previous version.

**Comment by theotherp** [comment]
That's the same as https://github.com/theotherp/nzbhydra2/issues/819
No idea why this happens, I ran the binary on Ubuntu 20.04 and 22.04 without problems.

I'd say switch to generic until the next update. That way at least you will have all the other improvements in the code.

**Comment by myopenflixr** [comment]
OK. I'll try the generic version and report back

**Comment by myopenflixr** [comment]
The link for the generic version isn't working...Comes back as `not found`

**Comment by RhvsW** [comment]
He's pulled the release at the minute due to the issues going on

**Comment by theotherp** [comment]
Yeah I forgot about that, sorry

**Comment by ich777** [comment]
@theotherp can you please tell me why you've deleted the 5.0.0 release? I've already customized my container and now it is broken again. :rofl: 
Please re-upload it again or delete the [Tag](https://github.com/theotherp/nzbhydra2/releases/tag/v5.0.0) too if possible.

**Comment by myopenflixr** [comment]
I've downgraded to 4.7.6 for now. I'll keep an eye out for 5.0.0 to be re-released

**Comment by RhvsW** [comment]
> can you please tell me why you've deleted the 5.0.0 release

because the release is broken? hope you're joking.

**Comment by theotherp** [comment]
Please downgrade to 4.7.6. You'll need to use the last backup because the database is not backwards compatible.

5.0.0 seems to work when auth is not enabled

**Comment by ich777** [comment]
@theotherp can you please delete the Tag too for version 5.0.0 like mentioned above?

**Comment by ich777** [comment]
> > can you please tell me why you've deleted the 5.0.0 release
> 
> because the release is broken? hope you're joking.

Had no issues after it was running. 😉

**Comment by theotherp** [comment]
@ich777 If you don't have auth enabled it works fine

**Comment by theotherp** [comment]
> @theotherp can you please delete the Tag too for version 5.0.0 like mentioned above?

Done

**Comment by ich777** [comment]
@theotherp Danke! :)

**Comment by theotherp** [comment]
Bitte

**Comment by myopenflixr** [comment]
I installed 5.0.1 and got it working.

HOWEVER.....Dark theme is NOT working. It reverts to bright theme when chosen and everything is misaligned. White theme is also misaligned. Gray theme seems to be working as expected.

**Comment by myopenflixr** [comment]
Found another error.

When searching for a movie, it used to automatically show potential search options along with movie posters. Now when I type a movie to search for, I instantly get an error that looks like this
![error](https://user-images.githubusercontent.com/33140130/213808551-357b2880-d131-4e6f-99e1-167389021335.jpg)

**Comment by theotherp** [comment]
Hm that's really weird as that's actually something I explicitly test in my pipeline.

**Comment by theotherp** [comment]
It's also something I can't reproduce. Please post your debug infos

**Comment by ich777** [comment]
> Dark theme is NOT working. It reverts to bright theme when chosen and everything is misaligned. White theme is also misaligned. Gray theme seems to be working as expected.

Can't confirm:
![grafik](https://user-images.githubusercontent.com/28066518/213808947-078d289e-332e-475b-a6bc-6f3139570d9d.png)

Everything is working just fine over here.



> When searching for a movie, it used to automatically show potential search options along with movie posters. Now when I type a movie to search for, I instantly get an error that looks like this

Seems to also work fine over here:
![grafik](https://user-images.githubusercontent.com/28066518/213809093-0abff69e-21a8-4d16-9ca7-6f26630d4e01.png)

**Comment by theotherp** [comment]
Glad it's working for someone ;-) Thanks for the feedback @ich777

**Comment by theotherp** [comment]
Looks like it's happening when a URL base is defined.

**Comment by theotherp** [comment]
Ok, found the issue, I think

**Comment by myopenflixr** [comment]
I'm using Nginx reverse proxy. Works fine with local IP (including URL base). But not working with www.mydomain/nzbhydra

**Comment by ich777** [comment]
> Glad it's working for someone ;-) Thanks for the feedback @ich777

I have to say thank you that you've put this all together. :)

**Comment by myopenflixr** [comment]
> > Dark theme is NOT working. It reverts to bright theme when chosen and everything is misaligned. White theme is also misaligned. Gray theme seems to be working as expected.
> 
> Can't confirm: ![grafik](https://user-images.githubusercontent.com/28066518/213808947-078d289e-332e-475b-a6bc-6f3139570d9d.png)
> 
> Everything is working just fine over here.
> 
> > When searching for a movie, it used to automatically show potential search options along with movie posters. Now when I type a movie to search for, I instantly get an error that looks like this
> 
> Seems to also work fine over here: ![grafik](https://user-images.githubusercontent.com/28066518/213809093-0abff69e-21a8-4d16-9ca7-6f26630d4e01.png)

Movie search results work fine using localip/URL BASE.....but Dark mode does not.

Neither working as expected when accessing via nginx reverse proxy

**Comment by ich777** [comment]
@myopenflixr jep, @theotherp is already aware of that and found the cause of the issue.

**Comment by theotherp** [comment]
Please try 5.0.2

**Comment by myopenflixr** [comment]
Trying now....

**Comment by myopenflixr** [comment]
seems to be working as expected.

Dark theme works as does Autocomplete Picture

**Comment by theotherp** [comment]
Awesome

**Comment by theotherp** [comment]
That was a stressful 5 hours

**Comment by myopenflixr** [comment]
Hang on...Think I found a new issue unfortunately.

When I do a search....and then click the icon to "Download NZB", it opens a new web browser and nothing happens.

Again, this is behind Nginx reverse proxy...with URL Base.

When using localip/urlbase, the same action tries to download the nzb file instead of sending it to SABnzbd...

And it looks like the reason is because the upgrade deleted SABznbd as a downloader...readding SAB to see if it works as expected

**Comment by theotherp** [comment]
I think the icon is invisible

**Comment by theotherp** [comment]
Hover the mouse to the right: 
![Uploading image.png…]()

**Comment by myopenflixr** [comment]
Correction...It did NOT delete SAB as a Downloader....However, it's not sending it to SAB, it's opening a new browser and trying to download the NZB file to my local PC

**Comment by myopenflixr** [comment]
Now it's working....I've got too many tabs open!!!

I refreshed the tab i was working with and tried again. It IS sending to SAB...but like you said, the icon is missing

**Comment by theotherp** [comment]
Right, that should be easy to fix and a minor inconvenience for now.

**Comment by myopenflixr** [comment]
Yes, no big deal at the moment. Just need to remember to click the hidden icon :)

**Comment by aarnoud** [comment]
Using 5.0.3, removing `-Xmx256M` in an LXC container allowed to launch, if it can help debug :)

```
plex@plex:/opt/nzbhydra2$ /opt/nzbhydra2/nzbhydra2 --nobrowser
Logging wrapper output to /opt/nzbhydra2/data/logs/wrapper.log
2023-01-21 01:13:16,852  INFO - Determined release type: native
2023-01-21 01:13:16,855  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=wsqxwmufkmhbarctkosa -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /opt/nzbhydra2/data in folder /opt/nzbhydra2
./core: /tmp/_MEIrV7Ep6/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
2023-01-21 01:13:17,534  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
```

```
plex@plex:/opt/nzbhydra2$ ./core -DfromWrapper=true -DinternalApiKey=wsqxwmufkmhbarctkosa -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /opt/nzbhydra2/data in folder /opt/nzbhydra2
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: file [/org/nzbhydra/config/migration/ConfigMigrationStep.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep009to010.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep010to011.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep011to012.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep012to013.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep013to014.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep014to015.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep015to016.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep016to017.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep017to018.class]
01:14:30.691 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/org/nzbhydra/config/migration/ConfigMigrationStep018to019.class]
01:14:30.699 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /opt/nzbhydra2/data/nzbhydra.yml
01:14:30.727 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing config took 34ms
01:14:30.727 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseWriteDelay to 5000
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
01:14:30.734 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
.__   __.  ________  .______   __    __  ____    ____  _______  .______          ___          ___
|  \ |  | |       /  |   _  \ |  |  |  | \   \  /   / |       \ |   _  \        /   \        |__ \
|   \|  | `---/  /   |  |_)  ||  |__|  |  \   \/   /  |  .--.  ||  |_)  |      /  ^  \          ) |
|  . `  |    /  /    |   _  < |   __   |   \_    _/   |  |  |  ||      /      /  /_\  \        / /
|  |\   |   /  /----.|  |_)  ||  |  |  |     |  |     |  '--'  ||  |\  \----./  _____  \      / /_
|__| \__|  /________||______/ |__|  |__|     |__|     |_______/ | _| `._____/__/     \__\    |____|
```

**Comment by myopenflixr** [comment]
@aarnoud Can you post your systemd startup script?

**Comment by aarnoud** [comment]
> @aarnoud Can you post your systemd startup script?

```
plex@plex:/opt/nzbhydra2$ diff -Nru systemd/nzbhydra2.service /etc/systemd/system/nzbhydra2.service
--- systemd/nzbhydra2.service	2023-01-07 10:46:47.069422924 +0100
+++ /etc/systemd/system/nzbhydra2.service	2021-12-31 15:07:53.217127613 +0100
@@ -5,8 +5,8 @@
 
 [Service]
 # Create this user by running: adduser --system --group nzbhydra
-User=nzbhydra2
-Group=nzbhydra2
+User=plex
+Group=plex
 Type=simple
 # Set to the folder where you extracted the ZIP
 WorkingDirectory=/opt/nzbhydra2
 ```

**Comment by myopenflixr** [comment]
here's my nzbhydra2.service file that is working just fine

Adjust `User` & `Group` to match your config as well as the `WorkingDirectory`. Double check the user & Group permissions for your nzbhydra2 directory. They need to match.




```
[Unit]
Description=NZBHydra2 Daemon
Documentation=https://github.com/theotherp/nzbhydra2
After=network.target

[Service]
User=nzbhydra
Group=nzbhydra
Type=simple
WorkingDirectory=/opt/nzbhydra2
ExecStart=/usr/bin/python3 /opt/nzbhydra2/nzbhydra2wrapperPy3.py --nobrowser

Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by aarnoud** [comment]
it works @myopenflixr, thanks for the tip :)

**Comment by myopenflixr** [comment]
@aarnoud Sweet!!!

**Comment by theotherp** [comment]
Awesome, thanks for the help.

**Comment by ich777** [comment]
@theotherp with the release from `5.0.3` are the core libraries not needed anymore from the releases section and you have to start NZBHydra2 with `nzbhydra2wrapperPy3.py`?
Just asking because the `*-core` download over on the release section is only about 50KB and has the same files as the which are in the `*-linux` download.

**Comment by theotherp** [comment]
What do you mean? [50.03](https://github.com/theotherp/nzbhydra2/releases/download/v5.0.3/nzbhydra2-5.0.3-linux.zip) contains the core executable.

**Comment by theotherp** [comment]
Btw, if you have discord feel free to join us there: https://discord.com/invite/uh9W3rd It flows a bit better than communication via comments

**Comment by theotherp** [comment]
Considering this fixed, finally :-)
