### ISSUE TITLE
nzbhydra doesn't connect with imdb 

### ISSUE THREAD

**Issue by aphelion1** [theotherp/nzbhydra2#823]
i installed the last version, deleted the lib folder and tried to search a movie, and it shows me this: 

An error occurred:
undefined: undefined

Message: undefined

when i try to type the movie i get that message, anyway in some way i tried to search something and worked, search works i got results but i doesn't connect or search in imdb which is very important for movies

**Comment by theotherp** [comment]
For god's sake, please post the debug infos zip or at least an excerpt from the log.

**Comment by aphelion1** [comment]
i am doing that, in log/raw do you need everthing from there right?

**Comment by theotherp** [comment]
Best is to create the debug infos zip via UI. If that doesn't work attach the lines in `nzbhydra.log` that are logged around the time of the error

**Comment by aphelion1** [comment]
i uploaded debug infos
`https://we.tl/t-7gVTVFl8rm`

**Comment by theotherp** [comment]
Ok, I can reproduce that.

**Comment by theotherp** [comment]
Try refreshing the browser cache using Ctrl+F5. That was a weird one.

**Comment by aphelion1** [comment]
thank you very much works now
