### ISSUE TITLE
Reverse Proxy Fails After 5.x Upgrade

### ISSUE THREAD

**Issue by BzowK** [theotherp/nzbhydra2#828]
Hey Guys - 

First of all, I love NZBHydra2 - Thanks for your work on it!

I manually upgraded to 5.1.0 tonight and after doing so, can no longer access NZBHydra via reverse proxy.  When I browse to the local URL I typically use, I simply get "HTTP Status 404 – Not Found."  Browsing using the local IP /w port works fine so assume something in 5.x requires different RP config.  Below are all the deets...

Platform: Windows 10 x64
Upgrade Procedure (4.x -> 5.1.0):

- Stopped NZBHydra2 Service
- Backed up NZBHydra2 folder
- Deleted "lib" folder
- Extracted 5.1.0 into folder overwriting files
- Started NZBHydra Service

Troubleshooting:
- Restarted nginx service
- Restarted computer
- No errors in nginx log

nginx Reverse Proxy Config (for NZBHydra)
_Note: nginx applies 3rd part signed cert to domain name_
		location /search {	
			proxy_pass http://192.168.0.35:5076/search/;
			proxy_set_header        X-Real-IP			$remote_addr;
			proxy_set_header        Host				$host;
			proxy_set_header        Scheme				$scheme;
			proxy_set_header        X-Forwarded-For		$proxy_add_x_forwarded_for;
			proxy_set_header        X-Forwarded-Proto	$scheme;
			proxy_set_header        X-Forwarded-Host	$host;
			proxy_set_header 		Upgrade 			$http_upgrade;
			proxy_set_header 		Connection 			"upgrade";
			proxy_redirect off;
		}

I'm trying some general configs and will update if a solution if found - Thanks!

**Comment by theotherp** [comment]
Huh, that's the first I've heard of this so it must be something specific - many users have reverse proxies going, including myself.

So, dumb question - you can connect to hydra using `http://192.168.0.35:5076/search/`?

Please try removing the trailing slash there, so `proxy_pass http://192.168.0.35:5076/search;`.

**Comment by BzowK** [comment]
Hey - 

Removing the trailing slash on the proxy_pass line seemed to do the trick!  Interesting.  Thanks for the suggestion!

**Comment by theotherp** [comment]
I've added a comment to the wiki to indicate this. I remember this causing troubles years ago but something in the framework changed which prevents trailing slashes in URL from being resolved.
