### ISSUE TITLE
"Undefined" error instead of autocomplete results when searching for TV show or movie 

### ISSUE THREAD

**Issue by GabeR9000** [theotherp/nzbhydra2#829]
[nzbhydra-debuginfos-2023-01-24-02-39.zip](https://github.com/theotherp/nzbhydra2/files/10487321/nzbhydra-debuginfos-2023-01-24-02-39.zip)

When i change the search criteria to TV and start typing in a show name, I get an undefined error message and it doesnt provide a list of show options. Entering a season number doesnt provide results for that season exclusively.

**Comment by theotherp** [comment]
Press ctrl + f5

**Comment by GabeR9000** [comment]
> Press ctrl + f5
> […](#)

Does that work for Macs?

**Comment by theotherp** [comment]
The OS doesn't matter but the browser. See here:
https://www.howtogeek.com/672607/how-to-hard-refresh-your-web-browser-to-bypass-your-cache/

**Comment by theotherp** [comment]
Sorry, obviously the OS matters as you don't have a ctrl key...

**Comment by theotherp** [comment]
I have renamed the ticket and will keep it open because this seems to affect a lot of people although I don't understand why.

**Comment by GabeR9000** [comment]
> I have renamed the ticket and will keep it open because this seems to affect a lot of people although I don't understand why.

It actually worked for me. Using Safari on Mac "Command+ Option+ E followed by holding Shift & click reload". No longer getting an error message. 

Thanks!

**Comment by theotherp** [comment]
Should be fixed with latest release.
