### ISSUE TITLE
Healthcheck/ping endpoint

### ISSUE THREAD

**Issue by modem7** [theotherp/nzbhydra2#837]
* What do you want to happen?
A Healthcheck/ping endpoint. Something like `/health` or `/ping` to be exposed unauthenticated. 
* If not clear, why do you want it? 
This will make both internal and external healthchecks a lot easier.
* Do you think it's something only you need or something that might be popular? 
Popular, especially with Docker

**Comment by theotherp** [comment]
I mean, if you curl it and get a 401 it's healthy enough to ask for auth.

But I could make /actuator/health/ping public.

**Comment by modem7** [comment]
> I mean, if you curl it and get a 401 it's healthy enough to ask for auth.
> 
> But I could make /actuator/health/ping public.

That would be ace!

To give a slightly more in depth use case: I currently have hydra behind authelia, and use an uptime monitor.

For the link, if I give just the hydra URL, it'd get the status of authelia rather than hydra itself.

But from another aspect, healthchecks in docker wouldn't have to curl the entire page, but instead a much smaller endpoint, which would make things somewhat neater.

Thanks!

**Comment by theotherp** [comment]
You can call `/actuator/health/ping` in 5.1.2

**Comment by modem7** [comment]
Thank you!
