### ISSUE TITLE
Allow bypassing checksum with a flag

### ISSUE THREAD

**Issue by John-Gee** [theotherp/nzbhydra2#839]
* What do you want to happen?
It'd be nice to be able bypass the check,  or simply hide the banner that pops up  about it with a toggle.
* If not clear, why do you want it?
We're currently distributing nzbhydra2 through AUR on Arch with some patches to the  py3 wrapper.
* Do you think it's something only you need or something that might be popular?
I think having more toggles could be useful for others.
* If not clear, explain the use case.
Not sure  if it's the best way, but right now we  have to ship the OG wrapper and a renamed copy aside to not have these warnings.
There could be  other toggles we would ask for, but let's start simpler.

Thanks!

**Comment by theotherp** [comment]
Can be disabled by setting the environment variable `NZBHYDRA_DISABLE_WRAPPER_CHECK` in 5.1.2

**Comment by John-Gee** [comment]
Awesome, I look forward to 5.1.2.

Thank you!
