### ISSUE TITLE
Categorized watch folders for torrents?

### ISSUE THREAD

**Issue by Metigoth** [theotherp/nzbhydra2#84]
**Feature Request**

Add subfolders or separate folders for blackhole watch folders for rutorrent autotools watch folders.
eg. 

- /autowatch/tv/

- /autowatch/movies

- /autowatch/comics

- /autowatch/ebooks

**Comment by theotherp** [comment]
That would require you to select a folder manually whenever you click to download a file.

**Comment by theotherp** [comment]
I would need to add a mapping from category to folder. That would make the config even more complicated.

**Comment by theotherp** [comment]
Sorry, to much work and too complicated.
