### ISSUE TITLE
Updating from 4.x to 5.x - Hydra fails to start up

### ISSUE THREAD

**Issue by silkw0rm** [theotherp/nzbhydra2#845]
I'm running Hydra on a Solid Run Cubox-i with Debian OS and I've done so happily for many years.
I tried to do the manual update to from 4.x to 5.x with the latest version, 5.1.2 and following the update instructions.
But after deleting the "lib" directory and copying over the files from the arm64-archive, I can get Hydra to start up at all.

Architecture is reported as : armv7l
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

I've been starting it with 
```
/etc/systemd/system/nzbhydra2.service

[Unit]
Description=NZBHydra2 Daemon
Documentation=https://github.com/theotherp/nzbhydra2
After=network.target

[Service]
User=debian
Group=debian
Type=simple
# Set to the folder where you extracted the ZIP
WorkingDirectory=/opt/nzbhydra2


# NZBHydra stores its data in a "data" subfolder of its installation path
# To change that set the --datafolder parameter:
# --datafolder /path-to/datafolder
ExecStart=/usr/bin/python /opt/nzbhydra2/nzbhydra2wrapper.py --nobrowser

Restart=on-failure

[Install]
WantedBy=multi-user.target

```
My Linux skills are not that good, so I don't know where to look for more logfiles or debug info but nothing is written in neither the nzbhydra2.log or wrapper.log since the application never makes it this far.

This is the result after checking with "systemctl -l status nzbhydra2"

```
● nzbhydra2.service - NZBHydra2 Daemon
   Loaded: loaded (/etc/systemd/system/nzbhydra2.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2023-02-07 15:33:16 CET; 6min ago
     Docs: https://github.com/theotherp/nzbhydra2
  Process: 2400 ExecStart=/usr/bin/python /opt/nzbhydra2/nzbhydra2wrapper.py --nobrowser (code=exited, status=1/FAILURE)
 Main PID: 2400 (code=exited, status=1/FAILURE)

Feb 07 15:33:16 sr-imx6 systemd[1]: nzbhydra2.service: Unit entered failed state.
Feb 07 15:33:16 sr-imx6 systemd[1]: nzbhydra2.service: Failed with result 'exit-code'.
Feb 07 15:33:16 sr-imx6 systemd[1]: nzbhydra2.service: Service hold-off time over, scheduling restart.
Feb 07 15:33:16 sr-imx6 systemd[1]: Stopped NZBHydra2 Daemon.
Feb 07 15:33:16 sr-imx6 systemd[1]: nzbhydra2.service: Start request repeated too quickly.
Feb 07 15:33:16 sr-imx6 systemd[1]: Failed to start NZBHydra2 Daemon.
Feb 07 15:33:16 sr-imx6 systemd[1]: nzbhydra2.service: Unit entered failed state.
Feb 07 15:33:16 sr-imx6 systemd[1]: nzbhydra2.service: Failed with result 'exit-code'.

```

**Comment by theotherp** [comment]
Please list the log files from the data folder (/opt/nzbhydra2/logs or
something).

**Comment by silkw0rm** [comment]
[nzbhydra2.2023-02-07.log](https://github.com/theotherp/nzbhydra2/files/10683093/nzbhydra2.2023-02-07.log)
[wrapper.log](https://github.com/theotherp/nzbhydra2/files/10683094/wrapper.log)
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/10683095/nzbhydra2.log)

Please find attached log files. Let me know if there is any other files or information that I can provide. 
Thanks in advance.

**Comment by theotherp** [comment]
I don't see anything in the logs. Perhaps the executable itself cannot start. Can you try running `/usr/bin/python /opt/nzbhydra2/nzbhydra2wrapper.py` in your console and see what happens?

You can always fall back to the generic release which contains all the features of 5.x without the performance improvements - which you've donehappily for many years  ;-)

**Comment by silkw0rm** [comment]
Tried starting and it gives me this:

```
@sr-imx6:~$ /usr/bin/python /opt/nzbhydra2/nzbhydra2wrapper.py
Traceback (most recent call last):
  File "/opt/nzbhydra2/nzbhydra2wrapper.py", line 582, in <module>
    args, unknownArgs = parser.parse_known_args(arguments)
NameError: name 'arguments' is not defined

```

**Comment by silkw0rm** [comment]
I'm getting the same error using the generic release as well.

**Comment by theotherp** [comment]
Run `/usr/bin/python /opt/nzbhydra2/nzbhydra2wrapperPy3.py`, you may be using python 3? Otherwise I can't explain it as that isn't something that was changed lately.

**Comment by silkw0rm** [comment]
I don't belive so, this is how it looks when starting Hydra successfully on the old version 4.7.6
```
@sr-imx6:~$ systemctl -l status nzbhydra2
● nzbhydra2.service - NZBHydra2 Daemon
   Loaded: loaded (/etc/systemd/system/nzbhydra2.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2023-02-08 11:06:31 CET; 27min ago
     Docs: https://github.com/theotherp/nzbhydra2
 Main PID: 13110 (python)
    Tasks: 31 (limit: 4915)
   CGroup: /system.slice/nzbhydra2.service
           ├─13110 /usr/bin/python /opt/nzbhydra2/nzbhydra2wrapper.py --nobrowser
           └─13130 java -Xmx512M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/nzbhydra2/data/logs -Dspring.output.ansi.enabled=ALWAYS -jar /opt/nzbhydra2/lib/core-4.7.6-exec.jar --
nobrowser --datafolder /opt/nzbhydra2/data
```

**Comment by theotherp** [comment]
Try 
[nzbhydra2wrapper.zip](https://github.com/theotherp/nzbhydra2/files/10684570/nzbhydra2wrapper.zip)

**Comment by theotherp** [comment]
I think it's actually broken and you're one of the few remaining people to use the python 2 version.

**Comment by silkw0rm** [comment]
```
@sr-imx6:~$ /usr/bin/python /opt/nzbhydra2/nzbhydra2wrapper.py
/opt/nzbhydra2/nzbhydra2wrapper.py:555: SyntaxWarning: name 'args' is assigned to before global declaration
  global args, unknownArgs, args
/opt/nzbhydra2/nzbhydra2wrapper.py:555: SyntaxWarning: name 'unknownArgs' is assigned to before global declaration
  global args, unknownArgs, args
/opt/nzbhydra2/nzbhydra2wrapper.py:555: SyntaxWarning: name 'args' is assigned to before global declaration
  global args, unknownArgs, args
Traceback (most recent call last):
  File "/opt/nzbhydra2/nzbhydra2wrapper.py", line 583, in <module>
    args, unknownArgs = parser.parse_known_args(arguments)
NameError: name 'arguments' is not defined

```

**Comment by silkw0rm** [comment]
Ok, I've been planning to do a new installation with Debian Bullseye, so maybe leave this as it is for now, if there isn't any easy fix for it.

**Comment by theotherp** [comment]
[nzbhydra2wrapper.zip](https://github.com/theotherp/nzbhydra2/files/10684743/nzbhydra2wrapper.zip)

That should actually work (better)

**Comment by silkw0rm** [comment]
When trying to start with arm64 release (lib folder deleted):

`@sr-imx6:~$ /usr/bin/python /opt/nzbhydra2/nzbhydra2wrapper.py
Logging wrapper output to /opt/nzbhydra2/data/logs/wrapper.log
2023-02-08 12:18:48,513  CRITICAL - Unable to determine the release type. Neither lib folder nor core(.exe) found
`

**Comment by theotherp** [comment]
So do you have the `core` file in there?

**Comment by silkw0rm** [comment]
I got it running with the generic release. The DB migration seems to went ok.
The only thing I could pick up in the logs is following but that might be expected?

```
The NZBHydra wrappers (i.e. the executables or python scripts you use to run NZBHydra) seem to be outdated. Please update them:
Shut down NZBHydra, download the latest version and extract *all files* into your main NZBHydra folder (overwriting all). Start NZBHydra again.
```

**Comment by theotherp** [comment]
Yeah that should be fixed with the next release.
