### ISSUE TITLE
Add more toggles

### ISSUE THREAD

**Issue by John-Gee** [theotherp/nzbhydra2#847]
* What do you want to happen?
  Following #839 I'm creating a new FR for more toggles.
Instead of bothering you with text, I'm hopeful code will make more sense so here are the patches that we carry which would be nice as toggles instead:
https://aur.archlinux.org/cgit/aur.git/plain/wrapper-remove-base-path-checks.patch?h=nzbhydra2-nojava-bin
https://aur.archlinux.org/cgit/aur.git/plain/wrapper-remove-release-type-detection.patch?h=nzbhydra2-nojava-bin
https://aur.archlinux.org/cgit/aur.git/plain/wrapper-remove-update-support.patch?h=nzbhydra2-nojava-bin
* If not clear, why do you want it?
  I'd rather be as close to upstream as possible without carrying extra patches.
* Do you think it's something only you need or something that might be popular?
  It's possible other package maintainers would like those too.

Thank you!

**Comment by theotherp** [comment]
Will look into it. I might have to change the wrappers anyway.

**Comment by theotherp** [comment]
What's the purpose of the first one?

**Comment by theotherp** [comment]
I read the comments on https://aur.archlinux.org/packages/nzbhydra2-nojava-bin. Not sure I understand everything but all right.

`NZBHYDRA_DISABLE_UPDATE_ON_SHUTDOWN`
`NZBHYDRA_FORCE_GENERIC`
`NZBHYDRA_USE_BASE_PATH_FOR_LIBS` 

Please verify: 
[nzbhydra2wrapperPy3.zip](https://github.com/theotherp/nzbhydra2/files/10687860/nzbhydra2wrapperPy3.zip)

**Comment by theotherp** [comment]
If it's not right just adapt it and post it.

**Comment by John-Gee** [comment]
Thank you for the quick update!

Are you sure about the wrapper you posted? diff shows no difference with the one from 5.1.2.

**Comment by theotherp** [comment]
Oops 
[nzbhydra2wrapperPy3.zip](https://github.com/theotherp/nzbhydra2/files/10689926/nzbhydra2wrapperPy3.zip)

**Comment by John-Gee** [comment]
Yup that works!

I also needed the NZBHYDRA_USE_BASE_PATH . :)

A few notes:

- readme = os.path.join(basePath, "readme.md") could go behind the check for the env var, not a big deal though
- I feel like I have to set NZBHYDRA_USE_BASE_PATH to false, whether I have  to set NZBHYDRA_USE_BASE_PATH_FOR_LIBS to true. I know you just check if they're set, but the it's the names.


Thank you!

**Comment by theotherp** [comment]
I've renamed it to `NZBHYDRA_SKIP_BASE_PATH_CHECK`.

**Comment by John-Gee** [comment]
Thank you!

**Comment by theotherp** [comment]
There it is.

**Comment by John-Gee** [comment]
Hey, I could be wrong but it does not seem that .5 has NZBHYDRA_FORCE_GENERIC or anything similar. Did you change that?

Thank you!

**Comment by John-Gee** [comment]
Actually updating  to .6, I realize another toggle is missing.  Those are:

NZBHYDRA_DISABLE_WRAPPER_CHECK
NZBHYDRA_FORCE_GENERIC

(since FORCE_GENERIC needed a value, maybe that was the wrong name too?)

Thank you!

**Comment by theotherp** [comment]
`NZBHYDRA_DISABLE_WRAPPER_CHECK` is in there but the main process doesn't inherit the environment variables from the wrapper.
`NZBHYDRA_SKIP_BASE_PATH_CHECK` is indeed missing. No idea what happened there. 

Sorry about that.

**Comment by theotherp** [comment]
I have multiple copies of the file, only one being tracked by git. I had changed the wrong one :-(

**Comment by theotherp** [comment]
Does it work now?

**Comment by John-Gee** [comment]
Yup it's fine, thanks a lot!
