### ISSUE TITLE
nzbhydra2 can't start

### ISSUE THREAD

**Issue by Xor-van-Dorf** [theotherp/nzbhydra2#848]
Hi,

Application doesn't want to start since this morning (since the auto update I'm guessing). I tried earlier version and still the same problem:

ERROR --- [              main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer': Found non-empty schema(s) "PUBLIC" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.

System: Ubuntu Server 22.04 (no docker). Executing the wrapper yield the same result.
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/10703033/nzbhydra2.log)

**Comment by theotherp** [comment]
Something is wrong with the database but hard to say why it happened. Easiest fix would be to delete the database folder. You'd lose history and stats but no settings.

**Comment by Xor-van-Dorf** [comment]
I deleted the database and it started fine. Weird, because the database is brand new. All is fine now! Thanks.
