### ISSUE TITLE
Error while communicating with indexer Drunken Slug. Server returned: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by PearsonFlyer** [theotherp/nzbhydra2#85]
I'm on version 1.1.4 (Windows), and began getting this error on most of my usenet indexers when a search occurs.

**Comment by theotherp** [comment]
Please post the debug infos.

**Comment by PearsonFlyer** [comment]
I did just update Java on that machine the day prior. That likely messed it up. I'll see if I can roll that back, and keep from updating it.

Thank you!

**Comment by PearsonFlyer** [comment]
Rolling back to JRE 8.151 fixed it. For at least those using windows, don't update to JRE 8.161 would be my recommendation.

**Comment by theotherp** [comment]
Thanks for the info.

**Comment by theotherp** [comment]
I can access DS and NZBGeek without issues with 1.8.161

**Comment by Elenedeath** [comment]
hello, i have this error on a fresh installation of nzbhydra2 and openjdk11 on  debian 9.7

openjdk are installed via apt-get

openjdk-11-jdk/stretch-backports,now 11.0.1+13-2~bpo9+1 amd64  [installé]
  OpenJDK Development Kit (JDK)

java -version
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Debian-2bpo91)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Debian-2bpo91, mixed mode, sharing)
```

[log.zip](https://github.com/theotherp/nzbhydra2/files/2805397/log.zip)
