### ISSUE TITLE
BUG (maybe?) - OutdatedWrapperDetector and crash on reinstallation

### ISSUE THREAD

**Issue by dma9** [theotherp/nzbhydra2#865]
Recently noticed something in the logs about using an outdated version. The version I thought I had installed (and what shows in the UI) is 5.1.8. My recollection is that I had simply downloaded and installed that version from Github shortly after it came out. In any event, what I see in the logs is the following:

`OutdatedWrapperDetector - Outdated file: nzbhydra2. Hash: b0191c8ad3258086ccc8c382e69772ba2a00a0af

OutdatedWrapperDetector - The NZBHydra wrappers (i.e. the executables or python scripts you use to run NZBHydra) seem to be outdated. Please update them: Shut down NZBHydra, download the latest version and extract *all files* into your main NZBHydra folder (overwriting all). Start NZBHydra again.`

Everything still seems to work despite the warning message (except for a problem with a constantly growing and huge database, which I'm in the process of separately trying to figure out). However, when I try following the recommended actions, when I start the NZBHydra2 service,  it more or less immediately exits. Journalctl doesn't provide much detail other than stating that the service terminated. Nothing is written to the NZBHydra2 logs, presumably because it crashes so quickly. I tried reinstalling both the AMD64 version and the generic version. Both times same result. 

I would be grateful for any suggestions on how to address the above, or for that matter if it's even necessary to do so given that things still seem to be working.

**Comment by theotherp** [comment]
Unfortunately the compiled file nzbhydra does not currently run on all
distributions. It's easiest if you delete it and run the python wrapper
using python instead. If the file nzbhydra2 does not exist hydra will not
check if it's outdated.

**Comment by dma9** [comment]
Thank you very much. That did the trick. Not sure if it might be helpful but I was running Ubuntu 22.04 in an LXC container.
