### ISSUE TITLE
NZBHydra - Proxy NZB's No Longer working with SAB

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [theotherp/nzbhydra2#871]
Logs: 
[logs.zip](https://github.com/theotherp/nzbhydra2/files/11834350/logs.zip)

Video Demo of the error: https://replay.dropbox.com/share/Ztm59BoPAQfWmsHu

Screens:
<img width="461" alt="Screen Shot 2023-06-22 at 11 12 36 pm" src="https://github.com/theotherp/nzbhydra2/assets/2242880/e180af83-e1fc-44be-be3e-8bf3fd93e961">
<img width="632" alt="Screen Shot 2023-06-22 at 11 12 29 pm" src="https://github.com/theotherp/nzbhydra2/assets/2242880/746ec77f-a4e8-4d56-8314-7635608dbb23">

Config:
<img width="878" alt="Screen Shot 2023-06-22 at 11 12 53 pm" src="https://github.com/theotherp/nzbhydra2/assets/2242880/ee4fca68-78ce-4335-ae89-b0ae1964cfdf">
<img width="1502" alt="Screen Shot 2023-06-22 at 11 12 46 pm" src="https://github.com/theotherp/nzbhydra2/assets/2242880/33824979-6728-46a6-a30d-d7e91bc272b9">

The issue is that the "Proxy NZB's From Indexer" option is no longer working with SAB, If I set to redirect to the indexer its all good, but all indexers that I use now for some reason does not work with the "Proxy NZB's From Indexer" option. 

I'm not sure what is going on here, whether it was some backend update that broke this as I tend to update python, openssl etc.. often.

Current Running Setup:
I'm on an Intel-based mac; 11.7.6
Python 3.11.4
I'm using java JDK ver: 17.0.5 to run hydra
I use the  nzbhydra2wrapperPy3.py wrapper
Sab Ver: 4.0.2 [[3a6f044](https://github.com/sabnzbd/sabnzbd/commit/3a6f044)]

Edit: I've tried earlier versions of python, no change in the bug/issue.

**Comment by theotherp** [comment]
I'm currently on vacation but I'll have a look next week.

**Comment by theotherp** [comment]
Unfortunately for some reason the log stops at 23:16 but the error seems to have occurred at 23:18 so I don' see anything.

Can you reproduce the problem again and post new logs please? Please use the built-in option to generate logs (see the system section, bug report).

**Comment by XxUnkn0wnxX** [comment]
I haven't been able to produce it since the last update 5.1.9, I'm closing the issue for now unless I get it again.
