### ISSUE TITLE
Binsearch "Search in other groups"

### ISSUE THREAD

**Issue by VorlonCD** [theotherp/nzbhydra2#875]
I see this search in the log for Binsearch:
`https://www.binsearch.info/?adv_col=on&postdate=date&adv_sort=date&min=0&max=500&q=The%20Heralds%20of%20Apocalypse%20`

I would like the "**Search in other groups**" option be an option in nzbhydra using the `&server=2` setting:
`https://www.binsearch.info/?q=The+Heralds+of+Apocalypse+&max=100&adv_age=1100&server=&server=2`

Or, just always issue 2 queries?   One without server=2 and one with. 

One reason is when I search for comics they are not found on alt.binaries.comics.dcp until that setting is enabled so I can never find them via nzbhydra.

Thanks!

**Comment by theotherp** [comment]
I could make it configurable in the indexer config.

**Comment by VorlonCD** [comment]
That would be great.  I wish binsearch returned everything by default.  But hey, what am I complaining for its a free service :)

**Comment by VorlonCD** [comment]
Thanks!  Not quite there yet.  Unless this is another bug?

With the update, if I enable "Search in other groups" and search Comics for "**superboy tomorrow**" I get 0 hits.  (For "**Superboy - The Man of Tomorrow**" results)

If I search on binsearch.info site I get 4 hits.

I believe this is because you are sending the space in the URL:

`q=superboy+tomorrow`  (is what Binsearch uses on their site)
`q=superboy%20tomorrow`  (is what you send according to the log)

Even if I search for the exact phrase I'm looking for I dont get any hits:  "Superboy - The Man of Tomorrow":

`q=Superboy+-+The+Man+of+Tomorrow`  (Binsearch)
`q=Superboy%20-%20The%20Man%20of%20Tomorrow`  (NZBHydra)
