### ISSUE TITLE
Custom Mappings: Can't filter properly

### ISSUE THREAD

**Issue by pannal** [theotherp/nzbhydra2#879]
Hey, thank you for this great piece of software.

I'm trying to sanitize queries containing dots, e.g.: "Any Series Name A.B.C." to "Any Series Name".

As far as I can see this currently isn't possible generally. I can add a custom mapping for every show that has dots in it, but not as a generic solution.

Am I missing something?

Thanks!

Edit: This can be used as a workaround, but is limited to three chars with dots trailing the query:
Input pattern: `{title:[^.]+}\.?{trail1:[^.]*}\.?{trail2:[^.]*}\.?{trail3:[^.]*}.*`
Output pattern: `{title}{trail1}{trail2}{trail3}`

**Comment by theotherp** [comment]
Just to be clear - you want to remove "A.B.C" as a suffix from any query
made to hydra?

**Comment by pannal** [comment]
Ideally I'd like to make two fallback queries all the time, even if the initial ID based query matched, and then with and without any dots in the title.

The positioning was only due to the fact that I don't know how to generalize the pattern in hydra.

And no, I want to remove _any_ dots.

**Comment by theotherp** [comment]
So you mean "Any Series Name A.B.C." to "Any Series Name ABC" (or both).

**Comment by pannal** [comment]
Exactly. Or "Peter A. B. Gunther" to "Peter A B Gunther" in addition to the one with the dots.

**Comment by theotherp** [comment]
I've added a switch so that the values may only match parts of the affected string. That way you can remove anything you want from anywhere in the query or title.
