### ISSUE TITLE
Change the wiki to include traefik as reverse proxy. 

### ISSUE THREAD

**Issue by JonasHess** [theotherp/nzbhydra2#891]
Please add these instructions on how to use Traefik as reverse proxy into your wiki at
https://github.com/theotherp/nzbhydra2/wiki/Exposing-Hydra-to-the-internet-and-using-reverse-proxies

# Traefik

    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: nzbhydra-ingress-https
      namespace: nzbhydra
    spec:
    entryPoints:
        - websecure
    routes:
      - match: Host(`nzbhydra.example.com`)
        kind: Rule
        priority: 10
        services:
          - name: nzbhydra-service
        port: 5076

Assuming you have configured the ingress with HTTPS (like in the example above) but are proxying requests to Nzbhydra in your docker / kubernetes cluster which are just listening on HTTP. You will see '400 bad request' errors. 
You need to tell Traefik to forward the x-forwarded- headers to the destination.

    additionalArguments:
      - --entryPoints.web.proxyProtocol.insecure
      - --entryPoints.web.forwardedHeaders.insecure

**Comment by theotherp** [comment]
Thanks! It's a wiki so you should be able to edit it, I think.

**Comment by JonasHess** [comment]
I am not a collaborator, so I don't think I am allowed to make changes to your wiki.

**Comment by theotherp** [comment]
Done. Thanks for the contribution!
