### ISSUE TITLE
Filter Results not working

### ISSUE THREAD

**Issue by shadyslim2018** [theotherp/nzbhydra2#893]
Filter Results stopped working. I'm using docker image - no matter what I type in there and then press enter, nothing gets filtered. There is nothing in the logs relating to filtered results.

**Comment by theotherp** [comment]
Try pressing Ctrl+F5. If that doesn't help, open the console (press F12, select the console tab) and check for errors and if you find some post them.

**Comment by shadyslim2018** [comment]
Seems to be a Firefox problem. Works OK in Opera and Chrome.

**Comment by theotherp** [comment]
Tried without any extensions? I use Firefox and it works fine for me.

**Comment by shadyslim2018** [comment]
I think it is one of the extensions. When I disabled all the extensions it started working, however, when I re-enabled all of the extensions it still worked, so I have no idea which extension might have caused the issue. Thanks for your help, might as well close this bug report since it wasn't a bug in nzbhydra but in a Firefox extension.
