### ISSUE TITLE
out of memory: qnap /tmp folder nzbhydra

### ISSUE THREAD

**Issue by LennyM8472** [theotherp/nzbhydra2#894]
Hi,

on the qnap nzbhydra uses the /tmp folder during the creation of the backup file.

In my case the backup file is too large for the /tmp folder, as qnap only grants approx 50mb space for the /tmp folder.

As a result of the size of the backup the backup fails and the temp backup file sits idle in the /tmp folder, resulting in the blocking of the qnap ram disk.

It would be great, if you change the temp folder to something in the app directory or so.

Best regards
Lenny

**Comment by theotherp** [comment]
Sorry, forgot about this. You can control the temp folder using the environment variable NZBHYDRA_TEMP_FOLDER from v.6.0.0 forward.
