### ISSUE TITLE
Disable color logging

### ISSUE THREAD

**Issue by Isilorn** [theotherp/nzbhydra2#897]
Hello,

I'm centralizing the logs from all my containers into a Graylog instance using Docker's capability to log in the GELF format (I know, it might be a bit overkill 😉).

The color codes in NZBHydra2 logs, while not incompatible, make the output in Graylog hard to read:

<img width="1356" alt="image" src="https://github.com/theotherp/nzbhydra2/assets/7522688/1eba5daf-5c21-4877-a8ba-ed3fc6188eac">

Could we have an option to disable the color codes in the logs?

**Comment by theotherp** [comment]
There's no way to configure it from the UI. You can try setting the
(docker) environment variable spring_output_ansi_enabled (upper case) to
"NEVER".

**Comment by Isilorn** [comment]
<img width="1367" alt="image" src="https://github.com/theotherp/nzbhydra2/assets/7522688/e4ed80ba-148b-4e40-b77d-57c8ac0294f3">

It works perfectly 😄 

Is there comprehensive documentation with Docker environment variables somewhere?

**Comment by theotherp** [comment]
No, the wrapper has some options which in turn set some properties for the
main process. I may document them when I'm back on vacation.
