### ISSUE TITLE
Docker instance keeps spamming github for new release

### ISSUE THREAD

**Issue by JHotterbeekx** [theotherp/nzbhydra2#898]
Hi,

I've been running nzbhydra for a long time now, without any significant issues.
The setup is using docker (on a synology nas), using the latest linuxserver image.
I don't check the logs often, but yesterday I noticed that there were a lot of failed requests to check for a new version.

If I'm not mistaken you can use the github api 60 times a day for this, but the calls seem to happen almost every minute for about 15 times and then stops for somewhere between 10 and 60 minutes before starting again. Causing the github API to be spammed quite a lot and my IP being blocked on the github API within a few hours, every day.

Am I missing something? As far as I'm aware there is no use in checking for the latest version while running as a docker image in the background. And I haven't been home all day, so there was no machine running with the page open, so that should not have been triggering this either.

Anybody got a clue what is going on here?

![image](https://github.com/theotherp/nzbhydra2/assets/3214419/52dec7a8-d1cc-4185-826e-ee23ef1a5576)

**Comment by theotherp** [comment]
Update checks are done every hour which should never be enough to be limited by Github as they allow 60 requests per hour.

Please attach debug infos.

**Comment by JHotterbeekx** [comment]
[nzbhydra-debuginfos-2023-11-06-22-29.zip](https://github.com/theotherp/nzbhydra2/files/13272723/nzbhydra-debuginfos-2023-11-06-22-29.zip)

I've attached the debug log.
Come to think of it, I'm running quite some other docker images. So the limit might be hit by another application, however when it keeps trying 10+ times when failing, it won't help reduce the problem either. I'll start debugging my own setup by stopping some of the other applications, but this might still be worth looking into. For example look at '2023-11-06 21:53:00.410' in de debug log, it shows the limit already hit on the first call, but it still tries 12 more times.

**Comment by JHotterbeekx** [comment]
Nevermind. After turning off all the other docker containers for the night and slowly turning them on one by one I've found the cause. I was running a docker image with a dashboarding solution, that integrates several services. One of these services was nzbhydra and it kept checking for if a new version was available every minute. And my best guess is making an API call to hydra that checks for a new version, performs a call to github. It seems to do this with other services as well, constantly spamming API calls because of this. NZBHydra is just the tool that actually made the failure logging visible in the UI. 

I will close the issue.

**Comment by JHotterbeekx** [comment]
Closing, not a nzbhydra issue.
