### ISSUE TITLE
results preceded by a space character

### ISSUE THREAD

**Issue by quidnun** [theotherp/nzbhydra2#900]
Is it intentional that results have a single space before them? It's not relevant visually but when you want to select the result to copy and paste it always has that space character at the beginning.

**Comment by theotherp** [comment]
Could you please provide more context?

**Comment by quidnun** [comment]
Like if I tried to select "Could you please provide more context?" on this page if it were a result on nzbyhdra2 it would be " Could you please provide more context?"

**Comment by theotherp** [comment]
Got it. Never noticed that. Will be fixed in next update.
