### ISSUE TITLE
API and download Hits won't be cleared in 5.3.5

### ISSUE THREAD

**Issue by Viper780** [theotherp/nzbhydra2#905]
I hit the API and Download Limit from several Indexer and they won't be bothered any further, which is a good thing. But there weren't any API requests in the last 3-4 days. 

I would expect that the Counter for the Hits would go to zero after 24h (when nothing is set in the Hit reset Time Field) 

Program info
Version: 5.3.5
Container version: v5.3.5-ls120
Container release type: Release
Container author: linuxserver.io

**Comment by theotherp** [comment]
Please set the log file level to debug and enable the logging marker for
api hits. Wait a day and then post new debug infos.
I won't be able to take a look before next Friday.

**Comment by Viper780** [comment]
![nzbhydra-debuginfos-2023-12-13-19-28.zip](https://github.com/theotherp/nzbhydra2/files/13664307/nzbhydra-debuginfos-2023-12-13-19-28.zip)

Sorry I didn't get a notification.
I hope you can see all the Info's in the debug log

**Comment by Viper780** [comment]
@theotherp did you already get the chance to look in to the debug log?
Here is another one https://file.io/uOSPXwse7bku

**Comment by Viper780** [comment]
@theotherp sorry for asking again - is it a bug or should I install nzbhydra2 fresh?

I've tried to restore a 1week old backup but the problem is the same

**Comment by theotherp** [comment]
Not sure. Don't have free time right now, got a puppy and am barely staying
afloat.

**Comment by Viper780** [comment]
It isn't urgent - just a nice to have.
And please share pictures of your puppy

**Comment by theotherp** [comment]
> And please share pictures of your puppy

Sure :-)

![puppygithub2](https://github.com/theotherp/nzbhydra2/assets/14368889/e79a7aa6-e091-4ca5-ba8a-20e79a4edb99)

![puppygithub1](https://github.com/theotherp/nzbhydra2/assets/14368889/b27158f2-a458-4a08-8ad3-a2012a2e4a13)

![puppygithub3](https://github.com/theotherp/nzbhydra2/assets/14368889/bb089f95-a5f8-4520-806d-f950cd0ed932)

**Comment by theotherp** [comment]
Sorry, actually got around to looking at it. So the thing is that limits actually aren't reset when indexers are not searched. That is something that could be improved because then the status page would actually show the current state. But limits are only determined and saved when an indexer is accessed for any API hit.

**Comment by Viper780** [comment]
Looks like a very young golden retriever - it is very cute!

Thank you very much. Is there a way to reset the counters to zero manually?

**Comment by theotherp** [comment]
There's currently no option. This is just so that the status page shows the correct values, right? The indexers should still be selected even if outdated hit values are shown on the status page.

**Comment by Viper780** [comment]
Okay I had issues with two indexers.
both wouldn't be used because the hitlimit was reached - but there were no API hits.
I've removed them, and reconfigured it under a different name. It works now
