### ISSUE TITLE
period substitution with spaces not consistent

### ISSUE THREAD

**Issue by eamonho** [theotherp/nzbhydra2#910]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076/system/bugreport). If other tools are involved post their logs as well.**

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* What do you expect to happen? What does happen? 
Filenames of a pattern <file.name>.-.# are replaced with <file.name>-# during search results, so during nzb authoritative renaming, the number is appended to the last word in the filename.
* Have you searched for this problem? You don't have to answer, just make sure.
* Can the problem be reproduced? How?
All searches with that particular pattern are consistent
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
* If you use a docker container please tell me which one.
linuxserver.io
* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.

**I will close your issues if I you didn't provide proper information as described as above**

The more information you provide up front the higher the chance that I can help you.

**Comment by theotherp** [comment]
Please attach debug infos and provide a concrete example.

**Comment by theotherp** [comment]
Closing this issue. Will reopen when you provide the requested information.

**Comment by eamonho** [comment]
![screenshot](https://github.com/theotherp/nzbhydra2/assets/7821888/308c1513-11a6-4159-91b4-e18d1332c32d)

**Comment by theotherp** [comment]
Please also attach a current debug infos zip.
