### ISSUE TITLE
Allow certain Tasks to be disabled or configured

### ISSUE THREAD

**Issue by MicBlaze** [theotherp/nzbhydra2#912]
* What do you want to happen?
I would like to configure the System Tasks (System > Tasks). Mainly 'Problem detector'.

* If not clear, why do you want it?
The "Problem detector" task beacons my IP out to api.ipify.org every hour. I don't want this. Maybe allow disabling this check or allow defining a custom server.

https://github.com/theotherp/nzbhydra2/blob/c28a29663a16b1091326ba19e40cda14e035fe0d/core/src/main/java/org/nzbhydra/misc/OpenPortChecker.java#L71

* Do you think it's something only you need or something that might be popular?
I think it may be popular since people who run this stuff tend to like their privacy

**Comment by theotherp** [comment]
I recently got a puppy and have no time for development. It shouldn't be too much work, I'll keep it in mind. Although I'd rather allow disabling this particular check.

**Comment by MicBlaze** [comment]
> I recently got a puppy
🐶 

No problem, disabling is perfectly fine.
