### ISSUE TITLE
History disapearing, only one very old history line remains

### ISSUE THREAD

**Issue by 1n5aN1aC** [theotherp/nzbhydra2#915]
Great software, btw, Thank you very much for developing it!

Details:
I have NZBhydra set up and functioning.
I have "Keep History" set to ON, "Keep history for..." and "keep stats for..." set to 30 weeks.

However, I have the weird problem where my history (both for searches, and for downloads) frequently disappears, I believe the history is resetting every day?  The weird thing is there is ONE history entry from before the cutoff date which always stays.  It is dated 2023-01-31 14:36

I would be glad to collect a debug info zip for you, but I can't exactly trigger it at will.  It happens frequently, but appears to be more than once a day but I am not sure of the schedule.

Using docker container:  https://github.com/linuxserver/docker-nzbhydra2
Version: 5.3.7
Screenshot:  https://i.imgur.com/ihAm5Yz.png

Seems like it could be the same issue as https://github.com/theotherp/nzbhydra2/issues/873
Is there any way to like reset history or something?  I'm glad to lose any of that, I'd just rather not have to re-configure all my indexers/etc.

**Comment by theotherp** [comment]
Please attach debug infos zip

**Comment by 1n5aN1aC** [comment]
Done!  See https://www.file.io/LVWY/download/z8kvYgVTbMRW

**Comment by theotherp** [comment]
You can try resetting the history by shutting down hydra and deleting the `data/database` folder. All the config is saved in a different file.

If there is one entry left after deletion it's possible that for some reason the history was left in an invalid state.

**Comment by 1n5aN1aC** [comment]
Awesome, didn't realize the database was only for history and related items, and the config is not saved there.

Deleted it, and so far so good.  The super old entry is gone and I will update in a day or so whether it's fully fixed or not.  Thanks!

**Comment by 1n5aN1aC** [comment]
Thank you very much, that appears to have solved it!

**Comment by kzshantonu** [comment]
Hi this happened to me too. Is there any way to restore my stats? Stats are very important to me

**Comment by theotherp** [comment]
You can try restoring from a previous backup.
