### ISSUE TITLE
[Binsearch] Unable to find main table in binsearch page. This happens sometimes ;-) (HAPPENS ALWAYS)

### ISSUE THREAD

**Issue by colemar** [theotherp/nzbhydra2#920]
`Binsearch: An unexpected error occurred while communicating with the indexer: Unable to find main table in binsearch page. This happens sometimes ;-)
`
Version: 5.3.7

At this time it happens always.
[binsearch.info](https://binsearch.info/) seems to be OK.

**Comment by Chathula** [comment]
Same here!

**Comment by themana** [comment]
@theotherp 
I believe the issue relates to how hydra2 is set to parse the HTML response from binsearch.info.

The code below is looking for a table called r2 but binsearch.info changed its HTML and no longer name the results table as such it's failing to find the results.

Binsearch.java
Line #116
        Elements mainTables = doc.select("table#r2");
Possible fix - can't test as I run it in a docker container
        Elements mainTables = doc.select("table.result-table");

**Comment by theotherp** [comment]
Thanks for the analysis, @themana. I'll look into it.
