### ISSUE TITLE
RSS feed doesn't return any results?

### ISSUE THREAD

**Issue by drelephant** [theotherp/nzbhydra2#921]
Using lscr.io/linuxserver/nzbhydra2:latest docker image.

I'm trying to add a feed from nzbhydra2 to FreshRSS so I can know when the latest linux isos are released.

But the rss feed never returns any results?
```
http://<serverip>:5076/api?apikey=<apikey>&t=search&q=linux+iso
```
The response is always:
```
<rss version="2.0">
<channel>
<title>NZBHydra 2</title>
<link>https://www.github.com/theotherp/nzbhydra2</link>
<webMaster>theotherp@posteo.net</webMaster>
<generator>NZBHydra2</generator>
<newznab:response offset="0" total="0"/>
</channel>
</rss>
```
Even though when I manually search, I get a lot of results.

In case it makes a difference, I'm only using torrent indexers.

What am I doing wrong?

**Comment by theotherp** [comment]
Please attach debug infos as requested in the issue template: https://github.com/theotherp/nzbhydra2/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by drelephant** [comment]
Aah, I checked the logs with `sudo docker logs -f nzbhydra2` and they all say:
```
Not using <tracker name> because torznab indexers cannot be used by API NZB searches
No indexers were selected for this search. You probably don't have any indexers configured which support the provided ID type or all of your indexers which do are currently disabled. You can enable query generation to work around this.
```
I tried going to `Config-Searching` and changing "Generate queries" to "All searches", but it still didn't work.

So I guess nzbhydra2 can't do what I'm trying to do?

**Comment by theotherp** [comment]
http://<serverip>:5076/torznab/api?apikey=<apikey>&t=search&q=linux+iso

In the config screen you can click the "API?" button for that info.

**Comment by drelephant** [comment]
Thank you!!

In FreshRSS, it doesn't show any info except the name and you can download the magnet/torrent. I can't even see which indexer the link came from (although I do see that that info is there in the raw feed `torznab:attr name="hydraIndexerName" `).

Is there some other app or app category that I should/could be using to read the nzbhydra2 feeds?

Sorry, the learning curve with docker/indexers/torznab/rss has been steep over the last few days...

**Comment by theotherp** [comment]
Automation tools like sonarr or radarr would be your best bet. Or NZB360 if you're on android. See https://trash-guides.info/

**Comment by drelephant** [comment]
Thanks again. I wasn't sure about those because they're supposedly for movies/TV shows - do they work for random files like linux isos as well?

**Comment by theotherp** [comment]
No, they work only for shows and movies, respectively.
