### ISSUE TITLE
Unsecured Dev Endpoints

### ISSUE THREAD

**Issue by jkhsjdhjs** [theotherp/nzbhydra2#923]
Some development endpoints don't require `ROLE_ADMIN` and may be accessed by anyone:

- `/dev/crash` may be used to crash any publicly accessible nzbhydra2 instance,
- `/dev/testAddToSonarr` is probably less problematic, but it still shouldn't be accessible without login.

https://github.com/theotherp/nzbhydra2/blob/master/core/src/main/java/org/nzbhydra/DevEndpoint.java

I wrote a mail regarding this issue at first, as it has some abuse potential. However, I didn't receive a reply in 2 weeks, which is why I'm creating this issue now.

**Comment by theotherp** [comment]
Sorry, I don't read the mails often enough.

**Comment by theotherp** [comment]
Thanks for the report, I've added required admin access and additionally made the crash endpoint require a certain system property to be set.
