### ISSUE TITLE
Can't run NZBHydra Windows, systray icon appears then disappears, service starts then stops

### ISSUE THREAD

**Issue by ak47uk** [theotherp/nzbhydra2#925]
When I run NZBHydra2.exe the systray icon appears but then it closes, I have tried running as a service and have the same issue. I have tried removing the service, rebooting, extracting a fresh download and running NZBHydra2.exe but the same happens, logs attached. 

[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/14636787/nzbhydra2.log)
[wrapper.log](https://github.com/theotherp/nzbhydra2/files/14636788/wrapper.log)

It was working ok until today I replaced the exe files to update the wrappers, and then ran the update in the app. Since then, even with a fresh download or restoring the original EXEs, I can't run the program.

**Comment by niko2** [comment]
same error on Linux installation (same error logs)

**Comment by Paladin-z** [comment]
Same issue on Windows 11, worked until a couple of hours ago.

**Comment by theotherp** [comment]
Stupid mistake on my end, fix is going live any minute.

**Comment by kramer987** [comment]
can confirm everything working as expected now

**Comment by niko2** [comment]
thank you for the quick fix @theotherp
 
since it is updating itself, how can I update it since it does not start ? a fresh install ?

**Comment by ak47uk** [comment]
> thank you for the quick fix @theotherp
> 
> since it is updating itself (I run it with systemd), how can I update it since it does not start ? a fresh install ?

That's what I did, fresh install then restored a backup.

**Comment by WPTK** [comment]
I just downloaded the latest x64 windows ZIP and it's still doing it for me. I tried a fresh install. Exact same issue as OP.

**Comment by RDHoworth** [comment]
I also cannot run on Linux - I get this error:

[9382] Error loading Python lib '/tmp/_MEI6SgWNw/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __libc_unwind_link_get, version GLIBC_PRIVATE

I have also tried a clean install with the same result

**Comment by theotherp** [comment]
Tun the python wrapper directly

**Comment by RDHoworth** [comment]
Hi,

This works. Since I am running this on Ubuntu, I have also set up SystemD to auto load the wrapper, which also works.

Thanks, It is a relief to get this running again, as if I run NZBHydra2 on Windows, it takes a very long time to load on either Mac or iPad / iPhone. Almost instant load from the Linux or Docker instances

**Comment by evilsh3ll** [comment]
Yesterday I had the nzbhydra2-nojava-bin 5.3.9 in archlinux and it worked, but today I upgraded to 5.3.10-1 and the service doesn't start anymore.
Where are the logs?

**Comment by theotherp** [comment]
The logs are in `data/logs`, wherever that is. Usually in the install folder.

**Comment by theotherp** [comment]
Only a warning, you can safely ignore it.

**Comment by evilsh3ll** [comment]
that was the only log for today (other logs are older) but nzbhydra can't run after the today update. As you can see by the last INFO in the log: _the main process has terminated_

**Comment by jkhsjdhjs** [comment]
Use `journalctl -eu nzbhydra2` to get more info, `systemctl status` only displays a few lines of log, which aren't helpful in this case.

**Comment by evilsh3ll** [comment]
**journalctl -eu nzbhydra2**
```
mar 20 10:45:47 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 3.
mar 20 10:45:47 dpc systemd[1]: Started NZBHydra2 Daemon.
mar 20 10:45:47 dpc nzbhydra2[17950]: Logging wrapper output to /var/lib/nzbhydra2/logs/wrapper.log
mar 20 10:45:47 dpc nzbhydra2[17950]: 2024-03-20 10:45:47,358  INFO - Release type native forced by environment variable
mar 20 10:45:47 dpc nzbhydra2[17950]: 2024-03-20 10:45:47,359  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXXXXXXXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.ena>
mar 20 10:45:47 dpc nzbhydra2[17950]: 2024-03-20 10:45:47,429  WARNING - Unable to read control ID from /var/lib/nzbhydra2/control.id: [Errno 2] No such file or directory: '/var/lib/nzbhydra2/control.id'. Falling back to process return code -7
mar 20 10:45:47 dpc nzbhydra2[17950]: 2024-03-20 10:45:47,429  INFO - NZBHydra main process has terminated for shutdown
mar 20 10:45:47 dpc systemd[1]: nzbhydra2.service: Deactivated successfully.
mar 20 10:45:47 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 4.
mar 20 10:45:47 dpc systemd[1]: Started NZBHydra2 Daemon.
mar 20 10:45:47 dpc nzbhydra2[17961]: Logging wrapper output to /var/lib/nzbhydra2/logs/wrapper.log
mar 20 10:45:47 dpc nzbhydra2[17961]: 2024-03-20 10:45:47,617  INFO - Release type native forced by environment variable
mar 20 10:45:47 dpc nzbhydra2[17961]: 2024-03-20 10:45:47,618  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXXXXXXXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.ena>
mar 20 10:45:47 dpc nzbhydra2[17961]: 2024-03-20 10:45:47,686  WARNING - Unable to read control ID from /var/lib/nzbhydra2/control.id: [Errno 2] No such file or directory: '/var/lib/nzbhydra2/control.id'. Falling back to process return code -7
mar 20 10:45:47 dpc nzbhydra2[17961]: 2024-03-20 10:45:47,686  INFO - NZBHydra main process has terminated for shutdown
mar 20 10:45:47 dpc systemd[1]: nzbhydra2.service: Deactivated successfully.
mar 20 10:45:48 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 5.
mar 20 10:45:48 dpc systemd[1]: nzbhydra2.service: Start request repeated too quickly.
mar 20 10:45:48 dpc systemd[1]: nzbhydra2.service: Failed with result 'start-limit-hit'.
mar 20 10:45:48 dpc systemd[1]: Failed to start NZBHydra2 Daemon.
mar 20 11:25:25 dpc systemd[1]: Started NZBHydra2 Daemon.
mar 20 11:25:25 dpc nzbhydra2[27231]: Logging wrapper output to /var/lib/nzbhydra2/logs/wrapper.log
mar 20 11:25:25 dpc nzbhydra2[27231]: 2024-03-20 11:25:25,197  INFO - Release type native forced by environment variable
mar 20 11:25:25 dpc nzbhydra2[27231]: 2024-03-20 11:25:25,199  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXXXXXXXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.ena>
mar 20 11:25:25 dpc nzbhydra2[27231]: 2024-03-20 11:25:25,269  WARNING - Unable to read control ID from /var/lib/nzbhydra2/control.id: [Errno 2] No such file or directory: '/var/lib/nzbhydra2/control.id'. Falling back to process return code -7
mar 20 11:25:25 dpc nzbhydra2[27231]: 2024-03-20 11:25:25,269  INFO - NZBHydra main process has terminated for shutdown
mar 20 11:25:25 dpc systemd[1]: nzbhydra2.service: Deactivated successfully.
mar 20 11:25:25 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 1.
mar 20 11:25:25 dpc systemd[1]: Started NZBHydra2 Daemon.
mar 20 11:25:25 dpc nzbhydra2[27255]: Logging wrapper output to /var/lib/nzbhydra2/logs/wrapper.log
mar 20 11:25:25 dpc nzbhydra2[27255]: 2024-03-20 11:25:25,667  INFO - Release type native forced by environment variable
mar 20 11:25:25 dpc nzbhydra2[27255]: 2024-03-20 11:25:25,669  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXXXXXXXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.ena>
mar 20 11:25:25 dpc nzbhydra2[27255]: 2024-03-20 11:25:25,738  WARNING - Unable to read control ID from /var/lib/nzbhydra2/control.id: [Errno 2] No such file or directory: '/var/lib/nzbhydra2/control.id'. Falling back to process return code -7
mar 20 11:25:25 dpc nzbhydra2[27255]: 2024-03-20 11:25:25,739  INFO - NZBHydra main process has terminated for shutdown
mar 20 11:25:25 dpc systemd[1]: nzbhydra2.service: Deactivated successfully.
mar 20 11:25:26 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 2.
mar 20 11:25:26 dpc systemd[1]: Started NZBHydra2 Daemon.
mar 20 11:25:26 dpc nzbhydra2[27267]: Logging wrapper output to /var/lib/nzbhydra2/logs/wrapper.log
mar 20 11:25:26 dpc nzbhydra2[27267]: 2024-03-20 11:25:26,149  INFO - Release type native forced by environment variable
mar 20 11:25:26 dpc nzbhydra2[27267]: 2024-03-20 11:25:26,150  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXXXXXXXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.ena>
mar 20 11:25:26 dpc nzbhydra2[27267]: 2024-03-20 11:25:26,223  WARNING - Unable to read control ID from /var/lib/nzbhydra2/control.id: [Errno 2] No such file or directory: '/var/lib/nzbhydra2/control.id'. Falling back to process return code -7
mar 20 11:25:26 dpc nzbhydra2[27267]: 2024-03-20 11:25:26,224  INFO - NZBHydra main process has terminated for shutdown
mar 20 11:25:26 dpc systemd[1]: nzbhydra2.service: Deactivated successfully.
mar 20 11:25:26 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 3.
mar 20 11:25:26 dpc systemd[1]: Started NZBHydra2 Daemon.
mar 20 11:25:26 dpc nzbhydra2[27279]: Logging wrapper output to /var/lib/nzbhydra2/logs/wrapper.log
mar 20 11:25:26 dpc nzbhydra2[27279]: 2024-03-20 11:25:26,666  INFO - Release type native forced by environment variable
mar 20 11:25:26 dpc nzbhydra2[27279]: 2024-03-20 11:25:26,667  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXXXXXXXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.ena>
mar 20 11:25:26 dpc nzbhydra2[27279]: 2024-03-20 11:25:26,739  WARNING - Unable to read control ID from /var/lib/nzbhydra2/control.id: [Errno 2] No such file or directory: '/var/lib/nzbhydra2/control.id'. Falling back to process return code -7
mar 20 11:25:26 dpc nzbhydra2[27279]: 2024-03-20 11:25:26,740  INFO - NZBHydra main process has terminated for shutdown
mar 20 11:25:26 dpc systemd[1]: nzbhydra2.service: Deactivated successfully.
mar 20 11:25:27 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 4.
mar 20 11:25:27 dpc systemd[1]: Started NZBHydra2 Daemon.
mar 20 11:25:27 dpc nzbhydra2[27293]: Logging wrapper output to /var/lib/nzbhydra2/logs/wrapper.log
mar 20 11:25:27 dpc nzbhydra2[27293]: 2024-03-20 11:25:27,091  INFO - Release type native forced by environment variable
mar 20 11:25:27 dpc nzbhydra2[27293]: 2024-03-20 11:25:27,092  INFO - Starting NZBHydra main process with command line: ./core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXXXXXXXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.ena>
mar 20 11:25:27 dpc nzbhydra2[27293]: 2024-03-20 11:25:27,149  WARNING - Unable to read control ID from /var/lib/nzbhydra2/control.id: [Errno 2] No such file or directory: '/var/lib/nzbhydra2/control.id'. Falling back to process return code -7
mar 20 11:25:27 dpc nzbhydra2[27293]: 2024-03-20 11:25:27,149  INFO - NZBHydra main process has terminated for shutdown
mar 20 11:25:27 dpc systemd[1]: nzbhydra2.service: Deactivated successfully.
mar 20 11:25:27 dpc systemd[1]: nzbhydra2.service: Scheduled restart job, restart counter is at 5.
mar 20 11:25:27 dpc systemd[1]: nzbhydra2.service: Start request repeated too quickly.
mar 20 11:25:27 dpc systemd[1]: nzbhydra2.service: Failed with result 'start-limit-hit'.
mar 20 11:25:27 dpc systemd[1]: Failed to start NZBHydra2 Daemon.

```

**Comment by jkhsjdhjs** [comment]
I just installed the AUR package `nzbhydra2-nojava-bin` on my system and it works fine for me. I also don't get any `Unable to read control ID` warning. Not sure what's wrong on your system, the log messages sadly also aren't helpful.

**Comment by evilsh3ll** [comment]
if I can provide other logs feel free to ask, I need to fix nzbhydra soon

**Comment by jkhsjdhjs** [comment]
The `control.id` warning indicates that the main process exits immediately or doesn't even start, normally it should write its exit code to the `control.id` file, where the wrapper attempts to read it from after exit. You can try running the main nzbhydra file manually and see if that outputs anything useful. The AUR package installs it as `/usr/lib/nzbhydra2/core`.

**Comment by evilsh3ll** [comment]
_sudo -u nzbhydra2 /usr/lib/nzbhydra2/core -Xmx256M -DfromWrapper=true -DinternalApiKey=XXXXXXXX -Dsun.security.pkcs11.enable-solaris=false -Dfile.encoding=UTF8 -Dspring.output.ansi.enabled=ALWAYS --nobrowser --datafolder /var/lib/nzbhydra2 in folder /usr/lib/nzbhydra2_

```[1]    60426 bus error  sudo -u nzbhydra2 /usr/lib/nzbhydra2/core -Xmx256M -DfromWrapper=true```

**Comment by jkhsjdhjs** [comment]
Hmm, are you on `x86_64` or `arm`? Did you perhaps install the arm64 version on `x86_64` or the other way around? This shouldn't happen accidently, so it's also possible that the current `arm64` release is broken (if you are on arm), I don't have an arm64 machine to test that. If you are on `x86_64`, then I don't know whats wrong, as it works fine for me.

Regarding bus errors: https://stackoverflow.com/questions/212466/what-is-a-bus-error-is-it-different-from-a-segmentation-fault

**Comment by evilsh3ll** [comment]
I'm in x86_64 and not in low memory

**Comment by jkhsjdhjs** [comment]
Then I can't help you unfortunately. It's possible that something changed in native build configuration (e.g. new graalvm version or something else). Another user is also reporting higher CPU usage with the new builds #928, so it's possible that there's something wrong with the new native builds in general.

You can switch to the java version for now, just install the `nzbhydra2` or `nzbhydra2-bin` for that.

**Comment by theotherp** [comment]
@evilsh3ll As @jkhsjdhjs helpfully pointed out for now your best bet right now may be switching to the generic version which requires java. It's nearly as good as the binary one. See if that helps. Unfortunately I can't properly debug your problem right now, it may be a weird one :-/

**Comment by evilsh3ll** [comment]
I tried to install the mainline nzbhydra2 or nzbhydra2-bin but the error is the same. if there were any error logs I could try to fix by myself.. there isn't any cue about the problem

**Comment by jkhsjdhjs** [comment]
Weird. And if you downgrade to e.g. 5.3.8 that still works? Have you tried rebooting the system already? That's a really odd issue.

**Comment by evilsh3ll** [comment]
yes I rebooted, the problem is that the previous version is not in aur, I can't downgrade without configuring a binary etc.. I'd prefer a clean setup. If the issue can't be solved in 1-2 days I'll make another installation with a previous version

**Comment by jkhsjdhjs** [comment]
AUR packages are just git repositories, you can always clone them, `checkout` a previous commit and `makepkg` that.
Or you could also modify the `PKGBUILD` by change the version and the checksums accordingly.

**Comment by evilsh3ll** [comment]
I downgraded to [5.3.10](https://github.com/theotherp/nzbhydra2/releases/tag/v5.3.10) but the problem is still present. That version worked yesterday maybe the problem is a dependence

**Comment by evilsh3ll** [comment]
Could you share your systemctl service?
Maybe there is a problem in the "Restart=always" line, I don't remember if I put this in the past
```
### /usr/lib/systemd/system/nzbhydra2.service
[Unit]
Description=NZBHydra2 Daemon
Documentation=https://github.com/theotherp/nzbhydra2
After=network.target

[Service]
User=nzbhydra2
Group=nzbhydra2
Type=simple
ExecStart=/usr/bin/nzbhydra2 --nobrowser --datafolder /var/lib/nzbhydra2
Restart=always
 
[Install]
WantedBy=multi-user.target
```

**Comment by jkhsjdhjs** [comment]
The systemd service file is part of the AUR package, it's the same for me. It cannot be the issue, as running `/usr/lib/nzbhydra2/core` also crashed for you, without systemd being involved. You could try asking on the Arch Linux forums (https://bbs.archlinux.org/), maybe the folks over there have an idea what's going wrong on your system.

**Comment by evilsh3ll** [comment]
I tried to ask but I'm not sure if I'll solve. The exit code su _0/SUCCESS_, I suppose it's a problem deeply releated to nzbhydra or its dependences, that arch forums can't solve

**Comment by evilsh3ll** [comment]
How can I save my nzbhydra settings and fully wipe my aur installation, than restore settings?

**Comment by evilsh3ll** [comment]
I installed nzbhydra in a new vanilla archlinux machine (different computer) and the problem is still present. This is not a problem of my configuration

**Comment by jkhsjdhjs** [comment]
Which other packages were updated when you updated nzbhydra from 5.3.8 to 5.3.10? Since 5.3.8 is now also not working anymore, there must've been some other change. You can try downgrading these packages and see if that makes it work again.

**Comment by evilsh3ll** [comment]
I can't partially upgrade archlinux, it's not allowed. I can make it working again by restoring an older timeshift backup but I don't want to keep my system outdated for weeks/months

**Comment by jkhsjdhjs** [comment]
Partial upgrades can make the system unstable, yes, but doing so is not prohibited. You're free to do whatever you want with your system. I would recommend you to downgrade the packages or restore a timeshift backup and then upgrade the packages in some clever way to quickly narrow down the problematic package. Then you can file a bug report for that package.

**Comment by jkhsjdhjs** [comment]
Or did you perhaps change/update your `makepkg.conf` when you updated nzbhydra?

**Comment by evilsh3ll** [comment]
never changed anything in config files of hydra

**Comment by theotherp** [comment]
@evilsh3ll Wrong thread but it's too late now.

Please try if the newest release works for you.

**Comment by evilsh3ll** [comment]
I updated nzbhydra2 but it's still not running, same problem

**Comment by jkhsjdhjs** [comment]
I just set up a new clean arch linux lxc and I can (to my surprise) reproduce your issue! Still not sure what could be causing this though.

```
[jkhsjdhjs@nzbhydra-test ~]$ /usr/lib/nzbhydra2/core
Bus error
[jkhsjdhjs@nzbhydra-test ~]$ echo $?
135
```

**Comment by jkhsjdhjs** [comment]
Seems like the `debug` makepkg option is the culprit here. Having it set while packaging will result in nzbhydra erroring, not sure why exactly. Anyway, the AUR packages have been updated to disable the `debug` option and should now work correctly.

**Comment by theotherp** [comment]
@jkhsjdhjs Glad you got it solved even though I'd rather would've had this discussion in a separate topic as it isn't related to the original issue. Anyway, I never would've been able to fix this or even determine the package as the source of the problem.

I don't really understand the debug flug or why it wouldn't work. Perhaps I'd need to compile my code with https://www.graalvm.org/latest/reference-manual/native-image/debugging-and-diagnostics/DebugInfo/ for your debug flag to work, I don't know. But it's working now :-)
