### ISSUE TITLE
5.3.9 python libc on debian failed to start

### ISSUE THREAD

**Issue by tunloop** [theotherp/nzbhydra2#927]
Just upgraded to 5.3.9 after the service repeatedly failed to start with the dev endpoints issue.
I am on Debian 12 and the updated version is failing to run on the system due to a library issue.
The systemd service wouldn't report any logs and the daemon dies before it can write to the log file as well. Running it manually from the command line yields the error:

```
/opt/nzbhydra/nzbhydra2 --nobrowser --datafolder /opt/nzbhydra/data
[137522] Error loading Python lib '/tmp/_MEIImsvJU/libpython3.7m.so.1.0': dlopen: /tmp/staticx-PHaCAp/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /lib/x86_64-linux-gnu/libpthread.so.0)
```

**Comment by theotherp** [comment]
Fix is on the way

**Comment by theotherp** [comment]
On linux it's best just loading the python wrapper instead of starting the binary.
