### ISSUE TITLE
Core.exe CPU Usage

### ISSUE THREAD

**Issue by Nmh2024** [theotherp/nzbhydra2#928]
Hi, 
I have found that since I have upgraded to version 5.3.10 on my Windows OS that core.exe is running at between 15 and 20% CPU all the time.  Is anyone else having this issue or know why this may be?

Thank you

**Comment by theotherp** [comment]
Please set log level to debug and enable the logging marker for
performance. Restart, reproduce the issue and create debug infos and attach
them.

**Comment by Nmh2024** [comment]
Hi, thank you for the response but I have switched to Prowlarr, I will close this
