### ISSUE TITLE
can't log into Hydra2 anymore

### ISSUE THREAD

**Issue by payne91166336633** [theotherp/nzbhydra2#929]
Hi all
I hope some one can help me with this problem I'm having with Hydra2. I can start the Hydra2 exe it shows up on my system tray but when i right click on it and open the web UI nothing happens. It us to to just open up and work just fine. But now nothing. I've tried to open the web 192.168.10.1:5076 and i get  Firefox can’t establish a connection to the server at 192.168.10.1:5076. it worked fine a few days ago and now nothing. my radarr and sonarr are both unable to connect to it as well. any help would be appreciated

**Comment by theotherp** [comment]
Please update manually using the latest release.

**Comment by theotherp** [comment]
That means download the appropriate artifact from https://github.com/theotherp/nzbhydra2/releases/tag/v5.3.10 and extract it into your hydra folder, overwriting everything.

**Comment by payne91166336633** [comment]
thank you so much that worked. im guessing this was some kind of update

**Comment by payne91166336633** [comment]
you rock sir. Thank you very much I so appreciate you response. you are a life saver. cheers jason

**Comment by theotherp** [comment]
Just helping to repair what I broke ;-)
