### ISSUE TITLE
NZBindex API version

### ISSUE THREAD

**Issue by jarvisxhi** [theotherp/nzbhydra2#930]
* What do you expect to happen? What does happen? 
I need the search performed with NZBIndex's api to use this url https://api.nzbindex.com/api/?key=abcdef instead of this one https://api.nzbindex.com/api/?apikey=abcdef
The key difference being no "api" preceding the key.

* Can the problem be reproduced? How?
When going to the following url it just shows their normal instructions page https://api.nzbindex.com/api/?apikey=abcdef
I need it to search https://api.nzbindex.com/api/?key=abcdef

Context: I'm trying to set up NZBIndex as a custom newznab indexer because there's no option to put an API key in for the presets version.

**Comment by theotherp** [comment]
I'll look into it, didn't know it wasn't free anymore
