### ISSUE TITLE
nzbhydra leaving behind GB's in local temp folder

### ISSUE THREAD

**Issue by tastyratz** [theotherp/nzbhydra2#931]
Nzbhydra appears to be creating a large number of temp files in windows under the local appdata temp directory.

An example filename created would be: 
nzbhydra15043945652466615372zip

It looks like it SHOULD be ending in .zip but forgot the . except manually renaming the extension does not allow it to be opened in winrar

it also looks like it's not cleaning up after itself regularly or periodically. This has, over time, left 4 or 5 gigs of temp, thousands of files in the last couple years. Some of these files are from 2021, some were very recent, all over the course of many updates.

I also see a TON of MEI folders there as well so this might be related to https://github.com/theotherp/nzbhydra2/issues/813 potentially if it's the same process leaving things behind?

This is on a server 2016 os, direct install no docker.

**Comment by theotherp** [comment]
I may have relied too much on the OS to clean them.
