### ISSUE TITLE
Feature Request: Add IP to History tables

### ISSUE THREAD

**Issue by devedse** [theotherp/nzbhydra2#932]
* What do you want to happen?
I would love to see what IP is downloading a specific NZB / doing API queries. Could this be added to the history table?

* If not clear, why do you want it?
I'm currently running multiple instances of Sonarr/Radarr and I want to see which one is making which queries.

* Do you think it's something only you need or something that might be popular?
It will be tremendously popular, 100% guaranteed.
And if not, a follow up of this feature could be to add configureable columns.

* If not clear, explain the use case.
N/A

**Comment by theotherp** [comment]
In the main config enable the display of advanced options and then select:

![image](https://github.com/theotherp/nzbhydra2/assets/14368889/e62ca485-f4b8-41d7-80b2-5189d8cf733b)

**Comment by devedse** [comment]
Hi @theotherp ,

I configured this but I don't see anything in the search / download pages:

![image](https://github.com/theotherp/nzbhydra2/assets/2350015/f72292de-fe15-4075-9372-51c73f2ead98)

![image](https://github.com/theotherp/nzbhydra2/assets/2350015/67c2ae9d-4c85-4ba2-a0b6-5259fe83bd01)

**Comment by theotherp** [comment]
You're right, sorry. There's a bug in the UI code, fixed with next release.

**Comment by devedse** [comment]
@theotherp , this feature now works correctly 😄 , would it be possible however to also add it to the `Download History` page?

**Comment by theotherp** [comment]
Oops, yes.
