### ISSUE TITLE
MAC OS -  wrappers report as outdated

### ISSUE THREAD

**Issue by nickdb01** [theotherp/nzbhydra2#933]
For some time, on starting the system it logs the following. Despite copying and overwriting the wrappers as instructed, the error persists.

2024-03-24 10:53:50.083  WARN --- [HT-Problem detecto] o.n.p.OutdatedWrapperDetector            : The NZBHydra wrappers (i.e. the executables or python scripts you use to run NZBHydra) seem to be outdated. Please update them:
Shut down NZBHydra, download the latest version and extract *all files* into your main NZBHydra folder (overwriting all). Start NZBHydra again.

**Comment by theotherp** [comment]
This is the list of files you need to update:

- NZBHydra2.exe
- NZBHydra2 Console.exe
- nzbhydra2
- nzbhydra2wrapper.py
- nzbhydra2wrapperPy3.py

**Comment by nickdb01** [comment]
Yes, I have already done that, by downloading the full generic bundle and overwritng them manually. It continues to report the error.
I can verify the checksums on all files and confirm they match the latest download, so it appears the files are dated in the bundle.

**Comment by theotherp** [comment]
Please post debug infos.

**Comment by nickdb01** [comment]
[nzbhydra-debuginfos-2024-03-24-13-16.zip](https://github.com/theotherp/nzbhydra2/files/14735243/nzbhydra-debuginfos-2024-03-24-13-16.zip)

**Comment by theotherp** [comment]
`nzbhydra2` is outdated. On mac you don't need it. It's not contained in the generic bundle so extracting that won't fix it.
