### ISSUE TITLE
Nzbhydra2 no longer launches on Ubuntu 22.04 after 6.0 update

### ISSUE THREAD

**Issue by ipkpjersi** [theotherp/nzbhydra2#938]
When trying to launch nzbhydra2 after the 6.0 update, I now get an error:

/opt/nzbhydra2/nzbhydra2 --nobrowser
[73487] Error loading Python lib '/tmp/_MEIPYKkqT/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __libc_unwind_link_get, version GLIBC_PRIVATE

python --version
Python 3.10.12

python3 --version
Python 3.10.12

OS: Xubuntu 22.04.4 LTS x86_64 
Host: X570S AORUS PRO AX -CF 
Kernel: 6.5.0-28-generic 
Uptime: 13 mins 
Packages: 4211 (dpkg), 14 (flatpak), 51 (snap) 
Shell: zsh 5.8.1 
Resolution: 1920x1200, 1920x1080 
DE: Xfce 4.16 
WM: Xfwm4 
WM Theme: Windows XP Luna 
Theme: Windows XP Luna [GTK2/3] 
Icons: elementary-xfce-darker [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Hack 11 
CPU: AMD Ryzen 9 5900X (24) @ 3.611GHz 
GPU: NVIDIA GeForce RTX 4070 
Memory: 8862MiB / 31980MiB 

If you need any other information, please let me know.

**Comment by theotherp** [comment]
Just run the python file instead, the binary will be phased out soon anyway.

**Comment by ipkpjersi** [comment]
> Just run the python file instead, the binary will be phased out soon anyway.

Sorry, how do I run the python file? There's multiple python files:

nzbhydra2wrapper.py
nzbhydra2wrapperPy3.py
