### ISSUE TITLE
REQ don't choose the smallest posting as the one fronting concatenated posts

### ISSUE THREAD

**Issue by snottyone** [theotherp/nzbhydra2#939]
example: 8 supposedly identical posts of the same file, 7 of them are 2GB in size, one is damaged and therefor a lot smaller.
THAT is the one presented in the listings (with the + icon listing the undamaged ones).
i get way too many "can't be completed" errors because of that, if i don't do a sanity check by hand.

**Comment by theotherp** [comment]
The result shown is the top one according to the sorting predicate. I.e. if you sort by newest the shown result in a title group is the one last posted.

**Comment by snottyone** [comment]
ok, so it's pure chance when that happens, 
thank you for the heads up!
