### ISSUE TITLE
support DETAILS function from Newznab API spec

### ISSUE THREAD

**Issue by maddox** [theotherp/nzbhydra2#942]
Can we please support the `details` function of the Newznab API spec? 

[DETAILS function in spec](https://newznab.readthedocs.io/en/latest/misc/api.html#details)

This function allows you to get the JSON/XML representation of an NZB via its GUID.

While search results return perfect representation of the NZBs from indexers in JSON/XML, there's no way to fetch a single record with nzbhydra2 using its GUID.

I apologize if I'm missing something, if someone could point me to how to do this with Nzbhydra2. I searched for a while but was unable to find how to do this, or an explanation of why it doesn't work. This includes the source code.

**Comment by theotherp** [comment]
I'll look into it. First time I've heard of that function. If the indexers support it it's a simple matter of delegating the call to them.

I'm curious, what do you need this for?

**Comment by maddox** [comment]
Awesome, thanks!

I have my own software that has the need to fetch an NZB via the GUID. After receiving search results, it uses it as the unique ID and stores it to fetch the nzb later for other needs when it only has the GUID. 

Everything is working great after moving to nzbhydra2, the results are great. But my this is the one thing that’s not working.

**Comment by maddox** [comment]
It's probably worth brining up that NZBs in results from nzbhydra2, have their own GUID and don't match the guid in the provider's NZB. So using this GUID and passing it through to the original provider would not just work. 

I'm also unclear about the architecture of nzbhydra2 and how it transforms the results. Obviously, a cache hit in nzbhydra2 would probably just immediately return the NZB again, but in cases where the GUID is from an NZB that may have been flushed from the cache, it would be problematic.
