### ISSUE TITLE
null id returned in link URL on new DETAILS response

### ISSUE THREAD

**Issue by maddox** [theotherp/nzbhydra2#943]
Thanks for getting #942 done so quick!

I'm seeing issues with the NZB url returned in the response. It seems to have a `null` id in the URL for the NZB

```
{link": "https://$HOST/getnzb/api/null?apikey=XXX}
```

**Comment by theotherp** [comment]
Woops. I looked at the result and thought everything was find, i missed that. Not hard to fix.
