### ISSUE TITLE
[REQ] When no Indexers with MediaID support available, hide MediaID support on Torznab API Endpoint

### ISSUE THREAD

**Issue by galeksandrp** [theotherp/nzbhydra2#945]
* What do you want to happen?
When this conditions are met, hide MediaID support on Torznab API endpoint
1. No Indexers with MediaID support available
2. Query Generation disabled for API searches
3. Query Generation Fallback disabled for API searches

* If not clear, why do you want it?
Aforemented configuration expected to return 0 results. It is so expected, that even Web Interface warns about it.

![image](https://github.com/theotherp/nzbhydra2/assets/3586205/1322b496-56ba-4ba5-9233-f84d5f47fdf7)

But what's not expected, that Radarr/Sonarr supports Query Generation on theirs side! When it sees that Indexer does not support MediaID, it converts it to plain old Title+Year search string.

* Do you think it's something only you need or something that might be popular?
Hmm, it depends on a country I guess.
1. My local country Indexers does not support MediaID at all.
2. As far as remember, default configuration have Query Generation disabled for API.
That mean that I was screwed already when I'm imported Indexers from Jackett.

* If not clear, explain the use case.
1. User installs NZBHydra.
2. User imports Indexers from Jackett. User's Indexers is shit without MediaID support
3. User adds Torznab API Endpoint into Radarr.
4. zero search results, woohoo!

**Comment by theotherp** [comment]
Well that was fast ;-)
