### ISSUE TITLE
Add Placeholder Text for Age and Size Filters in UI

### ISSUE THREAD

**Issue by apiweb** [theotherp/nzbhydra2#951]
<img width="895" alt="Screenshot 2024-05-24 at 07 13 43" src="https://github.com/theotherp/nzbhydra2/assets/5881027/540c7c00-558d-4993-b690-a3ceb597176c">

**What do you want to happen?**
I would like placeholder text to be added to the Min and Max Age and Min and Max Size input fields in the NZBHydra2 UI.

**If not clear, why do you want it?**
The current input fields do not contain any placeholder text, making it difficult to understand what values are expected. Adding placeholder text will improve usability by providing clear guidance to users on what inputs are acceptable.

**Do you think it's something only you need or something that might be popular?**
This improvement would benefit all users, not just me. Clearer input fields enhance the overall user experience and reduce confusion for everyone using the filters.

**If not clear, explain the use case.**
When using the filters to search for specific results, users are currently unsure what format or range of values can be entered in the Min and Max Age and Size fields. 
Placeholder text would serve as an example, helping users input values correctly and efficiently.
Sometimes I go a long time without using filters, then when I return, I forget what format size I can input for the size.

**Comment by theotherp** [comment]
Looks like this now:
![image](https://github.com/theotherp/nzbhydra2/assets/14368889/6576e473-1b47-4ff4-9a0e-11df550ba632)
