### ISSUE TITLE
Shift-clicking check boxes to select a range no longer works

### ISSUE THREAD

**Issue by kickerofelves** [theotherp/nzbhydra2#954]
* What do you expect to happen? What does happen? 
Prior to the new UI, clicking a checkbox and then shift-clicking another box would check all items in between.

* Have you searched for this problem? You don't have to answer, just make sure.
Seems this happened in the past #386 

* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.
 Version: 7.1.0
Linux
1080p
Firefox

**Comment by theotherp** [comment]
Can confirm. Probably a result of the changes for the redesing. Will look into it.

**Comment by kickerofelves** [comment]
TOP must stand for TheOtherP because that's what you are!
