### ISSUE TITLE
BUG Unable to get NZB to pass to download client

### ISSUE THREAD

**Issue by JCV129** [theotherp/nzbhydra2#957]
When searching for a item in Sonarr/Radarr the search works fine but when it tries to download it fails and I get a status that all indexers have failed.  I have been using this setup for years and it usually just sends the nzb to SABnzb and the download starts.

This seems to have started with the new updates this week.  I am troubleshooting the ARR's and SAB as it is unclear the issue is with NZBHydra.  

Here is the error in SONARR that seems to point to an issue with NZBHydra

Downloading nzb for episode '*****************' failed (http://localhost:5076/getnzb/api/-2823677805995163342?apikey=(removed): HTTP request failed: [500:InternalServerError] [GET] at [http://localhost:5076/getnzb/api/-2823677805995163342?apikey=(removed)]

I can manually download the nzb from the indexers as well

I am running a Windows 11 Pro 23H2 machine.

Thanks for a great app and I appreciate any assistance.
[nzbhydra2-debug-infos.zip](https://github.com/user-attachments/files/15776445/nzbhydra2-debug-infos.zip)

**Comment by reloxx13** [comment]
me2, error 500 and indexer is getting disabled all the time

**Comment by theotherp** [comment]
That's weird. Please enable debug log level for the log files, shutdown hydra and replace `core.exe` with this one: https://ufile.io/h8c3ildx

See if that helps and if not post new debug infos.

**Comment by reloxx13** [comment]
> That's weird. Please enable debug log level for the log files, shutdown hydra and replace `core.exe` with this one: https://ufile.io/h8c3ildx
> 
> See if that helps and if not post new debug infos.

https://file.io/ZGAFvTFe8fZb

**Comment by hoptional** [comment]
I'm experiencing the same problem. Started today.

**Comment by hoptional** [comment]
I have another instance running, which is working fine. I downgraded both for now.

**Comment by theotherp** [comment]
I just realised that you all may have been running the "old" version 6.0.0 because the others after that were marked beta by mistake. I released 7.x yesterday and it was the first final release since 6.0.0 so you got a lot more changes in one update that I realized. In that case you'd need to downgrade to 6.0.0

Please try this one: https://ufile.io/e2cd3ron

**Comment by reloxx13** [comment]
but it said update installed all the time and showed up 7.x changelogs Oo

> I just realised that you all may have been running the "old" version 6.0.0 because the others after that were marked beta by mistake. I released 7.x yesterday and it was the first final release since 6.0.0 so you got a lot more changes in one update that I realized. In that case you'd need to downgrade to 6.0.0
> 
> Please try this one: https://ufile.io/e2cd3ron

but it said update installed all the time and showed up 7.x changelogs Oo

**Comment by hoptional** [comment]
Well, I downgraded to 7.1 and it is working again, so I'm not sure what's going on.

**Comment by theotherp** [comment]
@reloxx13 Does the version from https://ufile.io/e2cd3ron help?

**Comment by reloxx13** [comment]
> @reloxx13 Does the version from https://ufile.io/e2cd3ron help? It should, it reverts changes to exactly the class that causes issues according to the logs.

Yes this version works!
Im going to bed now, thank you and good night.

**Comment by theotherp** [comment]
Already releasing a fix. Good night, I can go to bed now as well ;-)
