### ISSUE TITLE
Windows service won't start - "Unexpected status SERVICE_PAUSED in response to START control"

### ISSUE THREAD

**Issue by lvap** [theotherp/nzbhydra2#959]
OS: Windows 10
Release: Newest (7.2.3)
I run the application as windows service via the provided installer script

The program stopped working for me a week or so ago. I checked the service and its status was "Paused". Stopped the service, donwloaded the newest release, overwrote all files, reinstalled the service. Still doesn't work. The service status is always "Paused". 

I've tried reinstalling the service multiple times with reboots in-between. Sometimes it will seem to work (according to the console output), but the service still pauses afterwards. Sometimes there's an error message right away:

```
Administrator rights confirmed.
Installing service
Service "NzbHydra2" installed successfully!
Setting service exe
Set parameter "Application" for service "NzbHydra2".
Setting service folder
Set parameter "AppDirectory" for service "NzbHydra2".
Setting service description
Set parameter "Description" for service "NzbHydra2".
Setting service to shutdown on return code 0 of wrapper
Set parameter "AppExit" for service "NzbHydra2".
Service installed successfully. Starting service...
NzbHydra2: Unexpected status SERVICE_PAUSED in response to START control.
Drücken Sie eine beliebige Taste . . .
```

[wrapper.log](https://github.com/user-attachments/files/16169182/wrapper.log)
[wrapper-2024-07-09T23-17-33.506.log](https://github.com/user-attachments/files/16169183/wrapper-2024-07-09T23-17-33.506.log)
[nzbhydra2.log](https://github.com/user-attachments/files/16169186/nzbhydra2.log)

Hopefully this is enough to identify the issue. Many thanks for creating and maintaining NzbHydra!

**Comment by theotherp** [comment]
`Vom WOF-Treiber wurde eine Beschädigung in der Ressourcentabelle der komprimierten Datei festgestellt` 

That doesn't sound good. Try deleting the ´C:\Software\NZBHydra 2\data\\logs` folder. If that doesn't help you'll have to check for file corruptions on your disk.

**Comment by lvap** [comment]
That did the trick, thanks!
