### ISSUE TITLE
MOVIE API call with only tmdbid causes imdbid=null call to indexer that doesn't support tmbdid

### ISSUE THREAD

**Issue by eresonance** [theotherp/nzbhydra2#961]
Sorry for the long title, not sure how to word this.

I have nzbgeek as my indexer, it doesn't support tmdb:
![image](https://github.com/user-attachments/assets/fefa20af-70bf-4c35-8a9b-3e9e2d66d92f)

As confirmed by caps:
```
$ curl -s "https://api.nzbgeek.info/api?apikey=xxxx&t=caps" | xq
<caps>
  <server appversion="1.0.0" version="0.1" title="NZBgeek" strapline="" email="info@nzbgeek.info" url="https://api.nzbgeek.info/" imag
e="https://cdn.nzbgeek.info/covers/nzbgeek.png"/>
  <limits max="100" default="100"/>
  <registration available="no" open="no"/>
  <searching>
    <search available="yes" supportedParams="q,group"/>
    <tv-search available="yes" supportedParams="q,rid,tvdbid,season,ep"/>
    <movie-search available="yes" supportedParams="q,imdbid,genre"/>
    <audio-search available="yes" supportedParams="q"/>
  </searching>
```

I noticed that sometimes the geek indexer was going down, and I figured out it's because a search request comes in from radarr without an imdbid:
```
Received external newznab API call: NewznabParameters{t=MOVIE, cat=[2000, 2010, 2020, 2030, 2035, 2040, 2045, 2050, 2060], tmdbId=648981, offset=0, limit=100, raw=false, o=XML, attrs=[], extended=true, indexers=[]}
```
(for this movie: https://www.themoviedb.org/movie/648981-3)
(also for some reason this doesn't show up in the .log file as part of the debug zip?)

But the geek indexer doesn't support tmdbid so it gets queried with a null imdbid instead:
```
URL call to https://api.nzbgeek.info/api?apikey=xxxx&t=movie&extended=1&imdbid=null&password=1&cat=2000&limit=1000&offset=0 returned 500: 
```

I guess instead it should not query or send some error back to radarr, whatever the case may be.

You don't have to follow the next steps by the letter, just think about what you're trying to achieve ;-) 

* Have you searched for this problem? You don't have to answer, just make sure.
Yep, not really related to anything.

* If you use a docker container please tell me which one.
Program info
Version: 7.3.0
Container version: v7.3.0-ls18
Container release type: Release
Container author: linuxserver.io 

[nzbhydra-debuginfos-2024-08-08-22-47.zip](https://github.com/user-attachments/files/16555290/nzbhydra-debuginfos-2024-08-08-22-47.zip)

**Comment by theotherp** [comment]
Thanks for the "elaborate" bug report :-)

Fixed in new release.

**Comment by eresonance** [comment]
Glad I could help!
