### ISSUE TITLE
TMDB  search from IMDB fails and it move on to next indexer without using other db id

### ISSUE THREAD

**Issue by KMohZaid** [theotherp/nzbhydra2#964]
* What do you expect to happen? What does happen? 
  * It should find tmdb id as it was trying to do. If it fails, it should try imdb find or skip it and look for other db ids
 
* Can the problem be reproduced? How?
  *  If you search any series or show with imdb id, eg searched "sweet tooth" and select it from auto complete, then modify request and add `imdbId` in it, it will fails to do so
 
* If you use a docker container please tell me which one.
 * lastest one, v7.4.0-ls19
 
* If there's a bug with the GUI post at least your current version, OS, resolution and browser and post a screenshot if necessary.
 *  it is not appear in web view search because it is not searching with "imdb" when we select from autocomplete

Error : (same for all indexers)

```
nzbhydra2    | 2024-08-13 18:48:11.430  WARN --- [  pool-10-thread-4] org.nzbhydra.indexers.Newznab            : [ID: 00000, Host: 172.23.0.4] indexer-name. Unexpected error while preparing search: Error while getting infos to generate queries
nzbhydra2    | 2024-08-13 18:48:11.446 ERROR --- [  pool-10-thread-7] org.nzbhydra.mediainfo.InfoProvider      : [ID: 00000, Host: 172.23.0.4] Error while converting IMDB tt12809988
nzbhydra2    | 
nzbhydra2    | org.nzbhydra.mediainfo.InfoProviderException: TMDB query for IMDB ID tt12809988 returned no searchResults
nzbhydra2    |  at org.nzbhydra.mediainfo.TmdbHandler.getMovieByImdbId(TmdbHandler.java:79)
nzbhydra2    |  at org.nzbhydra.mediainfo.TmdbHandler.getInfos(TmdbHandler.java:38)
nzbhydra2    |  at org.nzbhydra.mediainfo.InfoProvider.convert(InfoProvider.java:118)
nzbhydra2    |  at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54) [5 skipped]
nzbhydra2    |  at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:366)
nzbhydra2    |  at org.springframework.cache.interceptor.CacheAspectSupport.lambda$handleSynchronizedGet$1(CacheAspectSupport.java:446)
nzbhydra2    |  at org.springframework.cache.caffeine.CaffeineCache$LoadFunction.apply(CaffeineCache.java:169)
nzbhydra2    |  at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:289)
nzbhydra2    |  at java.base@17.0.9/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
nzbhydra2    |  at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:285)
nzbhydra2    |  at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:106)
nzbhydra2    |  at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
nzbhydra2    |  at org.springframework.cache.caffeine.CaffeineCache.get(CaffeineCache.java:90)
nzbhydra2    |  at org.springframework.cache.interceptor.CacheAspectSupport.handleSynchronizedGet(CacheAspectSupport.java:441)
nzbhydra2    |  at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:382)
```

**Comment by theotherp** [comment]
Post full debug infos.

**Comment by theotherp** [comment]
Also enable debug log file level and restart hydra. As requested in the issue template.

**Comment by KMohZaid** [comment]
[nzbhydra-debuginfos-2024-09-14-15-13.zip](https://github.com/user-attachments/files/17001797/nzbhydra-debuginfos-2024-09-14-15-13.zip)

for imdb conversation error, search this time "09:42:03.289"

**Comment by theotherp** [comment]
Unfortunately I'm unable to reproduce it but I think I've managed to fix it.

**Comment by KMohZaid** [comment]
> Unfortunately I'm unable to reproduce it but I think I've managed to fix it.

It won't occur when we choose series auto complete from web search. When I was passing all IDs like IMDb tmdb, etc. 
I got this error 
So i removed IMDb I'd if any other I'd is there

Anyway thanks
