### ISSUE TITLE
Address Already in Use Error

### ISSUE THREAD

**Issue by dreh65** [theotherp/nzbhydra2#967]
NZBHydra2, any version, 4.7.6, 6.21, 7.4 all start but get to a point where an error, "Address already in use" happens. Then NZBHydra just cycles thru a restart. Any hints how to fix this? I've download new zips but doesn't seem to help. I'm macOS Sonoma using the Generic version.

**Comment by theotherp** [comment]
The port 5076 is already used by another program on your machine. Doesn't matter what hydra version you use.

Either free up the port or open `data/nzbhydra.yml`, search for 5076 and change to 5077 or whatever you like. Save, start hydra.
