### ISSUE TITLE
More details on Download history tab

### ISSUE THREAD

**Issue by jaywk** [theotherp/nzbhydra2#97]
* What do you want to happen?

I'm wondering if this is possible? I'd like to see a detail column, much like the one that exists on the ``History & Stats > Search History`` tab, but on the ``History & Stats > Download history`` tab too. 

* If not clear, why do you want it?

Clicking this detail icon would show you the indexers that returned similar/same results of the nzb file (and/or variations or it; i.e., same show, episode, and season but maybe different qualities that were available) that was sent to your download client. It would interesting to be able to see which indexers actually had that file but weren't picked to grab that particular nzb for whatever reason. 

For example, it may show that two indexers returned the file that was ultimately sent to your download client and it would be interesting to see what the other indexer was that had it available at the time it was picked. I think that could be valuable or at the very least interesting information to be able to see.

* Do you think it's something only you need or something that might be popular?

Everyone loves stats. The more details available the better!

**Comment by theotherp** [comment]
This would require a lot more data to be saved and make handling a lot more complicated.. Thanks for the request, but unfortunately for now it's too improbable to keep this open. Who knows, I might come back to this.
