### ISSUE TITLE
additional.css and .js not found (404 error)

### ISSUE THREAD

**Issue by ptruka** [theotherp/nzbhydra2#971]
* What do you expect to happen? What does happen? 
When you visit nzbhydra2 (latest, 7.8.0) you will receive 404 error on two files:

```
GET /nzbhydra2/static/css/additional.css HTTP/2.0
GET /nzbhydra2/static/js/additional.js HTTP/2.0
```

* Can the problem be reproduced? How?
Visit your instance of hydra in your browser and look into the browsers dev tools.

* If you use a docker container please tell me which one.
lscr.io/linuxserver/nzbhydra2:latest

* Why is it an issue?
E.g.: if you run fail2ban and you configure a jail to ban an IP adresses after n amount of 404 errors on your running websites, this behavior will lead to an unwanted ban action of a user simply accessing the nzbhydra page.

Example for an traefik access.log:
```
[user IP] - - [22/Oct/2024:10:24:48 +0000] "GET /nzbhydra2/static/css/additional.css HTTP/2.0" 404 431 "-" "-" 342 "nzbhydra2@docker" "http://172.18.0.3:5076" 2ms
[user IP] - - [22/Oct/2024:10:24:48 +0000] "GET /nzbhydra2/static/js/additional.js HTTP/2.0" 404 431 "-" "-" 344 "nzbhydra2@docker" "http://172.18.0.3:5076" 2ms
```

**Comment by theotherp** [comment]
Understood. Will look into it.
