### ISSUE TITLE
Sorry, this is just a question

### ISSUE THREAD

**Issue by Bahazzie** [theotherp/nzbhydra2#973]
Hello, I hope you don't mind I post a question here. I am interested in NZB Hydra, currently I use a JAVA script that 

1. Downloads the newest movie spots from nzbserver and/or clubnzb websites every x minutes
2. Enhances the spots with IMDB scores from webservice
3. Filters on imdbscore, size, genre, alreadydone, year based on criteria in application.properties file
4. For all selected movies the NZB download link is clicked (HtmlUnit can do this in JAVA)

So basically EVERYTHING matching the criteria is downloaded by NUC with some SSD's. Recently I have moved to SpringBoot and replaced the webservice with a full daily IMDB data extract pull (download and unzip the 2 main files and update repo takes under a minute).

My frustration is that clubnzb and nzbserver structures are not 100% the same plus clubnzb is down a lot. Can nzbhydra do what I describe above? If not can I fork it? I just need the spots that are listed on the nzbserver/clubnzb websites, but would like to get to the source and skip the websites. But how?

Thanks for any insights!

Bas

**Comment by theotherp** [comment]
NZBHydra is not designed to search or automatically. It can not filter by IMDB ratings.

**Comment by Bahazzie** [comment]
That's why I wrote my  robot-tool which has run for years ;-) There isn't anything else that does this: to auto download all movies that are watchable (about 0,1% of all movies).

**Comment by theotherp** [comment]
It may be easier watching TMBD or IMDB for new movies and adding them to radarr.
