### ISSUE TITLE
Database size issue

### ISSUE THREAD

**Issue by scottismyname** [theotherp/nzbhydra2#974]
I am running nzbhydra from a docker container on my Synology.  I regularly backup my appdata docker directories.  When I was archiving my backups to another location I noticed that starting sometime after 10/22 my weekly backups for nzbhydra went from about 400MB to about 5GB.  My nzbhydra.mv.db file is over 13GB in size uncompressed.  I am not sure if an update caused more data to be stored in the database possibly?

I don't think a log file would help since this seems like more of a general question rather than a bug report.  Also is there any setting to control the number of backups stored?

**Comment by theotherp** [comment]
The advanced config shows a setting `Delete backups after... days`.

The database size issue is known although I don't think I've heard of databases getting as big as yours. For comparison, mine are 70 and 590 MB. 

I've had some ideads how to solve this (basically by moving to a different database) but never got around to doing it. I'll try to find some time.

If you don't care about history and stats you can configure NZBHydra not to keep any history (again, enable advanced options) which should keep the database size to a minimum.

**Comment by scottismyname** [comment]
> The advanced config shows a setting `Delete backups after... days`.
> 
Yeah that's the only setting I saw, but I see weekly backups going back to May 6th.  I can manually purge them.  Maybe a debug log would help with this though?

> The database size issue is known although I don't think I've heard of databases getting as big as yours. For comparison, mine are 70 and 590 MB.
> 
> I've had some ideads how to solve this (basically by moving to a different database) but never got around to doing it. I'll try to find some time.
> 
> If you don't care about history and stats you can configure NZBHydra not to keep any history (again, enable advanced options) which should keep the database size to a minimum.
> 
> Try setting "Database retention time" to `0` in the main config. Restart hydra and see if that helps.
Wow, changing that setting shrunk the database to 835MB after a restart.  I can live with that, thanks!

**Comment by theotherp** [comment]
Great. Let me know when it gets big again.

**Comment by scottismyname** [comment]
Well it's back to 18GB now.  Let me know what I can do to troubleshoot

**Comment by theotherp** [comment]
I can't take care of this right now, sorry. The easiest solution would be to delete the database file.
