### ISSUE TITLE
3D filter button seems not to be working

### ISSUE THREAD

**Issue by nottherealshady** [theotherp/nzbhydra2#977]
In the search tab when searching for category "Movie" and filering the search results with the "3D" filter button, no search results are left/shown even though some of them clearly have "3D" in their title. E.g. this is filtered out and not shown:

```
Jurassic.World.Ein.neues.Zeitalter.2022.3D.German.DL.1080p.BluRay.x264-SPiCY
```

Before:
<img width="1726" alt="before" src="https://github.com/user-attachments/assets/e9664c59-f857-4f46-8fc7-0213eb2a11e1" />

After:
<img width="1712" alt="after" src="https://github.com/user-attachments/assets/aac896c1-acce-4101-9fd9-9908d8051d69" />

Seems like very unexpected behavior to me.

Program info
Version: 7.8.0
Container version: v7.8.0-ls28
Container release type: Release
Container author: linuxserver.io 

OS: MacOS 15.1.1
Resolution: 1728 × 1117
Browser: Firefox 133.0.3

**Comment by theotherp** [comment]
Sorry for the late response, will look into it.
