### ISSUE TITLE
Problem adding pre-defined indexer: NZBIndex

### ISSUE THREAD

**Issue by no0nee** [theotherp/nzbhydra2#98]
Disclosure: I am running this on the linuxserver.io (current) docker release, unsure if that is part of the problem.  This is a fresh install.

When attempting to add the pre-defined indexer NZBIndex I get the following message.

`The connection to the indexer failed: Error while communicating with indexer NZBIndex. Server returned: org.springframework.oxm.UnmarshallingFailureException: JAXB unmarshalling exception; nested exception is javax.xml.bind.UnmarshalException - with linked exception: [org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]
Do you want to add it anyway?`

Debug log and config attached. ;)

[nzbhydra-debuginfos-2018-01-29-09-57.zip](https://github.com/theotherp/nzbhydra2/files/1674216/nzbhydra-debuginfos-2018-01-29-09-57.zip)

I love Hydra1 and am trying to migrate to Hydra2, any assistance would be greatly appreciated.  Thank you!

**Comment by theotherp** [comment]
In the future please post the debug infos ZIP. It's easier for me to read and it helps to get more context information.

**Comment by no0nee** [comment]
Updated with ZIP, thank you.

**Comment by theotherp** [comment]
I can reproduce the problem. It will be fixed in the next version. You can just select "I know what I'm doing" and it will be added and usable.
