### ISSUE TITLE
update to 1.2.2 doesn´t work

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra2#99]
just tried an update from 1.2.1 to 1.2.2 from the GUI. Hydra didn´t start. So i stopped the service and updated by manually.

when i try to start hydra using ` ./nzbhydra` i get this errormessage:
```
Logging wrapper output to /home/stefan/data/logs/wrapper.log
Traceback (most recent call last):
  File "nzbhydra2wrapper.py", line 472, in <module>

  File "nzbhydra2wrapper.py", line 352, in startup

UnboundLocalError: local variable 'xmx' referenced before assignment
[1221] Failed to execute script nzbhydra2wrapper

```

even when i try to restore to 1.2.1 manually it doesn´t start. 
any idea?

**Comment by weirdcrap** [comment]
What OS are you running on? Are you using the latest version of the wrapper file?

I just updated my Pi3 Hydra install without issue, though I updated the app first then I downloaded the newest wrapper file since it was just updated a few hours ago.

**Comment by Hobbabobba** [comment]
my Debian machine updated fine, Ubuntu 16 has problems. i will try a new wrapperfile.

**Comment by Hobbabobba** [comment]
the failed update corrupted `nzbhydra.yml` - restored it from backup and it is up and running

**Comment by theotherp** [comment]
Thanks. That shouldn't happen. Could you please post the debug infos ZIP file.
